main/default/objects/Compass_Capture__c/Compass_Capture__c.object-meta.xml
<CustomObject>
    <label>Compass Capture</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Capture ID#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compass Capture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Impact_Capture__c/Impact_Capture__c.object-meta.xml
<CustomObject>
    <label>Impact Capture</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Change Impact ID#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Impact Capture</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Impact_Capture__c/fields/Capture_ID__c.field-meta.xml
<CustomField>
    <fullName>Capture_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Capture ID#</label>
    <referenceTo>Compass_Capture__c</referenceTo>
    <relationshipLabel>Impact Capture</relationshipLabel>
    <relationshipName>Impact_Capture</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/CloneCompassCaptureControllerTest.cls
@isTest
public class CloneCompassCaptureControllerTest {
	@isTest
    public static void test_doClone(){
        Compass_Capture__c compassCapture = new Compass_Capture__c();
        Insert compassCapture;
        
        Impact_Capture__c impactCapture = new Impact_Capture__c();
        impactCapture.Capture_ID__c = compassCapture.Id;
        Insert impactCapture;
        
        CloneCompassCaptureController.doClone(compassCapture.Id, 'Compass_Capture__c');
        
        system.assertEquals(2, [SELECT ID FROM Compass_Capture__c].size());
    }
}