main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Educator</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Trainor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Issue__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Project_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Issue__c/fields/Raised_By_Email__c.field-meta.xml
<CustomField>
    <fullName>Raised_By_Email__c</fullName>
    <label>Raised By Email</label>
    <type>Email</type>
</CustomField>

main/default/objects/Issue__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Session</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a session that exists on the selected event</errorMessage>
        <filterItems>
            <field>$Source.Event__c</field>
            <operation>equals</operation>
            <valueField>Session__c.Event__c</valueField>
        </filterItems>
        <filterItems>
            <field>Session__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Issue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domain Access Issue/User Sign-on Issues</fullName>
            </value>
            <value>
                <fullName>Domain Issue Impacting Workbook Execution</fullName>
            </value>
            <value>
                <fullName>Workflow Issue</fullName>
            </value>
            <value>
                <fullName>Hardware Issue</fullName>
            </value>
            <value>
                <fullName>Training Room Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/CommunityIssueControllerTest.cls
/**
@revision Kyzer Buhay - Removed Project in Class name (CommunityProjectIssueControllerTest) to CommunityIssueControllerTest
                      - Changed Object Reference from Project_Issue__c to Issue__c
**/
@isTest (SeeAllData = false)
public class CommunityIssueControllerTest {
    
    @testSetup static void createData() {
        
        TestFactory.ParkingLotTestDataFactory df = new TestFactory.ParkingLotTestDataFactory();
        df.make();
        df.persist();           
        
        Event__c evt = [SELECT Id, Event_Id__c FROM Event__c LIMIT 1];
        Session__c sess = [SELECT Id FROM Session__c WHERE Event__c =: evt.Id];
        
        //Create Existing Contact
        String email = 'test@email.com';
        String token = '123';
        Contact con = new Contact();
        con.LastName = email;
        con.Email = email;
        insert con;
        
        List<String> emailList = new List<String>{'test@email.com','test2@email.com','test3@email.com','test4@email.com','test5@email.com'};
            List<Issue__c> piList = new List<Issue__c>();
        for(String emailStr : emailList){
            Issue__c pi = new Issue__c();
            pi.Session__c = sess.Id;
            pi.Raised_By_Email__c = emailStr;
            pi.Event__c = evt.Id;
            piList.add(pi);
        }
        insert piList;
    }
    
    @isTest static void getProjectRaidDetailsTest(){
        Event__c evt = [SELECT Id, Event_Id__c FROM Event__c LIMIT 1];
        test.startTest();
        String results = CommunityIssueController.getProjectDetails(evt.Event_Id__c, null);
        test.stopTest();
        
        //Assert
        system.assert(String.isNotBlank(results));
        
    }
    
    @isTest static void createProjectIssueTest(){
          Event__c evt = [SELECT Id, Event_Id__c FROM Event__c LIMIT 1];
         Session__c sess = [SELECT Id FROM Session__c WHERE Event__c =: evt.Id];
        List<String> typeList= new List<String>();
        Schema.DescribeFieldResult fieldResult = Issue__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            typeList.add(pickListVal.getLabel());
        }  
        test.startTest();
        CommunityIssueController.createProjectIssue(evt.Event_Id__c, sess.Id, 'test@email.com', 'Description', typeList[0]);
        test.stopTest();
        
        //Assert
        List<Issue__c> results = [SELECT Id, Raised_By_Email__c FROM Issue__c WHERE Raised_By_Email__c = 'test@email.com'];
        system.assert(!results.isEmpty());
    }
    
    @isTest static void createProjectIssueErrorTest(){
          Event__c evt = [SELECT Id, Event_Id__c FROM Event__c LIMIT 1];
         Session__c sess = [SELECT Id FROM Session__c WHERE Event__c =: evt.Id];        
        try{
            CommunityIssueController.createProjectIssue(evt.Event_Id__c, sess.Id, 'test@email.com', 'description', 'type');
        }
        catch(Exception e){
            system.assert(String.isNotBlank(e.getMessage()));
        }
    }
    
    @isTest static void getProjectIssueDetailsErrorTest(){
        try{
            CommunityIssueController.getProjectDetails('evtId', null);
        }
        catch(Exception e){
            system.assert(String.isNotBlank(e.getMessage()));
        }
    }
    
    @isTest static void getProjectIssueDetailsErrorTest2(){
        try{
            Event__c evt = TestFactory.createEvent('TestEvent2');
            Event__c evtRec = [SELECT Id, Event_Id__c FROM Event__c WHERE Name = 'TestEvent2' LIMIT 1];
            CommunityIssueController.getProjectDetails(evtRec.Event_Id__c, null);
        }
        catch(Exception e){
            system.assert(String.isNotBlank(e.getMessage()));
        }
    }
}