main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Educator</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Trainor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Parking_Lot__c/Parking_Lot__c.object-meta.xml
<CustomObject>
    <label>Parking Lot</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Parking Lot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parking Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Parking_Lot__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Parking Lots</relationshipLabel>
    <relationshipName>Parking_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Raised_By__c.field-meta.xml
<CustomField>
    <fullName>Raised_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raised By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parking Lots</relationshipLabel>
    <relationshipName>Parking_Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a session that exists on the selected event</errorMessage>
        <filterItems>
            <field>$Source.Event__c</field>
            <operation>equals</operation>
            <valueField>Session__c.Event__c</valueField>
        </filterItems>
        <filterItems>
            <field>Session__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Parking Lots</relationshipLabel>
    <relationshipName>Parking_Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
            <value>
                <fullName>Statement BH</fullName>
                <isActive>false</isActive>
                <label>Statement BH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/CustomParkingLotForm_Test.cls
/**
* Description: Test Class for CustomParkingLotFormHelper
* Author: Jester Cabantog
* Version: 1.0
* Last modified date: 12/16/2020
**/
@isTest (SeeAllData = false)
private class CustomParkingLotForm_Test {
    
    @testSetup 
    static void setUp() {
        TestFactory.ParkingLotTestDataFactory df = new TestFactory.ParkingLotTestDataFactory();
        df.make();
        df.persist();
    }
    
    @isTest
    static void getParkingLotDetailsTestNoSessionParticipant_shouldThrowException_whenWithContact(){
        Contact con = [SELECT Id FROM Contact WHERE Name = 'Test Con' LIMIT 1];
        Event__c evt = [SELECT Id, Event_Id__c FROM Event__c LIMIT 1];
        evt.Start_Date_Time__c = DateTime.now();
        evt.End_Date_Time__c=DateTime.now().AddDays(1);
        evt.IsActive__c = true;

        update evt;

        Test.startTest();
        try {
            String result = CustomParkingLotFormController.getParkingLotDetails(evt.Event_Id__c, con.Id , null);
        } catch(AuraHandledException e){
            System.assert(e.getMessage().contains('Script-thrown exception'));
        }
        
        Test.stopTest();
    }

    @isTest
    static void getParkingLotDetailsTestNoSessionParticipant_shouldReturnResult_whenWithNoContact(){
        Event__c evt = [SELECT Id, Event_Id__c FROM Event__c LIMIT 1];
        String result;
        Test.startTest();
        try{
         result = CustomParkingLotFormController.getParkingLotDetails(evt.Event_Id__c, '', null);   
        }catch(exception e){
            
        }
        
        Test.stopTest();

        System.assert(String.isNotBlank(result), 'There should be a result');
    }
    
    @isTest
    static void getParkingLotDetailsTest_withNoContact(){
        OrgWideEmailAddress[] addresses = [SELECT Id, DisplayName, Address FROM OrgWideEmailAddress LIMIT 1];
        Contact con = [SELECT Id FROM Contact WHERE Name = 'Test Con' LIMIT 1];
        Event__c evt = [SELECT Id, Event_Id__c, Email_Sender_Name__c FROM Event__c LIMIT 1];
        evt.Email_Sender_Name__c = addresses[0].DisplayName;
        evt.Email_Sender_Id__c = addresses[0].Id;
        update evt;
        Session__c sess = [SELECT Id FROM Session__c WHERE Event__c =: evt.Id];
        sess.Meeting_URL__c = 'test.teams.com/test';
        update sess;
        
        Session_Participant__c sesPart = new Session_Participant__c(
            Event__c = evt.Id,
            Session__c = sess.Id,
            Contact__c = con.Id
        );
        System.debug('@@@@@@ ' + [SELECT Id, Email_Sender_Name__c FROM Event__c WHERE Id =: sesPart.Event__c]);
        insert sesPart;
        String result;
        Test.startTest();
        try{
           result = CustomParkingLotFormController.getParkingLotDetails(evt.Event_Id__c, '', null); 
        }catch(exception e){
            
        }
        
        Test.stopTest();

        System.assert(String.isNotBlank(result), 'There should be a result');
    }
    
    @isTest
    static void getParkingLotDetailsTest_withContact(){
        OrgWideEmailAddress[] addresses = [SELECT Id, DisplayName, Address FROM OrgWideEmailAddress LIMIT 1];
        Contact con = [SELECT Id FROM Contact WHERE Name = 'Test Con' LIMIT 1];
        Event__c evt = [SELECT Id, Event_Id__c, Email_Sender_Name__c FROM Event__c LIMIT 1];
        evt.Email_Sender_Name__c = addresses[0].DisplayName;
        evt.Email_Sender_Id__c = addresses[0].Id;
        update evt;
        Session__c sess = [SELECT Id FROM Session__c WHERE Event__c =: evt.Id];
        Session_Participant__c sesPart = new Session_Participant__c(
            Event__c = evt.Id,
            Session__c = sess.Id,
            Contact__c = con.Id
        );
        
        insert sesPart;
		String result;
        Test.startTest();
        try{
        result = CustomParkingLotFormController.getParkingLotDetails(evt.Event_Id__c, con.Id, null);
        }catch(exception e){
            
        }
        Test.stopTest();

        System.assert(String.isNotBlank(result), 'There should be a result');
    }
    
    @isTest
    static void createParkingLotTest(){
        String alias = 'tstSysAd';
        Profile profile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User sysad = new User(
            Username=alias+'@Test.com', Alias=alias, CommunityNickname=alias, TimeZoneSidKey='America/Chicago', 
            LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US',
            FirstName=alias, LastName=alias, Email=alias+'@Test.com', ProfileId=profile.Id, Department = 'Test');
        insert sysad;

        System.runAs(sysad) {
            Event__c evt = [SELECT Id, Event_Id__c FROM Event__c LIMIT 1];
            Session__c sess = [SELECT Id FROM Session__c WHERE Event__c =: evt.Id];

            Test.startTest();
                CustomParkingLotFormController.createParkingLot(evt.Id, sess.Id, 'test@test.com', '', 'Question', 'Issue', 'Workflow');
                CustomParkingLotFormController.createParkingLot(evt.Id, sess.Id, 'test2@test.com', '', 'Question', 'Issue', 'Workflow');
            Test.stopTest();

            List<Parking_Lot__c> results = [SELECT Id FROM Parking_Lot__c 
            WHERE Raised_By__r.Email = 'test@test.com' OR Raised_By__r.Email = 'test2@test.com'];

            System.assertEquals(2, results.size(), 'There should only be 2 results');
        }
    }
    
    @isTest
    static void updateParkingLotsTest(){
        Parking_Lot__c pl = [SELECT Id, Status__c FROM Parking_Lot__c LIMIT 1];

        Test.startTest();
        CustomParkingLotFormController.updateParkingLots('[{"'+ FLSUtils.prefix + 'Status__c":"Closed","Id":"' + pl.Id + '"}]');
        Test.stopTest();

        Parking_Lot__c result = [SELECT Id, Status__c FROM Parking_Lot__c WHERE Id = :pl.Id];
        System.assertNotEquals(pl.Status__c, result.Status__c, 'Status should already be updated');
    }

    @isTest
    static void updateParkingLotsStatusErrTest(){
        
        Parking_Lot__c pl = [SELECT Id FROM Parking_Lot__c LIMIT 1];
        try{
            Test.startTest();
            CustomParkingLotFormController.updateParkingLots('[{"Status__c":"err","Id":"'+pl.Id+'"}]');
            Test.stopTest();
        }
        catch(Exception e){
            System.assert(e.getMessage().contains('Script-thrown exception'), 'There should be an exception');
        }
    }
    
    @isTest
    static void updateParkingLotsTypeErrTest(){
        Parking_Lot__c pl = [SELECT Id FROM Parking_Lot__c LIMIT 1];
        try{
            Test.startTest();
            CustomParkingLotFormController.updateParkingLots('[{"Type__c":"err","Id":"'+pl.Id+'"}]');
            Test.stopTest();
        }
        catch(Exception e){
            System.assert(e.getMessage().contains('Script-thrown exception'), 'There should be an exception');
        }
    }
    
    @isTest
    static void updateParkingLotsDmlErrTest(){
        Parking_Lot__c pl = [SELECT Id FROM Parking_Lot__c LIMIT 1];
        try{
            Test.startTest();
            CustomParkingLotFormController.updateParkingLots('[{"Type__c":"err","Id":"' + pl.Id + '123' + '"}]');
            Test.stopTest();
        }
        catch(Exception e){
            System.assert(e.getMessage().contains('Script-thrown exception'), 'There should be an exception');
        }
    }
}