main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Educator</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Trainor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Outreach Notification. If this field is populated and related the Session does not have related Outreach Notification, this will be used as the setting for that Session.</description>
    <inlineHelpText>If the related Session does not have related Outreach Notification, this will be used as the setting for that Session.</inlineHelpText>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Outreach_Notification_History__c/Outreach_Notification_History__c.object-meta.xml
<CustomObject>
    <description>Contains historical data of notifications sent out to contacts.</description>
    <label>Outreach Notification History</label>
    <nameField>
        <displayFormat>ONH{000000}</displayFormat>
        <label>Outreach Notification History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreach Notification Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_History__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Links to the contact (participant)</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Outreach Notification Histories</relationshipLabel>
    <relationshipName>Outreach_Notification_Histories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Additional Information</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the Parent Outreach Notification</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Outreach Notification Histories</relationshipLabel>
    <relationshipName>Outreach_Notification_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Outreach_Notification_Setting__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification_Setting__c</fullName>
    <description>Lookup field to the Outreach Notification Setting</description>
    <label>Outreach Notification Setting</label>
    <referenceTo>Outreach_Notification_Setting__c</referenceTo>
    <relationshipLabel>Outreach Notification Histories</relationshipLabel>
    <relationshipName>Outreach_Notification_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/Outreach_Notification_Setting__c.object-meta.xml
<CustomObject>
    <description>Contains the configuration that will be used for each compass objects</description>
    <label>Outreach Notification Setting</label>
    <nameField>
        <label>Outreach Notification Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Notification Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_Setting__c/fields/L1_Days__c.field-meta.xml
<CustomField>
    <fullName>L1_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Level 1 Notification:
The number of days prior to Event/Session Start Date.</description>
    <inlineHelpText>Level 1 Notification:
A number of days prior to Event/Session Start Date or Catchup Start Date.</inlineHelpText>
    <label>L1 Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/L2_Days__c.field-meta.xml
<CustomField>
    <fullName>L2_Days__c</fullName>
    <description>Level 2 Notification:
The number of days prior to Event/Session Start Date</description>
    <inlineHelpText>Level 2 Notification:
The number of days prior to Event/Session Start Date or Catchup Start Date.</inlineHelpText>
    <label>L2 Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Outreach Notifiocation record</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Outreach Notification Settings</relationshipLabel>
    <relationshipName>Outreach_Notification_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <description>Time of the day that the notification will be sent out</description>
    <inlineHelpText>Time of the day that the notification will be sent out</inlineHelpText>
    <label>Time</label>
    <type>Time</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Notification Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Invitation Registration Reminder</fullName>
            </value>
            <value>
                <fullName>Registration Confirmation Reminder</fullName>
            </value>
            <value>
                <fullName>Session Attendance Thank you</fullName>
            </value>
            <value>
                <fullName>Session Catchup</fullName>
            </value>
            <value>
                <fullName>Session Catchup Reminder</fullName>
            </value>
            <value>
                <fullName>Session Catchup Thank you</fullName>
            </value>
            <value>
                <fullName>Survey Catchup</fullName>
            </value>
            <value>
                <fullName>Survey Catchup Reminder</fullName>
            </value>
            <value>
                <fullName>Survey Reminder</fullName>
            </value>
            <value>
                <fullName>Survey Thank You</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Member_Contact__c.field-meta.xml
<CustomField>
    <fullName>Member_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Event_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant__c/recordTypes/Participant.recordType-meta.xml
<RecordType>
    <fullName>Participant</fullName>
    <active>true</active>
    <label>Participant</label>
</RecordType>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Catchup__c.field-meta.xml
<CustomField>
    <fullName>Catchup__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if Survey Catch-Up is active</description>
    <label>Survey Catch-Up</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Survey__c/fields/Catchup_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Catchup_End_Date__c</fullName>
    <description>Survey Catch-Up End Date</description>
    <label>Survey Catch-Up End Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Survey__c/fields/Catchup_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Catchup_Start_Date__c</fullName>
    <description>Survey Catch-Up Start date</description>
    <label>Survey Catch-Up Start Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Journey_Milestone_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Journey_Milestone_End_Date__c</fullName>
    <description>Sets the date until when the survey can be answered as a milestone in a user journey</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Survey__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the Outreach Notification</description>
    <label>Outreach Notification</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Outreach_Notification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Participant__c/Survey_Participant__c.object-meta.xml
<CustomObject>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that has been selected as a participant for a survey</description>
    <inlineHelpText>Contact that has been selected as a participant for a survey</inlineHelpText>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <description>Survey that the contact has been selected to participate to</description>
    <inlineHelpText>Survey that the contact has been selected to participate to</inlineHelpText>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey_Response__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Response__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/OutreachNotificationSurveyHelper.cls
/*******************************************************************************
 * @author       Angelo Rivera
 * @date          01.12.2021
 * @description  [CCN-1059, CCN-1060, CCN-1061] Helper class for BatchOutreachNotificationCC
 * @revision      10.12.2021 - APRivera - Created
 *******************************************************************************/

public without sharing class OutreachNotificationSurveyHelper {

    /* ***************************************************************************** */
    public static String processSurveys(){
        Map<Id, Survey__c> mapSurveyById = new Map<Id, Survey__c>();
        mapSurveyById = getSurveys();

        if(!mapSurveyById.isEmpty()){
            // retrieve all Outreach Notification linked to Events
            Map<Id, List<Outreach_Notification_Setting__c>> mapOutreachNotificationSettingsByOutreachNotificationIds = new Map<Id, List<Outreach_Notification_Setting__c>>();
            mapOutreachNotificationSettingsByOutreachNotificationIds = OutreachNotificationHelper.getOutreachNotificationSettings();

            Map<Id, List<Participant__c>> mapParticipantsByEventId = new Map<Id, List<Participant__c>>();
            mapParticipantsByEventId = getEventParticipants(mapSurveyById.keySet());

            List<Outreach_Notification_History__c> lstNewOutreachNotificationHistories = new List<Outreach_Notification_History__c>();
            // iterate on Survey records
            for(Survey__c survey : mapSurveyById.values()){
                if(survey.Outreach_Notification__c != null){
                    System.debug(LoggingLevel.DEBUG, ' !@# Processing Survey: ' + survey.Name);
                    processSurveyOutreachNotifications(survey, mapOutreachNotificationSettingsByOutreachNotificationIds, lstNewOutreachNotificationHistories, mapParticipantsByEventId);
                }
            }

            try{
                System.debug(LoggingLevel.DEBUG, ' !@# lstNewOutreachNotificationHistories:' + lstNewOutreachNotificationHistories.size());
                if(!lstNewOutreachNotificationHistories.isEmpty()){
                    Database.insert(lstNewOutreachNotificationHistories);
                }
            }catch (Exception ex){
                System.debug(LoggingLevel.DEBUG, ' !@# ERROR:' + ex.getTypeName() + ' - ' + ex.getMessage());
            }
        }
        return 'Process Complete!';
    }


    /* ***************************************************************************** */
    public static void processSurveyOutreachNotifications(Survey__c survey,  Map<Id, List<Outreach_Notification_Setting__c>> mapOutreachNotificationSettingsByOutreachNotificationIds,
                                                                            List<Outreach_Notification_History__c> lstNewOutreachNotificationHistories, Map<Id, List<Participant__c>> mapParticipantsByEventId){

        List<Outreach_Notification_Setting__c> lstOutreachNotificationSettings = new List<Outreach_Notification_Setting__c>();
        lstOutreachNotificationSettings = mapOutreachNotificationSettingsByOutreachNotificationIds.get(survey.Outreach_Notification__c);

        if(!lstOutreachNotificationSettings.isEmpty()){
            Outreach_Notification_Setting__c outreachSurveyCatchupSetting = new Outreach_Notification_Setting__c();
            Outreach_Notification_Setting__c outreachSurveyCatchupReminderSetting = new Outreach_Notification_Setting__c();
            Outreach_Notification_Setting__c outreachSurveyThankYouSetting = new Outreach_Notification_Setting__c();
            Outreach_Notification_Setting__c outreachSurveyReminderSetting = new Outreach_Notification_Setting__c();
            Boolean bOutreachSurveyCatchupSettingFound = false, bOutreachSurveyCatchupReminderSettingFound = false, bOutreachSurveyThankYouSettingFound = false,  bOutreachSurveyReminderSettingFound = false;
            // retrieve outreach notification setting to be used
            for(Outreach_Notification_Setting__c ons : lstOutreachNotificationSettings){
                if(ons.Type__c == Label.Outreach_Notification_Survey_Catchup){
                    outreachSurveyCatchupSetting = ons;
                    bOutreachSurveyCatchupSettingFound = true;
                }
                if(ons.Type__c == Label.Outreach_Notification_Survey_Catchup_Reminder){
                    outreachSurveyCatchupReminderSetting = ons;
                    bOutreachSurveyCatchupReminderSettingFound = true;
                }
                if(ons.Type__c == Label.Outreach_Notification_Survey_Thank_you){
                    outreachSurveyThankYouSetting = ons;
                    bOutreachSurveyThankYouSettingFound = true;
                }
                if(ons.Type__c == Label.Outreach_Notification_Survey_Reminder){
                    outreachSurveyReminderSetting = ons;
                    bOutreachSurveyReminderSettingFound = true;
                }
            }

            List<Survey_Response__c> lstSurveyResponsesThankYouNotification = new List<Survey_Response__c>();
            List<SObject> lstParticipantsSurveyReminder  = new List<SObject>();
            List<SObject> lstParticipantsSurveyReminderL2Flag  = new List<SObject>();
            List<SObject> lstParticipantsSurveyCatchup  = new List<SObject>();
            List<SObject> lstParticipantsSurveyCatchupReminder  = new List<SObject>();
            List<SObject> lstParticipantsSurveyCatchupReminderL2Flag  = new List<SObject>();
            Set<Id> setSurveyResponsesContactIds = new Set<Id>();
            List<SObject> lstParticipants  = new List<SObject>();
            Boolean bIsStandaloneSurvey = false;
            // Independent Survey - get the Survey Participants
            if(!survey.Survey_Participants__r.isEmpty() && survey.Event__c == null){
                lstParticipants.addAll(survey.Survey_Participants__r);
                bIsStandaloneSurvey = true;
            }else{ // Event's Survey - get the Event Participants
                lstParticipants = mapParticipantsByEventId.get(survey.Event__c);
            }

            if(!survey.Survey_Responses__r.isEmpty()){
                for(Survey_Response__c sr : survey.Survey_Responses__r) {
                    // thank you notification flow
                    if(bOutreachSurveyThankYouSettingFound) {
                        // check if Survey response is due for Thank You notification
                        if (checkIfTodayIsDueForNotification(sr.CreatedDate, Integer.valueOf(outreachSurveyThankYouSetting.L1_Days__c), Label.Outreach_Notification_Survey_Thank_you)) {
                            lstSurveyResponsesThankYouNotification.add(sr);
                        }
                    }
                    //gather all contacts with survey response
                    setSurveyResponsesContactIds.add(sr.Contact__c);
                }
            }
            System.debug(LoggingLevel.DEBUG, ' !@# setSurveyResponsesContactIds : ' + setSurveyResponsesContactIds.size());


            // Survey reminder notification flow
            if(bOutreachSurveyReminderSettingFound){
                // check if Participants are due for Survey reminder notification
                Datetime dtSurvey = Datetime.newInstance(survey.Journey_Milestone_End_Date__c.year(), survey.Journey_Milestone_End_Date__c.month(), survey.Journey_Milestone_End_Date__c.day());
                if (checkIfTodayIsDueForNotification(dtSurvey, Integer.valueOf(outreachSurveyReminderSetting.L1_Days__c), Label.Outreach_Notification_Survey_Reminder)) {
                    lstParticipantsSurveyReminder.addAll(getListParticipants(lstParticipants, setSurveyResponsesContactIds));
                }else{ // check if Participants will be L2 Flagged
                    if(checkIfTodayIsDueForNotification(dtSurvey, Integer.valueOf(outreachSurveyReminderSetting.L2_Days__c), Label.Outreach_Notification_Survey_Reminder)){
                        lstParticipantsSurveyReminderL2Flag.addAll(getListParticipants(lstParticipants, setSurveyResponsesContactIds));
                    }
                }
            }

            // check if Survey catchup is active
            if(survey.Catchup__c){
                // Survey Catchup notification flow
                if(bOutreachSurveyCatchupSettingFound){
                    if (checkIfTodayIsDueForNotification(survey.Catchup_Start_Date__c, Integer.valueOf(outreachSurveyCatchupSetting.L1_Days__c), Label.Outreach_Notification_Survey_Catchup)) {
                        lstParticipantsSurveyCatchup.addAll(getListParticipants(lstParticipants, setSurveyResponsesContactIds));
                    }
                }
                // Survey Catchup Reminder notification flow
                if(bOutreachSurveyCatchupReminderSettingFound){
                    if (checkIfTodayIsDueForNotification(survey.Catchup_End_Date__c, Integer.valueOf(outreachSurveyCatchupReminderSetting.L1_Days__c), Label.Outreach_Notification_Survey_Catchup_Reminder)) {
                        lstParticipantsSurveyCatchupReminder.addAll(getListParticipants(lstParticipants, setSurveyResponsesContactIds));
                    }else{ // check if Participants will be L2 Flagged
                        if(checkIfTodayIsDueForNotification(survey.Catchup_End_Date__c, Integer.valueOf(outreachSurveyCatchupReminderSetting.L2_Days__c), Label.Outreach_Notification_Survey_Catchup_Reminder)){
                            lstParticipantsSurveyCatchupReminderL2Flag.addAll(getListParticipants(lstParticipants, setSurveyResponsesContactIds));
                        }
                    }
                }
            }

            System.debug(LoggingLevel.DEBUG, ' !@# --------------------------------------------');
            if(!lstSurveyResponsesThankYouNotification.isEmpty()){
                System.debug(LoggingLevel.DEBUG, ' !@# lstSurveyResponsesThankYouNotification:' + lstSurveyResponsesThankYouNotification.size());
                // record history
                lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(false, lstSurveyResponsesThankYouNotification, outreachSurveyThankYouSetting));
            }
            if(!lstParticipantsSurveyReminder.isEmpty()){
                System.debug(LoggingLevel.DEBUG, ' !@# lstParticipantsSurveyReminder:' + lstParticipantsSurveyReminder.size());
                // record history
                lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(false, lstParticipantsSurveyReminder, outreachSurveyReminderSetting));
            }
            if(!lstParticipantsSurveyReminderL2Flag.isEmpty()){
                System.debug(LoggingLevel.DEBUG, ' !@# lstParticipantsSurveyReminderL2Flag:' + lstParticipantsSurveyReminderL2Flag.size());
                // record history
                lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(true, lstParticipantsSurveyReminderL2Flag, outreachSurveyReminderSetting));
            }
            if(!lstParticipantsSurveyCatchup.isEmpty()){
                System.debug(LoggingLevel.DEBUG, ' !@# lstParticipantsSurveyCatchup:' + lstParticipantsSurveyCatchup.size());
                // record history
                lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(false, lstParticipantsSurveyCatchup, outreachSurveyCatchupSetting));
            }
            if(!lstParticipantsSurveyCatchupReminder.isEmpty()){
                System.debug(LoggingLevel.DEBUG, ' !@# lstParticipantsSurveyCatchupReminder:' + lstParticipantsSurveyCatchupReminder.size());
                // record history
                lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(false, lstParticipantsSurveyCatchupReminder, outreachSurveyCatchupReminderSetting));
            }
            if(!lstParticipantsSurveyCatchupReminderL2Flag.isEmpty()){
                System.debug(LoggingLevel.DEBUG, ' !@# lstParticipantsSurveyCatchupReminderL2Flag:' + lstParticipantsSurveyCatchupReminderL2Flag.size());
                // record history
                lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(true, lstParticipantsSurveyCatchupReminderL2Flag, outreachSurveyCatchupReminderSetting));
            }
            System.debug(LoggingLevel.DEBUG, ' !@# --------------------------------------------');
        }
    }

    /* ***************************************************************************** */
    public static List<SObject> getListParticipants(List<SObject> lstParticipants, Set<Id> setContactIds){
        System.debug(LoggingLevel.DEBUG, ' !@# --------------------------------------------');
        System.debug(LoggingLevel.DEBUG, ' !@# getListParticipants ');
        List<SObject> lstFilteredParticipants = new List<SObject>();
        if(!lstParticipants.isEmpty()){
            for(SObject sObj : lstParticipants){
                System.debug(LoggingLevel.DEBUG, ' !@# Object Type: ' + sObj.getSObjectType().getDescribe().getName());
                if(sObj.getSObjectType().getDescribe().getName() ==  Participant__c.SObjectType.getDescribe().getName()){
                    Participant__c p = (Participant__c)sObj;
                    System.debug(LoggingLevel.DEBUG, ' !@# Event Participant Contact : ' + p.Member_Contact__c);
                    if(!setContactIds.contains(p.Member_Contact__c)){
                        lstFilteredParticipants.add(p);
                    }
                }else{
                    Survey_Participant__c sp = (Survey_Participant__c)sObj;
                    System.debug(LoggingLevel.DEBUG, ' !@# Survey Participant Contact : ' + sp.Participant__c);
                    if(!setContactIds.contains(sp.Participant__c)){
                        lstFilteredParticipants.add(sp);
                    }
                }
            }
            System.debug(LoggingLevel.DEBUG, ' !@# lstFilteredParticipants:' + lstFilteredParticipants.size());
        }
        return lstFilteredParticipants;
    }


    /* ***************************************************************************** */
    public static List<Outreach_Notification_History__c> createOutreachNotificationHistory(Boolean L2Flag, List<SObject> lstSObjects, Outreach_Notification_Setting__c outreachNotificationSetting){
        System.debug(LoggingLevel.DEBUG, ' !@# --------------------------------------------');
        System.debug(LoggingLevel.DEBUG, ' !@# createOutreachNotificationHistory ');
        Datetime dtSchedule = Datetime.newInstance(System.today().year(), System.today().month(), System.today().day(),
                outreachNotificationSetting.Time__c.hour(), outreachNotificationSetting.Time__c.minute(), outreachNotificationSetting.Time__c.second());
        List<Outreach_Notification_History__c> lstOutreachNotificationHistories = new List<Outreach_Notification_History__c>();

        for(SObject sObj : lstSObjects){
            Outreach_Notification_History__c onhForSession = new Outreach_Notification_History__c();
            onhForSession.Outreach_Notification__c = outreachNotificationSetting.Outreach_Notification__c;
            if(L2Flag){
                onhForSession.Notes__c = Label.Outreach_Notification_L2_Flagged;
                if(outreachNotificationSetting.Type__c == Label.Outreach_Notification_Survey_Catchup_Reminder){
                    onhForSession.Notes__c = Label.Outreach_Notification_L2_Flagged + ' - ' + Label.Outreach_Notification_Survey_Catchup_Reminder;
                }else{
                    onhForSession.Notes__c = Label.Outreach_Notification_L2_Flagged + ' - ' + Label.Outreach_Notification_Survey_Reminder;
                }
            }else{
                onhForSession.Outreach_Notification_Setting__c = outreachNotificationSetting.Id;
                onhForSession.Schedule__c =  dtSchedule;
            }
            //Survey responses
            if(sObj.getSObjectType().getDescribe().getName() ==  Survey_Response__c.SObjectType.getDescribe().getName()){
                Survey_Response__c sr = (Survey_Response__c)sObj;
                onhForSession.Contact__c = sr.Contact__c;
                onhForSession.Related_To__c = sr.Survey__r.Name;
                onhForSession.Related_To_Id__c = sr.Survey__r.Id;
            }else if(sObj.getSObjectType().getDescribe().getName() ==  Participant__c.SObjectType.getDescribe().getName()){
                //Event Participants
                Participant__c p = (Participant__c)sObj;
                onhForSession.Contact__c = p.Member_Contact__c;
                onhForSession.Related_To__c = p.Event__r.Name;
                onhForSession.Related_To_Id__c = p.Event__c;
            }else if(sObj.getSObjectType().getDescribe().getName() ==  Survey_Participant__c.SObjectType.getDescribe().getName()){
                //Event Participants
                Survey_Participant__c sp = (Survey_Participant__c)sObj;
                onhForSession.Contact__c = sp.Participant__c;
                onhForSession.Related_To__c = sp.Survey__r.Name;
                onhForSession.Related_To_Id__c = sp.Survey__c;
            }
            lstOutreachNotificationHistories.add(onhForSession);
        }
        System.debug(LoggingLevel.DEBUG, ' !@# lstOutreachNotificationHistories:' + lstOutreachNotificationHistories.size());
        System.debug(LoggingLevel.DEBUG, ' !@# --------------------------------------------');
        return lstOutreachNotificationHistories;
    }



    /* ***************************************************************************** */
    public static Boolean checkIfTodayIsDueForNotification(Datetime dtSurveyDate, Integer iDays, String strType){

        System.debug(LoggingLevel.DEBUG, ' !@# --------------------------------------------');
        System.debug(LoggingLevel.DEBUG, ' !@# ' + strType);
        Boolean bReturn = false;
        System.debug(LoggingLevel.DEBUG, ' !@# Outreach Notification Setting Days :  ' +iDays);
        if(strType == Label.Outreach_Notification_Survey_Catchup){
            System.debug(LoggingLevel.DEBUG, ' !@# Days after Survey Catchup StartDate: ' + dtSurveyDate.date().daysBetween(System.now().date()));
            if(dtSurveyDate.date().daysBetween(System.now().date()) == iDays){
                bReturn = true;
            }
        }else if(strType == Label.Outreach_Notification_Survey_Reminder || strType == Label.Outreach_Notification_Survey_Catchup_Reminder){
            String strDate = (strType == Label.Outreach_Notification_Survey_Reminder) ? 'Survey EndDate' : 'Survey Catchup EndDate';
            System.debug(LoggingLevel.DEBUG, ' !@# Days prior to ' + strDate + ' : ' + System.now().date().daysBetween(dtSurveyDate.date()));
            if(System.now().date().daysBetween(dtSurveyDate.date()) == iDays){
                bReturn = true;
            }
        }else if(strType == Label.Outreach_Notification_Survey_Thank_you){
            System.debug(LoggingLevel.DEBUG, ' !@# Days after Survey Response CreatedDate: ' + dtSurveyDate.date().daysBetween(System.now().date()));
            if(dtSurveyDate.date().daysBetween(System.now().date()) == iDays){
                bReturn = true;
            }
        }
        return bReturn;
    }


    /* ***************************************************************************** */
    public static Map<Id, List<Participant__c>> getEventParticipants(Set<Id> setSurveyIds){
        Map<Id, List<Participant__c>> mapParticipantsByEventId = new Map<Id, List<Participant__c>>();
        Set<Id> setEventId = new Set<Id>();

        for(Survey__c survey : [SELECT Id, Event__c FROM Survey__c WHERE Id IN: setSurveyIds LIMIT : Limits.getLimitQueryRows()]){
            setEventId.add(survey.Event__c);
        }

        for(Event__c evt : [SELECT Id, Event_Id__c, Name, Outreach_Notification__c, Start_Date_Time__c, Time_Zone__c,
                                (SELECT Id, Member_Contact__c, Member_Contact__r.Name, Default_Member_Name__c, Event__c, Event__r.Name FROM Participants__r)
                                FROM Event__c WHERE Id IN: setEventId LIMIT : Limits.getLimitQueryRows()]){
            mapParticipantsByEventId.put(evt.Id, new List<Participant__c>(evt.Participants__r));
        }

        return mapParticipantsByEventId;
    }

    /* ***************************************************************************** */
    public static Map<Id, Survey__c> getSurveys(){
        System.debug(LoggingLevel.DEBUG, ' !@# Retrieve Surveys');
        Map<Id, Survey__c> mapSurveyById = new Map<Id, Survey__c>();

        for(Survey__c survey : [SELECT Id, Name, Journey_Milestone_Start_Date__c, Outreach_Notification__c, Journey_Milestone_End_Date__c,
                                    Event__c, Active__c, Catchup__c, Catchup_Start_Date__c, Catchup_End_Date__c,
                                 (SELECT Id,  Contact__c, CreatedDate, Survey__r.Name, Survey__c FROM Survey_Responses__r),
                                (SELECT Id, Survey__c, Survey__r.Name, Participant__c, CreatedDate FROM Survey_Participants__r)
                                    FROM Survey__c WHERE Outreach_Notification__c != NULL
                                     AND Active__c = TRUE LIMIT 2000]){
            mapSurveyById.put(survey.Id, survey);
        }

        return mapSurveyById;
    }

}