main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Educator</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Trainor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Parking_Lot__c/Parking_Lot__c.object-meta.xml
<CustomObject>
    <label>Parking Lot</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Parking Lot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parking Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Parking_Lot__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Domain</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Site Specific</fullName>
            </value>
            <value>
                <fullName>Functionality</fullName>
            </value>
            <value>
                <fullName>Preferences</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Permissions</fullName>
                <isActive>false</isActive>
                <label>Permissions</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Parking Lots</relationshipLabel>
    <relationshipName>Parking_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Raised_By__c.field-meta.xml
<CustomField>
    <fullName>Raised_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raised By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parking Lots</relationshipLabel>
    <relationshipName>Parking_Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a session that exists on the selected event</errorMessage>
        <filterItems>
            <field>$Source.Event__c</field>
            <operation>equals</operation>
            <valueField>Session__c.Event__c</valueField>
        </filterItems>
        <filterItems>
            <field>Session__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Parking Lots</relationshipLabel>
    <relationshipName>Parking_Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
            <value>
                <fullName>Statement BH</fullName>
                <isActive>false</isActive>
                <label>Statement BH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/CustomParkingLotFormHelper.cls
/**
* Description: This is the helper class for CustomParkingLotFormController, which creates a parking lot record
* Author: Jester Cabantog
* Version: 1.0
* Last modified date: 12/16/2020
**/

public with sharing class CustomParkingLotFormHelper {

    private static WithoutSharingClass withoutShare = new WithoutSharingClass(); 

    //PT-00333 Event Parking Lot
    public static void createParkingLotHelper(String eventId, String session, String email, String phone, String description, String type, String category){
        
        // Check a contact with entered email already exists to assign to the parking lot's raised by field
        // If no contacts found, a person account will be created along with a contact which will be used in the parking lot's raised by field
        String raisedById = checkContactExistsPL(email, phone);
        
        Parking_Lot__c newParkingLot = new Parking_Lot__c(
            Event__c = eventId,
            Session__c = session,
            Raised_By__c = raisedById,
            Description__c = description,
            Status__c = 'Open',
            Type__c = type,
            Category__c = category
        );

        try{
            //if(FlsUtils.isCreateable(newParkingLot, new List<String>{'Event__c','Session__c','Raised_By__c','Description__c','Status__c','Type__c'})){
                withoutShare.insertParkingLot(newParkingLot);
            //}
        } catch(DmlException e){
            throw new AuraHandledException(e.getMessage());
        }
    } 
    
    //PT-00333 Event Parking Lot
    // Check if a person account exists for the entered email
    public static String checkContactExistsPL(String email, String phone){
        List<Contact> contacts = new List<Contact>();
        if(FlsUtils.isAccessible('Contact', new List<String>{'Firstname','Lastname','Email'})){
            contacts = withoutShare.getContacts(email);
        }

        if (contacts.size() > 0){
            return contacts[0].Id;
        } else {
            String task_whoId = createContact(email, phone);
            return task_whoId;
        }
    }
	
	//START [00780] Fix Partking Lot and Contact Us Form - Jester 2/5/2021
    public static String createContact(String email, String phone){
        Contact conRecord = new Contact();
        conRecord.FirstName = '';
        conRecord.LastName = email;
        conRecord.Email = email;
        conRecord.Phone = phone;

        if(FlsUtils.isCreateable(conRecord, new List<String>{'FirstName','LastName','Email','Phone'})){
            withoutShare.insertContact(conRecord);
        }

        return conRecord.Id;
    }
    //END [00780] Fix Partking Lot and Contact Us Form - Jester 2/5/2021 

    //Needs inner class declared without sharing for guest users to retrieve relevant records
    private without sharing class WithoutSharingClass {

        public void insertParkingLot(Parking_Lot__c newParkingLot){
            insert newParkingLot;
        }

        public void insertContact(Contact conRecord){
            insert conRecord;
        }

        public List<Contact> getContacts(String email){
            return [SELECT Firstname, Lastname, Email FROM Contact WHERE Email = :email ORDER BY CreatedDate DESC LIMIT 1];
        }
    }
}