main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Educator</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Trainor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Checkpoint__c.field-meta.xml
<CustomField>
    <fullName>Checkpoint__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates milestone as checkpoint</description>
    <label>Checkpoint</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Milestone__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates Active milestone</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the milestone tagged as checkpoint</description>
    <label>Checkpoint Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone__c.Journey__c</field>
            <operation>equals</operation>
            <valueField>$Source.Journey__c</valueField>
        </filterItems>
        <filterItems>
            <field>Milestone__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Checkpoint</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Milestones &amp; Checkpoints</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Milestone__c/fields/Related_RecordId__c.field-meta.xml
<CustomField>
    <fullName>Related_RecordId__c</fullName>
    <description>Contains the related record id (Could be Event, Session, Survey or Communication)</description>
    <label>Related Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Milestone__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Indicates sort order of Milestone</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Milestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Milestone</description>
    <label>Journey Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attestation</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

main/default/objects/Participant_Milestone__c/Participant_Milestone__c.object-meta.xml
<CustomObject>
    <description>All milestones of participants</description>
    <label>Participant Milestone</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Participant Milestone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone__c/fields/Checkpoint__c.field-meta.xml
<CustomField>
    <fullName>Checkpoint__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates Checkpoint</description>
    <label>Checkpoint</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Checkpoint_Name__c.field-meta.xml
<CustomField>
    <fullName>Checkpoint_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Checkpoint</description>
    <label>Checkpoint Name</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones (Checkpoint Name)</relationshipLabel>
    <relationshipName>Checkpoints</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Checkpoint_Progress__c.field-meta.xml
<CustomField>
    <fullName>Checkpoint_Progress__c</fullName>
    <description>Checkpoint progress</description>
    <label>Checkpoint Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates active record</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey Participant</description>
    <label>Participant</label>
    <referenceTo>Journey_Participant__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Milestone</description>
    <label>Journey Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <description>Tracks the Milestone Progress</description>
    <formula>IF( Checkpoint__c , Checkpoint_Progress__c ,  Milestone_Progress__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/System_Generated__c.field-meta.xml
<CustomField>
    <fullName>System_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates system generated record</description>
    <label>System Generated</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/Participant_Milestone_Metric__c.object-meta.xml
<CustomObject>
    <description>Tracks the progress of participants milestone</description>
    <label>Participant Milestone Metric</label>
    <nameField>
        <displayFormat>PMM-{0000000}</displayFormat>
        <label>Participant Milestone Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestone Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone_Metric__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <description>Metric Completion Date</description>
    <label>Completion Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/fields/Metric_Used__c.field-meta.xml
<CustomField>
    <fullName>Metric_Used__c</fullName>
    <description>Metric Used</description>
    <label>Metric Used</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>Participants Milestone</description>
    <label>Milestone</label>
    <referenceTo>Participant_Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestone Metrics</relationshipLabel>
    <relationshipName>Participant_Milestone_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/fields/System_Generated__c.field-meta.xml
<CustomField>
    <fullName>System_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates System Generated record</description>
    <label>System Generated</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/journeyParticipantMilestoneServices.cls
public without sharing class journeyParticipantMilestoneServices {
    /*******************************************************************************
     * @author       Minh Ma
     * @date         03/28/2021
     * @description  method used in updateParticipantMilestone Aura component
     * @return       strResult
     * @revision     03/28/2021 - Minh Ma - Created
     *               05/04/2021 - Kyzer Buhay - Updated - Commented hard coded contact Id in query line 59-61 Method: getParticipantMilestone
     *               14/01/2022 - Dino Brinas - Migrated the logic to BatchSyncParticipantMilestoneMetric to handle large data
     *               19/01/2022 - APR - Fixed Query to exclude completed metrics
     *               10/08/2022 - Von Pernicia [CCN-1984]: Updated query to fix timeout issue
     *               11/11/2022 - Von Pernicia [CCN-2288]: Added "Failed" as part of the filter criteria
     *******************************************************************************/

    /*********** Auto Populating Jouney Participant Milestone Mectrics ***********/
    @AuraEnabled
    public static String updateParticipantMilestoneMetrics(Id jIds) {
        String strResult = 'running';
        String finalJourneyId ;
        String queryString;
        Set<Id> listJIDs = new Set<Id>();
        listJIDs.add(jIds);
        finalJourneyId = String.valueof(jIds);

        List<AsyncApexJob> aJob= [
                    SELECT Id, Status, ApexClassID 
                    FROM AsyncApexJob 
                    WHERE ApexClass.Name = 'BatchSyncParticipantMilestoneMetric' AND Status not in ('Completed', 'Aborted', 'Failed')
                    ];

        if(aJob.isEmpty()) {
            queryString = ' SELECT Id, Name, Completion_Date__c, Metric_Used__c, Milestone__c, System_Generated__c, ' +
            'Milestone__r.Name, ' +
            'Milestone__r.Journey__c, ' +
            'Milestone__r.Journey__r.Journey__c, ' +
            'Milestone__r.MileStone__r.Related_RecordId__c, ' +
            'Milestone__r.MileStone__r.Name, ' +
            'Milestone__r.Milestone__c, ' +
            'Milestone__r.Milestone__r.Parent__c, ' +
            'Milestone__r.Contact__c, ' +
            'Milestone__r.Type__c, ' +
            'Milestone__r.Checkpoint__c, ' +
            'Milestone__r.Sort_Order__c, ' +
            'Milestone__r.Progress__c, ' +
            'Milestone__r.Checkpoint_Name__c, ' +
            'Milestone__r.Checkpoint_Progress__c ' +
            'FROM Participant_Milestone_Metric__c ' +
            'WHERE Milestone__r.Journey__r.Journey__c =  \'' + String.valueOf(jIds) + '\' ' +
            'AND Milestone__r.Is_Active__c = TRUE ' +
            'ORDER BY Milestone__r.Journey__c, Milestone__r.Contact__c, Milestone__r.Sort_Order__c ';
            

            BatchSyncParticipantMilestoneMetric batchObj = new BatchSyncParticipantMilestoneMetric();
            batchObj.strQuery = queryString;
            batchObj.journeyId = finalJourneyId;
            Id batchProcessId = Database.executeBatch(batchObj,2000);
            strResult = '';
        }
        return strResult;

    }
}