main/default/objects/Communication__c/Communication__c.object-meta.xml
<CustomObject>
    <label>Communication</label>
    <nameField>
        <label>Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Communication__c/fields/Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Email_Date__c</fullName>
    <label>Email Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Communication__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Outbox</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/CommunicationTriggerHelper.cls
public with sharing class CommunicationTriggerHelper {
    public static void onBeforeInsert(List<Communication__c> newList){
        // 01103 - Ability to Add Date to Communications
        for(Communication__c newComm : newList){
            if(newComm.Email_Date__c == null && newComm.Status__c == 'Draft'){
                newComm.Email_Date__c = date.today().addDays(14);
            }
        }
    }
    // public static void onAfterInsert(Map<Id, Communication__c> newMap){
        
    // }
    // public static void onBeforeUpdate(Map<Id, Communication__c> newMap, Map<Id, Communication__c> oldMap){

    // }
    // public static void onAfterUpdate(Map<Id, Communication__c> newMap, Map<Id, Communication__c> oldMap){

    // }
    
    
}