main/default/objects/Communication__c/Communication__c.object-meta.xml
<CustomObject>
    <label>Communication</label>
    <nameField>
        <label>Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Communication__c/fields/Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Email_Date__c</fullName>
    <label>Email Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Communication__c/fields/Email_Recipient_BCC__c.field-meta.xml
<CustomField>
    <fullName>Email_Recipient_BCC__c</fullName>
    <inlineHelpText>Separate each email address with a comma</inlineHelpText>
    <label>Email Recipient BCC</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Communication__c/fields/Email_Recipient_CC__c.field-meta.xml
<CustomField>
    <fullName>Email_Recipient_CC__c</fullName>
    <inlineHelpText>Separate each email address with a comma</inlineHelpText>
    <label>Email Recipient CC</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Communication__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real-time</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Communication__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Communications</relationshipLabel>
    <relationshipName>Communications</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Communication__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Outbox</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Communication_Recipient__c/Communication_Recipient__c.object-meta.xml
<CustomObject>
    <label>Communication Recipient</label>
    <nameField>
        <displayFormat>CCCR{00000}</displayFormat>
        <label>CC Communication Recipient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Communication_Recipient__c/fields/CC_Communication__c.field-meta.xml
<CustomField>
    <fullName>CC_Communication__c</fullName>
    <label>CC Communication</label>
    <referenceTo>Communication__c</referenceTo>
    <relationshipName>CC_Communication_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Communication_Recipient__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Communication Recipients</relationshipLabel>
    <relationshipName>Communication_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Communication_Recipient__c/fields/Journey_Participant__c.field-meta.xml
<CustomField>
    <fullName>Journey_Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journey Participant</label>
    <referenceTo>Journey_Participant__c</referenceTo>
    <relationshipLabel>Communication Recipients</relationshipLabel>
    <relationshipName>Communication_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Communication_Recipient__c/fields/Send_as__c.field-meta.xml
<CustomField>
    <fullName>Send_as__c</fullName>
    <label>Send as</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>BCC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Email_Settings__c/Email_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Email_Settings</label>
</CustomObject>

main/default/objects/Email_Settings__c/fields/Default_Org_Wide_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Default_Org_Wide_Email_Id__c</fullName>
    <label>Default Org Wide Email Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Email_Settings__c/fields/Email_BCC_Limit_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Email_BCC_Limit_Error_Message__c</fullName>
    <label>Email BCC Limit Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Email_Settings__c/fields/Email_CC_Limit_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Email_CC_Limit_Error_Message__c</fullName>
    <label>Email CC Limit Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Email_Settings__c/fields/Email_Disabled_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Email_Disabled_Error_Message__c</fullName>
    <label>Email Disabled Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Email_Settings__c/fields/Email_Sent_Daily_Limit_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent_Daily_Limit_Error_Message__c</fullName>
    <label>Email Sent Daily Limit Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Email_Settings__c/fields/Email_To_Limit_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Email_To_Limit_Error_Message__c</fullName>
    <label>Email To Limit Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Email_Settings__c/fields/Email_Transaction_Limit_Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Email_Transaction_Limit_Error_Message__c</fullName>
    <label>Email Transaction Limit Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Email_Settings__c/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Email_Settings__c/fields/Max_Email_CC_BCC_Number__c.field-meta.xml
<CustomField>
    <fullName>Max_Email_CC_BCC_Number__c</fullName>
    <label>Max Email CC/BCC Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Email_Settings__c/fields/Max_Email_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Max_Email_To_Number__c</fullName>
    <label>Max Email To Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;For Review&quot;</defaultValue>
    <description>Status of the Journey</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey_Participant__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/CommunicationTriggerHelperTest.cls
@isTest
private class CommunicationTriggerHelperTest {
	
	@testSetup
    static void setup(){
        String alias = 'tstSysAd';
        Profile profile = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User sysad = new User(
            Username=alias+'@test.com', Alias=alias, CommunityNickname=alias, TimeZoneSidKey='America/Chicago', 
            LocaleSidKey='en_US', EmailEncodingKey='ISO-8859-1', LanguageLocaleKey='en_US',
            FirstName=alias, LastName=alias, Email=alias+'@test.com', ProfileId=profile.Id, Department = 'Test');
        insert sysad;
        
		//create email template
		EmailTemplate validEmailTemplate = new EmailTemplate();
		validEmailTemplate.isActive = true;
		validEmailTemplate.Name = 'unique_name_test_emailtemplate';
		validEmailTemplate.DeveloperName = 'unique_name_test_emailtemplate';
		validEmailTemplate.TemplateType = 'text';
		validEmailTemplate.FolderId = UserInfo.getUserId();
		validEmailTemplate.Subject = 'Test Template Subject';
		insert validEmailTemplate;
        
		System.runAs(sysad) {
            //create Account
            Account testAccount = new Account(Name='EmailUtilityTestAccount');
            insert testAccount;
            
            //create Contact
            List<Contact> contactList = new List<Contact>();
            for(Integer i=0;i<10;i++){
                contactList.add(new Contact(FirstName='EmailUtility', LastName='TestContact'+i, AccountId=testAccount.Id, Email='test_'+i+'@testEmailUtility.test'));
            }
            insert contactList;
            
            //create Journey__c
            Journey__c testJourney = new Journey__c(Name='EmailUtilityTestJourney');
            insert testJourney;
            
            //create Journey_Participant__c
            List<Journey_Participant__c> jpList = new List<Journey_Participant__c>();
            for(Contact cnt:contactList){
                jpList.add(new Journey_Participant__c(Journey__c=testJourney.Id, Contact__c=cnt.Id));
            }
            insert jpList;
            
            //create CommunicScheduliation__c record;
            Communication__c testRecord = new Communication__c();
            testRecord.Name = '';
            testRecord.Status__c = 'Draft';
            testRecord.Frequency__c = 'Real-time';
            testRecord.Active__c = true;
            testRecord.Subject__c = 'Test Comm Subject';
            testRecord.Body__c = 'Test Comm HTML Body';
            testRecord.Email_Recipient_CC__c = 'testCC1@testEmailUtility.test, testCC2@testEmailUtility.test, testCC3@testEmailUtility.test, testCC4@testEmailUtility.test';
            testRecord.Email_Recipient_BCC__c = 'testBCC1@testEmailUtility.test, testBCC2@testEmailUtility.test, testBCC3@testEmailUtility.test, testBCC4@testEmailUtility.test';
            testRecord.OwnerId = UserInfo.getUserId();
            insert testRecord;
            
            //create Communication_Recipient__c
            List<Communication_Recipient__c> crList = new List<Communication_Recipient__c>();
            for(Journey_Participant__c jp:jpList){
                //CCN-1004 Xen Reyes January 25, 2022
                crList.add(new Communication_Recipient__c(CC_Communication__c=testRecord.Id, Journey_Participant__c=jp.Id, Send_as__c = 'To'));
            }
            insert crList;
        }
	}
    
    static void populateActiveSettings(){
     	Email_Settings__c settings = new Email_Settings__c();
        settings.Default_Org_Wide_Email_Id__c = 'nicole@ulapp.co';
        settings.Email_BCC_Limit_Error_Message__c = 'Maximum Email BCC Address Count Reached: 25.';
        settings.Email_CC_Limit_Error_Message__c = 'Maximum Email CC Address Count Reached: 25.';
        settings.Email_Disabled_Error_Message__c = 'Email Sending is disabled in settings.';
        settings.Email_Sent_Daily_Limit_Error_Message__c = 'Maximum Daily Email Sent Reached: 5000.';
        settings.Email_To_Limit_Error_Message__c = 'Maximum Email To Address Count Reached: 100.';
        settings.Email_Transaction_Limit_Error_Message__c = 'Maximum Transaction Email Sent Reached: 10.';
        settings.isActive__c = true;
        settings.Max_Email_CC_BCC_Number__c = 5;
        settings.Max_Email_To_Number__c = 11;
        insert settings;
    }
    
    static void populateLowSettings(){
     	Email_Settings__c settings = new Email_Settings__c();
        settings.Default_Org_Wide_Email_Id__c = 'nicole@ulapp.co';
        settings.Email_BCC_Limit_Error_Message__c = 'Maximum Email BCC Address Count Reached: 25.';
        settings.Email_CC_Limit_Error_Message__c = 'Maximum Email CC Address Count Reached: 25.';
        settings.Email_Disabled_Error_Message__c = 'Email Sending is disabled in settings.';
        settings.Email_Sent_Daily_Limit_Error_Message__c = 'Maximum Daily Email Sent Reached: 5000.';
        settings.Email_To_Limit_Error_Message__c = 'Maximum Email To Address Count Reached: 100.';
        settings.Email_Transaction_Limit_Error_Message__c = 'Maximum Transaction Email Sent Reached: 10.';
        settings.isActive__c = true;
        settings.Max_Email_CC_BCC_Number__c = 5;
        settings.Max_Email_To_Number__c = 5;
        insert settings;
    }
    
    //happy path test for CommunicationTriggerHelper.onBeforeInsert()
    static testMethod void test_onBeforeInsert_positive_withDate(){

        EmailTemplate emailTemplate = Database.query(EmailUtility.getCreatableFieldsSOQL('EmailTemplate','DeveloperName =\'Event_Invitation_Template\''));
        Communication__c testRecord = new Communication__c();
        testRecord.Name = 'Positive Test Comms';
        testRecord.Status__c = 'Draft';
        testRecord.Frequency__c = 'Real-time';
        testRecord.Active__c = true;
        testRecord.Subject__c = 'Test Subject';
        testRecord.Body__c = 'Test HTML Body';
        testRecord.Email_Date__c = Date.newInstance(2021, 7, 1);
        testRecord.OwnerId = UserInfo.getUserId();

        test.startTest();
        insert testRecord;
        test.stopTest();

        Communication__c afterTestRecord = [SELECT Email_Date__c FROM Communication__c WHERE Id = :testRecord.Id];
        System.assertEquals(Date.newInstance(2021, 7, 1), afterTestRecord.Email_Date__c);
    }

    static testMethod void test_onBeforeInsert_positive_noDate(){

        EmailTemplate emailTemplate = Database.query(EmailUtility.getCreatableFieldsSOQL('EmailTemplate','DeveloperName =\'Event_Invitation_Template\''));
        Communication__c testRecord = new Communication__c();
        testRecord.Name = 'Positive Test Comms';
        testRecord.Status__c = 'Draft';
        testRecord.Frequency__c = 'Real-time';
        testRecord.Active__c = true;
        testRecord.Subject__c = 'Test Subject';
        testRecord.Body__c = 'Test HTML Body';
        testRecord.OwnerId = UserInfo.getUserId();

        test.startTest();
        insert testRecord;
        test.stopTest();

        Communication__c afterTestRecord = [SELECT Email_Date__c FROM Communication__c WHERE Id = :testRecord.Id];
        System.assertEquals(Date.today().addDays(14), afterTestRecord.Email_Date__c);
    }

    static testMethod void test_onBeforeInsert_negative(){
        EmailTemplate emailTemplate = Database.query(EmailUtility.getCreatableFieldsSOQL('EmailTemplate','DeveloperName =\'Event_Invitation_Template\''));
        Communication__c testRecord = new Communication__c();
        testRecord.Name = 'Negative Test Comms';
        testRecord.Status__c = 'Sent';
        testRecord.Frequency__c = 'Real-time';
        testRecord.Active__c = true;
        testRecord.Subject__c = 'Test Subject';
        testRecord.Body__c = 'Test HTML Body';
        testRecord.OwnerId = UserInfo.getUserId();

        test.startTest();
        insert testRecord;
        test.stopTest();

        Communication__c afterTestRecord = [SELECT Email_Date__c FROM Communication__c WHERE Id = :testRecord.Id];
        System.assertEquals(null, afterTestRecord.Email_Date__c);
    }
}