main/default/objects/Communication__c/Communication__c.object-meta.xml
<CustomObject>
    <label>Communication</label>
    <nameField>
        <label>Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Communication__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Communications</relationshipLabel>
    <relationshipName>Communications</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Communication__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates Milestone</description>
    <label>Milestone</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Communication_Recipient__c/Communication_Recipient__c.object-meta.xml
<CustomObject>
    <label>Communication Recipient</label>
    <nameField>
        <displayFormat>CCCR{00000}</displayFormat>
        <label>CC Communication Recipient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Communication_Recipient__c/fields/CC_Communication__c.field-meta.xml
<CustomField>
    <fullName>CC_Communication__c</fullName>
    <label>CC Communication</label>
    <referenceTo>Communication__c</referenceTo>
    <relationshipName>CC_Communication_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Communication_Recipient__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Communication Recipients</relationshipLabel>
    <relationshipName>Communication_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Communication_Recipient__c/fields/Send_as__c.field-meta.xml
<CustomField>
    <fullName>Send_as__c</fullName>
    <label>Send as</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>BCC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

main/default/classes/CommunicationRecipientTriggerHandler.cls
/*******************************************************************************************
  * @name: CommunicationRecipientTriggerHandler
  * @author: Von Pernicia
  * @created: 03-02-2022
  * @description: Handler for all the logic of the trigger for the Communication Recipient object
*********************************************************************************************/
public class CommunicationRecipientTriggerHandler {

    public static boolean bPreventAI = false;
    public static boolean bPreventAU = false;

    /*******************************************************************************************
    * @author: Von Pernicia
    * @created: 03-02-2022
    * @description: logic after update
    *
    * Changes (version)
    * -------------------------------------------------------------------------------------------
    *             No.   Date(dd-mm-yyy)   Author                Description
    *             ----  ---------------   --------------------  ---------------------------------
    * @version    1.0   03-02-2022        Von Pernicia          [CCN-496] Consolidate list of journey upon populating Date Sent field to update Participant Milestone Metrics
     *********************************************************************************************/
    public static void onAfterUpdate(List<Communication_Recipient__c> newCommRecipientList, Map<Id,Communication_Recipient__c> newCommRecipientMap, 
                                     List<Communication_Recipient__c> oldCommRecipientList, Map<Id,Communication_Recipient__c> oldCommRecipientMap){

        List<Id> comRecList = new List<Id>();

        for (Communication_Recipient__c cr: newCommRecipientList) {
            comRecList.add(cr.id);
        }

        Map<String, List<String>> journeyIdMap = new Map<String, List<String>> ();
        for (Communication_Recipient__c cr: [SELECT id, Contact__c, CC_Communication__c, CC_Communication__r.Journey__c, Date_Sent__c
                                        FROM Communication_Recipient__c 
                                        WHERE id in: comRecList 
                                        AND Contact__c != NULL
                                        AND CC_Communication__r.Milestone__c = TRUE
                                        AND CC_Communication__r.Journey__c <> NULL
                                        AND Send_as__c = 'To']) //XEN REYES Mar 14, 2022 CCN-1004
        {
            if (newCommRecipientMap.get(cr.id).Date_Sent__c <> oldCommRecipientMap.get(cr.id).Date_Sent__c) {

                if (!journeyIdMap.containsKey(cr.CC_Communication__r.Journey__c)) {

                    List<String> contactIdList = new List<String>{ cr.Contact__c };
                    journeyIdMap.put(cr.CC_Communication__r.Journey__c, contactIdList);
                }
            }
        }
     
        if (journeyIdMap.size() > 0) {
            BatchProcessorUtility.insertBatchRecord(journeyIdMap, 'BatchSyncParticipantMilestoneMetric','CommunicationRecipientTriggerHandler');
        }  
        
       
        
    }
        
    
}