main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Survey_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Reminder_Message__c</fullName>
    <label>Survey Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Participant__c/fields/Survey_Thank_You_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Thank_You_Message__c</fullName>
    <label>Survey Thank You Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field determines if a survey is active. Each event/session can only have one active survey at a time.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Catchup_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Message__c</fullName>
    <label>Survey Catch-Up Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Catchup_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Reminder_Message__c</fullName>
    <label>Survey Catch-Up Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Participant__c/Survey_Participant__c.object-meta.xml
<CustomObject>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that has been selected as a participant for a survey</description>
    <inlineHelpText>Contact that has been selected as a participant for a survey</inlineHelpText>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <description>Survey that the contact has been selected to participate to</description>
    <inlineHelpText>Survey that the contact has been selected to participate to</inlineHelpText>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Catchup_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Message__c</fullName>
    <label>Survey Catch-Up Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Catchup_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Reminder_Message__c</fullName>
    <label>Survey Catch-Up Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Reminder_Message__c</fullName>
    <label>Survey Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Thank_You_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Thank_You_Message__c</fullName>
    <label>Survey Thank You Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/TriggerSettings__c/TriggerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>These settings determine if a trigger has been disabled.</description>
    <label>Trigger Settings</label>
</CustomObject>

main/default/objects/TriggerSettings__c/fields/SurveyTriggerDisabled__c.field-meta.xml
<CustomField>
    <fullName>SurveyTriggerDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SurveyTriggerDisabled</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/SurveyTriggerHandler.cls
public with sharing class SurveyTriggerHandler {
    // Allows unit tests (or other code) to disable this trigger for the transaction
    public static Boolean TriggerDisabled = false;
 
    /*
        Checks to see if the trigger has been disabled either by custom setting or by running code
    */
    public Boolean IsDisabled(){
        if (TriggerSettings__c.getInstance().SurveyTriggerDisabled__c)
            return true;
        else
            return TriggerDisabled;
    }
 
    public static void onBeforeInsert(List<SObject> newItems, Map<Id, SObject> newItemMap) {
        // Check if Active__c is checked
        List<Survey__c> surveysToProcess = new List<Survey__c>();
        for (Survey__c s : (List<Survey__c>)newItems){
            if (s.Active__c) surveysToProcess.add(s);
        }
        SurveyTriggerHelper.checkExistingActiveSurveys(surveysToProcess);

        SurveyTriggerHelper.setSurveyCode(newItems);

        //XEN REYES CCN-SUR-3235-DV 14 July 2023
        SurveyTriggerHelper.setSiteValues(newItems);
    }

    public static void onBeforeUpdate(List<SObject> newItems, Map<Id, SObject> newItemsMap, List<SObject> oldItems, Map<Id, SObject> oldItemsMap) {
        // Check if the Active__c field has been updated and checked
        Map<Id, Survey__c> newSurveys = (Map<Id, Survey__c>)newItemsMap;
        Map<Id, Survey__c> oldSurveys = (Map<Id, Survey__c>)oldItemsMap;
        List<Survey__c> surveysToProcess = new List<Survey__c>();
        for (Survey__c s : newSurveys.values()){
            if ((s.Active__c == true) && (s.Active__c != oldSurveys.get(s.Id).Active__c)){
                surveysToProcess.add(s);
            }
        }
        SurveyTriggerHelper.checkExistingActiveSurveys(surveysToProcess);

        SurveyTriggerHelper.setSurveyCode(newItems);
    }
 
    /**
    public void BeforeDelete(Map<Id, SObject> oldItems) {}
 
    public void AfterInsert(Map<Id, SObject> newItems) {}
 
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) {}
 
    public void AfterDelete(Map<Id, SObject> oldItems) {}
 
    public void AfterUndelete(Map<Id, SObject> oldItems) {}
    **/
    
    // Added by RLugpatan [CCN-1049] Jan052022
    public static void syncSurveyRichTextFields(Map<Id,Survey__c > newMap) {
        Map<Id, Survey__c> eventToSurveyMap = new Map<Id, Survey__c>();
        List<sObject> recordsToUpdate = new List<sObject>();
        
        for(Survey_Participant__c sp : [SELECT Id, Survey_Thank_You_Message__c, Survey_Catchup_Reminder_Message__c, Survey_Catchup_Message__c, 
                                         Survey_Reminder_Message__c, Survey__r.Survey_Thank_You_Message__c, Survey__r.Survey_Catchup_Reminder_Message__c, 
                                         Survey__r.Survey_Catchup_Message__c, Survey__r.Survey_Reminder_Message__c
                                         FROM Survey_Participant__c WHERE Survey__c IN :newMap.keySet()]) { 
                                             sp.Survey_Thank_You_Message__c = sp.Survey__r.Survey_Thank_You_Message__c;
                                             sp.Survey_Catchup_Message__c = sp.Survey__r.Survey_Catchup_Message__c;
                                             sp.Survey_Catchup_Reminder_Message__c = sp.Survey__r.Survey_Catchup_Reminder_Message__c;
                                             sp.Survey_Reminder_Message__c = sp.Survey__r.Survey_Reminder_Message__c;
                                             recordsToUpdate.add(sp);
                                         }
        
        // Added by PQuiambao [CCN-1049] Jan082022
        for(Survey__c s : newMap.values()) {
            eventToSurveyMap.put(s.Event__c, s);
        }
        
        // Added by PQuiambao [CCN-1049] Jan082022
        for(Participant__c p : [SELECT Id, Event__c, Survey_Catchup_Message__c, Survey_Catchup_Reminder_Message__c, Survey_Reminder_Message__c, Survey_Thank_You_Message__c
                                FROM Participant__c WHERE Event__c IN :eventToSurveyMap.keySet()]) {
                                    Survey__c survey = eventToSurveyMap.get(p.Event__c);
                                    p.Survey_Thank_You_Message__c = survey.Survey_Thank_You_Message__c;
                                    p.Survey_Catchup_Message__c = survey.Survey_Catchup_Message__c;
                                    p.Survey_Catchup_Reminder_Message__c = survey.Survey_Catchup_Reminder_Message__c;
                                    p.Survey_Reminder_Message__c = survey.Survey_Reminder_Message__c;
                                    recordsToUpdate.add(p);
                                }
        try{
            if(!recordsToUpdate.isEmpty()){
                update recordsToUpdate;
            }
        }catch (Exception err) {
            System.Debug('TRY-CATCH-Exception-->' + err);
        }
        
    }
}