main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Location_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Event__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Internal_Resource_Role__c/Internal_Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Internal Resource Role</label>
    <nameField>
        <displayFormat>IRN-{0000}</displayFormat>
        <label>Internal Resource Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Resource_Role__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Internal Resource Roles</relationshipLabel>
    <relationshipName>Internal_Resource_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of milestone</description>
    <label>Journey Milestone Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Milestone__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Milestones &amp; Checkpoints</relationshipLabel>
    <relationshipName>Milestones_Checkpoints</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <description>This field is populated by a process upon the creation of a session record. It stores the ID of the contact linked to this session so guest user can query sessions without being given read permission on Contact object.</description>
    <label>ContactId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Do_Not_Send_Calendar_Invite__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Send_Calendar_Invite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Send Calendar Invite</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Campaign End Date</description>
    <formula>Campaign__r.EndDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Meeting_Info__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Info__c</fullName>
    <label>Meeting Info</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates Milestone</description>
    <label>Milestone</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Session__c/fields/Propose_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Propose_End_Date_Time__c</fullName>
    <label>Propose End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session__c/fields/Propose_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Propose_Start_Date_Time__c</fullName>
    <label>Propose Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <formula>TEXT( DATEVALUE(Session__r.Start_Date_Time__c) ) &amp; &quot; to &quot; &amp; TEXT( DATEVALUE(Session__r.End_Date_Time__c) )</formula>
    <label>Session Date</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Details__c.field-meta.xml
<CustomField>
    <fullName>Session_Details__c</fullName>
    <label>Session Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Details_Full__c.field-meta.xml
<CustomField>
    <fullName>Session_Details_Full__c</fullName>
    <description>For email template to show full month for session dates</description>
    <label>Session Details Full</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Id__c.field-meta.xml
<CustomField>
    <fullName>Session_Id__c</fullName>
    <label>Session Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Session__c/fields/Session_Location__c.field-meta.xml
<CustomField>
    <fullName>Session_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session Location</label>
    <referenceTo>Session_Location__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Sign_Up_Instructions_2__c.field-meta.xml
<CustomField>
    <fullName>Sign_Up_Instructions_2__c</fullName>
    <description>Holds the instructions for Sign-up</description>
    <label>Sign Up Instructions</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Sign_Up_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Sign_Up_Instructions__c</fullName>
    <description>Holds the instructions for Sign-up</description>
    <label>Sign Up Instructions (Deprecated)</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Session__c/fields/Start_Date_2__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_2__c</fullName>
    <formula>Start_Date_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session__c/fields/Start_Date_Time2__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time2__c</fullName>
    <label>Start Date Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Start_Date_Time_2__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time_2__c</fullName>
    <formula>Start_Date_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session__c/fields/User_Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>User_Time_Zone__c</fullName>
    <formula>TEXT($User.TimeZoneSidKey)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is the Timezone of the logged-in user.</inlineHelpText>
    <label>User Time Zone</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Role__c/Session_Role__c.object-meta.xml
<CustomObject>
    <description>01080 - Custom object for Session Role</description>
    <label>Session Role</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Session Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Session_Role__c/fields/Number_of_Role__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Role__c</fullName>
    <description>Number of Roles in a Session</description>
    <label>Number of Role</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Session_Role__c/fields/Role_Description__c.field-meta.xml
<CustomField>
    <fullName>Role_Description__c</fullName>
    <description>Description of Role</description>
    <label>Role Description</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Session_Role__c/fields/Role_Title__c.field-meta.xml
<CustomField>
    <fullName>Role_Title__c</fullName>
    <description>Title of the Role</description>
    <label>Role Title</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Role__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Session</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Roles</relationshipLabel>
    <relationshipName>Session_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/CloneSessionController.cls
/**
 * @description       : [CCN-EVE-1244-DV] CloneSessionController
 * @author            : adavid@ulapp.co
 * @group             : 
 * @last modified on  : 06-29-2022
 * @last modified by  : adavid@ulapp.co
 * @version     1.0     29-03-2022  Aaron David [CCN-EVE-1244-DV] Initial version.
 *              2.0     18-08-2022  Xen Reyes   [CCN-EVE-2067-DV] - Changed references of Sign_Up_Instructions__c to Sign_Up_Instructions_2__c due to field deprecation.
**/

public with sharing class CloneSessionController {

    /**
    * @description cloneSessionRecord [CCN-EVE-1244-DV]
    *   Clone Session record with its related Session Roles
    * @author adavid@ulapp.co | 03-29-2022 
    * @param sessionId 
    * @return String 
    **/
    @AuraEnabled
    public static String cloneSessionRecord(Id sessionId){
        String returnMsg;
        List<Session_Role__c> newSessionRoles = new List<Session_Role__c>();
		List<Internal_Resource_Role__c> newInternalRoles = new List<Internal_Resource_Role__c>();
        try{
            //Session

            //Start CCN-EVE-2067-DV Xen Reyes
            Session__c sessionCurrent = [Select Id, Name, IsActive__c, Contact__c, ContactId__c, Description__c, Do_Not_Send_Calendar_Invite__c, End_Date__c, End_Date_Time__c, Event__c, Event_Id__c, Location__c, Meeting_Info__c, Meeting_URL__c, Milestone__c, Propose_End_Date_Time__c, Propose_Start_Date_Time__c, Session__c, Session_Date__c, Session_Details__c, Session_Details_Full__c, Session_Location__c, Sign_Up_Instructions_2__c, Start_Date_2__c, Start_Date_Time_2__c, Start_Date_Time__c, Start_Date_Time2__c, Status__c, Subtitle__c, Time_Zone__c, User_Time_Zone__c, Virtual_Meeting_URL__c
            From Session__c
            Where Id =: sessionId LIMIT 1];
            //End CCN-EVE-2067-DV Xen Reyes

            CCEventTriggerHandler cc = new CCEventTriggerHandler();
            Session__c clonedSession = sessionCurrent.clone(false, true, false, false);  
            clonedSession.Name = clonedSession.Name+' Copy';
            //Start CCN-3213 defaulting Status to Planned and set propose start/end date time to blank - GabDelavin - 07/03/2023
             clonedSession.Status__c = 'Planned';
             clonedSession.Propose_Start_Date_Time__c = null;
             clonedSession.Propose_End_Date_Time__c = null;
             //End CCN-3213 defaulting Status to Planned and set propose start/end date time to blank - GabDelavin - 07/03/2023
            clonedSession.Session_Id__c = cc.getToken();

            Database.SaveResult srSession = Database.insert(clonedSession, false);

            // Iterate through each returned result
            
            if (srSession.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                //Session Roles
                List<Session_Role__c> sessionRoles = [Select Id, Name, Number_of_Role__c, Role_Description__c, Role_Title__c, Session__c
                From Session_Role__c
                Where Session__c =: sessionId];

                for(Session_Role__c s: sessionRoles){
                    Session_Role__c sessionRole = new Session_Role__c();
                    sessionRole = s.clone(false, true, false, false);
                    sessionRole.Session__c = clonedSession.Id;
                    newSessionRoles.add(sessionRole);
                }

                if(newSessionRoles.size() > 0){
                    Database.SaveResult[] srSessionRoles = Database.insert(newSessionRoles, false);
                    // Iterate through each returned result
                    for (Database.SaveResult sr : srSessionRoles) {
                        if (sr.isSuccess()) {
                            // Operation was successful, so get the ID of the record that was processed
                        }
                        else {
                            // Operation failed, so get all errors                
                            for(Database.Error err : sr.getErrors()) {
                                System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            }
                        }
                    }
                }
               /*Start- Added by Gab as part of CCN-EVE-3295-DV to clone Internal Resource if Session is Cloned 7/21/2023*/ 
                List<Internal_Resource_Role__c> internalRolesList = [Select Id, Session__c, Internal_Resource_Number_of_Role__c, Internal_Resource_Role_Description__c, Internal_Resource_Role_Title__c from Internal_Resource_Role__c where Session__c =: sessionId];
                If(internalRolesList.Size()>0){
                    for(Internal_Resource_Role__c s: internalRolesList){
                        Internal_Resource_Role__c InternalRole = new Internal_Resource_Role__c();
                        InternalRole = s.clone(false, true, false, false);
                        InternalRole.Session__c = clonedSession.Id;
                        newInternalRoles.add(InternalRole);
                    } 
                }
                
                if(newInternalRoles.size() > 0){
                    Database.SaveResult[] srInternalRoles = Database.insert(newInternalRoles, false);
                    // Iterate through each returned result
                    for (Database.SaveResult sr : srInternalRoles) {
                        if (sr.isSuccess()) {
                            // Operation was successful, so get the ID of the record that was processed
                        }
                        else {
                            // Operation failed, so get all errors                
                            for(Database.Error err : sr.getErrors()) {
                                System.debug(err.getStatusCode() + ': ' + err.getMessage());
                            }
                        }
                    }
                }
            /*End- Added by Gab as part of CCN-EVE-3295-DV to clone Internal Resource if Session is Cloned 7/21/2023*/ 
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : srSession.getErrors()) {
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                }
            }
           
            returnMsg = clonedSession.Id;

        }
        catch(Exception ex){
            system.debug('CloneSessionController Error>>> '+ex.getMessage()+ex.getLineNumber());
            returnMsg = 'Error>>>'+ex.getMessage();
        }

        return returnMsg;
    }
}