main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/ChangeEventTypeAction__c.field-meta.xml
<CustomField>
    <fullName>ChangeEventTypeAction__c</fullName>
    <description>Hidden field created for triggering MS Teams integration when the Event Type or Virtual Meeting Platform is updated via ChangeEventType Aura Component</description>
    <label>ChangeEventTypeAction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Meeting_Info__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Info__c</fullName>
    <label>Meeting Info</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/MS_Teams_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_Teams_Id__c</fullName>
    <description>MS Team Integration - Meeting Id</description>
    <label>MS Teams Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/classes/AzureAPIBatch.cls
/******************************************************************************    
* AzureAPIBatch - Class for Batch Processing Azure API
*            No.  Date(dd-mm-yyy) Author            Description
*           ----  ---------   --------------------  -----------------------------
* @version   1.0  23-05-2023   Rex David            [CCN-EVE-3056-DV] Virtual Meeting Integration (POC: Microsoft Teams Link)
******************************************************************************/
global class AzureAPIBatch implements database.Batchable<sObject>,Database.AllowsCallouts,Database.Stateful {
    
    public List<Session__c> sessionListToProcess = new List<Session__c>();
    public List<Session__c> sessionToUpdateList = new List<Session__c>();
    public String integAction = '';

    global AzureAPIBatch(String integAction, List<Session__c> sessionList) { 
        this.integAction = integAction;
        sessionListToProcess = sessionList;
    }

    global Database.querylocator start(Database.BatchableContext BC){
        string query = 'SELECT Id, Event__c, Event__r.ChangeEventTypeAction__c, Time_Zone__c, Start_Date_Time__c, End_Date_Time__c, Name, Meeting_Info__c, Meeting_URL__c, MS_Teams_Id__c FROM Session__c WHERE Id IN: sessionListToProcess';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        List<Session__c> sessionList = (List<Session__c>)scope;
    
        for(Session__c session : sessionList){
           
            if(LIMITS.getCallouts() < LIMITS.getLimitCallouts()){
                session.Meeting_URL__c = AzureAPI.processMeetingUrl(integAction,session).Meeting_URL__c;
                if(session.Meeting_URL__c != 'MSTeamsNotSetup') sessionToUpdateList.add(session);
            }
        }

    }

    global void finish(Database.BatchableContext BC){
        if(!sessionToUpdateList.isEmpty()){
            try{
                update sessionToUpdateList;
            }
            catch (Exception ex){
                System.debug(ex);
            }    
        }
    }
}