main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field determines if a survey is active. Each event/session can only have one active survey at a time.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Survey__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Survey description that will be displayed in the survey page</description>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/fields/Disclaimer__c.field-meta.xml
<CustomField>
    <fullName>Disclaimer__c</fullName>
    <label>Disclaimer</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Logo_Image_Id__c.field-meta.xml
<CustomField>
    <fullName>Logo_Image_Id__c</fullName>
    <label>Logo Image Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Survey_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Surveys (Campaign)</relationshipLabel>
    <relationshipName>CampaignSurveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Logo__c.field-meta.xml
<CustomField>
    <fullName>Survey_Logo__c</fullName>
    <formula>IF(ISBLANK( Survey_Logo_URL__c ) ,&apos;&apos;,  IMAGE( Survey_Logo_URL__c ,&apos;Survey Logo&apos;, 50 ,50))</formula>
    <label>Survey Logo</label>
    <type>Text</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Survey_Logo_URL__c</fullName>
    <formula>IF( ISBLANK( Logo_Image_Id__c ),&apos;&apos;, &apos;/sfc/servlet.shepherd/version/download/&apos;+Logo_Image_Id__c)</formula>
    <label>Survey Logo URL</label>
    <type>Text</type>
</CustomField>

main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey_Question__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Question displayed in the survey</description>
    <label>Description</label>
    <length>12000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Max_Value__c.field-meta.xml
<CustomField>
    <fullName>Max_Value__c</fullName>
    <label>Max Value</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Min_Value__c.field-meta.xml
<CustomField>
    <fullName>Min_Value__c</fullName>
    <label>Min Value</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <inlineHelpText>For multi-select question, provide more than one choice and it should be on its own line.</inlineHelpText>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <label>Free text</label>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
                <label>Radio buttons</label>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Multi-select</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Survey_Question__c/fields/Sorting_Order__c.field-meta.xml
<CustomField>
    <fullName>Sorting_Order__c</fullName>
    <label>Sorting Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Question</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/SurveyServices.cls
/*
 * @filename        : SurveyServices
 * @created         : 01.19.2021
 * @author          : JL
 * @description     : Service Class for Survey__c
 */
public with sharing class SurveyServices {
  public static String CLONED_SURVEY_NAME_IDENTIFIER = 'Copy of';
  public static String CLONED_SUCCESS_MESSAGE = 'survey cloned successfully';
  public static String GET_RECORD_FAIL_MESSAGE = 'record not found';
  public static String GET_RECORD_SUCCESS_MESSAGE = 'record found';

  @AuraEnabled
  public static Map<String, Object> getSurveyDetails(Id surveyId) {
    Map<String, Object> returnData = new Map<String, Object>();
    Boolean hasError = true;
    String message = GET_RECORD_FAIL_MESSAGE;
    List<Survey__c> soqlResults = new List<Survey__c>();
    if (
      surveyId != null &&
      surveyId.getSobjectType() == Schema.Survey__c.SObjectType
    ) {
      if (
        FlsUtils.isAccessible(
          'Survey__c',
          new List<String>{
            'Name',
            'Active__c',
            'Survey_Campaign__c',
            'Disclaimer__c',
            'Event__c',
            'Logo_Image_Id__c',
            'OwnerId',
            'Survey_Logo__c',
            'Survey_Logo_URL__c'
          }
        )
      ) {
        soqlResults = [
          SELECT
            Id,
            Name,
            Active__c,
            Survey_Campaign__c,
            Disclaimer__c,
            Event__c,
            Logo_Image_Id__c,
            OwnerId,
            Survey_Logo__c,
            Survey_Logo_URL__c,
            (
              SELECT
                Id,
                Name,
                Description__c,
                Max_Value__c,
                Min_Value__c,
                Options__c,
                Question_Type__c,
                Sorting_Order__c,
                Step__c,
                Survey__c
              FROM Survey_Questions__r
            )
          FROM Survey__c
          WHERE Id = :surveyId
        ];
      }
      if (!soqlResults.isEmpty()) {
        hasError = false;
        returnData.put('data', soqlResults[0]);
        message = GET_RECORD_SUCCESS_MESSAGE;
      }

      returnData.put('hasError', hasError);
      returnData.put('message', message);
    }

    return returnData;
  }

  @AuraEnabled
  public static String cloneSurvey(
    Id surveyId,
    Survey__c newRecord,
    Boolean setToActive,
    Boolean addClonePrefix
  ) {
    String message = '';

    if (surveyId != null) {
      Survey__c surveyToClone = new Survey__c();
      if (
        FlsUtils.isAccessible(
          'Survey__c',
          new List<String>{
            'Name',
            'Active__c',
            'Survey_Campaign__c',
            'Disclaimer__c',
            'Event__c',
            'Logo_Image_Id__c',
            'OwnerId',
            'Survey_Logo__c',
            'Survey_Logo_URL__c'
          }
        )
      ) {
        surveyToClone = [
          SELECT
            Id,
            Name,
            Active__c,
            Survey_Campaign__c,
            Disclaimer__c,
            Event__c,
            Logo_Image_Id__c,
            OwnerId,
            Survey_Logo__c,
            Survey_Logo_URL__c,
            (
              SELECT
                Id,
                Name,
                Description__c,
                Max_Value__c,
                Min_Value__c,
                Options__c,
                Question_Type__c,
                Sorting_Order__c,
                Step__c,
                Survey__c
              FROM Survey_Questions__r
            )
          FROM Survey__c
          WHERE Id = :surveyId
        ];
      }

      //deep clone survey
      Survey__c clonedSurvey = surveyToClone.clone(false, true, false, false); //clone(preserveId, isDeepClone, preserveReadonlyTimestamps, preserveAutonumber)
      if (newRecord != null) {
        clonedSurvey.Name = addClonePrefix
          ? CLONED_SURVEY_NAME_IDENTIFIER + newRecord.Name
          : newRecord.Name;
        clonedSurvey.Event__c = newRecord.Event__c;
        clonedSurvey.Active__c = newRecord.Active__c;
        clonedSurvey.Disclaimer__c = newRecord.Disclaimer__c;
      }

      //deep clone questions
      List<Survey_Question__c> clonedQuestions = new List<Survey_Question__c>();
      if (!surveyToClone.Survey_Questions__r.isEmpty()) {
        for (
          Survey_Question__c questionToClone : surveyToClone.Survey_Questions__r
        ) {
          Survey_Question__c clonedQuestion = questionToClone.clone(
            false,
            true,
            false,
            false
          ); //clone(preserveId, isDeepClone, preserveReadonlyTimestamps, preserveAutonumber)
          clonedQuestions.add(clonedQuestion);
        }
      }

      // Create a savepoint before insert cloned survey
      Savepoint sp = Database.setSavepoint();
      try {
        if (clonedSurvey != null) {
          if (
            FlsUtils.isCreateable(
              clonedSurvey,
              new List<String>{
                'Name',
                'Event__c',
                'Active__c',
                'Disclaimer__c'
              }
            )
          ) {
            insert clonedSurvey;
          }
        }

        if (!clonedQuestions.isEmpty()) {
          for (Survey_Question__c clonedQuestion : clonedQuestions) {
            clonedQuestion.Survey__c = clonedSurvey.Id;
          }

          if (
            FlsUtils.isCreateable(
              clonedQuestions.get(0),
              new List<String>{ 'Survey__c' }
            )
          ) {
            insert clonedQuestions;
          }
        }

        message = CLONED_SUCCESS_MESSAGE + '|' + clonedSurvey.Id;
      } catch (Exception e) {
        message = e.getMessage();
        // Rollback to the previous null value
        Database.rollback(sp);
      }
    }

    return message;
  }

  @AuraEnabled
  public static PrefixObjectAndFieldWrapper fetchObjectAndFieldPrefix() {
    PrefixObjectAndFieldWrapper prefObjField = new PrefixObjectAndFieldWrapper();
    try {
      prefObjField.surveyObjectPrefix = FlsUtils.applyPrefixToObject(
        'Survey__c'
      );
      Schema.DescribeSObjectResult[] dResult = Schema.describeSObjects(
        new List<String>{ prefObjField.surveyObjectPrefix }
      );

      prefObjField.activeFieldPrefix = FlsUtils.applyPrefixToField(
        dResult[0],
        'Active__c'
      );
      prefObjField.eventFieldPrefix = FlsUtils.applyPrefixToField(
        dResult[0],
        'Event__c'
      );
      prefObjField.disclaimerFieldPrefix = FlsUtils.applyPrefixToField(
        dResult[0],
        'Disclaimer__c'
      );
      prefObjField.errorMsg = '';
    } catch (Exception e) {
      prefObjField.errorMsg = e.getMessage();
    }
    return prefObjField;
  }

  public class PrefixObjectAndFieldWrapper {
    @AuraEnabled
    public String surveyObjectPrefix { get; set; }
    @AuraEnabled
    public String activeFieldPrefix { get; set; }
    @AuraEnabled
    public String eventFieldPrefix { get; set; }
    @AuraEnabled
    public String disclaimerFieldPrefix { get; set; }
    @AuraEnabled
    public String errorMsg { get; set; }
  }
}