main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Outreach Notification. If this field is populated and related the Session does not have related Outreach Notification, this will be used as the setting for that Session.</description>
    <inlineHelpText>If the related Session does not have related Outreach Notification, this will be used as the setting for that Session.</inlineHelpText>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification__c/Outreach_Notification__c.object-meta.xml
<CustomObject>
    <description>Links to the related notification settings and record that will use the settings</description>
    <label>Outreach Notification</label>
    <nameField>
        <label>Outreach Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_History__c/Outreach_Notification_History__c.object-meta.xml
<CustomObject>
    <description>Contains historical data of notifications sent out to contacts.</description>
    <label>Outreach Notification History</label>
    <nameField>
        <displayFormat>ONH{000000}</displayFormat>
        <label>Outreach Notification History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreach Notification Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_History__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Links to the contact (participant)</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Outreach Notification Histories</relationshipLabel>
    <relationshipName>Outreach_Notification_Histories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <description>Notification Type</description>
    <formula>Text(Outreach_Notification_Setting__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Notification Type</label>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the Parent Outreach Notification</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Outreach Notification Histories</relationshipLabel>
    <relationshipName>Outreach_Notification_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Outreach_Notification_Setting__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification_Setting__c</fullName>
    <description>Lookup field to the Outreach Notification Setting</description>
    <label>Outreach Notification Setting</label>
    <referenceTo>Outreach_Notification_Setting__c</referenceTo>
    <relationshipLabel>Outreach Notification Histories</relationshipLabel>
    <relationshipName>Outreach_Notification_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to indicate if the record has been processed by the Batch job</description>
    <label>Processed?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <description>This is what the notification was sent for</description>
    <label>Related To</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Related_To_Id__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Id__c</fullName>
    <description>Hidden field (contains the record id)</description>
    <label>Related To (Id)</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <description>Schedule of the notification to be sent out</description>
    <label>Schedule</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <description>Timezone</description>
    <label>Timezone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/Outreach_Notification_Setting__c.object-meta.xml
<CustomObject>
    <description>Contains the configuration that will be used for each compass objects</description>
    <label>Outreach Notification Setting</label>
    <nameField>
        <label>Outreach Notification Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Notification Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_Setting__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Email_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Id__c</fullName>
    <label>Email Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Outreach Notifiocation record</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Outreach Notification Settings</relationshipLabel>
    <relationshipName>Outreach_Notification_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Member_Contact__c.field-meta.xml
<CustomField>
    <fullName>Member_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Event_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant__c/recordTypes/Participant.recordType-meta.xml
<RecordType>
    <fullName>Participant</fullName>
    <active>true</active>
    <label>Participant</label>
</RecordType>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Outreach Notification</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the Outreach Notification</description>
    <label>Outreach Notification</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Outreach_Notification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Participant__c/Survey_Participant__c.object-meta.xml
<CustomObject>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that has been selected as a participant for a survey</description>
    <inlineHelpText>Contact that has been selected as a participant for a survey</inlineHelpText>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <description>Survey that the contact has been selected to participate to</description>
    <inlineHelpText>Survey that the contact has been selected to participate to</inlineHelpText>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/OutreachNotificationHistoryBatch.cls
/*******************************************************************************
 * @author       Paolo Quiambao
 * @date         01.09.2021
 * @description  Batch class - sends Journey Outreach Reminder emails
 * @revision     01.09.2021 - Paolo Quiambao - Created
 * 				 16.12.2021 - Paolo Quiambao - [CCN-878] Add email sending for WF#2
 * 				 28.12.2021 - Paolo Quiambao - [CCN-1062] Add email sending for WF#3
 *******************************************************************************/
public class OutreachNotificationHistoryBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        // Updated by Paolo Quiambao [CCN-878] Dec172021
		String query = 'SELECT Id, Outreach_Notification_Setting__c, Notification_Type__c, Contact__c, Related_To__c, Schedule__c, Timezone__c, Outreach_Notification__c, Processed__c, Related_To_Id__c, Outreach_Notification_Setting__r.Email_Template_Id__c, Outreach_Notification_Setting__r.Email_Sender_Id__c FROM Outreach_Notification_History__c WHERE Schedule__c != null AND Processed__c = false LIMIT ' + Limits.getLimitQueryRows();
        
        try {
            return Database.getQueryLocator(query);
        }
        catch(Exception e) {
            return null;
        }
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        Set<Id> setOfRelatedIds = new Set<Id>();
        Set<Id> setOfRelatedIdsToSP = new Set<Id>();
        Set<Id> setOfRelatedIdsToSurvey = new Set<Id>();
        List<Outreach_Notification_History__c> onhList = (List<Outreach_Notification_History__c>)scope;
        List<Outreach_Notification_History__c> onhToUpdate = new List<Outreach_Notification_History__c>();
        List<Messaging.SingleEmailMessage> mailsToSend = new List<Messaging.SingleEmailMessage>();
        Map<String, Id> relatedIdToWhatIdMap = new Map<String, Id>();
        
        if(!onhList.isEmpty()) {
            for(Outreach_Notification_History__c onh : onhList) {
                if(Date.newInstance(onh.Schedule__c.year(), onh.Schedule__c.month(), onh.Schedule__c.day()) <= Date.Today()) {
                    // Updated by Paolo Quiambao [CCN-878] Dec162021
                    if(onh.Notification_Type__c.containsIgnoreCase('Session')) {
                        setOfRelatedIdsToSP.add(onh.Related_To_Id__c);
                    }
                    
                    // Updated by Paolo Quiambao [CCN-1062] Dec282021
                    else if(onh.Notification_Type__c.containsIgnoreCase('Survey')) {
                        setOfRelatedIdsToSurvey.add(onh.Related_To_Id__c);
                        system.debug('SURVEY SET ID>>>>     ' + onh);
                    }
                    else {
                        setOfRelatedIds.add(onh.Related_To_Id__c);
                    }
                }
            }
            
            for(Participant__c participant : [SELECT Id, Event__c, Member_Contact__c FROM Participant__c WHERE Event__c IN :setOfRelatedIds OR Event__c IN :setOfRelatedIdsToSurvey]) { 
                relatedIdToWhatIdMap.put(participant.Event__c + '|' + participant.Member_Contact__c, participant.Id);
            }
            
            for(Session_Participant__c sp : [SELECT Id, Session__c, Participant__c, Contact__c FROM Session_Participant__c WHERE Session__c IN :setOfRelatedIds OR Session__c IN: setOfRelatedIdsToSP]) { 
                // Updated by Paolo Quiambao [CCN-878] Dec162021
                if(setOfRelatedIdsToSP.contains(sp.Session__c)) {
                    relatedIdToWhatIdMap.put(sp.Session__c + '|' + sp.Contact__c, sp.Id);
                }
                else {
					relatedIdToWhatIdMap.put(sp.Session__c + '|' + sp.Contact__c, sp.Participant__c);
                }
            }
            
            // Updated by Paolo Quiambao [CCN-1062] Jan092022
            for(Survey_Participant__c surveyParticipant : [SELECT Id, Participant__c, Survey__c, Survey__r.Event__c FROM Survey_Participant__c WHERE Survey__c IN :setOfRelatedIdsToSurvey]) {
                relatedIdToWhatIdMap.put(surveyParticipant.Survey__c + '|' + surveyParticipant.Participant__c, surveyParticipant.Id);
                system.debug('SURVEY ID>>>>     ' + surveyParticipant.Survey__c);
                system.debug('CONTACT>>>>     ' + surveyParticipant.Participant__c);
                system.debug('SP>>>>>      ' + surveyParticipant.Id);
            }
            
            for(Outreach_Notification_History__c onh : onhList) {
                if(Date.newInstance(onh.Schedule__c.year(), onh.Schedule__c.month(), onh.Schedule__c.day()) <= Date.Today() && onh.Outreach_Notification_Setting__r.Email_Sender_Id__c != null && onh.Outreach_Notification_Setting__r.Email_Template_Id__c != null) {                    
                    system.debug('INSIDE ONH FOR LOOP>>>>    ' + onh);
                    system.debug('MAP GET>>>    ' + relatedIdToWhatIdMap.get(onh.Related_To_Id__c + '|' + onh.Contact__c));
                    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                    message.setOrgWideEmailAddressId(onh.Outreach_Notification_Setting__r.Email_Sender_Id__c);
                    message.setSaveAsActivity(false);
                    message.setWhatId(relatedIdToWhatIdMap.get(onh.Related_To_Id__c + '|' + onh.Contact__c));
                    message.setTemplateId(onh.Outreach_Notification_Setting__r.Email_Template_Id__c);
                    message.setTargetObjectId(onh.Contact__c);
                    mailsToSend.add(message);
                    
                    onh.Processed__c = true;
                    onhToUpdate.add(onh);
                }
            }
            if(!Test.isRunningTest()){
                Messaging.sendEmail(mailsToSend);
                update onhToUpdate;
            }
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        
    }
}