main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Location_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/Internal_Resource_Session__c.object-meta.xml
<CustomObject>
    <label>Internal Resource Session</label>
    <nameField>
        <displayFormat>IRS-{000000}</displayFormat>
        <label>Session Resource  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Resource Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Resource_Session__c/fields/Calendar_Invite_Sent_to_Resource__c.field-meta.xml
<CustomField>
    <fullName>Calendar_Invite_Sent_to_Resource__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Calendar Invite Sent to Resource</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Is_Eligible_For_Calendar_Invite__c.field-meta.xml
<CustomField>
    <fullName>Is_Eligible_For_Calendar_Invite__c</fullName>
    <formula>OR(
    AND(
        TEXT(Resource_Session_Status__c) = &apos;Registered&apos;, 
        TEXT(Event__r.Resource_Calendar_Invite_Delivery__c) = &apos;Send on session registration&apos;
    ),
    AND(
        TEXT(Resource_Session_Status__c) = &apos;Confirmed&apos;, 
        TEXT(Event__r.Resource_Calendar_Invite_Delivery__c) = &apos;Send on session confirmation&apos;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Eligible For Calendar Invite</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Resource_Attendance_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Resource_Attendance_Date_Time__c</fullName>
    <label>Resource Attendance Date/Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Resource_Canceled_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Resource_Canceled_Date_Time__c</fullName>
    <label>Resource Canceled Date/Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Resource_Confirmed_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Resource_Confirmed_Date_Time__c</fullName>
    <label>Resource Confirmed Date/Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Resource_Declined_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Resource_Declined_Date_Time__c</fullName>
    <label>Resource Declined Date/Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Resource_Session_Status__c.field-meta.xml
<CustomField>
    <fullName>Resource_Session_Status__c</fullName>
    <label>Resource Session Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Do_Not_Send_Calendar_Invite__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Send_Calendar_Invite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Send Calendar Invite</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Meeting_Info__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Info__c</fullName>
    <label>Meeting Info</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Time_Zone_Offset__mdt/Time_Zone_Offset__mdt.object-meta.xml
<CustomObject>
    <label>Time Zone Offset</label>
    <pluralLabel>Time Zone Offsets</pluralLabel>
</CustomObject>

main/default/objects/Time_Zone_Offset__mdt/fields/Offset__c.field-meta.xml
<CustomField>
    <fullName>Offset__c</fullName>
    <label>Offset</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/classes/InternalResourceSessionTriggerHelper.cls
/******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyyy)          Author                      Description
    *           ----  -----------------    -------------------       -----------------------------
    * @version   1.0  20-06-2022                   JC Espino        [CCN-EVE-3072-DV] Intial Version. Helper Class for InternalResourceSessionTriggerHandler.cls
    * @version   1.3  11-29-2023                   Rexie David      [CCN-EVE-3566-DV] Meeting Reminder Enhancement
    ******************************************************************************/
public without sharing class InternalResourceSessionTriggerHelper {

    public static void sendCalendarInvites(Set<Id> internalResourceIds) {
        Map<Id, Internal_Resource_Session__c> resourceMap = new Map<Id, Internal_Resource_Session__c>(
            [SELECT Id, 
                    Is_Eligible_For_Calendar_Invite__c, 
                    Contact__c, 
                    Contact__r.Email, 
                    Event__r.Email_Sender_Id__c, 
                    Event__r.Email_Sender_Name__c, 
                    Event__r.Location__r.Name, 
                    Session__r.Do_Not_Send_Calendar_Invite__c, 
                    Session__r.Name, 
                    Session__r.Meeting_Info__c, 
                    Session__r.Start_Date_Time__c, 
                    Session__r.End_Date_Time__c, 
                    Session__r.Time_Zone__c, 
                    Session__r.Meeting_URL__c 
             FROM   Internal_Resource_Session__c 
             WHERE  Id IN :internalResourceIds AND 
                    Session__r.Do_Not_Send_Calendar_Invite__c = false AND 
                    Contact__r.Email != null AND 
                    Is_Eligible_For_Calendar_Invite__c = true]
        );

        if(resourceMap.isEmpty()) {
            return;
        }

        // *** EMAIL CREATION START ***

        List<Messaging.SingleEmailMessage> emailsToSend = new List<Messaging.SingleEmailMessage>();

        // OrgWideEmail
        List < OrgWideEmailAddress > orgwide = [SELECT id, Address, DisplayName FROM OrgWideEmailAddress];
        Map < String, OrgWideEmailAddress > orgwideMap = new Map < String, OrgWideEmailAddress > ();
        for (OrgWideEmailAddress o: orgwide) {
            orgwideMap.put(o.id, o);
        }

        String TimeZoneSidKey = [SELECT Id, TimeZoneSidKey FROM Organization].TimeZoneSidKey;

        // Get Custom Metadata for Time Zone offsets
        Map<String, Time_Zone_Offset__mdt> TZOffsets = Time_Zone_Offset__mdt.getAll();

        for(Internal_Resource_Session__c resource : resourceMap.values()) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

            mail.setOrgWideEmailAddressId(resource.Event__r.Email_Sender_Id__c);

            mail.setToAddresses(new List<String>{ resource.Contact__r.Email });

            mail.setSubject(resource.Session__r.Name);

            String htmlBody = (resource.Session__r.Meeting_Info__c != null ? resource.Session__r.Meeting_Info__c : '');

            mail.setHtmlBody(htmlBody);
            mail.setSaveAsActivity(true);
            mail.setTargetObjectId(resource.Contact__c);

            DateTime startDT    = resource.Session__r.Start_Date_Time__c;
            DateTime endDT      = resource.Session__r.End_Date_Time__c;
            DateTime modifiedDT = System.now();

            String startDTGMT       = startDT.format('MM/dd/yyyy/HH/mm/ss', TimeZoneSidKey);
            String endDTGMT         = endDT.format('MM/dd/yyyy/HH/mm/ss', TimeZoneSidKey);
            String modifiedDTGMT    = modifiedDT.format('MM/dd/yyyy/HH/mm/ss', TimeZoneSidKey);

            List<String> startDTtz      = startDTGMT.split('/');
            List<String> endDTtz        = endDTGMT.split('/');
            List<String> modifiedDTtz   = modifiedDTGMT.split('/');

            DateTime startDTNew = DateTime.newInstanceGMT(Integer.valueOf(startDTtz[2]), Integer.valueOf(startDTtz[0]), Integer.valueOf(startDTtz[1]), Integer.valueOf(startDTtz[3]),
                                  Integer.valueOf(startDTtz[4]), Integer.valueOf(startDTtz[5]));

            DateTime endDTNew = DateTime.newInstanceGMT(Integer.valueOf(endDTtz[2]), Integer.valueOf(endDTtz[0]), Integer.valueOf(endDTtz[1]), Integer.valueOf(endDTtz[3]),
                                Integer.valueOf(endDTtz[4]), Integer.valueOf(endDTtz[5]));
                                
            DateTime modifiedDTNew = DateTime.newInstanceGMT(Integer.valueOf(modifiedDTtz[2]), Integer.valueOf(modifiedDTtz[0]), Integer.valueOf(modifiedDTtz[1]), Integer.valueOf(modifiedDTtz[3]),
                                     Integer.valueOf(modifiedDTtz[4]), Integer.valueOf(modifiedDTtz[5]));

            // Apply offset from Custom Metadata
            Integer offset  = (Integer) (TZOffsets.get(resource.Session__r.Time_Zone__c).Offset__c * 60);
            startDT         = startDTNew.addMinutes(-offset);
            endDT           = endDTNew.addMinutes(-offset);
            modifiedDT      = modifiedDTNew.addMinutes(-offset);

            String startDTConverted     = startDT.formatGmt('yyyyMMdd\'T\'HHmmss\'Z\'');
            String endDTConverted       = endDT.formatGmt('yyyyMMdd\'T\'HHmmss\'Z\'');
            String modifiedDTConverted  = modifiedDT.formatGmt('yyyyMMdd\'T\'HHmmss\'Z\'');

            //Create Meeting Body
            String meetingInviteBody = '';

            meetingInviteBody += 'BEGIN:VCALENDAR\n';
            meetingInviteBody += 'PRODID:-//Microsoft Corporation//Outlook 12.0 MIMEDIR//EN\n';
            meetingInviteBody += 'VERSION:2.0\n';

            meetingInviteBody += 'METHOD:REQUEST\n';

            meetingInviteBody += 'CALSCALE:GREGORIAN\n';
            meetingInviteBody += 'X-MS-OLK-FORCEINSPECTOROPEN:TRUE\n';
            meetingInviteBody += 'BEGIN:VEVENT\n';
            meetingInviteBody += 'CLASS:PUBLIC\n';
            meetingInviteBody += 'CREATED:' + modifiedDTConverted + '\n';
            meetingInviteBody += 'ORGANIZER;CN=' + resource.Event__r.Email_Sender_Name__c + ':MAILTO:' + orgwideMap.get(resource.Event__r.Email_Sender_Id__c).Address + '\n';
            meetingInviteBody += 'DTEND:' + endDTConverted + '\n';
            meetingInviteBody += 'DTSTAMP:' + modifiedDTConverted + '\n';
            meetingInviteBody += 'DTSTART:' + startDTConverted + '\n';
            meetingInviteBody += 'LAST-MODIFIED:' + modifiedDTConverted + '\n';
            meetingInviteBody += 'LOCATION:' + (resource.Session__r.Meeting_URL__c != null ? resource.Session__r.Meeting_URL__c : resource.Event__r.Location__r.Name) + '\n';
            meetingInviteBody += 'PRIORITY:5\n';
            meetingInviteBody += 'SEQUENCE:0\n';
            meetingInviteBody += 'SUMMARY:' + (resource.Session__r.Name != null ? resource.Session__r.Name : '') + '\n';
            meetingInviteBody += 'DESCRIPTION:' + (resource.Session__r.Meeting_Info__c != null ? resource.Session__r.Meeting_Info__c : '') + '\n';
            meetingInviteBody += 'LANGUAGE=en-us:Meeting\n';
            meetingInviteBody += 'TRANSP:OPAQUE\n';
            meetingInviteBody += 'UID:4036587160834EA4AE7848CBD028D1D200000000000000000000000000000000' + resource.Id + '\n';
            meetingInviteBody += 'X-ALT-DESC;FMTTYPE=text/html:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN"><HTML><HEAD><META NAME="Generator" CONTENT="MS Exchange Server version 08.00.0681.000"><TITLE></TITLE></HEAD><BODY><!-- Converted from text/plain format -->' + resource.Session__r.Meeting_Info__c + '</BODY></HTML>\n';

            meetingInviteBody += 'X-MICROSOFT-CDO-IMPORTANCE:1\n';
            //CCN-EVE-3566-DV START RDAVID 11/29/2023
            meetingInviteBody += 'BEGIN:VALARM\n';
            meetingInviteBody += 'ACTION:DISPLAY\n';
            meetingInviteBody += 'DESCRIPTION:'+ (resource.Session__r.Name != null ? resource.Session__r.Name : '') + '\n';
            meetingInviteBody += 'TRIGGER:-PT15M\n';
            meetingInviteBody += 'END:VALARM\n';
            //CCN-EVE-3566-DV END RDAVID 11/29/2023
            meetingInviteBody += 'END:VEVENT\n';
            meetingInviteBody += 'END:VCALENDAR';

            // Meeting Email Attachment
            Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();

            attach.Filename     = 'meeting.ics';
            attach.ContentType  = 'text/calendar; charset=utf-8; method=REQUEST';
            attach.Inline       = true;
            attach.Body         = Blob.valueOf(meetingInviteBody);

            //Attach Meeting Attachment
            mail.setFileAttachments(new Messaging.EmailFileAttachment[] {
                attach
            });

            emailsToSend.add(mail);
        }
        // *** EMAIL CREATION END ***

        if(!emailsToSend.isEmpty()) {
            Boolean hasErrors = false;
            try{
                Messaging.SendEmailResult[] er = Messaging.sendEmail(emailsToSend);
            }
            catch(EmailException e) {
                hasErrors = true;
                System.debug('Error Sending Calendar Invites: ' + e.getMessage() + ' ' + e.getStackTraceString());
            }
            finally {
                if(!hasErrors) {
                    confirmCalendarInviteDelivery(resourceMap.keySet());
                }
            }            
        }
    }

    /******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyyy)          Author                      Description
    *           ----  -----------------    -------------------       -----------------------------
    * @version   1.0  23-06-2022             Von Pernicia            [CCN-EVE-2390-DV] Intial Version. This will update date and time depends on the status value.
    ******************************************************************************/ 
    public static void updateDateTime(Internal_Resource_Session__c irsRecord) {

        if (irsRecord.Resource_Session_Status__c == 'Confirmed') {
            irsRecord.Resource_Confirmed_Date_Time__c = System.now();
        } else if (irsRecord.Resource_Session_Status__c == 'Declined') {
            irsRecord.Resource_Declined_Date_Time__c = System.now();
        } else if (irsRecord.Resource_Session_Status__c == 'Attended') {
            irsRecord.Resource_Attendance_Date_Time__c = System.now();
        } else if (irsRecord.Resource_Session_Status__c == 'Canceled') {
            irsRecord.Resource_Canceled_Date_Time__c = System.now();
        } 
    }

    @Future
    public static void confirmCalendarInviteDelivery(Set<Id> internalResourceSessionIds) {
        List<Internal_Resource_Session__c> resourceSessionsList = new List<Internal_Resource_Session__c>(
            [SELECT Calendar_Invite_Sent_to_Resource__c FROM Internal_Resource_Session__c WHERE Id IN : internalResourceSessionIds]
        );

        for(Internal_Resource_Session__c rs :  resourceSessionsList) {
            rs.Calendar_Invite_Sent_to_Resource__c = true;
        }

        update resourceSessionsList;
    }
}