main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Start_Date_Time2__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time2__c</fullName>
    <label>Start Date Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session__c/fields/User_Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>User_Time_Zone__c</fullName>
    <formula>TEXT($User.TimeZoneSidKey)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is the Timezone of the logged-in user.</inlineHelpText>
    <label>User Time Zone</label>
    <type>Text</type>
</CustomField>

main/default/classes/RelatedListController.cls
public with sharing class RelatedListController {
    
       /******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyy) Author            Description
    *           ----  ---------   --------------------  -----------------------------
    * @version   1.0  03-12-2023   GDelavin             CCN-EVE-2633-DV
    ******************************************************************************/
	@AuraEnabled
    public static dataWrapper getData(String parentRecordId) {
        dataWrapper dWrapper = New dataWrapper();
        List<Session__c> listSession = [SELECT Id, Name, Status__c, Start_Date_Time2__c, toLabel(Time_Zone__c), Event_Id__c FROM Session__c where Event__c =: parentRecordId LIMIT 5];
        dWrapper.sessionList = listSession;
        dWrapper.eventId = listSession[0].Event_Id__c;
        return dWrapper;
    }
    @AuraEnabled
    public Static namespaceWrapper handleNameSpace(){
        namespaceWrapper fieldWrapper = New namespaceWrapper();
       
        List<Schema.SObjectType> objects = new List<Schema.SObjectType>{ Session__c.SObjectType};
            for(Schema.SObjectType objType: objects){
                for(Schema.SObjectField fld: objType.getDescribe().fields.getMap().values()){
                    if(fld.getDescribe().getName().contains('Status__c')){
                        fieldWrapper.recStatus = fld.getDescribe().getName();
                    }
                    if(fld.getDescribe().getName().contains('Start_Date_Time2__c')){
                        fieldWrapper.startDateTime = fld.getDescribe().getName();
                    }
                    if(fld.getDescribe().getName().contains('Time_Zone__c') && !fld.getDescribe().getName().contains('User_Time_Zone__c')){
                        fieldWrapper.timeZone = fld.getDescribe().getName();
                    }
                    if(fld.getDescribe().getName().contains('Event_Id__c') && !fld.getDescribe().getName().contains('Event__c')){
                        fieldWrapper.eventId = fld.getDescribe().getName();
                    }
                    //System.debug('API Field Name =  '+fld.getDescribe().getName());
                }
            }
        return fieldWrapper;
    }
    @AuraEnabled
    public static List<Session__c> deleteRec(String parentRecordId, String recordId) {
        
        UserRecordAccess recAccess = [
                SELECT
                        HasEditAccess,
                        HasDeleteAccess,
                        RecordId
                FROM UserRecordAccess
                WHERE UserId =: UserInfo.getUserId()
                AND RecordId =: recordId
        ];

        if (recAccess != null && recAccess.HasDeleteAccess) {
            try {
                sObject sObj = Schema.getGlobalDescribe().get('Session__c').newSObject();
                sObj.Id = recordId;
                delete sObj;
            } catch (DmlException e) {
                throw new AuraHandledException('Error while deleting data.');
            }
        }
        
        List<Session__c> listSession = [SELECT Id, Name, Status__c, Start_Date_Time2__c, toLabel(Time_Zone__c), Event_Id__c FROM Session__c where Event__c =: parentRecordId LIMIT 5];
        
        return listSession;
    }
    Public class namespaceWrapper {
        @AuraEnabled public String recStatus {get; set;}
        @AuraEnabled public String startDateTime {get; set;}
        @AuraEnabled public String timeZone {get; set;}
        @AuraEnabled public String eventId {get; set;}
    }
    Public class dataWrapper {
        @AuraEnabled public List<Session__c> sessionList {get; set;}
        @AuraEnabled public String eventId {get; set;}
       
    }
    
}