main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Attended_Participant_Fields_JSON__c.field-meta.xml
<CustomField>
    <fullName>Attended_Participant_Fields_JSON__c</fullName>
    <label>Attended Participant Fields JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact__r.FirstName+&apos; &apos;+Contact__r.LastName</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Date__c</fullName>
    <formula>Session__r.Start_Date_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session Start Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/CC_SessionParticipantsAttended.cls
/*******************************************************************************************
    * @name: CC_SessionParticipantsAttended 
    * @author: Heidi Tang
    * @created: 14-05-2021
    * @description: controller class that updates session participants status
    * 
    * Changes (version)
    * -------------------------------------------------------------------------------------------
    *               No.     Date(dd-mm-yyy) Author                  Description
    *               ----    ---------       --------------------    -----------------------------
    * @version      1.0     14-05-2021      Heidi Tang               Initial version.
    * @version      2.0     08-12-2021      Ruth Lugpatan            [CCN975] Get the Attended participant fields
*********************************************************************************************/
public with sharing class CC_SessionParticipantsAttended {

    @AuraEnabled
    public static List<Session_Participant__c> getSessionParticipants(String recordId){
        return [SELECT Id,Name,Contact_Name__c,Status__c,Session_Start_Date__c FROM Session_Participant__c 
                WHERE Session__c = :recordId AND Status__c != 'Attended' ORDER BY Contact_Name__c ];
    }

    @AuraEnabled
    public static List<Session_Participant__c> markSessionParticipantsToAttended(String recordId, List<Session_Participant__c> selectedParticipants){
        try {
            for(Session_Participant__c selectedParticipant : selectedParticipants) {
                selectedParticipant.Status__c = 'Attended';
            }    
            update selectedParticipants;
    
            return getSessionParticipants(recordId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    /**
    * @description  Get the Attended participant fields
    * @author       RLugpatan | 08/12/2021 | [CCN975]
    * @param sessionId
    **/
    @AuraEnabled
    public static String getEventAttendedParticipantFieldsJSON(Id sessionId){
        Event__c event = new Event__c();
        try{
            event = [SELECT Id, Attended_Participant_Fields_JSON__c FROM Event__c WHERE Id IN (SELECT Event__c FROM Session__c WHERE Id = :sessionId) LIMIT 1];
        }catch(Exception errorAPI){
            System.debug('TRY-CATCH-EventRecord-->' + errorAPI);
        }
        return event.Attended_Participant_Fields_JSON__c;
    }
    
    /**
    * @description  Used to get the picklist value.
    * @author       RLugpatan | 01/12/2021 | [CCN975]
    * @param fieldName
    **/
    @AuraEnabled
    public static List<String> getPickListValues(String fieldName){
        List<String> pickListValuesList= new List<String>();
        Schema.DescribeFieldResult fieldResult = Schema.getGlobalDescribe().get('Session_Participant__c').getDescribe().fields.getMap().get(fieldName).getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getValue());
            //pickListValuesList.add(new String(pickListVal.getLabel(), pickListVal.getValue()));
        }     
        return pickListValuesList;
    }
    
}