main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/BatchOutreachNotificationCC.cls
/*******************************************************************************
 * @author       Angelo Rivera
 * @date         18.08.2021
 * @description  [CCN-842, CCN-1059, CCN-1060, CCN-1061] Controller class for BatchOutreachNotification
 * @revision     18.08.2021 - APRivera - Created
 *******************************************************************************/
public without sharing class BatchOutreachNotificationCC {

    public static void sendOutreachNotifications(List<String> lstSObject){
        Boolean bEvents = false, bJourney = false, bSession = false, bSurvey = false;
        for(String strObject : lstSObject){
            // Event
            if(strObject == Event__c.SObjectType.getDescribe().getName()){
                bEvents = true;
            	System.debug(LoggingLevel.DEBUG, ' !@# EVENTS ' + bEvents);
            }
            // Session
            if(strObject == Session__c.SObjectType.getDescribe().getName()){
                bSession = true;
            	System.debug(LoggingLevel.DEBUG, ' !@# SESSION ' + bSession);
            }
            // Journey
            if(strObject == Journey__c.SObjectType.getDescribe().getName()){
                bJourney = true;
            	System.debug(LoggingLevel.DEBUG, ' !@# JOURNEY ' + bJourney);
            }
            // Survey
            if(strObject == Survey__c.SObjectType.getDescribe().getName()){
                bSurvey = true;
            	System.debug(LoggingLevel.DEBUG, ' !@# SURVEY ' + bSurvey);
            }
        }

        // Events
        if(bEvents){
            String strEventOutreachNotifications = '';
            strEventOutreachNotifications = OutreachNotificationHelper.processEvents();
            System.debug(LoggingLevel.DEBUG, ' !@# ' + strEventOutreachNotifications);
        }

        // Session
        if(bSession){
            String strSessionOutreachNotifications = '';
            strSessionOutreachNotifications = OutreachNotificationSessionHelper.processSessions();
            System.debug(LoggingLevel.DEBUG, ' !@# ' + strSessionOutreachNotifications);
        }


        // Survey
        if(bSurvey){
            String strSurveyOutreachNotifications = '';
            strSurveyOutreachNotifications = OutreachNotificationSurveyHelper.processSurveys();
            System.debug(LoggingLevel.DEBUG, ' !@# ' + strSurveyOutreachNotifications);
        }


    }



}