main/default/objects/ExceptionLog__c/ExceptionLog__c.object-meta.xml
<CustomObject>
    <description>To track all exceptions occuring</description>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EXCP - {0000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/ExceptionLog__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/ExceptionLog__c/fields/ContextUser__c.field-meta.xml
<CustomField>
    <fullName>ContextUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Context User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ExceptionLogs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/ExceptionLog__c/fields/ExceptionDetails__c.field-meta.xml
<CustomField>
    <fullName>ExceptionDetails__c</fullName>
    <label>Exception Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/ExceptionLog__c/fields/ExceptionLogTimestamp__c.field-meta.xml
<CustomField>
    <fullName>ExceptionLogTimestamp__c</fullName>
    <label>ExceptionLog Timestamp</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/ExceptionLog__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

main/default/classes/UTIL_LoggingServiceBatchTest.cls
@isTest
public class UTIL_LoggingServiceBatchTest {
    
    @testSetup static void setup(){
        //Insert Exception Logs records
        List<ExceptionLog__c> exceptLogInserted = new List<ExceptionLog__c>();
        for (Integer i = 0; i < 200; i++) {
            exceptLogInserted.add(new ExceptionLog__c(ApexTrigger__c = 'TestTrigger',
                                                      Application__c = 'Test App',
                                                      ClassName__c = 'Test Class' + i,
                                                      ContextUser__c = UserInfo.getUserId(),
                                                      ExceptionType__c = 'Test System.DmlException',
                                                      ExceptionDetails__c = 'Test System.DmlException Details',
                                                      ExceptionLogTimestamp__c = DateTime.now(),
                                                      MethodName__c = 'Test Method',
                                                      Severity__c = 'ERROR'
                                                     ));
        }
        insert exceptLogInserted;
    }
    
    @isTest
    static void testBatchDeleteExceptionLogs(){
        test.startTest();
        Database.executeBatch(new UTIL_LoggingServiceBatch());
        test.stopTest();
        system.assertEquals(0, [SELECT Count() FROM ExceptionLog__c WHERE Application__c = 'Test App']);
    }
    
    @isTest
    static void testSchedulableDeleteExceptionLogs(){
        Test.startTest();
        UTIL_LoggingServiceBatch sh1 = new UTIL_LoggingServiceBatch();
        String sch = '0 0 12 30 1/1 ?'; 
        system.schedule('Schedule Delete Exception Logs', sch, sh1); 
        Test.stopTest();
    }

}