main/default/objects/Campaign/fields/Campaign_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Logo_URL__c</fullName>
    <label>Campaign Logo URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_Message__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Message__c</fullName>
    <label>Contact Us Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_Tag_Line__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Tag_Line__c</fullName>
    <label>Contact Us Tag Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_User__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the user to whom activities raised from the Contact Us page will be assigned to. If this field is empty, the activities will be assigned to the campaign&apos;s owner.</description>
    <label>Contact Us User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Campaign/fields/Hero_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Hero_Image_URL__c</fullName>
    <label>Hero Image URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Brief introduction to the campaign that displays under the campaign name on the campaign summary page.</inlineHelpText>
    <label>Campaign Summary Page Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Contact/fields/Profile_Description__c.field-meta.xml
<CustomField>
    <fullName>Profile_Description__c</fullName>
    <label>Profile Description</label>
    <length>121072</length>
    <type>Html</type>
</CustomField>

main/default/objects/Contact/fields/Profile_Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture_URL__c</fullName>
    <label>Profile Picture URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scrum Master</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Campaign_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Logo_URL__c</fullName>
    <label>Campaign Logo URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_Message__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Message__c</fullName>
    <label>Contact Us Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_Tag_Line__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Tag_Line__c</fullName>
    <label>Contact Us Tag Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_User__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the user to whom activities raised from the Contact Us page will be assigned to. If this field is empty, the activities will be assigned to the campaign&apos;s owner.</description>
    <label>Contact Us User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contact_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/fields/Hero_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Hero_Image_URL__c</fullName>
    <label>Hero Image URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Location_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Materials_Page_Title__c.field-meta.xml
<CustomField>
    <fullName>Materials_Page_Title__c</fullName>
    <defaultValue>&apos;Materials&apos;</defaultValue>
    <label>Materials Page Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Parking_Lot_Page_Title__c.field-meta.xml
<CustomField>
    <fullName>Parking_Lot_Page_Title__c</fullName>
    <defaultValue>&apos;Parking Lot&apos;</defaultValue>
    <label>Parking Lot Page Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Survey_Page_Title__c.field-meta.xml
<CustomField>
    <fullName>Survey_Page_Title__c</fullName>
    <defaultValue>&apos;Survey&apos;</defaultValue>
    <label>Survey Page Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event_Role__c/Event_Role__c.object-meta.xml
<CustomObject>
    <label>Event Role</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>Event Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event_Role__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Event Roles</relationshipLabel>
    <relationshipName>Event_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Roles</relationshipLabel>
    <relationshipName>Event_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Role__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Roles</relationshipLabel>
    <relationshipName>Event_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Event Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Speaker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event_Role__c/fields/Show_in_Event_Site__c.field-meta.xml
<CustomField>
    <fullName>Show_in_Event_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show in Event Site</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/CCEHeroController.cls
public with sharing class CCEHeroController {

    private static WithoutSharingClass withoutShare = new WithoutSharingClass();

    @AuraEnabled
    public static CCEEventWrapper getEventDetails(String eventId) {
        try {
            Campaign campaignRecord = new Campaign();
        
            CCEEventWrapper eventRecord = new CCEEventWrapper();
            if(FlsUtils.isAccessible('Campaign', new List<String>{'Name','Subtitle__c','Event_Id__c','Hero_Image_URL__c','Campaign_Logo_URL__c',
                'Description__c','Contact_Us_Tag_Line__c','Contact_Us_Message__c', 'OwnerId', 'Start_Date_Time__c','Contact_Us_User__c',
                'Time_Zone__c','Status','End_Date_Time__c'}) && FlsUtils.isAccessible('Account', new List<String>{'BillingStreet','BillingCity',
                'BillingPostalCode','BillingState','BillingCountry'})){
    
                campaignRecord =  withoutShare.getCampaign(eventId);
            }
            
            // If Contact Us User is populated then use this user's timezone, otherwise use campaign owner's timezone
            String timezone;
            if(FlsUtils.isAccessible('User', new List<String>{'TimeZoneSidKey'})){
                if (campaignRecord.Contact_Us_User__c != null){
                    timezone = withoutShare.getUserTimezone(campaignRecord.Contact_Us_User__c);
                } else {
                    timezone = withoutShare.getUserTimezone(campaignRecord.OwnerId);
                }
            }
            Event__c eventRec = new Event__c();
            eventRec = withoutShare.getEvent(eventId);
            eventRecord.EventExternalId = campaignRecord.Event_Id__c;
            eventRecord.title = campaignRecord.Name;
            eventRecord.subtitle = campaignRecord.Subtitle__c;
            eventRecord.HeroUrl = campaignRecord.Hero_Image_URL__c;
            eventRecord.CampaignLogoUrl= campaignRecord.Campaign_Logo_URL__c;
            eventRecord.Street = campaignRecord.Location__r.BillingStreet;
            eventRecord.City = campaignRecord.Location__r.BillingCity;
            eventRecord.PostalCode = campaignRecord.Location__r.BillingPostalCode;
            eventRecord.State = campaignRecord.Location__r.BillingState;
            eventRecord.Country = campaignRecord.Location__r.BillingCountry;
            eventRecord.Description = campaignRecord.Description__c; 
            eventRecord.contactTag = campaignRecord.Contact_Us_Tag_Line__c; 
            eventRecord.contactMessage = campaignRecord.Contact_Us_Message__c; 
            String strTZone = [SELECT Id, TimeZoneSidKey FROM Organization].TimeZoneSidKey;
            //eventRecord.StartDateTime = campaignRecord.Start_Date_Time__c.format('MMMM d, yyyy h:mm a', strTZone) + ' ' + campaignRecord.Time_Zone__c;
            //eventRecord.EndDateTime = campaignRecord.End_Date_Time__c.format('MMMM d, yyyy h:mm a', strTZone) + ' ' + campaignRecord.Time_Zone__c;
            eventRecord.StartDateTime = system.now()+ '';
            eventRecord.EndDateTime = system.now()+ '';
            eventRecord.CampaignStatus = campaignRecord.Status;
            eventRecord.surveyPageTitle = eventRec.Survey_Page_Title__c;
            eventRecord.materialsPageTitle = eventRec.Materials_Page_Title__c;
            return eventRecord;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getStackTraceString());    
        }
    }
    
    @AuraEnabled
    public static CCEEventWrapper getEventSession(String eventId) {
        Campaign campaignRecord = new Campaign();
        CCEEventWrapper eventRecord = new CCEEventWrapper();
        List<Campaign> campaignList = new List<Campaign>();
        if(FlsUtils.isAccessible('Campaign', new List<String>{'OwnerId','Contact_Us_User__c'})){
            campaignRecord = withoutShare.getCampaignForContactUsUser(eventId);
        }

        // If Contact Us User is populated then use this user's timezone, otherwise use campaign owner's timezone
        String timezone;
        if(FlsUtils.isAccessible('User', new List<String>{'TimeZoneSidKey'})){
            if (campaignRecord.Contact_Us_User__c != null){
                timezone = withoutShare.getUserTimezone(campaignRecord.Contact_Us_User__c);
            } else {
                timezone = withoutShare.getUserTimezone(campaignRecord.OwnerId);
            }
        }

        String strTZone = [SELECT Id, TimeZoneSidKey FROM Organization LIMIT 1].TimeZoneSidKey;
        if(FlsUtils.isAccessible('Campaign', new List<String>{'Name','Subtitle__c','Event_Id__c','Start_Date_Time__c','End_Date_Time__c','Description__c','Time_Zone__c'})){
            campaignList = withoutShare.getCampaigns(campaignRecord.Id);
        }

        eventRecord.SessionList = new List<CCEEventWrapper.SessionDetail>();
        
        String SessionDateMatch = '';
        
        for(Campaign CampaignRec : campaignList){
            
            String SessionDateMatchCompare = '';
            if (CampaignRec.Start_Date_Time__c != null){
                SessionDateMatchCompare = CampaignRec.Start_Date_Time__c.format('MMM d', strTZone);
            }
            
            if(SessionDateMatch != SessionDateMatchCompare){
                CCEEventWrapper.SessionDetail sessionRecHeader = new CCEEventWrapper.SessionDetail();
                sessionRecHeader.isHeader = true;
                sessionRecHeader.SessionDate = CampaignRec.Start_Date_Time__c.format('EEEE, MMMM d, yyyy');
                sessionRecHeader.SessionMonth = String.valueOf(CampaignRec.Start_Date_Time__c.month());
                eventRecord.SessionList.add(sessionRecHeader);
                SessionDateMatch = SessionDateMatchCompare;
            }
            
            CCEEventWrapper.SessionDetail sessionRec = new CCEEventWrapper.SessionDetail();
            sessionRec.isHeader = false;
            sessionRec.title  = CampaignRec.Name;
            sessionRec.subtitle = CampaignRec.Subtitle__c;
            if (CampaignRec.Start_Date_Time__c != null && CampaignRec.End_Date_Time__c != null){
                sessionRec.SessionDate = CampaignRec.Start_Date_Time__c.format('MMM d, yyyy', strTZone);
                sessionRec.StartTime = CampaignRec.Start_Date_Time__c.format('h:mm a', strTZone);
                sessionRec.EndTime = CampaignRec.End_Date_Time__c.format('h:mm a', strTZone);
                sessionRec.TimeZone = CampaignRec.Time_Zone__c;
            }
            
            eventRecord.SessionList.add(sessionRec);
        }

        return eventRecord;
    }
    
    @AuraEnabled
    public static List<CCESpeakerWrapper> getSpeakerDetails(String eventId) {
        Campaign campaignRecord = new Campaign();
        List<Event_Role__c> eventRoleList = new List<Event_Role__c>();
        List<CCESpeakerWrapper> speakerList = new List<CCESpeakerWrapper>();

        if(FlsUtils.isAccessible('User', new List<String>{'Name'})){
            campaignRecord = withoutShare.getCampaignName(eventId);
        }

        if(FlsUtils.isAccessible('Contact', new List<String>{'FirstName','lastName','Title','Profile_Description__c','Profile_Picture_URL__c'})){
            eventRoleList = withoutShare.getEventRoles(campaignRecord.Id);
        }

        for(Event_Role__c er : eventRoleList){
            CCESpeakerWrapper speaker = new CCESpeakerWrapper();
            speaker.FirstName = er.Contact__r.FirstName;
            speaker.lastName = er.Contact__r.lastName;
            speaker.Title = er.Contact__r.Title;
            speaker.Description = er.Contact__r.Profile_Description__c;
            speaker.ProfilePicUrl = er.Contact__r.Profile_Picture_URL__c;
            speakerList.add(speaker);
        }
        
        return speakerList;
    } 
    
    @AuraEnabled
    // Create task for each request sent from the custom contact support form
    public static void createTask(String eventId, String firstname, String lastname, String email, String phone, String subject, String comments){
        if (String.isBlank(eventId) || String.isBlank(firstname) || String.isBlank(lastname) || String.isBlank(email) || String.isBlank(subject) || String.isBlank(comments)){
            return;
        } 
        
        CustomContactSupportFormHelper.createTaskHelper(eventId, firstname, lastname, email, phone, subject, comments);
    }

     //Needs inner class declared without sharing for guest users to retrieve relevant records
     private without sharing class WithoutSharingClass {
		
         public Event__c getEvent(String eventId){
            return [SELECT Name,
                    Subtitle__c,
                    Event_Id__c,
                    Materials_Page_Title__c,
                    Parking_Lot_Page_Title__c,
                    Survey_Page_Title__c FROM Event__c WHERE Event_Id__c =: eventId];
        }
         
        public List<Campaign> getCampaigns(String campaignId){
            return [SELECT Name, Subtitle__c, Event_Id__c, Start_Date_Time__c, End_Date_Time__c, Description__c, Time_Zone__c
                    FROM Campaign 
                    WHERE ParentId = :campaignId 
                    ORDER BY Start_Date_Time__c];
        }

        public Campaign getCampaignName(String eventId){
            return [SELECT Name FROM Campaign WHERE Event_Id__c =: eventId];
        }

        public Campaign getCampaignForContactUsUser(String eventId){
            return [SELECT Id, OwnerId, Contact_Us_User__c FROM Campaign WHERE Event_Id__c = :eventId];
        }

        public Campaign getCampaign(String eventId){

            List<Campaign> campaignList = [SELECT Name,Subtitle__c,Event_Id__c,Hero_Image_URL__c,Campaign_Logo_URL__c, Description__c,
                                                Contact_Us_Tag_Line__c,Contact_Us_Message__c,Location__r.BillingStreet,Location__r.BillingCity, 
                                                Location__r.BillingPostalCode,Location__r.BillingState,Location__r.BillingCountry,
                                                OwnerId,Start_Date_Time__c, Contact_Us_User__c,Time_Zone__c,Status,End_Date_Time__c
                                            FROM Campaign WHERE Event_Id__c =: eventId];
            
            if(!campaignList.isEmpty()){
                return campaignList[0];
            }

            return new Campaign();
        }

        public String getUserTimezone(Id userId){
            List<User> userList = [SELECT ID, TimeZoneSidKey FROM User WHERE ID = :userId LIMIT 1];
            
            if(!userList.isEmpty()){
                return userList[0].TimeZoneSidKey;
            }

            return '';
        }

        public List<Event_Role__c> getEventRoles(Id campaignId){
            return [SELECT Contact__r.FirstName ,
                        Contact__r.lastName,
                        Contact__r.Title,
                        Contact__r.Profile_Description__c,
                        Contact__r.Profile_Picture_URL__c 
                    FROM Event_Role__c 
                    WHERE Campaign__c = :campaignId
                        AND Show_in_Event_Site__c = true 
                        AND Role__c = 'Speaker'];
        }
    }
    
}