main/default/objects/Campaign/fields/Campaign_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Logo_URL__c</fullName>
    <label>Campaign Logo URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_Message__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Message__c</fullName>
    <label>Contact Us Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_Tag_Line__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Tag_Line__c</fullName>
    <label>Contact Us Tag Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Campaign/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Campaign/fields/Hero_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Hero_Image_URL__c</fullName>
    <label>Hero Image URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Brief introduction to the campaign that displays under the campaign name on the campaign summary page.</inlineHelpText>
    <label>Campaign Summary Page Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Email_Template_Invitation_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Invitation_Id__c</fullName>
    <label>Email Template - Invitation Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/fields/Email_Template_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Registration_Id__c</fullName>
    <label>Email Template - Registration Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scrum Master</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Campaign_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Logo_URL__c</fullName>
    <label>Campaign Logo URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_Message__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Message__c</fullName>
    <label>Contact Us Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_Tag_Line__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Tag_Line__c</fullName>
    <label>Contact Us Tag Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Message_BCC__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_BCC__c</fullName>
    <label>Email Message BCC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Message_CC__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_CC__c</fullName>
    <label>Email Message CC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/fields/Hero_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Hero_Image_URL__c</fullName>
    <label>Hero Image URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Location_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Event_Role__c/Event_Role__c.object-meta.xml
<CustomObject>
    <label>Event Role</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>Event Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event_Role__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Event Roles</relationshipLabel>
    <relationshipName>Event_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Role__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Roles</relationshipLabel>
    <relationshipName>Event_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Event Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Speaker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/ChangeCloudControllerTest.cls
@isTest 
private class ChangeCloudControllerTest { 
    
    @testSetup
    static void makeTestData(){
        
        String inpputString = '2023-10-23T01:44:00.000Z';
        DateTime resultDateTime = DateTime.ValueofGmt(inpputString.replace('T', ' ')); 

        OrgWideEmailAddress owea = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];
        EmailTemplate eTemp = new EmailTemplate (developerName = 'test', FolderId = UserInfo.getUserId(), TemplateType= 'Text', Name = 'test', IsActive = true);
        system.runAs( new User(Id = UserInfo.getUserId())){
            insert eTemp;
        }
        Compass_Setting__c setting = new Compass_Setting__c();
        setting.Name = 'Default Settings';
        setting.Email_Sender_Name__c = 'NAME';
        setting.Email_Template_Invitation_Id__c = eTemp.Id;
        setting.Email_Template_Registration_Id__c = eTemp.Id;
        setting.Email_Sender_Id__c = owea.Id;
        insert setting;
        
        Apex_Trigger_Switch__c aps = new Apex_Trigger_Switch__c();
        aps.Name = 'EventTrigger';
        aps.Active__c = false;
        insert aps;
        
        
        Campaign__c camp = new Campaign__c();
        camp.Name = 'Test Campaign';
        insert camp;
        
        Account a = new Account();
        a.BillingStreet = 'Balston';
        a.BillingCity = 'Melbourne';
        a.BillingPostalCode = '3006';
        a.BillingState  = 'VIC';
        a.BillingCountry  = 'Australia';
        a.Name  = 'Imagine Marco';
        insert a;
        
        Contact c = new Contact();
        c.FirstName = 'John';
        c.LastName = 'John';
        c.Department = 'IT';
        c.Email = 'John@test.com';
        insert c;
        
        Event__c e = new Event__c();
        e.Event_Id__c = 'xxxxxxxxxx';
        e.IsActive__c = true;
        e.Campaign__c = camp.id;
        e.Start_Date_Time__c = DateTime.Now();
        e.End_Date_Time__c = DateTime.Now() + 1;
        e.Location__c = a.Id;
        e.Email_Sender_Name__c = 'TEST 123';
        e.Email_Message_CC__c = 'testMail@mail.com';
        e.Email_Message_BCC__c = 'testMail@mail.com';
        e.Email_Sender_Id__c = owea.Id;
        e.Time_Zone__c = 'EDT';  // Added by JaysonLabnao [CCN-EVE-2160-DV] October102022
        insert e;
        
        Campaign campaignRecord = new Campaign();
        campaignRecord.Event_Id__c = 'kkjdu34302';
        campaignRecord.Name= 'Evendra123';
        campaignRecord.Subtitle__c= 'Evendra123';
        campaignRecord.Hero_Image_URL__c= 'https://www.google.com';
        campaignRecord.Campaign_Logo_URL__c= 'https://www.google.com';
        campaignRecord.Description__c= 'Evendra123';
        campaignRecord.Contact_Us_Tag_Line__c= 'Evendra123';
        campaignRecord.Contact_Us_Message__c= 'Evendra123';
        campaignRecord.Location__c = a.Id;
        campaignRecord.Start_Date_Time__c = DateTime.newInstance(2020, 08, 29, 22, 30, 0);
        campaignRecord.End_Date_Time__c = DateTime.newInstance(2020, 08, 30, 4, 50, 30);
        insert campaignRecord;
        
        Event_Role__c newEventRole = new Event_Role__c();
        newEventRole.Show_in_Event_Site__c = true;
        newEventRole.Role__c = 'Speaker';
        newEventRole.Contact__c = c.Id;
        newEventRole.Event__c = e.Id;
        newEventRole.Campaign__c = campaignRecord.Id ;
        insert newEventRole;
        
        Participant__c p = new Participant__c();
        p.Member_Contact__c = c.id;
        p.Event__c = e.id;
        insert p;
        
        Session__c s = new Session__c();
        s.Event__c = e.id;
        s.IsActive__c = true;
        s.Time_Zone__c = 'CDT';  
        s.Start_Date_Time__c = resultDateTime;
        s.End_Date_Time__c = resultDateTime.addHours(1);
        insert s;
        
        Session_Role__c sr = new Session_Role__c();
        sr.Role_Title__c = 'Sample Role';
        sr.Role_Description__c = 'Sample Description';
		sr.Session__c = s.Id;
        sr.Number_of_Role__c = 4;
        insert sr;
        
        Session_Participant__c sp = new Session_Participant__c();
        sp.Participant__c = p.Id;
        sp.Session__c = s.Id;
        insert sp;
        
        Lead l = new Lead();
        l.FirstName = 'Jane';
        l.LastName = 'Doe';
        l.Email = 'JaneDoe@test.com';
        l.Company = 'ABC Company';
        insert l;
        
        ContentVersion contentVersion = new ContentVersion(
            Title          = 'a picture',
            PathOnClient   = 'Pic.jpg',
            VersionData    = Blob.valueOf('Test Content'),
            IsMajorVersion = true);
        insert contentVersion;
        
        List<ContentDocument> documents = [
            SELECT Id, Title, LatestPublishedVersionId 
            FROM ContentDocument
        ];
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=e.id;
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId=documents[0].Id;
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;
        
        ContentDocumentLink contentlink2=new ContentDocumentLink();
        contentlink2.LinkedEntityId=s.id;
        contentlink2.ShareType= 'V';
        contentlink2.ContentDocumentId=documents[0].Id;
        contentlink2.Visibility = 'AllUsers'; 
        insert contentlink2;
        
        ContentDistribution cd = new ContentDistribution();
        cd.Name = 'Test';
        cd.ContentVersionId = contentVersion.id;
        cd.PreferencesAllowViewInBrowser= true;
        cd.PreferencesLinkLatestVersion=true;
        cd.PreferencesNotifyOnVisit=false;
        cd.PreferencesPasswordRequired=false;
        cd.PreferencesAllowOriginalDownload= true;
        insert cd;
        
    }
    
    @IsTest
    static void testInitTest() {
        CCEEventWrapper resultWrappers = new CCEEventWrapper();
        Participant__c p = [SELECT id,Name FROM Participant__c LIMIT 1];
        Test.startTest();
        Event__c event = [Select Event_Id__c from Event__c LIMIT 1];
        resultWrappers = ChangeCloudController.getEventDetails(event.Event_Id__c);
        Test.stopTest();
        System.assertNotEquals(resultWrappers, null);
    }    

    @IsTest
    static void testInit1Exception() {
        CCEEventWrapper resultWrappers = new CCEEventWrapper();
        Test.startTest();
        try{
            resultWrappers = ChangeCloudController.getEventDetails(null);            
        }catch (Exception e){
            system.assert(TRUE);
        }
        Test.stopTest();
    }  
    
    @IsTest
    static void testInitTest2() {
        CCEEventWrapper resultWrappers = new CCEEventWrapper();
        Participant__c p = [SELECT id,Name FROM Participant__c LIMIT 1];
        Test.startTest();
        Event__c event = [Select Event_Id__c from Event__c LIMIT 1];
        resultWrappers = ChangeCloudController.getEventDetailsHeader(event.Event_Id__c,p.Name);
        Test.stopTest();
        System.assertNotEquals(resultWrappers, null);
    }    
    
    @IsTest
    static void testInit2Exception() {
        CCEEventWrapper resultWrappers = new CCEEventWrapper();
        Test.startTest();
        try{
            resultWrappers = ChangeCloudController.getEventDetailsHeader(null, null);            
        }catch (Exception e){
            system.assert(TRUE);
        }
        Test.stopTest();
    } 
    
    
    @IsTest
    static void getEventSessionTest() {
        CCEEventWrapper resultWrappers = new CCEEventWrapper();
        Participant__c p = [SELECT id,Name FROM Participant__c LIMIT 1];
        Test.startTest();
        Event__c event = [Select Event_Id__c from Event__c LIMIT 1];
        resultWrappers = ChangeCloudController.getEventSession(event.Event_Id__c,p.Name,true);
        Test.stopTest();
        System.assertNotEquals(resultWrappers, null);
    } 

    @IsTest
    static void testgetEventSessionException() {
        CCEEventWrapper resultWrappers = new CCEEventWrapper();
        Test.startTest();
        try{
            resultWrappers = ChangeCloudController.getEventSession(null, null, null);            
        }catch (Exception e){
            system.assert(TRUE);
        }
        Test.stopTest();
    }   
    
    @IsTest
    static void getEventSessionTest2() {
        CCEEventWrapper resultWrappers = new CCEEventWrapper();
        List<CCESpeakerWrapper> cceSpeaker = new List<CCESpeakerWrapper>(); 
        
        Participant__c p = [SELECT id,Name FROM Participant__c LIMIT 1];
        Test.startTest();
        Event__c event = [Select Event_Id__c from Event__c LIMIT 1];
        resultWrappers = ChangeCloudController.getEventSession(event.Event_Id__c,p.Name,false);
        cceSpeaker = ChangeCloudController.getSpeakerDetails(event.Event_Id__c);
        Test.stopTest();
        System.assertNotEquals(resultWrappers, null);
    }    
    
    @IsTest
    static void testgetEventMaterialst() {
        String result;
        Participant__c p = [SELECT id,Name FROM Participant__c LIMIT 1];
        Test.startTest();
        Event__c event = [Select Event_Id__c from Event__c LIMIT 1];
        result = ChangeCloudController.getEventMaterials(event.Event_Id__c);
        Test.stopTest();
    }    
    
    @IsTest
    static void getParticipantSessionTest() {
        List<compass_session_wrapper> resultWrappers = new List<compass_session_wrapper>();
        Participant__c p = [SELECT id,Name FROM Participant__c LIMIT 1];
        Test.startTest();
        resultWrappers = ChangeCloudController.getParticipantSession(p.Name);
        Test.stopTest();
        System.assertNotEquals(resultWrappers, null);
    }    
    
    @IsTest
    static void updateAttendanceTest() {
        Boolean resultWrappers;
        Session_Participant__c p = [SELECT id FROM Session_Participant__c LIMIT 1];
        Test.startTest();
        resultWrappers = ChangeCloudController.updateAttendance(p.Id);
        Test.stopTest();
        System.assertNotEquals(resultWrappers, null);
    }  
    
    @IsTest
    static void getParticipantByNumberTest() {
        Participant__c resultWrappers = new Participant__c();
        Participant__c p = [SELECT id,Name FROM Participant__c LIMIT 1];
        Test.startTest();
        resultWrappers = ChangeCloudController.getParticipantDetailByNumber(p.Name);
        Test.stopTest();
        System.assertNotEquals(resultWrappers, null);
    }    
    
    @IsTest
    static void getParticipantDetailTest() {
        Participant__c resultWrappers = new Participant__c();
        Test.startTest();
        resultWrappers = ChangeCloudController.getParticipantDetail('John@test.com','xxxxxxxxxx');
        Test.stopTest();
        System.assertNotEquals(resultWrappers, null);
    }    
    
    @IsTest
    static void createTaskTest() {
        Test.startTest();
        Event__c event = [Select Event_Id__c from Event__c LIMIT 1];
        ChangeCloudController.createTask(event.Event_Id__c, 'John', 'Test', 'John@test.com','021111111','Subject', 'Comment');
        Test.stopTest();
    }    
    
    @IsTest
    static void catchUpSessionTest() {
        Test.startTest();
        Boolean status;
        Session_Participant__c p = [SELECT id FROM Session_Participant__c LIMIT 1];
        Event__c event = [Select Event_Id__c from Event__c LIMIT 1];
        try{
           status = ChangeCloudController.catchUpSession(p.Id, event.Event_Id__c); 
        }
        catch (Exception e){
            System.assert(TRUE);
        }
        Test.stopTest();
    }    

    @IsTest
    static void getEventsListTest() {
        Test.startTest();
        Campaign camp = [Select Id From Campaign LIMIT 1];
        List<CCEEventWrapper> cceWrapper = new List<CCEEventWrapper>(); 
        List<String> eventTypes = new List<String>();
        List<String> eventNames = new List<String>();
        cceWrapper = ChangeCloudController.getEventsList(camp.Id, eventTypes, eventNames);
        eventTypes.add('Virtual'); 
        cceWrapper = ChangeCloudController.getEventsList(camp.Id, eventTypes, eventNames);
        eventNames.add('Evendra123'); 
        cceWrapper = ChangeCloudController.getEventsList(camp.Id, eventTypes, eventNames);
        eventTypes.clear();
        cceWrapper = ChangeCloudController.getEventsList(camp.Id, eventTypes, eventNames);
        Test.stopTest();
    }    

    @IsTest
    static void getSortedEventsListTest() {
        Test.startTest();
        Campaign camp = [Select Id From Campaign LIMIT 1];
        List<CCEEventWrapper> cceWrapper = new List<CCEEventWrapper>(); 
        List<String> eventTypes = new List<String>();
        List<String> eventNames = new List<String>();
        try{
            cceWrapper = ChangeCloudController.getSortedEventsList(camp.Id, 'ASC', eventTypes, eventNames); 
            eventTypes.add('Virtual'); 
            cceWrapper = ChangeCloudController.getSortedEventsList(camp.Id, 'ASC', eventTypes, eventNames);
            eventNames.add('Evendra123'); 
            cceWrapper = ChangeCloudController.getSortedEventsList(camp.Id, 'ASC', eventTypes, eventNames);
            eventTypes.clear();
            cceWrapper = ChangeCloudController.getSortedEventsList(camp.Id, 'ASC', eventTypes, eventNames);
        }
        catch (Exception e){
            system.debug(TRUE);
        }
        Test.stopTest();
    }  
    @IsTest
    static void getSessionDetailsTest() {
        Test.startTest();
        Session__c p = [SELECT id FROM Session__c LIMIT 1];
 		Session__c result = ChangeCloudController.getSessionDetails(p.Id); 	
        Test.stopTest();
    }   
    @IsTest
    static void getSessionRolesTest() {
        Test.startTest();
        Session__c p = [SELECT id FROM Session__c LIMIT 1];
 		List<Session_Role__c> result = ChangeCloudController.getSessionRoles(p.Id); 	
        Test.stopTest();
    }   
    @IsTest
    static void getSessionParticipantsTest() {
        Test.startTest();
        Session__c p = [SELECT id FROM Session__c LIMIT 1];
 		List<Session_Participant__c> result = ChangeCloudController.getSessionParticipants(p.Id); 	
        Test.stopTest();
    }   
    @IsTest
    static void setSessionParticipantsStatusTest() {
        Test.startTest();
        Session_Participant__c p = [SELECT id FROM Session_Participant__c LIMIT 1];
 		ChangeCloudController.setSessionParticipantsStatus(p.Id); 	
        Test.stopTest();
    }   
    @IsTest
    static void addSessionParticipantsTest() {
        Test.startTest();
        Event__c e = [SELECT id FROM Event__c LIMIT 1];
        Session__c s = [SELECT id FROM Session__c LIMIT 1];
		// Updated By JaysonLabnao [CCN-EVE-2160-DV] OCT092022, XEN REYES March 5, 2023 CCN-EVE-2631-DV
 		ChangeCloudController.addSessionParticipants('xxxxxxxxxx',s.id,'fname','lname','role','sample@sample.com', 'Mr.', 'Others','Test'); 	
        Test.stopTest();
    } 

    // Added By JaysonLabnao [CCN-EVE-2160-DV] OCT102022
    @IsTest
    static void getRankPicklistsTest() {
        Test.startTest();
 		List<ChangeCloudController.PicklistOption> options = ChangeCloudController.getRankPicklists(); 	
        Test.stopTest();

        System.assert(!options.isEmpty(), 'ChangeCloudController.getRankPicklists() should return picklist values.');
    } 
    
    //XEN REYES March 5, 2023 CCN-EVE-2631-DV
    @IsTest
    static void getRankAndRankGroupDependenciesTest() {
        Test.startTest();
            Map<Object,List<String>> options = ChangeCloudController.getRankAndRankGroupDependencies(); 	
        Test.stopTest();

        System.assert(!options.isEmpty(), 'ChangeCloudController.getRankAndRankGroupDependencies() should return picklist values.');
    } 
}