main/default/objects/Campaign/fields/Campaign_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Logo_URL__c</fullName>
    <label>Campaign Logo URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_Message__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Message__c</fullName>
    <label>Contact Us Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_Tag_Line__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Tag_Line__c</fullName>
    <label>Contact Us Tag Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_User__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the user to whom activities raised from the Contact Us page will be assigned to. If this field is empty, the activities will be assigned to the campaign&apos;s owner.</description>
    <label>Contact Us User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Campaign/fields/Hero_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Hero_Image_URL__c</fullName>
    <label>Hero Image URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Logo_URL__c</fullName>
    <label>Campaign Logo URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_Message__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Message__c</fullName>
    <label>Contact Us Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_Tag_Line__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Tag_Line__c</fullName>
    <label>Contact Us Tag Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_User__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the user to whom activities raised from the Contact Us page will be assigned to. If this field is empty, the activities will be assigned to the campaign&apos;s owner.</description>
    <label>Contact Us User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contact_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/fields/Hero_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Hero_Image_URL__c</fullName>
    <label>Hero Image URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Parking_Lot_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Parking_Lot_Close_Date__c</fullName>
    <label>Parking Lot Close Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Event__c/fields/Parking_Lot_Close_Message__c.field-meta.xml
<CustomField>
    <fullName>Parking_Lot_Close_Message__c</fullName>
    <label>Parking Lot Close Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Parking_Lot_Message__c.field-meta.xml
<CustomField>
    <fullName>Parking_Lot_Message__c</fullName>
    <label>Parking Lot Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Parking_Lot_Tag_Line__c.field-meta.xml
<CustomField>
    <fullName>Parking_Lot_Tag_Line__c</fullName>
    <label>Parking Lot Tag Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Parking_Lot__c/Parking_Lot__c.object-meta.xml
<CustomObject>
    <label>Parking Lot</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Parking Lot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parking Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Parking_Lot__c/fields/Addressed_By__c.field-meta.xml
<CustomField>
    <fullName>Addressed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Addressed By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parking Lots (Addressed By)</relationshipLabel>
    <relationshipName>Parking_Lots1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Escalated_To__c.field-meta.xml
<CustomField>
    <fullName>Escalated_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Escalated To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parking Lots (Escalated To)</relationshipLabel>
    <relationshipName>Parking_Lots2</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Parking Lots</relationshipLabel>
    <relationshipName>Parking_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Raised_By__c.field-meta.xml
<CustomField>
    <fullName>Raised_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raised By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parking Lots</relationshipLabel>
    <relationshipName>Parking_Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Resolution_Answer__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Answer__c</fullName>
    <label>Resolution/Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select a session that exists on the selected event</errorMessage>
        <filterItems>
            <field>$Source.Event__c</field>
            <operation>equals</operation>
            <valueField>Session__c.Event__c</valueField>
        </filterItems>
        <filterItems>
            <field>Session__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Parking Lots</relationshipLabel>
    <relationshipName>Parking_Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/CustomParkingLotFormController.cls
/**
* Description: This is the controller class for communityEventParkingLot, which creates a parking lot record and display exisiting records
* Author: Jester Cabantog
* Version: 1.0
* Last modified date: 12/16/2020
* Modified by: 7/18/2023 Rex David - CCN-EVE-3029-DV: Events - Parking Lot view only option
**/
public with sharing class CustomParkingLotFormController {
    
    private static WithoutSharingClass withoutShare = new WithoutSharingClass(); 
    private final static String STARTDATE_SAME_WITH_ENDDATE_FORMAT = '{0} - {1}, {2} to {3} {4}';
    private final static String STARTDATE_NOT_SAME_WITH_ENDDATE_FORMAT = '{0} - {1}, {2} to {3}, {4} {5}';
    
    
    // Added by JaysonLabnao [NamespaceIssueFixes] August172022
    @AuraEnabled
    public static string getNamespacePrefix(){
        String prefix = String.isNotBlank(FlsUtils.prefix) ? FlsUtils.prefix : '';
        return prefix;
    }

    //PT-00333 Event Parking Lot
    //Updated by MMallorca [CCN790,791,792] Oct212021 
    @AuraEnabled 
    public static string getParkingLotDetails(String eventId, String contactId, String sortByValue){
        Map<String,Object> returnMap = new Map <String,Object>();
        Event__c campaignRecord = new Event__c();
        String eventRecordId;
        try{
            //CCN-EVE-3029-DV Rex David - Added fields
            if(FlsUtils.isAccessible('Event__c', new List<String>{'Name','Subtitle__c','Event_Id__c','Hero_Image_URL__c','Campaign_Logo_URL__c',
                'Description__c','Contact_Us_Tag_Line__c','Contact_Us_Message__c', 'OwnerId', 'Start_Date_Time__c','Contact_Us_User__c',
                'Time_Zone__c','Status__c','End_Date_Time__c','Parking_Lot_Tag_Line__c','Parking_Lot_Message__c','Parking_Lot_Close_Date__c','Parking_Lot_Close_Message__c'}) 
               && FlsUtils.isAccessible('Account', new List<String>{'BillingStreet','BillingCity',
                   'BillingPostalCode','BillingState','BillingCountry','Name'})){
                       campaignRecord = withoutShare.getEvent(eventId); 
                   }
            eventRecordId = campaignRecord.Id;
            returnMap.put('campaignRecord', campaignRecord);
            
        } catch (QueryException e){
            if(String.isBlank(eventRecordId)){
                throw new AuraHandledException('Invalid Event Id');     
            }
        }
        
        if(FlsUtils.isAccessible('Contact', new List<String>{'FirstName','LastName','Email'})){
            List<Contact> contactDetails = withoutShare.getContacts(contactId);
            if(!contactDetails.isEmpty()){
                returnMap.put('contact',contactDetails[0]);
            }
        }
        
        List<Session__c> sessionList;
        List<Parking_Lot__c> parkingLotList;
        if(FlsUtils.isAccessible('Session__c', new List<String>{'Name','Subtitle__c','Start_Date_Time__c','End_Date_Time__c','Description__c','Time_Zone__c'})){
            sessionList = withoutShare.getSessions(eventRecordId);
        }       
        if(!sessionList.isEmpty()){
            returnMap.put('session', sessionList.get(0));
        } else {
            throw new AuraHandledException('The event has no active session');
        }
        
        if(String.isBlank(contactId)){
            if(FlsUtils.isAccessible('Parking_Lot__c', new List<String>{'Name','Description__c','Escalated_To__c','Event__c','Raised_By__c',
                'Addressed_By__c','Resolution_Answer__c','Session__c','Site__c','Status__c','Type__c','Category__c'})
               && FlsUtils.isAccessible('Event__c', new List<String>{'Name'})
               && FlsUtils.isAccessible('Contact', new List<String>{'FirstName','LastName','Email','Name'})
               && FlsUtils.isAccessible('Session__c', new List<String>{'Name'})){
                   // Updated by MMallorca [CCN790,791,792] Oct212021 
                   parkingLotList = withoutShare.getParkingLots(eventRecordId, sortByValue);
               }
        } else {
            if(FlsUtils.isAccessible('Session__c', new List<String>{'Name','Subtitle__c','Start_Date_Time__c','End_Date_Time__c','Description__c','Time_Zone__c'})){
                sessionList = withoutShare.getSessionsWithParticipants(eventRecordId, contactId);
            }
            
            if(sessionList.isEmpty()){
                throw new AuraHandledException('Participant is not registered on any session');
            }
            
            if(FlsUtils.isAccessible('Parking_Lot__c', new List<String>{'Name','Description__c','Escalated_To__c','Event__c','Raised_By__c',
                'Addressed_By__c','Resolution_Answer__c','Session__c','Site__c','Status__c','Type__c','Category__c'})
               && FlsUtils.isAccessible('Event__c', new List<String>{'Name'})
               && FlsUtils.isAccessible('Contact', new List<String>{'FirstName','LastName','Email','Name'})
               && FlsUtils.isAccessible('Session__c', new List<String>{'Name'})){
                   // Updated by MMallorca [CCN790,791,792] Oct212021 
                   parkingLotList = withoutShare.getParkingLots(eventRecordId, sortByValue);
               }
        }
        
        //20201230 JL bug fix#00601:Session Picklist(https://ulapp-developers.force.com/projects/s/detail/a0x3k00001UqIwYAAV)
        String strTZone = [SELECT Id, TimeZoneSidKey FROM Organization LIMIT 1].TimeZoneSidKey;
        //wrap sessionList
        List<CustomParkingLotFormController.SessionWrapper> sessionWrapper = new List<CustomParkingLotFormController.SessionWrapper>();
        
        for(Session__c session: sessionList){
            CustomParkingLotFormController.SessionWrapper wrapper = new CustomParkingLotFormController.SessionWrapper();
            String sessionName = '';
            DateTime startDT = session.Start_Date_Time__c;
            DateTime endDT = session.End_Date_Time__c;
            if(startDT != null || endDT != null){
                if(startDT.date() == endDT.date()){
                    sessionName = String.format(STARTDATE_SAME_WITH_ENDDATE_FORMAT, 
                                                new List<Object>{session.Name, startDT.format('MMMMM dd, yyyy', strTZone),
                                                    startDT.format('hh:mm aaa', strTZone), endDT.format('hh:mm aaa', strTZone),
                                                    session.Time_Zone__c});
                    
                } else {
                    sessionName = String.format(STARTDATE_NOT_SAME_WITH_ENDDATE_FORMAT, 
                                                new List<Object>{session.Name, startDT.format('MMMMM dd, yyyy', strTZone),
                                                    startDT.format('hh:mm aaa', strTZone), endDT.format('hh:mm aaa', strTZone),
                                                    endDT.format('hh:mm aaa', strTZone), session.Time_Zone__c});
                } 
            }
            wrapper.recordId = session.Id;
            wrapper.sessionName = session.Name;
            wrapper.sessionFullName = sessionName;
            wrapper.startdatetime = startDT;
            wrapper.enddatetime = endDT;
            wrapper.description = session.Description__c;
            wrapper.timezone = session.Time_Zone__c;
            sessionWrapper.add(wrapper);
        }
        
        returnMap.put('sessionWrapper',sessionWrapper);
        returnMap.put('sessionList',sessionList);
        returnMap.put('parkingLotList',parkingLotList);
        
        List<String> typeList= new List<String>();
        Schema.DescribeFieldResult fieldResult = Parking_Lot__c.Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        
        for( Schema.PicklistEntry pickListVal : ple){
            typeList.add(pickListVal.getLabel());
        }
        
        returnMap.put('typeList',typeList);
        
        //Categories picklist values
        List<String> categoryList= new List<String>();
        Schema.DescribeFieldResult categoryFieldResult = Parking_Lot__c.Category__c.getDescribe();
        List<Schema.PicklistEntry> categoryPle = categoryFieldResult.getPicklistValues();
        
        for( Schema.PicklistEntry pickListVal : categoryPle){
            categoryList.add(pickListVal.getLabel());
        }
        
        returnMap.put('categoryList',categoryList);
        
        return JSON.serialize(returnMap);                                    
    }
    
    //PT-00333 Event Parking Lot
    @AuraEnabled
    // Create parkinglot for each request sent from the custom parking lot form
    // Updated by MMallorca [CCN790,791,792] Oct212021 
    public static void createParkingLot(String eventId, String session, String email, String phone, String description, String type, String category){
        
        if (String.isBlank(eventId) || String.isBlank(session) || String.isBlank(email) || String.isBlank(description) || String.isBlank(type)){
            throw new AuraHandledException('Error on creating parking lot: Required fields missing');
        } 
        
        CustomParkingLotFormHelper.createParkingLotHelper(eventId, session,  email, phone, description, type, category);
    }
    
    //PT-00333 Event Parking Lot
    @AuraEnabled
    // Update parking lot from parking lot data table below parking lot form
    public static void updateParkingLots(String parkingLots){
        
        List<Parking_Lot__c> editedParkingLots = (List<Parking_lot__c>)JSON.deserialize(parkingLots,List<Parking_lot__c>.Class);
        try{
            withoutShare.updateParkingLots(editedParkingLots);
        }
        catch(DmlException e){
            if(e.getMessage().contains('INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST') && e.getMessage().contains('Type__c')){
                List<String> typeList= new List<String>();
                Schema.DescribeFieldResult fieldResult = Parking_Lot__c.Type__c.getDescribe();
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                for( Schema.PicklistEntry pickListVal : ple){
                    typeList.add(pickListVal.getLabel());
                }    
                throw new AuraHandledException('Invalid Type value: '+typeList.toString());
            }
            else if(e.getMessage().contains('INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST') && e.getMessage().contains('Status__c')){
                List<String> statusList= new List<String>();
                Schema.DescribeFieldResult fieldResult = Parking_Lot__c.Status__c.getDescribe();
                List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
                for( Schema.PicklistEntry pickListVal : ple){
                    statusList.add(pickListVal.getLabel());
                }    
                throw new AuraHandledException('Invalid Status value: '+statusList.toString());
            }
            else{
                throw new AuraHandledException(e.getMessage());
            }
        }
    }
    
    public class SessionWrapper{
        @AuraEnabled public Id recordId                 {get; set;}
        @AuraEnabled public String  sessionName         {get; set;}
        @AuraEnabled public String  sessionFullName     {get; set;}
        @AuraEnabled public DateTime  startdatetime     {get; set;}
        @AuraEnabled public DateTime  enddatetime       {get; set;}
        @AuraEnabled public String  description         {get; set;}
        @AuraEnabled public String  timezone            {get; set;}
    }
    
    //Needs inner class declared without sharing for guest users to retrieve relevant records
    private without sharing class WithoutSharingClass {
        
        public void updateParkingLots(List<Parking_Lot__c> editedParkingLots){
            update editedParkingLots;
        }
        
        public List<Contact> getContacts(String contactId){
            return [SELECT Id, Name, Email from Contact WHERE Id = :contactId];
        }
        
        public List<Session__c> getSessions(String eventId){
            return [SELECT Name, Id,
                    Subtitle__c,  
                    Start_Date_Time__c, 
                    End_Date_Time__c, 
                    Description__c, 
                    Time_Zone__c
                    FROM Session__c 
                    WHERE Event__r.Id = :eventId 
                    AND IsActive__c = true 
                    ORDER By Name ASC, Start_Date_Time__c ASC];
        }
        
        public List<Session__c> getSessionsWithParticipants(String eventRecordId, String contactId){
            return [SELECT Name, Id,
                    Subtitle__c,  
                    Start_Date_Time__c, 
                    End_Date_Time__c, 
                    Description__c, 
                    Time_Zone__c
                    FROM Session__c 
                    WHERE Event__r.Id = :eventRecordId 
                    AND Id IN (SELECT Session__c FROM Session_Participant__c
                               WHERE Contact__c =: contactId 
                               AND Event__c = :eventRecordId)
                    AND IsActive__c = true 
                    ORDER By Name ASC, Start_Date_Time__c ASC];
        }
        
        // Updated by MMallorca [CCN790,791,792] Oct212021 
        public List<Parking_Lot__c> getParkingLots(String eventRecordId, String sortByValue){
            String soqlQuery = 'SELECT Id, Name, Description__c, Escalated_To__c, Event__c, Event__r.Name,';
                    soqlQuery += 'Raised_By__c, Raised_By__r.FirstName, Raised_By__r.LastName, Raised_By__r.Email, Raised_By__r.Name, ';
                    soqlQuery += 'Addressed_By__c, Addressed_By__r.FirstName, Addressed_By__r.LastName, Addressed_By__r.Email, Addressed_By__r.Name, '; 
                    soqlQuery += 'Resolution_Answer__c, Session__c, Session__r.Name, ';
                    soqlQuery += 'Site__c, Status__c, Type__c, Category__c ';
                    soqlQuery += 'FROM Parking_Lot__c ';
                    soqlQuery += 'WHERE Event__c = :eventRecordId ';
            if(sortByValue != null){
                soqlQuery += 'ORDER BY '+ sortByValue +' ';
            }
            else{
                soqlQuery += 'ORDER BY Name DESC ';
            }
            system.debug('soqlQuery'+soqlQuery);
            return Database.query(soqlQuery);
        }
        //CCN-EVE-3029-DV Rex David - Added fields
        public Event__c getEvent(String eventCode){
            return [SELECT Id, Name,
                    Subtitle__c,
                    Event_Id__c,
                    Hero_Image_URL__c,
                    Campaign_Logo_URL__c, 
                    Description__c,
                    Parking_Lot_Tag_Line__c,
                    Parking_Lot_Message__c,
                    Location__r.BillingStreet,
                    Location__r.BillingCity, 
                    Location__r.BillingPostalCode,
                    Location__r.BillingState,
                    Location__r.BillingCountry,
                    Location__r.Name,
                    OwnerId,
                    Start_Date_Time__c, 
                    Contact_Us_User__c,
                    Time_Zone__c,
                    Status__c,
                    Parking_Lot_Page_Title__c,
                    End_Date_Time__c,
                    Parking_Lot_Close_Date__c,
                    Parking_Lot_Close_Message__c
                    FROM Event__c 
                    WHERE Event_Id__c = :eventCode 
                    LIMIT 1];
        }
    } 
}