main/default/objects/Campaign/fields/Campaign_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Logo_URL__c</fullName>
    <label>Campaign Logo URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_Message__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Message__c</fullName>
    <label>Contact Us Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_Tag_Line__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Tag_Line__c</fullName>
    <label>Contact Us Tag Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_User__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the user to whom activities raised from the Contact Us page will be assigned to. If this field is empty, the activities will be assigned to the campaign&apos;s owner.</description>
    <label>Contact Us User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Campaign/fields/Hero_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Hero_Image_URL__c</fullName>
    <label>Hero Image URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Campaign/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Brief introduction to the campaign that displays under the campaign name on the campaign summary page.</inlineHelpText>
    <label>Campaign Summary Page Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scrum Master</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Campaign_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Logo_URL__c</fullName>
    <label>Campaign Logo URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_Message__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Message__c</fullName>
    <label>Contact Us Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_Tag_Line__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_Tag_Line__c</fullName>
    <label>Contact Us Tag Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_User__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the user to whom activities raised from the Contact Us page will be assigned to. If this field is empty, the activities will be assigned to the campaign&apos;s owner.</description>
    <label>Contact Us User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contact_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/fields/Hero_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Hero_Image_URL__c</fullName>
    <label>Hero Image URL</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Location_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Event_Role__c/Event_Role__c.object-meta.xml
<CustomObject>
    <label>Event Role</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>Event Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event_Role__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Event Roles</relationshipLabel>
    <relationshipName>Event_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Roles</relationshipLabel>
    <relationshipName>Event_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Role__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Roles</relationshipLabel>
    <relationshipName>Event_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Event Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Speaker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event_Role__c/fields/Show_in_Event_Site__c.field-meta.xml
<CustomField>
    <fullName>Show_in_Event_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show in Event Site</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/CCEHeroControllerTest.cls
@isTest 
private with sharing class CCEHeroControllerTest {
    
    @isTest private static void getEventDetailsMethod(){
        
        // Setup test data
        // Create a unique UserName
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg45.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName=uniqueUserName);
        insert u;
        
        Account newAccount = new Account();
        newAccount.Name = 'Location';
        newAccount.BillingStreet = '222 Lonsdale Street';
        newAccount.BillingCity = 'Melbourne';
        newAccount.BillingPostalCode = '3000';
        newAccount.BillingState = 'VIC';
        newAccount.BillingCountry = 'Australia';
        insert newAccount;
        
        system.debug('--- newAccount ' + newAccount);

		
        Campaign campaignRecord = new Campaign();
        campaignRecord.Event_Id__c = 'kkjdu34301';
        campaignRecord.Name= 'Evendra123';
        campaignRecord.Subtitle__c= 'Evendra123';
        campaignRecord.Hero_Image_URL__c= 'https://www.google.com';
        campaignRecord.Campaign_Logo_URL__c= 'https://www.google.com';
        campaignRecord.Description__c= 'Evendra123';
        campaignRecord.Contact_Us_Tag_Line__c= 'Evendra123';
        campaignRecord.Contact_Us_Message__c= 'Evendra123';
        campaignRecord.Location__c = newAccount.Id;
        campaignRecord.Start_Date_Time__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        campaignRecord.End_Date_Time__c = DateTime.newInstance(2020, 08, 29, 18, 30, 0);
        //campaignRecord.Contact_Us_User__c = u.Id;
        campaignRecord.OwnerId = u.Id;
        System.runAs(u) {
            insert campaignRecord;
        }
        system.debug('--- campaignRecord ' + campaignRecord);
        
        Campaign campaignRecord2 =  [SELECT 	Name,
                                     Subtitle__c,
                                     Event_Id__c,
                                     OwnerId
                                     FROM Campaign WHERE Id =:campaignRecord.Id];
        
        system.debug('--- campaignRecord2 ' + campaignRecord2);
        
        Campaign__c camp = new Campaign__c();
        camp.Name = 'Camp 1';
        insert camp;  
        
        Compass_Setting__c comp = TestDataFactory.createCSData(1);
        insert comp;
        
        Event__c eventRecord = new Event__c();
        eventRecord.Name= 'Evendra123';
        //eventRecord.Subtitle__c= 'Evendra123';
        eventRecord.Hero_Image_URL__c= 'https://www.google.com';
        eventRecord.Campaign_Logo_URL__c= 'https://www.google.com';
        eventRecord.Description__c= 'Evendra123';
        eventRecord.Contact_Us_Tag_Line__c= 'Evendra123';
        eventRecord.Contact_Us_Message__c= 'Evendra123';
        eventRecord.Location__c = newAccount.Id;
        eventRecord.Start_Date_Time__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        eventRecord.End_Date_Time__c = DateTime.newInstance(2020, 08, 29, 18, 30, 0);
        eventRecord.OwnerId = u.Id;
        eventRecord.Campaign__c = camp.Id;         
        eventRecord.Time_Zone__c = 'EDT'; 
        insert eventRecord; 
        
		Event__c event = [Select Event_Id__c From Event__c Where Id =: eventRecord.Id];        
        
         
        Test.startTest();
        try{
            CCEHeroController.getEventDetails(campaignRecord2.Event_Id__c);
        }
        catch(exception e){}
        try{
            CCEHeroController.getEventDetails(event.Event_Id__c);
        }
        catch(exception e){}
        Test.stopTest();
    }
    
    @isTest private static void getEventSessionMethod(){
        
        Account newAccount = new Account();
        newAccount.Name = 'Location';
        newAccount.BillingStreet = '222 Lonsdale Street';
        newAccount.BillingCity = 'Melbourne';
        newAccount.BillingPostalCode = '3000';
        newAccount.BillingState = 'VIC';
        newAccount.BillingCountry = 'Australia';
        insert newAccount;
        
        system.debug('--- newAccount ' + newAccount);
        
        Campaign campaignRecord = new Campaign();
        campaignRecord.Event_Id__c = 'kkjdu34304';
        campaignRecord.Name= 'Evendra123';
        campaignRecord.Subtitle__c= 'Evendra123';
        campaignRecord.Hero_Image_URL__c= 'https://www.google.com';
        campaignRecord.Campaign_Logo_URL__c= 'https://www.google.com';
        campaignRecord.Description__c= 'Evendra123';
        campaignRecord.Contact_Us_Tag_Line__c= 'Evendra123';
        campaignRecord.Contact_Us_Message__c= 'Evendra123';
        campaignRecord.Location__c = newAccount.Id;
        campaignRecord.Start_Date_Time__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        campaignRecord.End_Date_Time__c = DateTime.newInstance(2020, 08, 29, 18, 30, 0);
        insert campaignRecord;
        
        Campaign campaignRecord2 =  [SELECT 	Name,
                                     Subtitle__c,
                                     Event_Id__c
                                     FROM Campaign WHERE Id =:campaignRecord.Id];
        
        Campaign campaignRecord3 = new Campaign();
        campaignRecord3.Event_Id__c = 'kkjdu34305';
        campaignRecord3.ParentId = campaignRecord.Id;
        campaignRecord3.Name= 'Evendra123';
        campaignRecord3.Subtitle__c= 'Evendra123';
        campaignRecord3.Hero_Image_URL__c= 'https://www.google.com';
        campaignRecord3.Campaign_Logo_URL__c= 'https://www.google.com';
        campaignRecord3.Description__c= 'Evendra123';
        campaignRecord3.Contact_Us_Tag_Line__c= 'Evendra123';
        campaignRecord3.Contact_Us_Message__c= 'Evendra123';
        campaignRecord3.Location__c = newAccount.Id;
        campaignRecord3.Start_Date_Time__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        campaignRecord3.End_Date_Time__c = DateTime.newInstance(2020, 08, 29, 18, 30, 0);
        insert campaignRecord3;
        
        Test.startTest();
        CCEHeroController.getEventSession(campaignRecord2.Event_Id__c);
        Test.stopTest(); 
        System.assertNotEquals(CCEHeroController.getEventSession(campaignRecord2.Event_Id__c), null);
    }
    @isTest private static void getSpeakerDetailsMethod(){
        
        Account newAccount = new Account();
        newAccount.Name = 'Location';
        newAccount.BillingStreet = '222 Lonsdale Street';
        newAccount.BillingCity = 'Melbourne';
        newAccount.BillingPostalCode = '3000';
        newAccount.BillingState = 'VIC';
        newAccount.BillingCountry = 'Australia';
        insert newAccount;
        
        Contact newContact = new Contact();
        newContact.FirstName = 'Joe';
        newContact.LastName = 'Joe';
        insert newContact;
        
        
        
        Campaign campaignRecord = new Campaign();
        campaignRecord.Event_Id__c = 'kkjdu34302';
        campaignRecord.Name= 'Evendra123';
        campaignRecord.Subtitle__c= 'Evendra123';
        campaignRecord.Hero_Image_URL__c= 'https://www.google.com';
        campaignRecord.Campaign_Logo_URL__c= 'https://www.google.com';
        campaignRecord.Description__c= 'Evendra123';
        campaignRecord.Contact_Us_Tag_Line__c= 'Evendra123';
        campaignRecord.Contact_Us_Message__c= 'Evendra123';
        campaignRecord.Location__c = newAccount.Id;
        campaignRecord.Start_Date_Time__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        campaignRecord.End_Date_Time__c = DateTime.newInstance(2020, 08, 29, 18, 30, 0);
        insert campaignRecord;
        
        
        Event_Role__c newEventRole = new Event_Role__c();
        newEventRole.Show_in_Event_Site__c = true;
        newEventRole.Role__c = 'Speaker';
        newEventRole.Contact__c = newContact.Id;
        newEventRole.Campaign__c = campaignRecord.Id ;
        insert newEventRole;
        
        Campaign campaignRecord2 =  [SELECT 	Name,
                                     Subtitle__c,
                                     Event_Id__c
                                     FROM Campaign WHERE Id =:campaignRecord.Id];
        
        
        Test.startTest();
        CCEHeroController.getSpeakerDetails(campaignRecord2.Event_Id__c);
        Test.stopTest(); 
        System.assertNotEquals(CCEHeroController.getSpeakerDetails(campaignRecord2.Event_Id__c), null);
    }
    
}