main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the client or organization the campaign is associated with. This connects the campaign to client data.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Educator</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Trainor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Journey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;For Review&quot;</defaultValue>
    <description>Status of the Journey</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey_Participant__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/fields/Related_RecordId__c.field-meta.xml
<CustomField>
    <fullName>Related_RecordId__c</fullName>
    <description>Contains the related record id (Could be Event, Session, Survey or Communication)</description>
    <label>Related Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Milestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Milestone</description>
    <label>Journey Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attestation</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

main/default/objects/Participant_Milestone__c/Participant_Milestone__c.object-meta.xml
<CustomObject>
    <description>All milestones of participants</description>
    <label>Participant Milestone</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Participant Milestone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Event End Date</description>
    <label>Milestone End Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey Participant</description>
    <label>Participant</label>
    <referenceTo>Journey_Participant__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Milestone</description>
    <label>Journey Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/Participant_Milestone_Metric__c.object-meta.xml
<CustomObject>
    <description>Tracks the progress of participants milestone</description>
    <label>Participant Milestone Metric</label>
    <nameField>
        <displayFormat>PMM-{0000000}</displayFormat>
        <label>Participant Milestone Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestone Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone_Metric__c/fields/Metric_Used__c.field-meta.xml
<CustomField>
    <fullName>Metric_Used__c</fullName>
    <description>Metric Used</description>
    <label>Metric Used</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>Participants Milestone</description>
    <label>Milestone</label>
    <referenceTo>Participant_Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestone Metrics</relationshipLabel>
    <relationshipName>Participant_Milestone_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/TheProviderJourney_Test.cls
/*******************************************************************************
* @author       Allen Francisco
* @date         11.02.2021
* @description  Test class for TheProviderJourney
* @revision     11.02.2021 - ADFrancisco - Created
*******************************************************************************/
@isTest(IsParallel=true)
public class TheProviderJourney_Test {
    @TestSetup
    static void createData() {

        Compass_Setting__c compassSetting = new Compass_Setting__c();
        compassSetting.Name = 'Default Settings';
        compassSetting.Email_Sender_Name__c = 'Test Sender';
        insert compassSetting;

        Account ac = new Account(name ='Ulapp3');
        insert ac;
        Campaign__c testCampaign = new Campaign__c();
        testCampaign.Name = 'Test Campaign Name';
        testCampaign.Account__c = ac.Id;
        insert testCampaign;

        Event__c eve = new Event__c();
        eve.Name = 'Test Event';
        eve.Campaign__c = testCampaign.Id;
        eve.Email_Sender_Id__c = null;
        insert eve;
        
        Journey__c testJourney = new Journey__c();
        testJourney.Name = 'Test Journey';
        testJourney.Campaign__c = testCampaign.Id;
        testJourney.Status__c = 'For Review';
        testJourney.End_Date__c = Date.TODAY() + 10;
        insert testJourney;
        
        Account newAccount = new Account();
        newAccount.Name = 'John Doe\'s Inc.';
        
        Id accRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Customer')
            .getRecordTypeId();
        newAccount.RecordTypeId = accRecordTypeId;
        insert newAccount;
        
        Contact newContact = new Contact();
        newContact.Firstname = 'John';
        newContact.Lastname = 'Doe';
        newContact.Email = 'john.doe@test.com';
        newContact.AccountId = newAccount.Id;
        insert newContact;
        
        Journey_Participant__c testParticipant = new Journey_Participant__c();
        testParticipant.Journey__c = testJourney.Id;
        testParticipant.Contact__c = newContact.Id;
        insert testParticipant;

        Participant_Milestone__c testPMilestones = new Participant_Milestone__c();
        testPMilestones.Journey__c = testParticipant.Id;
        insert testPMilestones;

        Participant_Milestone__c testPMilestones2 = new Participant_Milestone__c();
        testPMilestones2.Journey__c = testParticipant.Id;
        insert testPMilestones2;

        Milestone__c testMilestoneComms = new Milestone__c();
        testMilestoneComms.Journey__c = testJourney.Id;
        testMilestoneComms.Name = 'Test Milestone Comms';
        testMilestoneComms.Type__c = 'Communication';
        testMilestoneComms.Related_RecordId__c = eve.Id;
        insert testMilestoneComms;
        
        Milestone__c testMilestoneSurvey = new Milestone__c();
        testMilestoneSurvey.Journey__c = testJourney.Id;
        testMilestoneSurvey.Name = 'Test Milestone Survey';
        testMilestoneSurvey.Type__c = 'Survey';
        testMilestoneSurvey.Related_RecordId__c = eve.Id;
        insert testMilestoneSurvey;
        
        testPMilestones.Milestone__c = testMilestoneComms.Id;
        update testPMilestones;

        testPMilestones.Milestone__c = testMilestoneSurvey.Id;
        update testPMilestones2;

        Participant_Milestone_Metric__c pMilesMetric = new Participant_Milestone_Metric__c();
        pMilesMetric.Milestone__c = testPMilestones.Id;
        // Updated by RiannoRizarri [CCN843] March252022
        pMilesMetric.Metric_used__c = 'Attendance Date';
        // Updated by RiannoRizarri [CCN843] March252022
        insert pMilesMetric;
        
        Task testTask = new Task();
        testTask.WhatId = testPMilestones.Id;
        testTask.Type = 'Related Information';
        insert testTask;
    }
    
    @IsTest
    static void getUserJourney() {
        Test.startTest();
        try {
            Journey__c jData = [SELECT Id FROM Journey__c LIMIT 1];
            Journey_Participant__c jParticipant = [
                SELECT Id
                FROM Journey_Participant__c
                LIMIT 1
            ];
            TheProviderJourney.UserJourneyWrapperClass wrapperClass = new TheProviderJourney.UserJourneyWrapperClass();
            wrapperClass = TheProviderJourney.getUserJourney(jParticipant.Id);
            wrapperClass = TheProviderJourney.getUserJourney(jData.Id);
            System.assertNotEquals(wrapperClass, null);
        } catch (Exception e) {
            System.debug(
                LoggingLevel.DEBUG,
                '!@# ERROR IN INSERT: ' + e.getMessage()
            );
        }
        Test.stopTest();
    }
    
    //Kyzer Buhay - 05/03/2021
    //01057 - positive testing
    @IsTest
    static void contactUsProcessingNoErrors() {
        Journey_Participant__c jParticipant = [
            SELECT
            Id,
            Contact__r.Id,
            Contact__r.FirstName,
            Contact__r.LastName,
            Contact__r.Email,
            Contact__r.Phone,
            Journey__r.Id,
            Journey__r.CreatedById
            FROM Journey_Participant__c
            LIMIT 1
        ];
        Test.startTest();
        try {
            //Sample Contact Us Form input values to TheProviderJourney.createTaskContactUs
            Boolean hasError = TheProviderJourney.createTaskContactUs( jParticipant.Contact__r.Id, jParticipant.Contact__r.FirstName, jParticipant.Contact__r.LastName,
                                                                      jParticipant.Contact__r.Email, jParticipant.Contact__r.Phone, jParticipant.Journey__r.Id, 'Test Subject', 'Test Comment' );
            
            Integer taskCount = [ SELECT COUNT() FROM Task WHERE WhoId = :jParticipant.Contact__r.Id AND Subject = 'Test Subject'];
            //System.assertEquals(1, taskCount);
            //System.assert(!hasError);
        } catch (Exception e) {
            System.debug(LoggingLevel.DEBUG, '!@# ERROR IN INSERT: ' + e.getMessage());
        }
        Test.stopTest();
    }
    
    @IsTest
    static void processSurveyAssessmentCompleteTest(){
        String ppmId = [SELECT Id FROM Participant_Milestone__c LIMIT 1].Id;
        Test.startTest();
        Boolean hasError = TheProviderJourney.processSurveyAssessmentComplete(ppmId);
        Test.stopTest();
        //System.assert(!hasError);
    }

    @IsTest
    static void processEventCatchUpTest(){
        String ppmId = [SELECT Id FROM Participant_Milestone__c LIMIT 1].Id;
        Test.startTest();
        Boolean hasError = TheProviderJourney.processEventCatchUp(ppmId);
        Test.stopTest();
        System.assert(!hasError);
    }

    @IsTest
    static void checkObjectTest(){
        String ppmId = [SELECT Id FROM Participant_Milestone__c LIMIT 1].Id;
        Test.startTest();
        String objType = TheProviderJourney.checkObject(ppmId);
        Test.stopTest();
        System.assertNotEquals(objType, null);
    }

    @IsTest
    static void validateParticipantTest(){
        Journey__c jData = [SELECT Id FROM Journey__c LIMIT 1];
        Test.startTest();
        String resp = TheProviderJourney.validateParticipant('john.doe@test.com',jData.Id);
        Test.stopTest();
        System.assertNotEquals(resp, null);
    }
    // Updated by RiannoRizarri [CCN843] March252022
    @isTest
    static void test_updateParticipantMilestone(){
        Participant_Milestone__c ppmId = [SELECT Id FROM Participant_Milestone__c LIMIT 1];
        TheProviderJourney.ElevatedContext provider = new TheProviderJourney.ElevatedContext();
        provider.updateParticipantMilestone(ppmId);
    }
    // Updated by RiannoRizarri [CCN843] March252022
    
    @isTest
    static void test_saveAnswers(){
        String json = '[{"a9GDS0000004boK2AQ":{"Answer":"Canberra","QuickCheckId":"a9FDS0000000KWB2A2","ParticipantMilestoneId":"a5DDS000003m3672AA","QuestionId":"a9GDS0000004boK2AQ","Question":"<p>What is the Capital of Canberra</p>","CorrectAnswers":"Melbourne","ContactId":"003DS00000uBYdzYAG"}}]';
        Test.startTest();
        TheProviderJourney.saveAnswers(json);
        Test.stopTest();
    }
}