main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Brief introduction to the campaign that displays under the campaign name on the campaign summary page.</inlineHelpText>
    <label>Campaign Summary Page Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Outreach Notification. If this field is populated and related the Session does not have related Outreach Notification, this will be used as the setting for that Session.</description>
    <inlineHelpText>If the related Session does not have related Outreach Notification, this will be used as the setting for that Session.</inlineHelpText>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification__c/Outreach_Notification__c.object-meta.xml
<CustomObject>
    <description>Links to the related notification settings and record that will use the settings</description>
    <label>Outreach Notification</label>
    <nameField>
        <label>Outreach Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates whether setting is Active or Inactive</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Outreach_Notification__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describes the Outreach Notification</description>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/Outreach_Notification_History__c.object-meta.xml
<CustomObject>
    <description>Contains historical data of notifications sent out to contacts.</description>
    <label>Outreach Notification History</label>
    <nameField>
        <displayFormat>ONH{000000}</displayFormat>
        <label>Outreach Notification History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreach Notification Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_History__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the Parent Outreach Notification</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Outreach Notification Histories</relationshipLabel>
    <relationshipName>Outreach_Notification_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/Outreach_Notification_Setting__c.object-meta.xml
<CustomObject>
    <description>Contains the configuration that will be used for each compass objects</description>
    <label>Outreach Notification Setting</label>
    <nameField>
        <label>Outreach Notification Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Notification Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_Setting__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describes the purpose of the notification</description>
    <label>Description</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Outreach Notifiocation record</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Outreach Notification Settings</relationshipLabel>
    <relationshipName>Outreach_Notification_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Outreach Notification</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field determines if a survey is active. Each event/session can only have one active survey at a time.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Survey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is to be deleted</description>
    <label>Campaign(old)</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Survey description that will be displayed in the survey page</description>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the Outreach Notification</description>
    <label>Outreach Notification</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Outreach_Notification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Participant__c/Survey_Participant__c.object-meta.xml
<CustomObject>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that has been selected as a participant for a survey</description>
    <inlineHelpText>Contact that has been selected as a participant for a survey</inlineHelpText>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/OutreachNotificationHistoryBatchTest.cls
@isTest
public class OutreachNotificationHistoryBatchTest {
    @testSetup
    public static void testSetup() {
        List<Apex_Trigger_Switch__c> atsList = new List<Apex_Trigger_Switch__c>();
        Apex_Trigger_Switch__c aps_p = new Apex_Trigger_Switch__c();
        aps_p.Name = 'ParticipantTrigger';
        aps_p.Active__c = false;
        atsList.add(aps_p);
        
        Apex_Trigger_Switch__c aps_sp = new Apex_Trigger_Switch__c();
        aps_sp.Name = 'SessionParticipantTrigger';
        aps_sp.Active__c = false; 
        atsList.add(aps_sp);
        
        Apex_Trigger_Switch__c aps_c = new Apex_Trigger_Switch__c();
        aps_c.Name = 'campaignTrigger';
        aps_c.Active__c = false;
        atsList.add(aps_c);
        
        insert atsList;
        
        Contact c = new Contact();
        c.LastName = 'Test Name';
        c.Email = 'test@test.com';
        insert c;    
        
        EmailTemplate et = new EmailTemplate (developerName = 'test', FolderId = UserInfo.getUserId(), TemplateType= 'Text', Name = 'test', IsActive = true);
        system.runAs(new User(Id = UserInfo.getUserId())) {
            insert et;
        }
        
        OrgWideEmailAddress addresses = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];
        
        Campaign__c cpgn = new Campaign__c();
        cpgn.Name = 'Campaign Test';
        insert cpgn;
        
        Outreach_Notification__c outreachNotif = new Outreach_Notification__c();
        outreachNotif.Name = 'ON Test';
        outreachNotif.Description__c = 'Test';
        outreachNotif.Active__c = true;
        insert outreachNotif;
        
        Compass_Setting__c comp = TestDataFactory.createCSData(1);
        insert comp;
        
        Event__c e = new Event__c();
        e.Name = '';
        e.Campaign__c = cpgn.Id;
        e.Outreach_Notification__c = outreachNotif.Id;
        insert e;
        
        Participant__c p = new Participant__c();
        p.Event__c = e.Id;
        insert p;
        
        List<Session__c> sessionList = new List<Session__c>();
        Session__c s = new Session__c();
        s.Name = 'Session Test';
        s.Event__c = e.Id; 
        
        Session__c s2 = new Session__c();
        s2.Name = 'Session Test 2';
        s2.Event__c = e.Id; 

        sessionList.add(s);
        sessionList.add(s2);
        insert sessionList;
        
        List<Session_Participant__c> sessionParticipantList = new List<Session_Participant__c>();
        Session_Participant__c sp = new Session_Participant__c();
        sp.Session__c = s.Id;
        
        Session_Participant__c sp2 = new Session_Participant__c();
        sp2.Session__c = s2.Id;
        
        sessionParticipantList.add(sp);
        sessionParticipantList.add(sp2);
        insert sessionParticipantList;
        
        Survey__c survey = new Survey__c();
        survey.Name = 'Test';
        insert survey;
        
        Survey_Participant__c surveyParticipant = new Survey_Participant__c();
        surveyParticipant.Survey__c = survey.Id;
        surveyParticipant.Participant__c = c.Id;
        insert surveyParticipant;
        
        Outreach_Notification_Setting__c onsRegistration = new Outreach_Notification_Setting__c();
        onsRegistration.Name = 'ONS Test';
        onsRegistration.Description__c = 'Test';
        onsRegistration.Outreach_Notification__c = outreachNotif.Id;
        onsRegistration.Type__c = 'Invitation Registration Reminder';
        onsRegistration.Email_Template_Name__c = 'Test';
        onsRegistration.Email_Template_Id__c = et.Id;
        onsRegistration.Email_Sender_Id__c = addresses.Id;
        onsRegistration.L1_Days__c = 5;
        onsRegistration.Time__c = Time.newInstance(1, 2, 3, 4);
        
        Outreach_Notification_Setting__c onsConfirmation = new Outreach_Notification_Setting__c();
        onsConfirmation.Name = 'ONS Test';
        onsConfirmation.Description__c = 'Test';
        onsConfirmation.Outreach_Notification__c = outreachNotif.Id;
        onsConfirmation.Type__c = 'Registration Confirmation Reminder';
        onsConfirmation.Email_Template_Name__c = 'Test';
        onsConfirmation.Email_Template_Id__c = et.Id;
        onsConfirmation.Email_Sender_Id__c = addresses.Id;
        onsConfirmation.L1_Days__c = 5;
        onsConfirmation.Time__c = Time.newInstance(1, 2, 3, 4);
        
        Outreach_Notification_Setting__c onsSession = new Outreach_Notification_Setting__c();
        onsSession.Name = 'ONS Test';
        onsSession.Description__c = 'Test';
        onsSession.Outreach_Notification__c = outreachNotif.Id;
        onsSession.Type__c = 'Session Catchup Reminder';
        onsSession.Email_Template_Name__c = 'Test';
        onsSession.Email_Template_Id__c = et.Id;
        onsSession.Email_Sender_Id__c = addresses.Id;
        onsSession.L1_Days__c = 5;
        onsSession.Time__c = Time.newInstance(1, 2, 3, 4);

        Outreach_Notification_Setting__c onsSurvey = new Outreach_Notification_Setting__c();
        onsSurvey.Name = 'ONS Test';
        onsSurvey.Description__c = 'Test';
        onsSurvey.Outreach_Notification__c = outreachNotif.Id;
        onsSurvey.Type__c = 'Survey Thank You';
        onsSurvey.Email_Template_Name__c = 'Test';
        onsSurvey.Email_Template_Id__c = et.Id;
        onsSurvey.Email_Sender_Id__c = addresses.Id;
        onsSurvey.L1_Days__c = 5;
        onsSurvey.Time__c = Time.newInstance(1, 2, 3, 4);

		List<Outreach_Notification_Setting__c> onsList = new List<Outreach_Notification_Setting__c>();
        onsList.add(onsRegistration);
        onsList.add(onsConfirmation);
        onsList.add(onsSession);
        onsList.add(onsSurvey);
        insert onsList;

        Outreach_Notification_History__c onhRegistration = new Outreach_Notification_History__c();
        onhRegistration.Contact__c = c.Id;
        onhRegistration.Related_To__c = 'Test';
        onhRegistration.Related_To_Id__c = e.Id;
        onhRegistration.Outreach_Notification__c = outreachNotif.Id;
        onhRegistration.Outreach_Notification_Setting__c = onsRegistration.Id;
        onhRegistration.Processed__c = false;
        onhRegistration.Schedule__c = Date.today();
        
        Outreach_Notification_History__c onhConfirmation = new Outreach_Notification_History__c();
        onhConfirmation.Contact__c = c.Id;
        onhConfirmation.Related_To__c = 'Test';
        onhConfirmation.Related_To_Id__c = s.Id;
        onhConfirmation.Outreach_Notification__c = outreachNotif.Id;
        onhConfirmation.Outreach_Notification_Setting__c = onsConfirmation.Id;
        onhConfirmation.Processed__c = false;
        onhConfirmation.Schedule__c = Date.today();
        
        Outreach_Notification_History__c onhSession = new Outreach_Notification_History__c();
        onhSession.Contact__c = c.Id;
        onhSession.Related_To__c = 'Test';
        onhSession.Related_To_Id__c = s2.Id;
        onhSession.Outreach_Notification__c = outreachNotif.Id;
        onhSession.Outreach_Notification_Setting__c = onsSession.Id;
        onhSession.Processed__c = false;
        onhSession.Schedule__c = Date.today();
        
        Outreach_Notification_History__c onhSurvey = new Outreach_Notification_History__c();
        onhSurvey.Contact__c = c.Id;
        onhSurvey.Related_To__c = 'Test';
        onhSurvey.Related_To_Id__c = survey.Id;
        onhSurvey.Outreach_Notification__c = outreachNotif.Id;
        onhSurvey.Outreach_Notification_Setting__c = onsSurvey.Id;
        onhSurvey.Processed__c = false;
        onhSurvey.Schedule__c = Date.today();
        
		List<Outreach_Notification_History__c> onhList = new List<Outreach_Notification_History__c>();
        onhList.add(onhRegistration);
        onhList.add(onhConfirmation);
        onhList.add(onhSession);
        onhList.add(onhSurvey);
        insert onhList;
    }
    
    @isTest
    public static void outreachNotificationHistoryBatchTest() {
        Test.startTest();
        OutreachNotificationHistoryBatch onhb = new OutreachNotificationHistoryBatch();
        Database.executeBatch(onhb, 200);
        Test.stopTest();
        
        List<Outreach_Notification_History__c> onhList = [SELECT Id FROM Outreach_Notification_History__c WHERE Processed__c = true];
        //system.assertEquals(4, onhList.size());
    }

}