main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Active_Outreach_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Active_Outreach_Notifications__c</fullName>
    <description>Stores Object API name where Outreach Notifications will be enabled.</description>
    <inlineHelpText>Enter object&apos;s API Name separated by comma.
(e.g Session__c,Journey__c)</inlineHelpText>
    <label>Active Outreach Notifications</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Compass_Setting__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Default Settings</description>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Compass_Setting__c/fields/Email_Template_Invitation_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Invitation_Id__c</fullName>
    <label>Email Template - Invitation Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/fields/Email_Template_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Registration_Id__c</fullName>
    <label>Email Template - Registration Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;For Review&quot;</defaultValue>
    <description>Status of the Journey</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/Outreach_Notification_Setting__c.object-meta.xml
<CustomObject>
    <description>Contains the configuration that will be used for each compass objects</description>
    <label>Outreach Notification Setting</label>
    <nameField>
        <label>Outreach Notification Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Notification Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_Setting__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Member_Status</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/globalValueSets/Member_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Attended</fullName>
    </customValue>
    <customValue>
        <fullName>Catch-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Responded</fullName>
        <isActive>false</isActive>
        <label>Responded</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <isActive>false</isActive>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <masterLabel>Member Status</masterLabel>
</GlobalValueSet>

main/default/classes/BatchOutreachNotification_Test.cls
/*******************************************************************************
 * @author       Angelo Rivera
 * @date           18.09.2021
 * @description  Test class for BatchOutreachNotification
 * @revision     18.09.2021 - APRivera - Created
 *******************************************************************************/

@IsTest
private class BatchOutreachNotification_Test {

    @TestSetup
    static void createData() {
        OrgWideEmailAddress owea = [SELECT Id, DisplayName FROM OrgWideEmailAddress WHERE DisplayName = 'Edera' LIMIT 1];

        EmailTemplate e = new EmailTemplate(
                DeveloperName = 'test',
                FolderId = UserInfo.getUserId(),
                TemplateType = 'Text',
                Name = 'test',
                IsActive = true
        );

        System.runAs(new User(Id = UserInfo.getUserId())) {
            insert e;
        }

        Compass_Setting__c compSetting = new Compass_Setting__c();
        compSetting.Name = 'Default Settings';
        compSetting.Email_Sender_Id__c = '123';
        compSetting.Email_Sender_Name__c = 'NAME';
        compSetting.Email_Template_Invitation_Id__c = e.Id;
        compSetting.Email_Template_Registration_Id__c = e.Id;
        compSetting.Active_Outreach_Notifications__c = 'Event__c';
        compSetting.Default__c = true;
        insert compSetting;

        Contact testContact = new Contact();
        testContact.LastName = 'Test Contact';
        testContact.Email = 'test@email.com';
        insert testContact;

        Contact testContact2 = new Contact();
        testContact2.LastName = 'Test Contact2';
        testContact2.Email = 'test2@email.com';
        insert testContact2;

        Contact testContact3 = new Contact();
        testContact3.LastName = 'Test Contact3';
        testContact3.Email = 'test3@email.com';
        insert testContact3;

        Contact testContact4 = new Contact();
        testContact4.LastName = 'Test Contact4';
        testContact4.Email = 'test4@email.com';
        insert testContact4;

        Campaign__c testCampaign = new Campaign__c();
        testCampaign.Name = 'Test Campaign Name';
        insert testCampaign;

        Journey__c testJourney = new Journey__c();
        testJourney.Name = 'Test Journey';
        testJourney.Campaign__c = testCampaign.Id;
        testJourney.Status__c = 'Approved';
        insert testJourney;

        Outreach_Notification__c outreachNotification = new Outreach_Notification__c(
                Name = 'Test Outreach Notification',
                Description__c = 'Outreach Notification for Test Event');
        insert outreachNotification;

        Outreach_Notification_Setting__c outreachNotificationSetting = new Outreach_Notification_Setting__c(
                Outreach_Notification__c = outreachNotification.Id,
                Name = 'L1 Outreach Notification - Event Registration Reminder',
                Description__c = 'L1 Outreach Notification - Event Registration Reminder',
                Type__c = 'Invitation Registration Reminder',
                Email_Template_Name__c = 'Test',
                L1_Days__c = 5,
                L2_Days__c = 2,
                Time__c = Time.newInstance(13,0, 0,0));
        insert outreachNotificationSetting;

        Outreach_Notification_Setting__c outreachNotificationSetting2 = new Outreach_Notification_Setting__c(
                Outreach_Notification__c = outreachNotification.Id,
                Name = 'L1 Outreach Notification - Event Confirmation Reminder',
                Description__c = 'L1 Outreach Notification - Event Confirmation Reminder',
                Type__c = 'Registration Confirmation Reminder',
                Email_Template_Name__c = 'Test',
                L1_Days__c = 5,
                L2_Days__c = 2,
                Time__c = Time.newInstance(13,0, 0,0));
        insert outreachNotificationSetting2;

        Event__c testEvent = new Event__c();
        testEvent.Campaign__c = testCampaign.Id;
        testEvent.Journey__c = testJourney.Id;
        testEvent.Milestone__c = true;
        testEvent.Email_Sender_Id__c = testContact.Id;
        testEvent.Email_Sender_Id__c = owea.Id;
        testEvent.Start_Date_Time__c = System.today()+6;
        testEvent.End_Date_Time__c = System.today() + 10;
        testEvent.Outreach_Notification__c = outreachNotification.Id;
        testEvent.Time_Zone__c = 'EDT'; 
        insert testEvent;

        Event__c testEvent2 = new Event__c();
        testEvent2.Campaign__c = testCampaign.Id;
        testEvent2.Journey__c = testJourney.Id;
        testEvent2.Milestone__c = true;
        testEvent2.Email_Sender_Id__c = testContact2.Id;
        testEvent2.Email_Sender_Id__c = owea.Id;
        testEvent2.Start_Date_Time__c = System.today()+3;
        testEvent2.End_Date_Time__c = System.today() + 10;
        testEvent2.Outreach_Notification__c = outreachNotification.Id;
        testEvent2.Time_Zone__c = 'EDT'; 
        insert testEvent2;

        Session__c testSession = new Session__c();
        testSession.Name = 'Test CC Session';
        testSession.Event__c = testEvent.Id;
        testSession.Milestone__c = true;
        testSession.Time_Zone__c = 'AKDT';
        testSession.Start_Date_Time__c = System.today()+6;
        testSession.End_Date_Time__c = System.today() + 10;
        testSession.Time_Zone__c = 'EDT'; 
        insert testSession;

        Session__c testSession2 = new Session__c();
        testSession2.Name = 'Test CC Session';
        testSession2.Event__c = testEvent.Id;
        testSession2.Milestone__c = true;
        testSession2.Time_Zone__c = 'AKDT';
        testSession2.Start_Date_Time__c = System.today()+6;
        testSession2.End_Date_Time__c = System.today() + 10;
        insert testSession2;

        Session__c testSession3 = new Session__c();
        testSession3.Name = 'Test CC Session';
        testSession3.Event__c = testEvent2.Id;
        testSession3.Milestone__c = true;
        testSession3.Time_Zone__c = 'AKDT';
        testSession3.Start_Date_Time__c = System.today()+3;
        testSession3.End_Date_Time__c = System.today() + 10;
        insert testSession3;

        Participant__c participantData = new Participant__c();
        participantData.Event__c = testEvent.Id;
        participantData.Member_Contact__c = testContact.Id;
        participantData.Status__c = 'Invited';
        insert participantData;

        Participant__c participantData2 = new Participant__c();
        participantData2.Event__c = testEvent2.Id;
        participantData2.Member_Contact__c = testContact2.Id;
        participantData2.Status__c = 'Invited';
        insert participantData2;

        Participant__c participantData3 = new Participant__c();
        participantData3.Event__c = testEvent.Id;
        participantData3.Member_Contact__c = testContact3.Id;
        participantData3.Status__c = 'Invited';
        insert participantData3;

        Participant__c participantData4 = new Participant__c();
        participantData4.Event__c = testEvent2.Id;
        participantData4.Member_Contact__c = testContact4.Id;
        participantData4.Status__c = 'In Progress';
        insert participantData4;

        Session_Participant__c sessParticipant = new Session_Participant__c();
        sessParticipant.Event__c = testEvent.Id;
        sessParticipant.Contact__c = testContact.Id;
        sessParticipant.Session__c = testSession.Id;
        sessParticipant.Participant__c = participantData.Id;
        sessParticipant.Status__c = 'Registered';
        insert sessParticipant;

        Session_Participant__c sessParticipant2 = new Session_Participant__c();
        sessParticipant2.Event__c = testEvent.Id;
        sessParticipant2.Contact__c = testContact.Id;
        sessParticipant2.Session__c = testSession2.Id;
        sessParticipant2.Participant__c = participantData.Id;
        sessParticipant2.Status__c = 'Declined';
        insert sessParticipant2;

        Session_Participant__c sessParticipant3 = new Session_Participant__c();
        sessParticipant3.Event__c = testEvent2.Id;
        sessParticipant3.Contact__c = testContact4.Id;
        sessParticipant3.Session__c = testSession3.Id;
        sessParticipant3.Participant__c = participantData4.Id;
        sessParticipant3.Status__c = 'Registered';
        insert sessParticipant3;

        Outreach_Notification_History__c outreachNotificationHistory = new Outreach_Notification_History__c(
                Outreach_Notification_Setting__c = outreachNotificationSetting.Id,
                Contact__c = testContact2.Id,
                Outreach_Notification__c = outreachNotification.Id,
                Related_To__c = 'Test Event 2',
                Related_To_Id__c = testEvent2.Id,
                Timezone__c = 'AKDT'
        );
        insert outreachNotificationHistory;

        Outreach_Notification_History__c outreachNotificationHistory2 = new Outreach_Notification_History__c(
                Outreach_Notification_Setting__c = outreachNotificationSetting2.Id,
                Contact__c = testContact4.Id,
                Outreach_Notification__c = outreachNotification.Id,
                Related_To__c = 'Test CC Session',
                Related_To_Id__c = testSession3.Id,
                Timezone__c = 'AKDT'
        );
        insert outreachNotificationHistory2;
    }


    @IsTest
    static void testOutreachNotificationBatch() {
        Test.startTest();

        BatchOutreachNotification  batchObj = new  BatchOutreachNotification ();
        batchObj.strQuery='SELECT Active_Outreach_Notifications__c, Default__c FROM Compass_Setting__c WHERE Default__c = TRUE';
        Id batchProcessId = Database.executeBatch(batchObj,100);


        String CRON_EXP = '0 0 0 3 9 ? 2024';
        String jobId = System.schedule('testBasicScheduledApex', CRON_EXP, new BatchOutreachNotification());

        Test.stopTest();

        List<Outreach_Notification_History__c> onh = new List<Outreach_Notification_History__c>();
        onh = [SELECT Id FROM Outreach_Notification_History__c];
        System.assert(onh.size() > 0);

    }
}