main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Location_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Internal_Resource__c/Internal_Resource__c.object-meta.xml
<CustomObject>
    <label>Internal Resource</label>
    <nameField>
        <displayFormat>IR-{000000}</displayFormat>
        <label>Event Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Resource__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Internal Resources</relationshipLabel>
    <relationshipName>Internal_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Internal Resources</relationshipLabel>
    <relationshipName>Internal_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/Internal_Resource_Session__c.object-meta.xml
<CustomObject>
    <label>Internal Resource Session</label>
    <nameField>
        <displayFormat>IRS-{000000}</displayFormat>
        <label>Session Resource  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Resource Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Resource_Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Resource Number</label>
    <referenceTo>Internal_Resource__c</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Member_Status</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Domain_Name__c</fullName>
    <label>Domain Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/globalValueSets/Member_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Attended</fullName>
    </customValue>
    <customValue>
        <fullName>Catch-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Responded</fullName>
        <isActive>false</isActive>
        <label>Responded</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <isActive>false</isActive>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <masterLabel>Member Status</masterLabel>
</GlobalValueSet>

main/default/classes/BatchEventDeliveryConfirmationTest.cls
@isTest
public with sharing class BatchEventDeliveryConfirmationTest {

    @TestSetup
    static void makeData(){
        //User testUser = TestFactory.createInteralUser('Test', 'User', 'testUser15092020@gmail.com', 'System Administrator');
        User testUser = TestDataFactory.createUser('Test', 'User', 'testUser15092020@gmail.com', 'System Administrator');
        System.runAs(testUser){
            Compass_Setting__c cSetting = TestDataFactory.createCSData(1);
            cSetting.Domain_Name__c  = 'https://dev3-nationalcoordinationcenter.cs90.force.com/Compass';
            insert cSetting;
            
            List<Apex_Trigger_Switch__c> atsList = new List<Apex_Trigger_Switch__c>();
            Apex_Trigger_Switch__c aps_p = TestDataFactory.createTriggerSwitch('ParticipantTrigger');
            aps_p.Active__c = false;
            atsList.add(aps_p);
            
            Apex_Trigger_Switch__c aps_sp = TestDataFactory.createTriggerSwitch('SessionParticipantTrigger');
            aps_sp.Active__c = false;
            atsList.add(aps_sp);
            insert atsList;
            
            Account testAccount = TestDataFactory.createAccount('Test Account');
            testAccount.BillingStreet = '123 Green Avenue';
            testAccount.BillingCity = 'Melbourne';
            testAccount.BillingPostalCode = '3000';
            testAccount.BillingState = 'VIC';
            testAccount.BillingCountry = 'Australia';
            insert testAccount;
            
            User campaignOwner = TestDataFactory.createUser('Campaign', 'Owner', 'campaign.owner@gmail.com', 'System Administrator');
            campaignOwner.TimeZoneSidKey = 'America/New_York';
            insert campaignOwner;
            
            Campaign parentEvent = TestDataFactory.createStandardCampaign('Parent Event');
            parentEvent.Location__c = testAccount.Id;
            parentEvent.OwnerId = campaignOwner.Id;
            parentEvent.Start_Date_Time__c = DateTime.newInstance(2020, 8, 29, 8, 30, 0);
            parentEvent.End_Date_Time__c = DateTime.newInstance(2020, 8, 31, 12, 30, 0);
            insert parentEvent;
            
            Campaign childSession = TestDataFactory.createStandardCampaign('Child Session');
            childSession.ParentId = parentEvent.Id;
            childSession.Start_Date_Time__c = DateTime.newInstance(2020, 8, 29, 8, 30, 0);
            childSession.End_Date_Time__c = DateTime.newInstance(2020, 8, 29, 12, 30, 0);
            insert childSession;
            
            Contact attendee = TestDataFactory.createContact('Test', 'Attendee', 'test.attendee@gmail.com');
            insert attendee;
            
            CampaignMember cm = TestFactory.createCampaignMember(parentEvent.Id, attendee);
            Event__c e = TestFactory.createEvent('Test Event');
	    
	    DateTime dt = System.now().addDays(7);
	    
            Session__c testSessionRec = new Session__c();
            testSessionRec.Contact__c = attendee.Id;
            testSessionRec.Session__C = childSession.Id;
            testSessionRec.Event__c = e.Id;
            testSessionRec.Start_Date_Time__c = Datetime.newInstance(dt.year(), dt.month(), dt.day(), 12, 30, 2);
            testSessionRec.End_Date_Time__c = Datetime.newInstance(dt.year(), dt.month(), dt.day(), 12, 31, 2);
            testSessionRec.Time_Zone__c = 'PST';
            insert testSessionRec;
            
            Participant__c p = TestDataFactory.createParticipant(e.Id, attendee.Id);
            insert p;
            
            Session_Participant__c sp = TestDataFactory.createSessionParticipant(testSessionRec.Id);
            sp.Event__c = e.Id;
            sp.Contact__c = attendee.Id;
            sp.Status__c = 'Registered';
            insert sp;

            // Create Internal Resources
            Internal_Resource__c ir = new Internal_Resource__c();
            ir.Contact__c  = attendee.Id;
            ir.Event__c    = e.Id;

            insert ir;

            // Create Internal Resources Session
            Internal_Resource_Session__c irs = new Internal_Resource_Session__c();
            irs.Contact__c  = attendee.Id;
            irs.Event__c    = e.Id;
            irs.Resource__c = ir.Id;
            irs.Session__c  = testSessionRec.Id;
            irs.Resource_Session_Status__c = 'Registered';

            insert irs;

            Batch_Processor__c bp = new Batch_Processor__c();
            bp.Record_Id__c = ir.Id;
            bp.Type__c = 'BatchEventDeliveryConfirmation';
            bp.Trigger_Source__c = 'InternalResourceSessionTriggerHandler';
            insert bp;
        }
    }

    @isTest
    static void BatchEventDeliveryConfirmationExcuteTest() {
        
        Test.startTest();
        BatchEventDeliveryConfirmation abc = new BatchEventDeliveryConfirmation();
        abc.execute(null);
        Test.stopTest();       
    }
}