main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_User__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the user to whom activities raised from the Contact Us page will be assigned to. If this field is empty, the activities will be assigned to the campaign&apos;s owner.</description>
    <label>Contact Us User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Domain_Name_Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Domain_Name_Event_Registration__c</fullName>
    <label>Domain Name (Event Registration)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_User__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the user to whom activities raised from the Contact Us page will be assigned to. If this field is empty, the activities will be assigned to the campaign&apos;s owner.</description>
    <label>Contact Us User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contact_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Location_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Member_Contact__c.field-meta.xml
<CustomField>
    <fullName>Member_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Event_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Member_Status</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Participant__c/recordTypes/Participant.recordType-meta.xml
<RecordType>
    <fullName>Participant</fullName>
    <active>true</active>
    <label>Participant</label>
</RecordType>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Confirm_Response_Link__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Response_Link__c</fullName>
    <formula>Domain_Name__c + &quot;/?id=&quot; +  Id + &quot;&amp;response=Confirmed&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Confirm Response Link</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Decline_Response_Link__c.field-meta.xml
<CustomField>
    <fullName>Decline_Response_Link__c</fullName>
    <formula>Domain_Name__c + &quot;/?id=&quot; +  Id + &quot;&amp;response=Declined&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Decline Response Link</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Domain_Name__c</fullName>
    <label>Domain Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/globalValueSets/Member_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Attended</fullName>
    </customValue>
    <customValue>
        <fullName>Catch-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Responded</fullName>
        <isActive>false</isActive>
        <label>Responded</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <isActive>false</isActive>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <masterLabel>Member Status</masterLabel>
</GlobalValueSet>

main/default/classes/EventConfirmationHelper.cls
/*******************************************************************************************
* @author: Jasmine Nguyen
* @created: 05-09-2020
* @description: Generates the wrapper that will be displayed in the table for Confirmation Emails
*
* Changes (version)
* -------------------------------------------------------------------------------------------
*             No.   Date(dd-mm-yyy)   Author                Description
*             ----  ---------------   --------------------  ---------------------------------
* @version    1.0   05-09-2020        Jasmine Nguyen        Initial Creation
*			  2.0	??-??-????		  Angelo Rivera			Updated object references
*			  3.0   26-08-2021        Paolo Quiambao        added Confirm/Decline response link and Status in sessionWrapper, added DateTime conversion
* 			  4.0	30-04-2022		  Paolo Quiambao		[CCN-1216] Enhance logic to accept multiple Session Participant Ids
*			  5.0	12-06-2022		  Paolo Quiambao		[CCN-1216] Added filter to consider only Registered, Confirmed, Declined, and Cancelled status
*             6.0   17-06-2022        Von Pernicia          [CCN-EVE-1773-DV] - Updated status value from Cancelled to Canceled
*********************************************************************************************/

public with sharing class EventConfirmationHelper {

    @testVisible
    public static Boolean throwFakeException = false;
    
    // Get sessions details
    public static EventConfirmationWrapper getSessionsDetails(String campaignMemberId) {
        String idStringForUrl = ''; // Updated by PaoloQuiambao [ccneve1216dv] April302022
        //String domainName = [SELECT Id, Domain_Name_Event_Registration__c FROM Compass_Setting__c WHERE Name = 'Default Settings' LIMIT 1].Domain_Name_Event_Registration__c; - Commented out since Domain Name Event Registration is not yet in UAT onwards
        String domainName = [SELECT Id, Domain_Name__c FROM Compass_Setting__c WHERE Name = 'Default Settings' LIMIT 1].Domain_Name__c;
        EventConfirmationWrapper eventConfirmationWrapper = new EventConfirmationWrapper(); // Updated by PaoloQuiambao [ccneve1216dv] April302022
        Set<String> statusToConsider = new Set<String>{'Registered', 'Confirmed', 'Declined', 'Canceled'}; // CCN-EVE-1773-DV // Updated by PaoloQuiambao [ccneve1216dv] June122022
        List<SessionWrapper> sessionsWrappers = new List<SessionWrapper>();
        List<Participant__c> campaignMembers = new List<Participant__c>(); 
        List<Id> sessionParticipantIds = new List<Id>(); // Added by Paolo Quiambao [CCN-EVE-1216-DV] April292022
        Map<Id, Participant__c> mapCampaignMembers; // Added by DinoBrinas [CCN-EVE-1191-QA-BUG-2] April072022
        if(FlsUtils.isAccessible('Participant__c', new List<String>{'Event__c','Member_Contact__c'})&&FlsUtils.isAccessible('Contact', new List<String>{'AccountId'})
           &&FlsUtils.isAccessible('Event__c', new List<String>{'OwnerId','Contact_Us_User__c','Location__c','Time_Zone__c'})){
            campaignMembers = [SELECT Id, Event__c, Member_Contact__c, Member_Contact__r.AccountId, Event__r.OwnerId,
                                Event__r.Contact_Us_User__c, Event__r.Location__c, Event__r.Time_Zone__c
                                FROM Participant__c WHERE Id =: campaignMemberId LIMIT 1];
            mapCampaignMembers = new Map<Id, Participant__c>(campaignMembers); // Added by DinoBrinas [CCN-EVE-1191-QA-BUG-2] April072022
        }

        if (mapCampaignMembers <> null && mapCampaignMembers.size() > 0){ // Updated by DinoBrinas [CCN-EVE-1191-QA-BUG-2] April072022
            String strTZone = [SELECT Id, TimeZoneSidKey FROM Organization LIMIT 1].TimeZoneSidKey;
            if(FlsUtils.isAccessible('Session_Participant__c', new List<String>{'Name','Event__c','Contact__c'})&&
               FlsUtils.isAccessible('Session__c', new List<String>{'Start_Date_Time__c','End_Date_Time__c','Time_Zone__c','Name'})){
                   for (Session_Participant__c s : [SELECT Id, Name,Event__c, Contact__c, Session__r.Start_Date_Time__c, Session__r.End_Date_Time__c,
                                                    Event__r.Location__r.Name, Session__r.Time_Zone__c, Session__r.Name, Session__r.Location__c, Confirm_Response_Link__c, 
                                                    Decline_Response_Link__c, Status__c
                                                    FROM Session_Participant__c
                                                    WHERE Contact__c =: mapCampaignMembers.get(campaignMemberId).Member_Contact__c
                                                    AND Status__c IN :statusToConsider // Updated by PaoloQuiambao [ccneve1216dv] June122022
                                                    AND Event__c =: mapCampaignMembers.get(campaignMemberId).Event__c]){ // Updated by DinoBrinas [CCN-EVE-1191-QA-BUG-2] April072022
                                                        // if (s != null && convertDateTimeToOtherTimeZone(convertDateTimeToOtherTimeZone(s.Session__r.Start_Date_Time__c, 'UTC', strTZone), s.Session__r.Time_Zone__c, 'UTC') > System.now()){
                                                        // UPDATED by JC ESPINO [CCN-EVE-1191-QA-BUG-2] - DateTime is saved in UTC, no need to convert. System.now() is in UTC as well.
                                                        // UPDATED by JC ESPINO [CCN-EVE-1360-DV] - Updated location info to the Session Location field if present
                                                        if(s != null && (s.Session__r.Start_Date_Time__c > System.now())) {
                                                            SessionWrapper sw = new SessionWrapper();
                                                            sw.Name = s.Session__r.Name;
                                                            sw.SessionDate = s.Session__r.Start_Date_Time__c.format('MMMM dd, yyyy', strTZone);
                                                            sw.SessionTime = s.Session__r.Start_Date_Time__c.format('h:mm a', strTZone) + ' to '; 
                                                            sw.SessionTime2 = s.Session__r.End_Date_Time__c.format('h:mm a', strTZone) + ' ' + s.Session__r.Time_Zone__c;
                                                            sw.SessionLocation = s.Session__r.Location__c != null ? s.Session__r.Location__c : s.Event__r.Location__r.Name;
                                                            sw.confirmResponseLink = s.Confirm_Response_Link__c;
                                                            sw.declineResponseLink = s.Decline_Response_Link__c;
                                                            sw.status = s.Status__c;
                                                            sessionsWrappers.add(sw);
                                                            
                                                            // Updated by PaoloQuiambao [ccneve1216dv] April302022
                                                            if(s.Status__c == 'Registered') {
                                                                sessionParticipantIds.add(s.Id);   
                                                            }
                                                        }
                                                    }
                   
                   // Updated by PaoloQuiambao [ccneve1216dv] April302022
                   for(Id spId : sessionParticipantIds) {
                       idStringForUrl += String.valueOf(spId) + '+';
                   }
                   
                   eventConfirmationWrapper.showConfirmDeclineAllButton = sessionParticipantIds.size() > 1 ? true : false; // Updated by PaoloQuiambao [ccneve1216dv] April302022
                   eventConfirmationWrapper.confirmAllLink = domainName + '/?id=' + idStringForUrl.removeEnd('+') + '&response=Confirmed'; // Updated by PaoloQuiambao [ccneve1216dv] April302022
                   eventConfirmationWrapper.declineAllLink = domainName + '/?id=' + idStringForUrl.removeEnd('+') + '&response=Declined'; // Updated by PaoloQuiambao [ccneve1216dv] April302022
                   eventConfirmationWrapper.sessionList = sessionsWrappers; // Updated by PaoloQuiambao [ccneve1216dv] April302022
               }
        }

        return eventConfirmationWrapper; // Updated by PaoloQuiambao [ccneve1216dv] April302022
    }
    
    // Updated by PaoloQuiambao [ccneve1216dv] April302022
    public class EventConfirmationWrapper {
        public Boolean showConfirmDeclineAllButton {get;set;}
        public String confirmAllLink {get;set;}
        public String declineAllLink {get;set;}
        public List<SessionWrapper> sessionList {get;set;}
    }
    
    public class SessionWrapper{
        public String Name {get; set;}
        public String SessionDate {get; set;}
        public String SessionTime {get; set;}
        public String SessionTime2 {get;set;}
        public String SessionLocation {get; set;}
        public String confirmResponseLink {get;set;}
        public String declineResponseLink {get;set;}
        public String status {get;set;}
    }
    
    // Get formatted date time
    public static String getFormattedDateTimeHelper(String campaignOwnerId, String campaignId, String startOrEndDate, String defined_format, String timeOrDate){
        String FormattedDatetime;
        if (campaignOwnerId == null || campaignId == null || startOrEndDate == null){
            return '';
        } else {
            String queryString = (startOrEndDate.toLowerCase() == 'start') ? 'SELECT Start_Date_Time__c, End_Date_Time__c, OwnerId, Contact_Us_User__c, Time_Zone__c FROM Event__c WHERE Id =: campaignId LIMIT 1'
                : 'SELECT Start_Date_Time__c, End_Date_Time__c, OwnerId, Contact_Us_User__c, Time_Zone__c FROM Event__c WHERE Id =: campaignId LIMIT 1';
            List<sObject> sobjList = Database.query(queryString);
            if (sobjList.size() > 0){
                Event__c campaign = (Event__c)sobjList[0];
                if (campaign != null ){
                    String strTZone = [SELECT Id, TimeZoneSidKey FROM Organization LIMIT 1].TimeZoneSidKey;
                    if (campaign != null && throwFakeException == false){
                        DateTime localDateTime;
                        if (startOrEndDate.toLowerCase() == 'start' && campaign.Start_Date_Time__c != null){
                            localDateTime = campaign.Start_Date_Time__c;
                        } 
                        if (startOrEndDate.toLowerCase() == 'end' && campaign.End_Date_Time__c != null ){
                            localDateTime = campaign.End_Date_Time__c; 
                        }
                        if (localDateTime != null) {
                            if(timeOrdate.toLowerCase() == 'date' || (startOrEndDate.toLowerCase() == 'start' && timeOrdate.toLowerCase() != 'date')) {
                                FormattedDatetime = localDateTime.format(defined_format, strTZone);
                            }
                            else {
                                FormattedDatetime = localDateTime.format(defined_format, strTZone) + ' ' + campaign.Time_Zone__c;
                            }
                        }
                            
                        return FormattedDatetime;
                    }
                }  
            }
          
            return '';
            
        }
    }
    
    // UPDATED by JC ESPINO [CCN-EVE-1191-QA-BUG-2] - DateTime is saved in UTC, no need to convert. System.now() is in UTC as well.
    // public static DateTIme convertDateTimeToOtherTimeZone(DateTime dTime, String sourceTimeZone, String targetTimeZone) {
    //     TimeZone sourceTZ = Timezone.getTimeZone(sourceTimeZone);
    //     Integer offset = sourceTZ.getOffset(dTime);
        
    //     TimeZone targetTZ = Timezone.getTimeZone(targetTimeZone);
    //     Integer offsetTotargetTZ = targetTZ.getOffset(dTime);
    //     Integer correction = offsetTotargetTZ - offset;
        
    //     return dTime.addMinutes(correction / (1000 * 60));
    // }

}