main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Attended_Participant_Fields_JSON__c.field-meta.xml
<CustomField>
    <fullName>Attended_Participant_Fields_JSON__c</fullName>
    <label>Attended Participant Fields JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Readiness_Self_Ranking__c.field-meta.xml
<CustomField>
    <fullName>Readiness_Self_Ranking__c</fullName>
    <label>Readiness Self Ranking</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novice</fullName>
            </value>
            <value>
                <fullName>Advanced Beginner</fullName>
            </value>
            <value>
                <fullName>Proficient</fullName>
            </value>
            <value>
                <fullName>Expert</fullName>
            </value>
            <value>
                <fullName>Observer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session_Participation__c.field-meta.xml
<CustomField>
    <fullName>Session_Participation__c</fullName>
    <label>Session Participation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distracted</fullName>
            </value>
            <value>
                <fullName>Observed</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Challenged</fullName>
            </value>
            <value>
                <fullName>Progressing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/AttendedParticipantsFieldPickerCntlrTest.cls
/*******************************************************************************
 * @author       RLugpatan
 * @date         10/12/2021
 * @description  Test class for SetAttendedParticipantsFieldPickerCtrl [CCN975]
 *******************************************************************************/
@IsTest
public class AttendedParticipantsFieldPickerCntlrTest {
    @TestSetup static void createData(){
        Campaign__c camp = new Campaign__c();
        camp.Name = 'Test Campaign';
        insert camp;
        
        Contact c = new Contact();
        c.FirstName = 'John';
        c.LastName = 'John';
        c.Department = 'IT';
        c.Email = 'John@test.com';
        insert c;
        
        Compass_Setting__c comp = TestDataFactory.createCSData(1);
        insert comp;

        Event__c e = new Event__c();
        e.Event_Id__c = 'xxxxxxxxxx';
        e.Campaign__c = camp.id;
        e.Start_Date_Time__c = DateTime.Now();
        e.End_Date_Time__c = DateTime.Now()+1;        
        e.Time_Zone__c = 'EDT'; 
        insert e;
    }
    
    @IsTest
    static void hasExistingAttendedFieldJSONTest(){
        Event__c eventRec = [SELECT Id FROM Event__c LIMIT 1];
        eventRec.Attended_Participant_Fields_JSON__c = '{"Readiness_Self_Ranking-Session_Participant__c|Readiness_Self_Ranking__c":true,"Session_Participation-Session_Participant__c|Session_Participation__c":true}';
        update eventRec;
        
        Test.startTest();
        	List<AttendedParticipantFields> regFields = SetAttendedParticipantsFieldPickerCtrl.getAttendedParticipantFields(eventRec.Id);
        Test.stopTest();
    }
    
    @IsTest
    static void hasNoExistingAttendedFieldJSONTest(){
        Event__c eventRec = [SELECT Id FROM Event__c LIMIT 1];
        Test.startTest();
        	List<AttendedParticipantFields> regFields = SetAttendedParticipantsFieldPickerCtrl.getAttendedParticipantFields(eventRec.Id);
        Test.stopTest();
    }
    
    
    @IsTest
    static void handleSaveAttendedConfigurationTest(){
        Event__c eventRec = [SELECT Id FROM Event__c LIMIT 1];
        
        String jsonFieldConfig = '{"Readiness_Self_Ranking-Session_Participant__c|Readiness_Self_Ranking__c":true,"Session_Participation-Session_Participant__c|Session_Participation__c":true}';
        
        Test.startTest();
        	Boolean hasErrors = SetAttendedParticipantsFieldPickerCtrl.saveAttendedParticipantFields(eventRec.Id, jsonFieldConfig);
        Test.stopTest();
        
        System.assert(!hasErrors);
    }
    
    @IsTest
    static void handleExceptionTest(){
        Test.startTest();
        try {
            List<AttendedParticipantFields> regFields = SetAttendedParticipantsFieldPickerCtrl.getAttendedParticipantFields(null);
            Boolean hasErrors = SetAttendedParticipantsFieldPickerCtrl.saveAttendedParticipantFields(null, null);
        }catch (Exception e){
            System.assert(TRUE);
        }
        Test.stopTest();
        
    }
}