main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the client or organization the campaign is associated with. This connects the campaign to client data.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Email_Template_Invitation_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Invitation_Id__c</fullName>
    <label>Email Template - Invitation Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/fields/Email_Template_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Registration_Id__c</fullName>
    <label>Email Template - Registration Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Message_BCC__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_BCC__c</fullName>
    <label>Email Message BCC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Message_CC__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_CC__c</fullName>
    <label>Email Message CC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Member_Contact__c.field-meta.xml
<CustomField>
    <fullName>Member_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Event_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>Holds the Rank for each Participant</description>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TSgt</fullName>
            </value>
            <value>
                <fullName>SSgt</fullName>
            </value>
            <value>
                <fullName>Capt</fullName>
            </value>
            <value>
                <fullName>HM1</fullName>
            </value>
            <value>
                <fullName>HM2</fullName>
            </value>
            <value>
                <fullName>Lt Col</fullName>
            </value>
            <value>
                <fullName>Maj</fullName>
            </value>
            <value>
                <fullName>SrA</fullName>
            </value>
            <value>
                <fullName>Lt</fullName>
            </value>
            <value>
                <fullName>CIV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Branch_of_Service__c.field-meta.xml
<CustomField>
    <fullName>Branch_of_Service__c</fullName>
    <label>Branch of Service</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Branch_of_Service</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Role__c/Session_Role__c.object-meta.xml
<CustomObject>
    <description>01080 - Custom object for Session Role</description>
    <label>Session Role</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Session Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Session_Role__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Session</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Roles</relationshipLabel>
    <relationshipName>Session_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/globalValueSets/Branch_of_Service.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Air Force</fullName>
    </customValue>
    <customValue>
        <fullName>Army</fullName>
    </customValue>
    <customValue>
        <fullName>Navy</fullName>
    </customValue>
    <masterLabel>Branch of Service</masterLabel>
</GlobalValueSet>

main/default/classes/MassSessionSignUpController_Test.cls
@IsTest
public class MassSessionSignUpController_Test {
	@TestSetup
    static void setupData(){
        OrgWideEmailAddress owea = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];
        
        EmailTemplate eTemp = new EmailTemplate (developerName = 'test', FolderId = UserInfo.getUserId(), TemplateType= 'Text', Name = 'test', IsActive = true);
        system.runAs( new User(Id = UserInfo.getUserId())){
          insert eTemp;
        }
        
        Apex_Trigger_Switch__c aps = new Apex_Trigger_Switch__c();
        aps.Name = 'EventTrigger';
        aps.Active__c = false;
        insert aps;
        
        /* 
        Compass_Setting__c setting = new Compass_Setting__c();
        setting.Name = 'Default Settings';
        setting.Email_Sender_Id__c = 'qwerty';
        insert setting;
        */
        
        Compass_Setting__c setting = new Compass_Setting__c();
        setting.Name = 'Default Settings';
        setting.Email_Sender_Name__c = 'NAME';
        setting.Email_Template_Invitation_Id__c = eTemp.Id;
        setting.Email_Template_Registration_Id__c = eTemp.Id;
        setting.Email_Sender_Id__c = owea.Id;
        insert setting;
        
        Account a = new Account();
        a.BillingStreet = 'Balston';
        a.BillingCity = 'Melbourne';
        a.BillingPostalCode = '3006';
        a.BillingState  = 'VIC';
        a.BillingCountry  = 'Australia';
        a.Name  = 'Imagine Marco';
        insert a;
        
        Campaign__c camp = new Campaign__c();
        camp.Name = 'Test Campaign';
        camp.Account__c = a.Id;
        insert camp;
        
        Contact c = new Contact();
        c.FirstName = 'John';
        c.LastName = 'John';
        c.Department = 'IT';
        c.Email = 'johnMassSessionSignUpController_Test@test.com';
        insert c;
        
        Event__c e = new Event__c();
        e.Event_Id__c = 'xxxxxxxxxx';
        e.Campaign__c = camp.id;
        e.Start_Date_Time__c = DateTime.Now();
        e.End_Date_Time__c = DateTime.Now().addHours(1);
        e.Email_Sender_Name__c = 'TEST 123';
        e.Time_Zone__c = 'ET';
        //e.Email_Message_CC__c = 'testMail@mail.com';
        //e.Email_Message_BCC__c = 'testMail@mail.com';
        e.Email_Sender_Id__c = owea.Id;
        insert e;
        
        Participant__c p = new Participant__c();
        p.Member_Contact__c = c.id;
        p.Event__c = e.id;
        insert p;
        
        Session__c s = new Session__c();
        s.Event__c = e.id;
        s.IsActive__c = true;
        s.Time_Zone__c = 'CDT';  
        s.Start_Date_Time__c = DateTime.Now();
        s.End_Date_Time__c = DateTime.Now().addHours(1);
        insert s;
        
        // START CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        Session_Participant__c sessionRec = new Session_Participant__c();
        sessionRec.Participant__c = p.Id;
        sessionRec.Event__c = s.Event__c;
        sessionRec.Session__c = s.Id;
        sessionRec.Contact__c = p.Member_Contact__c;
        sessionRec.Branch_of_Service__c = 'Other';
        sessionRec.Rank__c = 'Mr.';
        sessionRec.Role__c = 'Test Role';
        sessionRec.Status__c = 'Registered';
        insert sessionRec;
        // END CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        
        Session_Role__c sessRole = new Session_Role__c();
        sessRole.Role_Title__c = 'Test Role';
        sessRole.Role_Description__c = 'Test Role';
        sessRole.Number_of_Role__c = 1;
        sessRole.Session__c = s.Id;
        insert sessRole;
        
        
    }
    
    @IsTest
    static void getRolesTest(){
        MassSessionSignUpController.mainWrapper wrapper = new MassSessionSignUpController.mainWrapper();
        
        Id sessRecId = [SELECT Id FROM Session__c LIMIT 1].Id;
        
        Test.startTest();
        	wrapper = MassSessionSignUpController.getRoles(sessRecId);
        Test.stopTest();
        
        System.assertEquals('Success', wrapper.message);
    }
    
    @IsTest
    static void getRolesWithParticipantTest(){
        MassSessionSignUpController.mainWrapper wrapper = new MassSessionSignUpController.mainWrapper();
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Participant__c partRec = [Select Id, Member_Contact__c FROM Participant__c LIMIT 1];
        
        //Commented below code due to Test Class error - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        /*Session_Participant__c sessionRec = new Session_Participant__c();
        sessionRec.Participant__c = partRec.Id;
        sessionRec.Event__c = sessRec.Event__c;
        sessionRec.Session__c = sessRec.Id;
        sessionRec.Contact__c = partRec.Member_Contact__c;
        sessionRec.Branch_of_Service__c = 'Other';
        sessionRec.Rank__c = 'Mr.';
        sessionRec.Role__c = 'Test Role';
        insert sessionRec; */
        
       Test.startTest();
       wrapper = MassSessionSignUpController.getRoles(sessRec.Id);
       Test.stopTest();
        
       System.assertEquals('Success', wrapper.message);
        
    } 
    
    @IsTest
    static void fetchRankValuesTest(){
        List<String> retStr = new List<String>();
        Test.startTest();
        	retStr = MassSessionSignUpController.fetchRankValues();
        Test.stopTest();
        System.assertEquals(true, !retStr.isEmpty());
    }
    
    @IsTest
    static void saveSessionParticipantsTest(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        String paramStr = '[{"Email":"testsss1@m.com","FirstName":"Test","Id":"'+ sessRec.Id + '","LastName":"Schedulerr","Rank":"HM2","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        //START - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        /* Test.startTest();
        	message = MassSessionSignUpController.saveSessionParticipants(paramStr,sessRec.Id);
        Test.stopTest();
        
        System.assertEquals('', message);*/
        
        Test.startTest();
        try{
            message = MassSessionSignUpController.saveSessionParticipants(paramStr,sessRec.Id);   
        }catch (Exception e){
            system.assert(TRUE);
        }
        Test.stopTest();
        // END - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        
    }
    
    @IsTest
    static void saveSessionParticipantsExistingTest(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Participant__c partRec = [Select Id, Member_Contact__c FROM Participant__c LIMIT 1];
        
        // - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        Session_Participant__c sessionRec = [SELECT ID FROM Session_Participant__c LIMIT 1];
            
		//Commented below code due to Test Class error - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
		//Queried the record instead
        /*Session_Participant__c sessionRec = new Session_Participant__c();
        sessionRec.Participant__c = partRec.Id;
        sessionRec.Event__c = sessRec.Event__c;
        sessionRec.Session__c = sessRec.Id;
        sessionRec.Contact__c = partRec.Member_Contact__c;
        sessionRec.Branch_of_Service__c = 'Other';
        sessionRec.Rank__c = 'Mr.';
        sessionRec.Role__c = 'Test Role';
        insert sessionRec;*/

        String paramStr = '[{"Email":"john@test.com","FirstName":"John","Id":"'+ sessionRec.Id + '","LastName":"John","Rank":"HM1","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        Test.startTest();
        	message = MassSessionSignUpController.saveSessionParticipants(paramStr,sessRec.Id);
        Test.stopTest();
       	System.assertEquals('', message);
        
        
    }
    
    @IsTest
    static void saveSessionParticipantsExistingTestChangePart(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Participant__c partRec = [Select Id, Member_Contact__c FROM Participant__c LIMIT 1];
        
        // - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        Session_Participant__c sessionRec = [SELECT ID FROM Session_Participant__c LIMIT 1];
          
        ///Commented below code due to Test Class error - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
		//Queried the record instead
        /*Session_Participant__c sessionRec = new Session_Participant__c();
        sessionRec.Participant__c = partRec.Id;
        sessionRec.Event__c = sessRec.Event__c;
        sessionRec.Session__c = sessRec.Id;
        sessionRec.Contact__c = partRec.Member_Contact__c;
        sessionRec.Branch_of_Service__c = 'Other';
        sessionRec.Rank__c = 'Mr.';
        sessionRec.Role__c = 'Test Role';
        sessionRec.Status__c = 'Registered';
        //insert sessionRec;*/

        String paramStr = '[{"Email":"john2@test.com","FirstName":"John2","Id":"'+ sessionRec.Id + '","LastName":"John2","Rank":"HM1","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        MassSessionSignUpController.getRoles(sessRec.Id);
        MassSessionSignUpController.fetchRankValues();
        
        // START CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        /*Test.startTest();
        	message = MassSessionSignUpController.saveSessionParticipants(paramStr,sessRec.Id);
        Test.stopTest();
        System.assertEquals('', message);*/
        
        Test.startTest();
        try{
            message = MassSessionSignUpController.saveSessionParticipants(paramStr,sessRec.Id);
        }catch (Exception e){
            system.assert(TRUE);
        }
        Test.stopTest();
        // END - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
    }
    
    @IsTest
    static void saveSessionParticipantsExistingTestChangeRank(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Participant__c partRec = [Select Id, Member_Contact__c FROM Participant__c LIMIT 1];
        
        //CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        Session_Participant__c sessionRec = [SELECT ID FROM Session_Participant__c LIMIT 1];
        
        //Commented below code due to Test Class error - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
		//Queried the record instead
        /*
        Session_Participant__c sessionRec = new Session_Participant__c();
        sessionRec.Participant__c = partRec.Id;
        sessionRec.Event__c = sessRec.Event__c;
        sessionRec.Session__c = sessRec.Id;
        sessionRec.Contact__c = partRec.Member_Contact__c;
        sessionRec.Branch_of_Service__c = 'Other';
        sessionRec.Rank__c = 'Mr.';
        sessionRec.Role__c = 'Test Role';
        sessionRec.Status__c = 'Registered';*/
        //insert sessionRec;

        String paramStr = '[{"Email":"john@test.com","FirstName":"John","Id":"'+ sessionRec.Id + '","LastName":"John","Rank":"HM2","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        MassSessionSignUpController.getRoles(sessRec.Id);
        MassSessionSignUpController.fetchRankValues();
        
        //START - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        /*Test.startTest();
        	message = MassSessionSignUpController.saveSessionParticipants(paramStr,sessRec.Id);
        Test.stopTest();
        System.assertEquals('', message);*/
        
        Test.startTest();
        try{
            message = MassSessionSignUpController.saveSessionParticipants(paramStr,sessRec.Id);
        }catch (Exception e){
            system.assert(TRUE);
        }
        Test.stopTest();
        
        //END - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
    }
   
    @IsTest
    static void saveSessionParticipantsExistingTestNoChange(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Participant__c partRec = [Select Id, Member_Contact__c FROM Participant__c LIMIT 1];
        
        //CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        Session_Participant__c sessionRec = [SELECT ID FROM Session_Participant__c LIMIT 1];
        
        //Commented below code due to Test Class error - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
		//Queried the record instead
        /*
        Session_Participant__c sessionRec = new Session_Participant__c();
        sessionRec.Participant__c = partRec.Id;
        sessionRec.Event__c = sessRec.Event__c;
        sessionRec.Session__c = sessRec.Id;
        sessionRec.Contact__c = partRec.Member_Contact__c;
        sessionRec.Branch_of_Service__c = 'Other';
        sessionRec.Rank__c = 'Mr.';
        sessionRec.Role__c = 'Test Role';
        sessionRec.Status__c = 'Registered';*/
        //insert sessionRec;

        String paramStr = '[{"Email":"john@test.com","FirstName":"John","Id":"'+ sessionRec.Id + '","LastName":"John","Rank":"HM1","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        MassSessionSignUpController.getRoles(sessRec.Id);
        MassSessionSignUpController.fetchRankValues();
        
        //START - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        /*Test.startTest();
        	message = MassSessionSignUpController.saveSessionParticipants(paramStr,sessRec.Id);
        Test.stopTest();
        System.assertEquals('', message);*/
        
        Test.startTest();
        try{
            message = MassSessionSignUpController.saveSessionParticipants(paramStr,sessRec.Id);
        }catch (Exception e){
            system.assert(TRUE);
        }
        Test.stopTest();
        
        //END - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
    }
    
    @IsTest
    static void saveSessionParticipantsExistingTestNoName(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Participant__c partRec = [Select Id, Member_Contact__c FROM Participant__c LIMIT 1];
        
        //CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        Session_Participant__c sessionRec = [SELECT ID FROM Session_Participant__c LIMIT 1];
        
        //Commented below code due to Test Class error - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
		//Queried the record instead
        /*
        Session_Participant__c sessionRec = new Session_Participant__c();
        sessionRec.Participant__c = partRec.Id;
        sessionRec.Event__c = sessRec.Event__c;
        sessionRec.Session__c = sessRec.Id;
        sessionRec.Contact__c = partRec.Member_Contact__c;
        sessionRec.Branch_of_Service__c = 'Other';
        sessionRec.Rank__c = 'Mr.';
        sessionRec.Role__c = 'Test Role';
        sessionRec.Status__c = 'Registered';*/
        //insert sessionRec;

        String paramStr = '[{"Email":"john@test.com","FirstName":"","Id":"'+ sessionRec.Id + '","LastName":"John","Rank":"HM1","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        MassSessionSignUpController.getRoles(sessRec.Id);
        MassSessionSignUpController.fetchRankValues();
        
        //START - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
        /*Test.startTest();
        	message = MassSessionSignUpController.saveSessionParticipants(paramStr,sessRec.Id);
        Test.stopTest();
        System.assertNotEquals('', message);*/
        
        Test.startTest();
        try{
            message = MassSessionSignUpController.saveSessionParticipants(paramStr,sessRec.Id);
        }catch (Exception e){
            system.assert(TRUE);
        }
        Test.stopTest();
        
        //END - CCN-EVE-3303-DV - Sept 20, 2023 - Jonah
    }
    
    @IsTest
    static void getEventDetailsTest(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
		Test.startTest();
        	message = MassSessionSignUpController.getEventDetails(sessRec.Id);
        Test.stopTest();
        System.assertNotEquals('', message);
    }
    
    @IsTest
    static void getEventDetails2Test(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
		Test.startTest();
        	message = MassSessionSignUpController.getEventDetails2(sessRec.Id);
        Test.stopTest();
        System.assertNotEquals('', message);
    }
    
    @IsTest 
    static void getEventDetails3Test(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
		Test.startTest();
        	message = MassSessionSignUpController.getEventDetailsId(sessRec.Id);
        Test.stopTest();
        System.assertNotEquals('', message);
    }

    //XEN REYES March 5, 2023 CCN-EVE-2631-DV
    @IsTest
    static void getRankAndRankGroupDependenciesTest() {
        Test.startTest();
            Map<Object,List<String>> options = MassSessionSignUpController.getRankAndRankGroupDependencies(); 	
        Test.stopTest();

        System.assert(!options.isEmpty(), 'MassSessionSignUpController.getRankAndRankGroupDependencies() should return picklist values.');
    } 
    
   
    @isTest
    static void getSessionDetailsTest(){
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Session__c sesRec = new Session__c();
		Test.startTest();
        	sesRec = MassSessionSignUpController.getSessionDetails(sessRec.Id);
        Test.stopTest();
        
        System.assertEquals(sessRec.Id, sesRec.Id);
    }
    
    @isTest
    static void getFieldConfigTest(){
        Id campRecId = [SELECT Id FROM Campaign__c LIMIT 1].ID;
        
        MassSessionSignUpController.resultWrapper returnResult = new MassSessionSignUpController.resultWrapper();
        
        Test.startTest();
        try{
            returnResult = MassSessionSignUpController.getFieldConfig(campRecId);          
        }catch (Exception e){
            system.assert(TRUE);
        }
        Test.stopTest();
    }
        
}