main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/CampaignHierarchyPageTest.cls
@isTest
private class CampaignHierarchyPageTest {
    
    @testSetup
    static void testSetup() {
        //Campaign 
        Campaign__c camp1 = new Campaign__c();
        camp1.Name = 'Test Campaign 001';
        
        insert camp1;
        
        Compass_Setting__c comp = TestDataFactory.createCSData(1);
        insert comp;
        //Event
        List<Event__c> eventList = new List<Event__c>();
        Event__c event1 = new Event__c();
        event1.Name = 'Test Event 001';
        event1.Campaign__c = camp1.Id;
        eventList.add(event1);
        
        Event__c event2 = new Event__c();
        event2.Name = 'Test Event 002';
        event2.Campaign__c = camp1.Id;
        eventList.add(event2);

        insert eventList;
        
        //Session
        List<Session__c> sessionList = new List<Session__c>();
        Session__c session1 = new Session__c();
        session1.Name = 'Test Session 001';
        session1.Event__c = event1.Id;
        sessionList.add(session1);
        
        Session__c session2 = new Session__c();
        session2.Name = 'Test Session 002';
        session2.Event__c = event2.Id;
        sessionList.add(session2);
        
        insert sessionList;
    }
    
    @isTest
    static void checkObjectTypeTest(){
        Campaign__c camp = [SELECT Id FROM Campaign__c LIMIT 1];
        String objectType;

        Test.startTest();
        objectType = CampaignHierarchyPage.objectType(camp.Id);
        Test.stopTest();

        System.assertNotEquals(null, objectType, 'objectType not found');
    }
    
    @isTest
    static void searchForCampaignTest(){
        Campaign__c camp = [SELECT Id FROM Campaign__c LIMIT 1];
        List<Campaign__c> campList = new List<Campaign__c>();

        Test.startTest();
        
            campList = CampaignHierarchyPage.searchForCampaign(camp.Id);
        
        Test.stopTest();
        System.assert(!campList.isEmpty(), 'No campList');
    }
    
    @isTest
    static void searchForEventTest(){
        Event__c event = [SELECT Id FROM Event__c LIMIT 1];
        List<Event__c> eventList = new List<Event__c>();

        Test.startTest();
        eventList = CampaignHierarchyPage.searchForEvent(event.Id);
        Test.stopTest();

        System.assert(!eventList.isEmpty(), 'no eventList');
    }
    
    @isTest
    static void searchForEventTest2(){
        Campaign__c campaign = [SELECT Id FROM Campaign__c LIMIT 1];
        List<Event__c> eventList = new List<Event__c>();

        Test.startTest();
        eventList = CampaignHierarchyPage.searchForEvent(campaign.Id);
        Test.stopTest();

        System.assert(!eventList.isEmpty(), 'no campaignList');
    }
    
    @isTest
    static void searchForSessionTest(){
        Event__c event = [SELECT Id FROM Event__c LIMIT 1];
        List<Session__c> sessionList;

        Test.startTest();
        sessionList = CampaignHierarchyPage.searchForSession(new List<Id>{event.Id}, null);
        Test.stopTest();

        System.assert(!sessionList.isEmpty(), 'no eventsessionList');
    }
    
    @isTest
    static void searchForSessionTest2(){
        Session__c session = [SELECT Id FROM Session__c LIMIT 1];
        List<Session__c> sessionList;

        Test.startTest();
        sessionList = CampaignHierarchyPage.searchForSession(new List<Id>(), session.Id);
        Test.stopTest();

        System.assert(!sessionList.isEmpty(), 'no sessionList');
    }
}