main/default/objects/Campaign/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <description>Contains meeting URL</description>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Location_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/fields/Subtitle__c.field-meta.xml
<CustomField>
    <fullName>Subtitle__c</fullName>
    <label>Subtitle</label>
    <length>600</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Org_timezone_difference__mdt/Org_timezone_difference__mdt.object-meta.xml
<CustomObject>
    <label>Org timezone difference</label>
    <pluralLabel>Org timezones difference</pluralLabel>
</CustomObject>

main/default/objects/Org_timezone_difference__mdt/fields/Hour_Difference__c.field-meta.xml
<CustomField>
    <fullName>Hour_Difference__c</fullName>
    <label>Hour Difference</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Do_Not_Send_Calendar_Invite__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Send_Calendar_Invite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Send Calendar Invite</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Session__c/fields/End_Date_Time2__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time2__c</fullName>
    <label>End Date Time2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Meeting_Info__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Info__c</fullName>
    <label>Meeting Info</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Send_Updated_Calendar_Invite__c.field-meta.xml
<CustomField>
    <fullName>Send_Updated_Calendar_Invite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Updated Calendar Invite</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Catchup_Message__c.field-meta.xml
<CustomField>
    <fullName>Session_Catchup_Message__c</fullName>
    <label>Session Catch-Up Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Catchup_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Session_Catchup_Reminder_Message__c</fullName>
    <label>Session Catch-Up Reminder Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Catchup_Thank_You_Message__c.field-meta.xml
<CustomField>
    <fullName>Session_Catchup_Thank_You_Message__c</fullName>
    <label>Session Catch-Up Thank You Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Details__c.field-meta.xml
<CustomField>
    <fullName>Session_Details__c</fullName>
    <label>Session Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Details_Full__c.field-meta.xml
<CustomField>
    <fullName>Session_Details_Full__c</fullName>
    <description>For email template to show full month for session dates</description>
    <label>Session Details Full</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Details_Start_Full__c.field-meta.xml
<CustomField>
    <fullName>Session_Details_Start_Full__c</fullName>
    <label>Session Details Start Full</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Start_Date_Time2__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time2__c</fullName>
    <label>Start Date Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Start_Date_Time_on_Timezone__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time_on_Timezone__c</fullName>
    <description>CCN-EVE-1834-DV: the start datetime on the session timezone converted to org default timezone</description>
    <label>Start Date Time on Timezone</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session_Attendance_Thank_You_Message__c.field-meta.xml
<CustomField>
    <fullName>Session_Attendance_Thank_You_Message__c</fullName>
    <label>Session Attendance Thank You Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session_Catchup_Message__c.field-meta.xml
<CustomField>
    <fullName>Session_Catchup_Message__c</fullName>
    <label>Session Catchup Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session_Catchup_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Session_Catchup_Reminder_Message__c</fullName>
    <label>Session Catchup Reminder Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session_Catchup_Thank_You_Message__c.field-meta.xml
<CustomField>
    <fullName>Session_Catchup_Thank_You_Message__c</fullName>
    <label>Session Catchup Thank You Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/SessionTriggerHandler.cls
/*******************************************************************************************
  * @name: SessionTriggerHandler
  * @author: 
  * @created: XX-XX-XXXX
  * @description: Handler for all the logic of the trigger for the Session object
  *
  * Changes (version)
  * -------------------------------------------------------------------------------------------
  *       		No.   Date(dd-mm-yyy) 	Author         	   	  Description
  *       		----  ---------------   --------------------  -----------------------------
  * @version    1.0	  XX-XX-XXXX							  Initial Creation
  *             2.0   20-10-2021   		Paolo Quiambao        [CCN745] Added code to populate
  * 														  Session_Details_Start_Full__c
  *             3.0   06-12-2021   		Paolo Quiambao        [CCN981] Added syncSessionRichTextFields()
  * 														  method to sync Rich Text fields from Session
  * 														  to Session Participants
  *             4.0   24-08-2022  		Rianno Rizarri        [CCN-EVE-1834-DV] Total Participants Registered field at session start
  *                                                           Added Start_Date_Time_on_Timezone__c for getting the start datetime on
  *                                                           the session timezone converted to org default timezone.
  *             4.1   27-08-2022  		Rianno Rizarri        [CCN-EVE-1834-DV] Update to code standards
  *             4.2   27-11-2022        Xen Reyes             [CCN-LOG-2217-DV] Update Event Internal Logistics when inserting / updating Session
  *             4.3   23-05-2023        Rex David             [CCN-2534] Virtual Meeting Integration (POC: Microsoft Teams Link) 
  *********************************************************************************************/
  public with sharing class SessionTriggerHandler {

    public class MyException extends Exception {}

    //Start CCN-EVE-1834-DV: Rianno Rizarri
    public static boolean bPreventAI = false;
    public static boolean bPreventAU = false;

    public static void onBeforeInsert(List<Session__c> newSessionList, Map<Id,Session__c> newSessionMap){
        populateSessionDetails(newSessionList,null,null,null);
    }

    public static void onBeforeUpdate(List<Session__c> newSessionList, Map<Id,Session__c> newSessionMap, 
                                      List<Session__c> oldSessionList, Map<Id,Session__c> oldSessionMap){ 
        populateSessionDetails(newSessionList, newSessionMap, oldSessionList, oldSessionMap);
    }

    public static void onAfterInsert(List<Session__c> newSessionList, Map<Id,Session__c> newSessionMap, 
                                     List<Session__c> oldSessionList, Map<Id,Session__c> oldSessionMap){
        updateEventInternalLogistics(newSessionList, newSessionMap, null, null);
        processMeetingUrl(newSessionList,null);//CCN-EVE-3056-DV adavid@ulapp.co Virtual Meeting Integration 
                                         
    }
    public static void onAfterUpdate(List<Session__c> newSessionList, Map<Id,Session__c> newSessionMap, 
                                    List<Session__c> oldSessionList, Map<Id,Session__c> oldSessionMap){
        syncSessionRichTextFields(newSessionList, newSessionMap, oldSessionList, oldSessionMap);
        updateEventInternalLogistics(newSessionList, newSessionMap, oldSessionList, oldSessionMap);
        processMeetingUrl(newSessionList,oldSessionMap);//CCN-EVE-3056-DV adavid@ulapp.co Virtual Meeting Integration 
    }

    //End CCN-EVE-1834-DV: Rianno Rizarri
    public static void populateSessionDetails(List<Session__c> newList, Map<Id,Session__c > newMap,List<Session__c > oldList, Map<Id,Session__c > oldMap){
        String strTZone = String.ValueOf(userinfo.getTimeZone());
        //Start CCN-EVE-1834-DV: Rianno Rizarri
        Map<String, Org_timezone_difference__mdt> TZDiffMeta = new Map<String, Org_timezone_difference__mdt>();
        TZDiffMeta = Org_timezone_difference__mdt.getAll();
        //End CCN-EVE-1834-DV: Rianno Rizarri

        Boolean isUpdate = (oldMap != null);
        
        for(Session__c session : newList){

            //CCN-2871 Xen Reyes Apr242023
            Session__c oldSession = new Session__c();
            if(isUpdate) oldSession = oldMap.get(session.Id);
            
            String sessionName = '';
            String sessionDetailsFull = '';
            // Updated by Paolo Quiambao [CCN-745] Oct082021
            String sessionDetailsStartFull = '';
            
            //CCN-2871 Xen Reyes Apr242023 - Additional checks in filling in session details
            //CCN-3002 Xen Reyes May122023 - Include Time zone change in the checks to re-evaluate session details
            if( (!isUpdate && session.Start_Date_Time__c != null && session.End_Date_Time__c != null) || 
                (isUpdate && session.Start_Date_Time__c != null && session.End_Date_Time__c != null && session.Time_Zone__c != null &&
                (oldSession.Start_Date_Time__c != session.Start_Date_Time__c || oldSession.End_Date_Time__c != session.End_Date_Time__c || oldSession.Time_Zone__c != session.Time_Zone__c))){
                
                DateTime startDT = session.Start_Date_Time__c;
                DateTime endDT = session.End_Date_Time__c;
                sessionName = startDT.format('MMM dd, yyyy', strTZone)+ ', '
                    +startDT.format('hh:mm aaa', strTZone) + ' ' 
                    +' to '+endDT.format('MMM dd, yyyy', strTZone)+', '+endDT.format('hh:mm aaa', strTZone) + ' ' + session.Time_Zone__c;
                
                //00707 1/21/2020 - Parking Lot Email notification - JC
                sessionDetailsFull = startDT.format('MMMMM dd, yyyy', strTZone)+ ', '
                    +startDT.format('hh:mm aaa', strTZone) + ' ' 
                    +' to '+endDT.format('MMMMM dd, yyyy', strTZone)+', '+endDT.format('hh:mm aaa', strTZone) + ' ' + session.Time_Zone__c;
                session.Start_Date_Time2__c = startDT.format('MM/dd/yyyy', strTZone)+ ', ' +startDT.format('hh:mm aaa', strTZone);
                session.End_Date_Time2__c = endDT.format('MM/dd/yyyy', strTZone)+ ', ' +endDT.format('hh:mm aaa', strTZone);
                // Updated by Paolo Quiambao [CCN-745] Oct082021
                sessionDetailsStartFull = startDT.format('MMMM dd, yyyy', strTZone) + ', ' + startDT.format('hh:mm aaa', strTZone) +
                    ' to ' + endDT.format('hh:mm aaa', strTZone) + ' ' + session.Time_Zone__c;
                //Start CCN-EVE-1834-DV: Rianno Rizarri
                if(String.isNotBlank(session.Time_Zone__c) && TZDiffMeta.containsKey(session.Time_Zone__c)){
                    Decimal difference = TZDiffMeta.get(session.Time_Zone__c).Hour_Difference__c*-60;
                    session.Start_Date_Time_on_Timezone__c = startDT.addMinutes(Integer.valueOf(difference));
                }
                //End CCN-EVE-1834-DV: Rianno Rizarri

                session.Session_Details__c = sessionName;
                //00707 1/21/2020 - Parking Lot Email notification - JC
                session.Session_Details_Full__c = sessionDetailsFull;
                // Updated by Paolo Quiambao [CCN-745] Oct082021
                session.Session_Details_Start_Full__c = sessionDetailsStartFull;
            }

            // UPDATED BY JC ESPINO CCN-EVE-1191-DV MAR172022
            // Resets Send_Updated_Calendar_Invite__c when session date/time/tz details are updated
            if(isUpdate) {
                if((oldSession.Time_Zone__c != session.Time_Zone__c || 
                    // UPDATED by JC ESPINO [CCN-EVE-1360-DV] - Changed the referenced field from Meeting_URL__c to Location__c
                    oldSession.Location__c != session.Location__c || 
                    oldSession.Start_Date_Time__c != session.Start_Date_Time__c || 
                    oldSession.End_Date_Time__c != session.End_Date_Time__c) && 
                    session.Send_Updated_Calendar_Invite__c
                ){
                    session.Send_Updated_Calendar_Invite__c = false;
                }
            }
        }
    }
    
    // Updated by Paolo Quiambao [CCN-981] Dec062021
    public static void syncSessionRichTextFields(List<Session__c> newList, Map<Id,Session__c > newMap, List<Session__c > oldList, Map<Id,Session__c > oldMap) {
        Session_Participant__c participant = new Session_Participant__c();
        Set<Id> sessionsToSendCalendarUpdate = new Set<Id>();
        Set<Id> sessionsWithUpdatedMessages = new Set<Id>();

        // UPDATED BY JC ESPINO CCN-EVE-1191-DV MAR172022
        // Send updated Calendar Invites to Confirmed Participants
        for(Session__c session : newList) {
            Session__c oldSession = oldMap.get(session.Id);

            System.debug('### oldSession.Send_Updated_Calendar_Invite__c: ' + oldSession.Send_Updated_Calendar_Invite__c);
            System.debug('### session.Send_Updated_Calendar_Invite__c: ' + session.Send_Updated_Calendar_Invite__c);
            System.debug('### session.Do_Not_Send_Calendar_Invite__c: ' + session.Do_Not_Send_Calendar_Invite__c);
            if(!oldSession.Send_Updated_Calendar_Invite__c && 
                session.Send_Updated_Calendar_Invite__c && 
                !session.Do_Not_Send_Calendar_Invite__c
            ){
                sessionsToSendCalendarUpdate.add(session.Id);
            }

            if(session.Session_Attendance_Thank_You_Message__c != oldSession.Session_Attendance_Thank_You_Message__c || 
               session.Session_Catchup_Message__c != oldSession.Session_Catchup_Message__c || 
               session.Session_Catchup_Reminder_Message__c != oldSession.Session_Catchup_Reminder_Message__c || 
               session.Session_Catchup_Thank_You_Message__c != oldSession.Session_Catchup_Thank_You_Message__c 
            ) {
                sessionsWithUpdatedMessages.add(session.Id);
            }
        }

        if(!sessionsToSendCalendarUpdate.isEmpty()) {
            // List<Session_Participant__c> confirmedSessionParticpants = [SELECT Id, Name, Contact__c, Contact__r.Email, Status__c, Session__c, 
            //                                                             Event__r.Location__r.Name, Event__r.Email_Sender_Id__c, Event__r.Email_Sender_Name__c,
            //                                                             Session__r.Name, Session__r.Subtitle__c,
            //                                                             Session__r.Time_Zone__c, Session__r.Description__c, Session__r.Meeting_Info__c, Session__r.Meeting_URL__c, 
            //                                                             Session__r.Start_Date_Time__c, Session__r.End_Date_Time__c, Session__r.Do_Not_Send_Calendar_Invite__c
            //                                                             FROM Session_Participant__c WHERE Status__c = 'Confirmed' AND Session__c IN :sessionsToSendCalendarUpdate];
            // SessionParticipantTriggerUtility.sendUpdatedCalendarInvite(confirmedSessionParticpants);
            SessionParticipantTriggerUtility.sendUpdatedCalendarInvite(sessionsToSendCalendarUpdate);
        }

        List<Session_Participant__c> spToUpdate = new List<Session_Participant__c>();
        //Added checker if isUpdateable for [CCN-1148] Feb112022
        if(FlsUtils.isUpdateable(participant, new List<String>{'Session_Attendance_Thank_You_Message__c','Session_Catchup_Message__c','Session_Catchup_Reminder_Message__c','Session_Catchup_Thank_You_Message__c'})){
            system.debug('isUpdateable');
            for(Session_Participant__c sp : [SELECT Id, Session_Attendance_Thank_You_Message__c, Session_Catchup_Message__c, Session_Catchup_Reminder_Message__c, 
                                             Session_Catchup_Thank_You_Message__c, Session__r.Session_Attendance_Thank_You_Message__c, Session__r.Session_Catchup_Message__c, 
                                             Session__r.Session_Catchup_Reminder_Message__c, Session__r.Session_Catchup_Thank_You_Message__c, Session__r.Send_Updated_Calendar_Invite__c 
                                             FROM Session_Participant__c WHERE Session__c IN :sessionsWithUpdatedMessages]) {
                                                 
                                                 sp.Session_Attendance_Thank_You_Message__c = sp.Session__r.Session_Attendance_Thank_You_Message__c;
                                                 sp.Session_Catchup_Message__c = sp.Session__r.Session_Catchup_Message__c;
                                                 sp.Session_Catchup_Reminder_Message__c = sp.Session__r.Session_Catchup_Reminder_Message__c;
                                                 sp.Session_Catchup_Thank_You_Message__c = sp.Session__r.Session_Catchup_Thank_You_Message__c;
                                                 spToUpdate.add(sp);
                                             }
            update spToUpdate;
        }
    }

    /******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyy) Author            Description
    *           ----  ---------   --------------------  -----------------------------
    * @version   1.0  25-11-2022   Xen Reyes            [CCN-LOG-2217-DV] Initial version.
    ******************************************************************************/
    public static void updateEventInternalLogistics(List<Session__c> newList, Map<Id,Session__c > newMap, List<Session__c > oldList, Map<Id,Session__c > oldMap) {
        
        try{
            Set<Id> eventIdToUpdate = new Set<Id>();
            for(Session__c session : newList) {
                if(session.IsActive__c && session.Event__c != null){
                    if(oldList != null) {
                        if(oldMap.get(session.Id).Meeting_URL__c != session.Meeting_URL__c) eventIdToUpdate.add(session.Event__c);
                    } else {
                        eventIdToUpdate.add(session.Event__c);
                    }
                }
            }

            Map<Id, Set<String>> eventIdSessionMeetingLocationsMap = new Map<Id, Set<String>>();
            List<Internal_Logistics__c> logisticListToUpdate = new List<Internal_Logistics__c>();
            List<Event__c> eventList = [SELECT Id, (SELECT Id, Event_Name__c FROM Internal_Logistics__r), (SELECT Id, Meeting_URL__c FROM CC_Sessions__r WHERE IsActive__c = true) FROM Event__c WHERE Id IN: eventIdToUpdate];
            
            for(Event__c e : eventList){
                Set<String> sessionMeetingLocations = new Set<String> ();
                for(Session__c s : e.CC_Sessions__r){
                    if(s.Meeting_URL__c != null) sessionMeetingLocations.add(s.Meeting_URL__c);
                }
                eventIdSessionMeetingLocationsMap.put(e.Id, sessionMeetingLocations);
            }

            for(Event__c e : eventList){
                for(Internal_Logistics__c ie : e.Internal_Logistics__r){

                    String sessionMeetingLocationsCon = '';
                    Integer numberOfSessionMeetingLocations = 0;
                    if(eventIdSessionMeetingLocationsMap.containsKey(ie.Event_Name__c)){

                        List<String> locationList = new List<String>(eventIdSessionMeetingLocationsMap.get(ie.Event_Name__c));
                        locationList.sort();
                        sessionMeetingLocationsCon = String.join(locationList, ', ');
                        numberOfSessionMeetingLocations = eventIdSessionMeetingLocationsMap.get(ie.Event_Name__c).size();

                        logisticListToUpdate.add(new Internal_Logistics__c( Id = ie.Id, 
                                                                            Session_Locations__c = sessionMeetingLocationsCon,
                                                                            Number_of_Locations__c = numberOfSessionMeetingLocations));
                    }
                }
            }
            update logisticListToUpdate;
        } catch (exception e) {
            throw new MyException(e);
        }
    }

    /******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyy) Author            Description
    *           ----  ---------   --------------------  -----------------------------
    * @version   1.0  14-06-2023   Rex David            [CCN-2534] [CCN-EVE-3056-DV] Virtual Meeting Integration (Microsoft Teams Link)
    ******************************************************************************/
    public static void processMeetingUrl(List<Session__c> newList, Map<Id,Session__c> oldMap){
        
        String action = oldMap == NULL ? 'POST' : 'PATCH';
        
        Set<Id> sessionEventIds = new Set<Id>();
        List<Session__c> sessionListToProcess = new List<Session__c>();

        for(Session__c session : newList){
            if(action == 'POST'){
                if(session.Event__c != NULL) sessionEventIds.add(session.Event__c);
            }
            else if(action == 'PATCH'){
                if(session.Name != oldMap.get(session.Id).Name 
                || session.Start_Date_Time__c != oldMap.get(session.Id).Start_Date_Time__c 
                || session.End_Date_Time__c != oldMap.get(session.Id).End_Date_Time__c){
                    if(session.Event__c != NULL) sessionEventIds.add(session.Event__c);
                }
            }   
        }

        if(!sessionEventIds.isEmpty()){
            Map<Id,Event__c> eventMap = new Map<Id,Event__c> ([SELECT Id, (SELECT Id, Name, Event__c FROM CC_Sessions__r WHERE ID IN: newList) FROM Event__c WHERE Id IN: sessionEventIds AND Event_Type__c = 'Virtual' AND Virtual_Meeting_Platform__c = 'MS Teams']);
            if(!eventMap.isEmpty()){
                for(Id eventId : eventMap.keySet()){
                    for(Session__c session : eventMap.get(eventId).CC_Sessions__r){
                        sessionListToProcess.add(session);
                    }
                }
                if(!sessionListToProcess.isEmpty()) Database.executeBatch(new AzureAPIBatch(action,sessionListToProcess),10); 
            }
            System.debug(eventMap.isEmpty() ? 'Current Event Type and Virtual_Meeting_Platform__c are not supported in MS Teams integration.' : '');
        }
    }
}