main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scrum Master</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Location_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Event_Role__c/Event_Role__c.object-meta.xml
<CustomObject>
    <label>Event Role</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>Event Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event_Role__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Event Roles</relationshipLabel>
    <relationshipName>Event_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Event Roles</relationshipLabel>
    <relationshipName>Event_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Role__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Roles</relationshipLabel>
    <relationshipName>Event_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Event Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Speaker</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event_Role__c/fields/Show_in_Event_Site__c.field-meta.xml
<CustomField>
    <fullName>Show_in_Event_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show in Event Site</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Internal_Resource_Role__c/Internal_Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Internal Resource Role</label>
    <nameField>
        <displayFormat>IRN-{0000}</displayFormat>
        <label>Internal Resource Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Resource_Role__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Internal Resource Roles</relationshipLabel>
    <relationshipName>Internal_Resource_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Role__c/Session_Role__c.object-meta.xml
<CustomObject>
    <description>01080 - Custom object for Session Role</description>
    <label>Session Role</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Session Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Session_Role__c/fields/Number_of_Role__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Role__c</fullName>
    <description>Number of Roles in a Session</description>
    <label>Number of Role</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Session_Role__c/fields/Role_Description__c.field-meta.xml
<CustomField>
    <fullName>Role_Description__c</fullName>
    <description>Description of Role</description>
    <label>Role Description</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Session_Role__c/fields/Role_Title__c.field-meta.xml
<CustomField>
    <fullName>Role_Title__c</fullName>
    <description>Title of the Role</description>
    <label>Role Title</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Role__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Session</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Roles</relationshipLabel>
    <relationshipName>Session_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is to be deleted</description>
    <label>Campaign(old)</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/CloneEventControllerTest.cls
/*
* @filename        : CloneEventController
* @created         : 09.25.2021
* @author          : Mel
* @description     : CloneEventController Test Class
*/ 

@isTest
public with sharing class CloneEventControllerTest {
    
 @isTest
    public static void testcloneEventRecord(){
        //Account
        Account testAccount2 = new Account();
        testAccount2.Name = 'Test Account 09252021';
        testAccount2.BillingStreet = '12345 Gold Street';
        testAccount2.BillingCity = 'Melbourne';
        testAccount2.BillingPostalCode = '3055';
        testAccount2.BillingState = 'VIC';
        testAccount2.BillingCountry = 'Australia';
        insert testAccount2;
        
        
        Campaign parentEvent = TestFactory.createCampaign('Parent Event 2', 'Event');
        parentEvent.Location__c = testAccount2.Id;
        parentEvent.Start_Date_Time__c = DateTime.newInstance(2020, 8, 29, 8, 30, 0);
        parentEvent.End_Date_Time__c = DateTime.newInstance(2020, 8, 31, 12, 30, 0);
        update parentEvent;
        
        Campaign childSession = TestFactory.createCampaign('Child Session 2', 'Session');
        childSession.ParentId = parentEvent.Id;
        childSession.Start_Date_Time__c = DateTime.newInstance(2020, 8, 29, 8, 30, 0);
        childSession.End_Date_Time__c = DateTime.newInstance(2020, 8, 29, 12, 30, 0);
        update childSession;
        
        Contact attendee = TestFactory.createContact('Test', 'Attendee2', 'test.attendee2@gmail.com');
        CampaignMember cm = TestFactory.createCampaignMember(parentEvent.Id, attendee);
       
        //Event
        Event__c e = TestFactory.createEvent('Test Event');
        
        //Event Role
        Event_Role__c newEventRole = new Event_Role__c();
        newEventRole.Show_in_Event_Site__c = true;
        newEventRole.Role__c = 'Speaker';
        newEventRole.Contact__c = attendee.Id;
        newEventRole.Event__c = e.Id;
        newEventRole.Campaign__c = childSession.Id;
        insert newEventRole;
        
        //Session
        Session__c testSessionRec = new Session__c();
        testSessionRec.Contact__c = attendee.Id;
        testSessionRec.Session__C = childSession.Id;
        testSessionRec.Event__c = e.Id;
        insert testSessionRec;
        
        //Session Role
        Session_Role__c sessRole = new Session_Role__c();
        sessRole.Role_Title__c = 'Test Role';
        sessRole.Role_Description__c = 'Test Role';
        sessRole.Number_of_Role__c = 1;
        sessRole.Session__c = testSessionRec.Id;
        insert sessRole;
        
        //Internal Session Role
        Internal_Resource_Role__c intRole = new Internal_Resource_Role__c();
        intRole.Session__c = testSessionRec.Id;
        insert intRole;
        
        //Survey
        Survey__c newSurvey1 = TestFactory.createSurvey(e.Id, 'Test Survey With Event With No Selected Fields');
        TestFactory.createSurveyQuestion(newSurvey1.Id, 'What is your name?', 'Text', 1);
        
        Test.startTest();
        System.assertNotEquals(CloneEventController.cloneEventRecord(e.Id), null);
        Test.stopTest();
    }
}