main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Outreach Notification. If this field is populated and related the Session does not have related Outreach Notification, this will be used as the setting for that Session.</description>
    <inlineHelpText>If the related Session does not have related Outreach Notification, this will be used as the setting for that Session.</inlineHelpText>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Outreach_Notification_History__c/Outreach_Notification_History__c.object-meta.xml
<CustomObject>
    <description>Contains historical data of notifications sent out to contacts.</description>
    <label>Outreach Notification History</label>
    <nameField>
        <displayFormat>ONH{000000}</displayFormat>
        <label>Outreach Notification History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outreach Notification Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_History__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Links to the contact (participant)</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Outreach Notification Histories</relationshipLabel>
    <relationshipName>Outreach_Notification_Histories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the Parent Outreach Notification</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Outreach Notification Histories</relationshipLabel>
    <relationshipName>Outreach_Notification_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification_History__c/fields/Outreach_Notification_Setting__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification_Setting__c</fullName>
    <description>Lookup field to the Outreach Notification Setting</description>
    <label>Outreach Notification Setting</label>
    <referenceTo>Outreach_Notification_Setting__c</referenceTo>
    <relationshipLabel>Outreach Notification Histories</relationshipLabel>
    <relationshipName>Outreach_Notification_Histories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/Outreach_Notification_Setting__c.object-meta.xml
<CustomObject>
    <description>Contains the configuration that will be used for each compass objects</description>
    <label>Outreach Notification Setting</label>
    <nameField>
        <label>Outreach Notification Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Notification Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_Setting__c/fields/L1_Days__c.field-meta.xml
<CustomField>
    <fullName>L1_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Level 1 Notification:
The number of days prior to Event/Session Start Date.</description>
    <inlineHelpText>Level 1 Notification:
A number of days prior to Event/Session Start Date or Catchup Start Date.</inlineHelpText>
    <label>L1 Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/L2_Days__c.field-meta.xml
<CustomField>
    <fullName>L2_Days__c</fullName>
    <description>Level 2 Notification:
The number of days prior to Event/Session Start Date</description>
    <inlineHelpText>Level 2 Notification:
The number of days prior to Event/Session Start Date or Catchup Start Date.</inlineHelpText>
    <label>L2 Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Outreach Notifiocation record</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Outreach Notification Settings</relationshipLabel>
    <relationshipName>Outreach_Notification_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <description>Time of the day that the notification will be sent out</description>
    <inlineHelpText>Time of the day that the notification will be sent out</inlineHelpText>
    <label>Time</label>
    <type>Time</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Notification Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Invitation Registration Reminder</fullName>
            </value>
            <value>
                <fullName>Registration Confirmation Reminder</fullName>
            </value>
            <value>
                <fullName>Session Attendance Thank you</fullName>
            </value>
            <value>
                <fullName>Session Catchup</fullName>
            </value>
            <value>
                <fullName>Session Catchup Reminder</fullName>
            </value>
            <value>
                <fullName>Session Catchup Thank you</fullName>
            </value>
            <value>
                <fullName>Survey Catchup</fullName>
            </value>
            <value>
                <fullName>Survey Catchup Reminder</fullName>
            </value>
            <value>
                <fullName>Survey Reminder</fullName>
            </value>
            <value>
                <fullName>Survey Thank You</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Attendance_Date__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Date__c</fullName>
    <description>Date of Attendance</description>
    <label>Attendance Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Member_Status</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Participant__c/recordTypes/Participant.recordType-meta.xml
<RecordType>
    <fullName>Participant</fullName>
    <active>true</active>
    <label>Participant</label>
</RecordType>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Catch_up__c.field-meta.xml
<CustomField>
    <fullName>Catch_up__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked - Indicates that session is offered with catchup session</description>
    <label>Session Catch-Up</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Session__c/fields/Catchup_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Catchup_End_Date__c</fullName>
    <description>End date of the catchup sesion</description>
    <label>Session Catch-Up End Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session__c/fields/Catchup_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Catchup_Start_Date__c</fullName>
    <description>Start date of the Catchup session</description>
    <label>Session Catch-Up Start Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Outreach Notification</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Attendance_Date__c.field-meta.xml
<CustomField>
    <fullName>Attendance_Date__c</fullName>
    <label>Attendance Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Catchup_Date__c.field-meta.xml
<CustomField>
    <fullName>Catchup_Date__c</fullName>
    <description>Participant&apos;s Session Catchup Date/Time</description>
    <label>Catch-Up Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/globalValueSets/Member_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Attended</fullName>
    </customValue>
    <customValue>
        <fullName>Catch-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Responded</fullName>
        <isActive>false</isActive>
        <label>Responded</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <isActive>false</isActive>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <masterLabel>Member Status</masterLabel>
</GlobalValueSet>

main/default/classes/OutreachNotificationSessionHelper.cls
/*******************************************************************************
 * @author       Angelo Rivera
 * @date          01.10.2021
 * @description  [CCN-842, CCN-1059, CCN-1060, CCN-1061] Helper class for BatchOutreachNotificationCC
 * @revision      10.10.2021 - APRivera - Created
 *******************************************************************************/

public without sharing class OutreachNotificationSessionHelper {

    /* ***************************************************************************** */
    public static String processSessions(){
        Map<Id, Session__c> mapSessionById = new Map<Id,Session__c>();
        mapSessionById = getSessions();
        if(!mapSessionById.isEmpty()){
            // retrieve all Outreach Notification linked to Events
            Map<Id, List<Outreach_Notification_Setting__c>> mapOutreachNotificationSettingsByOutreachNotificationIds = new Map<Id, List<Outreach_Notification_Setting__c>>();
            mapOutreachNotificationSettingsByOutreachNotificationIds = OutreachNotificationHelper.getOutreachNotificationSettings();

            // retrieve all Session Participants
            Map<Id, List<Session_Participant__c>> mapSessionParticipantsBySessionIds = new Map<Id, List<Session_Participant__c>>();
            mapSessionParticipantsBySessionIds = getSessionParticipants(mapSessionById.keySet());

            List<Outreach_Notification_History__c> lstOutreachNotificationHistories = new List<Outreach_Notification_History__c>();
            // iterate on Session records
            for(Session__c session : mapSessionById.values()){
                if(session.Outreach_Notification__c != null){
                    System.debug(LoggingLevel.DEBUG, '!@# Processing Session:' + session.Name + ' - Catchup: ' + session.Catch_up__c);
                    processSessionOutreachNotifications(session, mapSessionParticipantsBySessionIds,mapOutreachNotificationSettingsByOutreachNotificationIds,lstOutreachNotificationHistories);
                    System.debug(LoggingLevel.DEBUG, ' !@# lstOutreachNotificationHistories:' + lstOutreachNotificationHistories.size());
                }
            }

            //try{
                if(!lstOutreachNotificationHistories.isEmpty()){
                    Database.insert(lstOutreachNotificationHistories);
                }
            //}catch (Exception ex){
                //System.debug(LoggingLevel.DEBUG, ' !@# ERROR:' + ex.getTypeName() + ' - ' + ex.getMessage());
            //}
        }
        return 'Process Complete!';
    }

    /* ***************************************************************************** */
    public static void processSessionOutreachNotifications(Session__c session, Map<Id, List<Session_Participant__c>> mapSessionParticipantsBySessionIds,
            Map<Id, List<Outreach_Notification_Setting__c>> mapOutreachNotificationSettingsByOutreachNotificationIds,
            List<Outreach_Notification_History__c> lstNewOutreachNotificationHistories){

        List<Outreach_Notification_Setting__c> lstOutreachNotificationSettings = new List<Outreach_Notification_Setting__c>();
        lstOutreachNotificationSettings = mapOutreachNotificationSettingsByOutreachNotificationIds.get(session.Outreach_Notification__c);
        if(!lstOutreachNotificationSettings.isEmpty()){
            Outreach_Notification_Setting__c outreachSessionCatchupSetting = new Outreach_Notification_Setting__c();
            Outreach_Notification_Setting__c outreachSessionCatchupReminderSetting = new Outreach_Notification_Setting__c();
            Outreach_Notification_Setting__c outreachSessionAttendanceThankYouSetting = new Outreach_Notification_Setting__c();
            Outreach_Notification_Setting__c outreachSessionCatchThankYouSetting = new Outreach_Notification_Setting__c();
            Boolean bOutreachSessionCatchupSettingFound = false, bOutreachSessionCatchupReminderSettingFound = false, bOutreachAttendanceThankYouSettingFound = false,  bOutreachCatchupThankYouSettingFound = false;
            // retrieve outreach notification setting to be used
            for(Outreach_Notification_Setting__c ons : lstOutreachNotificationSettings){
                if(ons.Type__c == Label.Outreach_Notification_Session_Catchup){
                    outreachSessionCatchupSetting = ons;
                    bOutreachSessionCatchupSettingFound = true;
                }
                if(ons.Type__c == Label.Outreach_Notification_Session_Catchup_Reminder){
                    outreachSessionCatchupReminderSetting = ons;
                    bOutreachSessionCatchupReminderSettingFound = true;
                }
                if(ons.Type__c == Label.Outreach_Notification_Session_Attendance_Thank_you){
                    outreachSessionAttendanceThankYouSetting = ons;
                    bOutreachAttendanceThankYouSettingFound = true;
                }
                if(ons.Type__c == Label.Outreach_Notification_Session_Catchup_Thank_you){
                    outreachSessionCatchThankYouSetting = ons;
                    bOutreachCatchupThankYouSettingFound = true;
                }
            }

            // retrieve all session participants
            List<Session_Participant__c> lstNotAttendedSessionParticipants = new List<Session_Participant__c>();
            lstNotAttendedSessionParticipants = getSessionParticipantsPerStatus(mapSessionParticipantsBySessionIds.get(session.Id), 'Attended', false);
            List<Session_Participant__c> lstIncompleteCatchupSessionParticipants = new List<Session_Participant__c>();
            lstIncompleteCatchupSessionParticipants = getSessionParticipantsPerStatus(mapSessionParticipantsBySessionIds.get(session.Id), 'Catchup', false);
            List<Session_Participant__c> lstAttendAndCatchupSessionParticipants = new List<Session_Participant__c>();
            lstAttendAndCatchupSessionParticipants = getSessionParticipantsPerStatus(mapSessionParticipantsBySessionIds.get(session.Id), Label.Outreach_Notification_Session_Attended, true);

            // thank you notification flow
            if(System.now() > session.End_Date_Time__c || System.now() > session.Catchup_Start_Date__c){
                // Session Attendance Thank you Setting
                if(bOutreachAttendanceThankYouSettingFound || bOutreachCatchupThankYouSettingFound) {
                    System.debug(LoggingLevel.DEBUG, '!@# outreachSessionAttendanceThankYouSetting: ' + outreachSessionAttendanceThankYouSetting);
                    System.debug(LoggingLevel.DEBUG, '!@# outreachSessionCatchThankYouSetting: ' + outreachSessionCatchThankYouSetting);

                    if (!lstAttendAndCatchupSessionParticipants.isEmpty()) {
                        System.debug(LoggingLevel.DEBUG, '!@# lstAttendAndCatchupSessionParticipants:' + lstAttendAndCatchupSessionParticipants.size());
                        List<Session_Participant__c> lstSessionParticipantsForAttendanceThankYouNotification = new List<Session_Participant__c>();
                        List<Session_Participant__c> lstSessionParticipantsForCatchupThankYouNotification = new List<Session_Participant__c>();
                        // iterate on each session participant to check the Attendance Date
                        for(Session_Participant__c sp : lstAttendAndCatchupSessionParticipants){
                            if(sp.Status__c == Label.Outreach_Notification_Session_Attended){
                                // check if Session participant is due for Session Attendance Thank You L1 notification
                                if(checkIfTodayIsDueForNotification(sp.Attendance_Date__c, Integer.valueOf(outreachSessionAttendanceThankYouSetting.L1_Days__c), Label.Outreach_Notification_Session_Attendance_Thank_you)) {
                                    lstSessionParticipantsForAttendanceThankYouNotification.add(sp);
                                }
                            }else{
                                // check if Session participant is due for Session Catchup Thank You L1 notification
                                if(checkIfTodayIsDueForNotification(sp.Catchup_Date__c, Integer.valueOf(outreachSessionCatchThankYouSetting.L1_Days__c), Label.Outreach_Notification_Session_Catchup_Thank_you)) {
                                    lstSessionParticipantsForCatchupThankYouNotification.add(sp);
                                }
                            }
                        }
                        if(!lstSessionParticipantsForAttendanceThankYouNotification.isEmpty()){
                            System.debug(LoggingLevel.DEBUG, '!@# lstSessionParticipantsForAttendanceThankYouNotification:' + lstSessionParticipantsForAttendanceThankYouNotification.size());
                            // record history
                            lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(false, true, lstSessionParticipantsForAttendanceThankYouNotification, outreachSessionAttendanceThankYouSetting));
                        }
                        if(!lstSessionParticipantsForCatchupThankYouNotification.isEmpty()){
                            System.debug(LoggingLevel.DEBUG, '!@# lstSessionParticipantsForCatchupThankYouNotification:' + lstSessionParticipantsForCatchupThankYouNotification.size());
                            // record history
                            lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(false, true, lstSessionParticipantsForCatchupThankYouNotification, outreachSessionCatchThankYouSetting));
                        }

                    } else{
                        System.debug(LoggingLevel.DEBUG, '!@# No Session Participant due for Thank You Notification.');
                    }
                }
            }

            // Session catchup flow
            if(session.Catch_up__c){
                if(System.now() > session.Catchup_Start_Date__c){
                    // Session Catchup Setting
                    if(bOutreachSessionCatchupSettingFound){
                        System.debug(LoggingLevel.DEBUG, '!@# outreachSessionCatchupSetting:' + outreachSessionCatchupSetting);
                        // check if Session is due for Session Catchup L1 notification
                        if(checkIfTodayIsDueForNotification(session.Catchup_Start_Date__c, Integer.valueOf(outreachSessionCatchupSetting.L1_Days__c), Label.Outreach_Notification_Session_Catchup)) {
                            System.debug(LoggingLevel.DEBUG, '!@# lstNotAttendedSessionParticipants:' + lstNotAttendedSessionParticipants.size());
                            // check if there are participants where status != Attended
                            if(!lstNotAttendedSessionParticipants.isEmpty()){
                                // record history
                                lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(false, true, lstNotAttendedSessionParticipants, outreachSessionCatchupSetting));
                            }
                        }else{
                            System.debug(LoggingLevel.DEBUG, '!@# Session - ' + session.Name + ' not due for Session Catchup L1 notification.');
                            // Session Catchup Reminder Setting
                            if(bOutreachSessionCatchupReminderSettingFound){
                                System.debug(LoggingLevel.DEBUG, '!@# outreachSessionCatchupReminderSetting:' + outreachSessionCatchupReminderSetting);

                                // check if Session is due for Session Catchup Reminder L1 notification
                                if(checkIfTodayIsDueForNotification(session.Catchup_End_Date__c, Integer.valueOf(outreachSessionCatchupReminderSetting.L1_Days__c), Label.Outreach_Notification_Session_Catchup_Reminder)) {
                                    System.debug(LoggingLevel.DEBUG, '!@# lstIncompleteCatchupSessionParticipants:' + lstIncompleteCatchupSessionParticipants.size());
                                    // check if there are participants where status != Attended and != Catchup
                                    if(!lstIncompleteCatchupSessionParticipants.isEmpty()){
                                        // record history
                                        lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(false, true, lstIncompleteCatchupSessionParticipants, outreachSessionCatchupReminderSetting));
                                    }
                                }else{
                                    System.debug(LoggingLevel.DEBUG, '!@# Session - ' + session.Name + ' not due for Session Catchup Reminder L1 notification.');

                                    // check if Session is due for Session Catchup Reminder L2 notification
                                    if(checkIfTodayIsDueForNotification(session.Catchup_End_Date__c, Integer.valueOf(outreachSessionCatchupReminderSetting.L2_Days__c), Label.Outreach_Notification_Session_Catchup_Reminder_L2)) {
                                        System.debug(LoggingLevel.DEBUG, '!@# lstIncompleteCatchupSessionParticipants:' + lstIncompleteCatchupSessionParticipants.size());
                                        // check if there are participants where status != Attended and != Catchup
                                        if(!lstIncompleteCatchupSessionParticipants.isEmpty()){
                                            // record history
                                            lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(true, true, lstIncompleteCatchupSessionParticipants, outreachSessionCatchupReminderSetting));
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }else{
                if(System.now() > session.End_Date_Time__c && !lstNotAttendedSessionParticipants.isEmpty()){
                    System.debug(LoggingLevel.DEBUG, '!@# lstNotAttendedSessionParticipants:' + lstNotAttendedSessionParticipants.size());
                    // record Outreach History for L2 Outreach report
                    lstNewOutreachNotificationHistories.addAll(createOutreachNotificationHistory(false, false, lstNotAttendedSessionParticipants, outreachSessionCatchupSetting));
                }
            }
        }
    }

    /* ***************************************************************************** */
    public static Boolean checkIfTodayIsDueForNotification(Datetime dtSessionDate, Integer iDays, String strType){
        Boolean bReturn = false;
        System.debug(LoggingLevel.DEBUG, ' !@# Outreach Notification Setting Days :  ' +iDays);
        if(strType == Label.Outreach_Notification_Session_Catchup){
            System.debug(LoggingLevel.DEBUG, ' !@# Days after Session Catchup StartDate: ' + dtSessionDate.date().daysBetween(System.now().date()));
            if(dtSessionDate.date().daysBetween(System.now().date()) == iDays){
                bReturn = true;
            }
        }else if(strType == Label.Outreach_Notification_Session_Catchup_Reminder || strType == Label.Outreach_Notification_Session_Catchup_Reminder_L2){
            System.debug(LoggingLevel.DEBUG, ' !@# Days prior to Session Catchup EndDate: ' + System.now().date().daysBetween(dtSessionDate.date()));
            if(System.now().date().daysBetween(dtSessionDate.date()) == iDays){
                bReturn = true;
            }
        }else if(strType == Label.Outreach_Notification_Session_Catchup_Thank_you || strType == Label.Outreach_Notification_Session_Attendance_Thank_you){
            System.debug(LoggingLevel.DEBUG, ' !@# Days after Session Participant Attendance Date: ' + dtSessionDate.date().daysBetween(System.now().date()));
            if(dtSessionDate.date().daysBetween(System.now().date()) == iDays){
                bReturn = true;
            }
        }
        return bReturn;
    }

    /* ***************************************************************************** */
    public static List<Outreach_Notification_History__c> createOutreachNotificationHistory(Boolean L2Flag, Boolean bCatchup, List<Session_Participant__c> lstSessionParticipants, Outreach_Notification_Setting__c outreachNotificationSetting){
        Datetime dtSchedule = Datetime.newInstance(System.today().year(), System.today().month(), System.today().day(),outreachNotificationSetting.Time__c.hour(), outreachNotificationSetting.Time__c.minute(), outreachNotificationSetting.Time__c.second());
        List<Outreach_Notification_History__c> lstOutreachNotificationHistories = new List<Outreach_Notification_History__c>();

        System.debug(LoggingLevel.DEBUG, ' !@# lstSessionParticipants: ' + lstSessionParticipants.size());
        for(Session_Participant__c sp : lstSessionParticipants){
            Outreach_Notification_History__c onhForSession = new Outreach_Notification_History__c();
            onhForSession.Contact__c = sp.Contact__c;
            onhForSession.Outreach_Notification__c = outreachNotificationSetting.Outreach_Notification__c;
            onhForSession.Related_To__c = sp.Session__r.Name;
            onhForSession.Related_To_Id__c = sp.Session__r.Id;
            if(!bCatchup || L2Flag){
                if(!bCatchup){
                    onhForSession.Notes__c = Label.Outreach_Notification_L2_Flagged + ' - ' + Label.Outreach_Notification_Missed_Attendance;
                }else{
                    onhForSession.Notes__c = Label.Outreach_Notification_L2_Flagged + ' - ' + Label.Outreach_Notification_Session_Catchup;
                }
            }else{
                onhForSession.Outreach_Notification_Setting__c = outreachNotificationSetting.Id;
                onhForSession.Schedule__c =  dtSchedule;
            }
            System.debug(LoggingLevel.DEBUG, ' !@# onhForSession: ' + onhForSession);
            lstOutreachNotificationHistories.add(onhForSession);
        }
        System.debug(LoggingLevel.DEBUG, ' !@# lstOutreachNotificationHistories: ' + lstOutreachNotificationHistories.size());
        return lstOutreachNotificationHistories;
    }


    /* ***************************************************************************** */
    public static List<Session_Participant__c> getSessionParticipantsPerStatus(List<Session_Participant__c> lstSesParticipants, String strStatus, Boolean bCondition){
        List<Session_Participant__c> lstSessionParticipants = new List<Session_Participant__c>();
        for(Session_Participant__c sp : lstSesParticipants){
            if(!bCondition){
                // get participants where status != Attended
                if(strStatus == 'Attended'){
                    if(sp.Status__c != strStatus) lstSessionParticipants.add(sp);
                }
                // get participants where status != Attended and != Catchup
                if(strStatus == 'Catchup'){
                    if(sp.Status__c != strStatus && sp.Status__c != 'Attended') lstSessionParticipants.add(sp);
                }
            }else{
                // get participants where status != Attended and != Catchup
                if((sp.Status__c == 'Catchup' && sp.Catchup_Date__c != null) || (sp.Status__c == 'Attended' && sp.Attendance_Date__c != null)) lstSessionParticipants.add(sp);
            }
        }
        return lstSessionParticipants;
    }


    /* ***************************************************************************** */
    public static Map<Id, Session__c> getSessions(){
        System.debug(LoggingLevel.DEBUG, ' !@# Retrieve Sessions');
        Map<Id, Session__c> mapSessionById = new Map<Id,Session__c>();

        for(Session__c session : [SELECT Id, Name, Event_Id__c, Event__c , IsActive__c, Outreach_Notification__c, Start_Date_Time__c, End_Date_Time__c,
                Catch_up__c, Catchup_Start_Date__c, Catchup_End_Date__c,
        (SELECT Id FROM Session_Participants__r)
        FROM Session__c WHERE Outreach_Notification__c != NULL
        AND IsActive__c = TRUE LIMIT 2000]){
            mapSessionById.put(session.Id, session);
        }

        return mapSessionById;
    }

    /* ***************************************************************************** */
    public static Map<Id, List<Session_Participant__c>> getSessionParticipants(Set<Id> setSessionIds){
        System.debug(LoggingLevel.DEBUG, ' !@# Retrieve Session Participants');
        Map<Id, List<Session_Participant__c>> mapSessionParticipantsByIds = new Map<Id, List<Session_Participant__c>>();
        for(Session_Participant__c sp : [SELECT Id, Name,Session__r.Id, Session__r.Name, Session__r.Event__r.Id, Session__r.Event__r.Name, Session__r.Time_Zone__c,
                Status__c, Contact__c, Participant__c, Session_Start_Date__c, Attendance_Date__c, Catchup_Date__c
        FROM Session_Participant__c
        WHERE Session__r.Id IN: setSessionIds AND Participant__c != NULL
        AND Contact__c != NULL ORDER BY  CreatedDate DESC  LIMIT 5000]){
            if(mapSessionParticipantsByIds.containsKey(sp.Session__r.Id)){
                mapSessionParticipantsByIds.get(sp.Session__r.Id).add(sp);
            }else{
                mapSessionParticipantsByIds.put(sp.Session__r.Id, new List<Session_Participant__c>{sp});
            }
        }
        //System.debug(LoggingLevel.DEBUG, ' !@# mapSessionParticipantsByIds: ' + JSON.serializePretty(mapSessionParticipantsByIds));
        return  mapSessionParticipantsByIds;
    }

}