main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/fields/Registration_Fields_JSON__c.field-meta.xml
<CustomField>
    <fullName>Registration_Fields_JSON__c</fullName>
    <label>Registration Fields JSON</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/classes/EventRegistrationFieldPickerCntlrTest.cls
/*******************************************************************************
 * @author       Kyzer Buhay
 * @date         06/07/2021
 * @description  Test class for EventRegistrationFieldPickerControllerTest
 * @revision     06/07/2021 - ADFrancisco - Created
 *******************************************************************************/
@IsTest
public class EventRegistrationFieldPickerCntlrTest {
    @TestSetup static void createData(){
        Campaign__c camp = new Campaign__c();
        camp.Name = 'Test Campaign';
        insert camp;
        
        Contact c = new Contact();
        c.FirstName = 'John';
        c.LastName = 'John';
        c.Department = 'IT';
        c.Email = 'John@test.com';
        insert c;
        
        Event__c e = new Event__c();
        e.Event_Id__c = 'xxxxxxxxxx';
        e.Campaign__c = camp.id;
        e.Start_Date_Time__c = DateTime.Now();
        e.End_Date_Time__c = DateTime.Now()+1;
        //Start [CCN-2530] RIANNO RIZARRI Feb01.2023 - Added this required field for test data.
        e.time_zone__c = 'AKDT';
        //End [CCN-2530] RIANNO RIZARRI Feb01.2023 - Added this required field for test data.
        insert e;
    }
    
    @IsTest
    static void hasExistingRegistrationFieldJSONTest(){
        Event__c eventRec = [SELECT Id FROM Event__c LIMIT 1];
        //Start [CCN-2530] RIANNO RIZARRI Feb01.2023  - Add the activation of field on the event registration field picker component.
        eventRec.Registration_Fields_JSON__c = '{"RegistrationField_FirstName-Contact|FirstName":{"required":true,"active":true},"RegistrationField_LastName-Contact|LastName":{"required":true,"active":true},"RegistrationField_Email-Contact|Email":{"required":true,"active":true},"RegistrationField_Site-Contact|Site__c":{"required":false,"active":true},"RegistrationField_Department-Contact|Department":{"required":false,"active":false},"RegistrationField_Title-Contact|Title":{"required":false,"active":true}}';
		//END [CCN-2530] RIANNO RIZARRI Feb01.2023  - Add the activation of field on the event registration field picker component.        
        update eventRec;
        
        Test.startTest();
        	List<RegistrationFields> regFields = EventRegistrationFieldPickerController.getAvailableRegistrationFields(eventRec.Id);
        Test.stopTest();
        System.assert(regFields.size() > 0);
    }
    
    @IsTest
    static void hasNoExistingRegistrationFieldJSONTest(){
        Event__c eventRec = [SELECT Id FROM Event__c LIMIT 1];
        Test.startTest();
        	List<RegistrationFields> regFields = EventRegistrationFieldPickerController.getAvailableRegistrationFields(eventRec.Id);
        Test.stopTest();
        System.assert(regFields.size() > 0);
    }
    
    
    @IsTest
    static void handleSaveRegistrationConfigurationTest(){
        Event__c eventRec = [SELECT Id FROM Event__c LIMIT 1];
        
        String jsonFieldConfig = '{"RegistrationField_FirstName-Contact|FirstName":true,"RegistrationField_LastName-Contact|LastName":true,' +
            									'"RegistrationField_Email-Contact|Email":true,"RegistrationField_Site-Contact|Department":false}';
        
        Test.startTest();
        	Boolean hasErrors = EventRegistrationFieldPickerController.saveRegistrationFormFields(eventRec.Id, jsonFieldConfig);
        Test.stopTest();
        
        System.assert(!hasErrors);
    }
}