main/default/objects/Campaign/fields/Event_Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Event_Page_URL__c</fullName>
    <label>Event Page URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <inlineHelpText>Image address link to the logo to display on the campaign summary page. Upload image to the Notes and Attachments section, and create a public link for the image. Paste the public link into a new browser, right-click, and copy the image address. Paste the link into the Campaign Summary Logo Link field.</inlineHelpText>
    <label>Campaign Summary Logo Link</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Event_Page_URL__c</fullName>
    <label>Event Page URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Event__c/fields/Show_To_Links__c.field-meta.xml
<CustomField>
    <fullName>Show_To_Links__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add Event Page to Summary Page</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/classes/LinktreeController.cls
/*******************************************************************************************
  * @name: LinktreeController 
  * @author: Minh
  * @created: 01-10-2021
  * @description: Campaign's Event summary page
  *
  * Changes (version)
  * -------------------------------------------------------------------------------------------
  *            No.  Date(dd-mm-yyy) Author                Description
  *           ----  ---------       --------------------  -----------------------------
  * @version   1.0  01-10-2021      Minh                  Initial version.
  *********************************************************************************************/
public without sharing class LinktreeController {

    @AuraEnabled (cacheable = true)
    public static Campaign__c getcampaignDetail(String campaignId){
        
        System.debug('campaignId: ' + campaignId);

        if (String.isBlank(campaignId)){
            return null;
        }
        
        Campaign__c objCampaign = new Campaign__c();
        
        try {
           	objCampaign = [SELECT Id, name, Logo_URL__c FROM Campaign__c WHERE id = :campaignId  LIMIT 1];               
        } catch (Exception err) {
            System.Debug('TRY-CATCH-CampaignDetailException-->' + err);
        }
        
        return objCampaign;
    }

    @AuraEnabled (cacheable = true)
    public static List<Event__c> getcampaignEvents(String campaignId){
        
        if (String.isBlank(campaignId)){
            return null;
        }
        
        List<Event__c> EventList = new List<Event__c>();
        
        try {
			EventList = [SELECT Id, name, Event_Page_URL__c, Show_To_Links__c FROM Event__c 
                WHERE Campaign__c = :campaignId and Show_To_Links__c=true and Event_Page_URL__c<>null
                order by name];        
        } catch (Exception err) {
            System.Debug('TRY-CATCH-campaignEventsException-->' + err);
        }
        return EventList; 
        
    }
}