main/default/objects/Campaign/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <formula>IF( RecordType.Name = &apos;Session&apos; &amp;&amp; ParentId &lt;&gt; null, HYPERLINK(&apos;/&apos; + ParentId, &apos;Event: &apos; +  Parent.Name),
IF( RecordType.Name = &apos;Event&apos; &amp;&amp; ParentId &lt;&gt; null, HYPERLINK(&apos;/&apos; + ParentId, &apos;Campaign: &apos; +  Parent.Name),
&apos;None&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent</label>
    <type>Text</type>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;For Review&quot;</defaultValue>
    <description>Status of the Journey</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates Active milestone</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the milestone tagged as checkpoint</description>
    <label>Checkpoint Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone__c.Journey__c</field>
            <operation>equals</operation>
            <valueField>$Source.Journey__c</valueField>
        </filterItems>
        <filterItems>
            <field>Milestone__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Checkpoint</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Milestones &amp; Checkpoints</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Milestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Milestone</description>
    <label>Journey Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attestation</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Milestone__c/recordTypes/Checkpoint.recordType-meta.xml
<RecordType>
    <fullName>Checkpoint</fullName>
    <active>true</active>
    <label>Checkpoint</label>
</RecordType>

main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

main/default/classes/MilestoneTriggerHandler_Test.cls
/*******************************************************************************
 * @author       Allen Francisco
 * @date         13.02.2021
 * @description  Test class for MilestoneTriggerHandler
 * @revision     13.02.2021 - ADFrancisco - Created
 *******************************************************************************/
@isTest(IsParallel=true)
public class MilestoneTriggerHandler_Test {
  @IsTest
  static void runTrigger() {
    Campaign__c testCampaign = new Campaign__c();
    testCampaign.Name = 'Test Campaign Name';
    insert testCampaign;

    Journey__c testJourneyA = new Journey__c();
    testJourneyA.Name = 'Test Journey A';
    testJourneyA.Campaign__c = testCampaign.Id;
    testJourneyA.Status__c = 'For Review';
    insert testJourneyA;

    Id recordTypeId = Schema.SObjectType.Milestone__c.getRecordTypeInfosByDeveloperName()
      .get('Checkpoint')
      .getRecordTypeId();
    Test.startTest();
    Milestone__c testMilestoneA = new Milestone__c();
    testMilestoneA.Journey__c = testJourneyA.Id;
    testMilestoneA.Name = 'Test Milestone A';
    testMilestoneA.Type__c = 'Communication';
    testMilestoneA.RecordTypeId = recordTypeId;
    testMilestoneA.Is_Active__c = true;
    insert testMilestoneA;

    Milestone__c testMilestoneB = new Milestone__c();
    testMilestoneB.Parent__c = testMilestoneA.Id;
    testMilestoneB.Journey__c = testJourneyA.Id;
    testMilestoneB.Name = 'Test Milestone B';
    testMilestoneB.Type__c = 'Communication';
    insert testMilestoneB;

    //Added by Kyzer Buhay 05/03/2021
    Milestone__c testInsertedMilestone = [
      SELECT Id, Name
      FROM Milestone__c
      WHERE Id = :testMilestoneB.Id
      LIMIT 1
    ];
    testInsertedMilestone.Name = 'Test Milestone C';
    update testInsertedMilestone;

    delete testInsertedMilestone;
    Test.stopTest();

    System.assertNotEquals([SELECT Id FROM Milestone__c], null);
  }
}