main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scrum Master</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Start_Date_Time2__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time2__c</fullName>
    <label>Start Date Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <description>Holds the Rank for each Participant</description>
    <label>Title/Rank</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch_of_Service__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>COL</fullName>
            </value>
            <value>
                <fullName>Lt Col</fullName>
            </value>
            <value>
                <fullName>LTC</fullName>
            </value>
            <value>
                <fullName>MAJ</fullName>
            </value>
            <value>
                <fullName>CAPT</fullName>
            </value>
            <value>
                <fullName>1st Lt</fullName>
            </value>
            <value>
                <fullName>2d Lt</fullName>
            </value>
            <value>
                <fullName>CMSgt</fullName>
            </value>
            <value>
                <fullName>SMSgt</fullName>
            </value>
            <value>
                <fullName>MSgt</fullName>
            </value>
            <value>
                <fullName>TSgt</fullName>
            </value>
            <value>
                <fullName>SSgt</fullName>
            </value>
            <value>
                <fullName>SrA</fullName>
            </value>
            <value>
                <fullName>A1C</fullName>
            </value>
            <value>
                <fullName>Amn</fullName>
            </value>
            <value>
                <fullName>CPT</fullName>
            </value>
            <value>
                <fullName>1LT</fullName>
            </value>
            <value>
                <fullName>2LT</fullName>
            </value>
            <value>
                <fullName>CSM</fullName>
            </value>
            <value>
                <fullName>SGM</fullName>
            </value>
            <value>
                <fullName>1SG</fullName>
            </value>
            <value>
                <fullName>MSG</fullName>
            </value>
            <value>
                <fullName>SFC</fullName>
            </value>
            <value>
                <fullName>SSG</fullName>
            </value>
            <value>
                <fullName>SGT</fullName>
            </value>
            <value>
                <fullName>CPL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Participant Role</description>
    <label>Session Role</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Role__c/Session_Role__c.object-meta.xml
<CustomObject>
    <description>01080 - Custom object for Session Role</description>
    <label>Session Role</label>
    <nameField>
        <displayFormat>SR-{000000}</displayFormat>
        <label>Session Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Session_Role__c/fields/Number_of_Role__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Role__c</fullName>
    <description>Number of Roles in a Session</description>
    <label>Number of Role</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Session_Role__c/fields/Role_Title__c.field-meta.xml
<CustomField>
    <fullName>Role_Title__c</fullName>
    <description>Title of the Role</description>
    <label>Role Title</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Role__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Session</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Session Roles</relationshipLabel>
    <relationshipName>Session_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/SignedUpRolesSummaryController.cls
public class SignedUpRolesSummaryController {
    
    private static WithoutSharingClass withoutShare = new WithoutSharingClass(); 
    
    @AuraEnabled
    public static mainWrapper getRecords(Id eventId){
        String hasData = 'No';
        
        mainWrapper returnWrapper = new mainWrapper();
        
        try{
            List<sessionParticipantWrapper> sessionPartList = new List<sessionParticipantWrapper>();
            
            Map<String, List<Session_Participant__c>> sessionParticipantMap = new Map<String, List<Session_Participant__c>>();
            Map<String, List<Session_Participant__c>> sessionParticipantMapCancelled = new Map<String, List<Session_Participant__c>>();
            
            //Loop through session participants and get Session-Role : Participant Mapping
            for(Session_Participant__c sessionPartRec : withoutShare.getSessionParticipants(eventId)){
                String mapKey = sessionPartRec.Session__c + '-' + sessionPartRec.Role__c;
                if(!sessionParticipantMap.containsKey(mapKey)){
                    sessionParticipantMap.put(mapKey, new List<Session_Participant__c>());
                }
                sessionParticipantMap.get(mapKey).add(sessionPartRec);
            }      
            
            //Loop through session participants and get Session-Role : Participant Mapping
            for(Session_Participant__c sessionPartRec : withoutShare.getSessionParticipantsCancelled(eventId)){
                String mapKey = sessionPartRec.Session__c + '-' + sessionPartRec.Role__c;
                if(!sessionParticipantMapCancelled.containsKey(mapKey)){
                    sessionParticipantMapCancelled.put(mapKey, new List<Session_Participant__c>());
                }
                sessionParticipantMapCancelled.get(mapKey).add(sessionPartRec);
            }
            
            //Loop through each role and participants(if any) then contruct table
            for(Session_Role__c sessionRoleRec : withoutShare.getSessionRoles(eventId)){
                String mapKey = sessionRoleRec.Session__c + '-' + sessionRoleRec.Role_Title__c;
                for(Integer i = 0; i < sessionRoleRec.Number_of_Role__c; i++){
                    
                    sessionParticipantWrapper sessionPart = new sessionParticipantWrapper();
                    sessionPart.SessionName = sessionRoleRec.Session__r.Name;
                    sessionPart.SessionStartDate = sessionRoleRec.Session__r.Start_Date_Time2__c+'';
                    sessionPart.SessionRole = sessionRoleRec.Role_Title__c;
                    sessionPart.ParticipantFirstName = '';
                    sessionPart.ParticipantLastName = '';
                    sessionPart.ParticipantEmail = '';
                    sessionPart.Status = '';
                    
                    if(!sessionParticipantMap.isEmpty() && sessionParticipantMap.containsKey(mapKey)){
                        hasData = 'Yes';
                        Integer participantSize = sessionParticipantMap.get(mapKey).size();
                        if(i < participantSize){
                            sessionPart.ParticipantFirstName = sessionParticipantMap.get(mapKey)[i].Contact__r.FirstName;
                            sessionPart.ParticipantLastName = sessionParticipantMap.get(mapKey)[i].Contact__r.LastName;
                            sessionPart.ParticipantEmail = sessionParticipantMap.get(mapKey)[i].Contact__r.Email;
                            sessionPart.Status = sessionParticipantMap.get(mapKey)[i].Status__c;
                        }
                    }
                    sessionPartList.add(sessionPart);
                }
                
                if(!sessionParticipantMapCancelled.isEmpty() && sessionParticipantMapCancelled.containsKey(mapKey)){
                    for(Session_Participant__c sessRec : sessionParticipantMapCancelled.get(mapKey)){
                        sessionParticipantWrapper sessionPart = new sessionParticipantWrapper();
                        sessionPart.SessionName = sessionRoleRec.Session__r.Name;
                        sessionPart.SessionStartDate = sessionRoleRec.Session__r.Start_Date_Time2__c+'';
                        sessionPart.SessionRole = sessionRoleRec.Role_Title__c;
                        sessionPart.ParticipantFirstName = sessRec.Contact__r.FirstName;
                        sessionPart.ParticipantLastName = sessRec.Contact__r.LastName;
                        sessionPart.ParticipantEmail = sessRec.Contact__r.Email;
                        sessionPart.Status = sessRec.Status__c;
                        sessionPartList.add(sessionPart);
                    }
                }
            }        
            
            System.debug('Gab: ' + sessionPartList);
            
            //Debugging
            if(!sessionPartList.isEmpty()){
                returnWrapper.message = 'Success';
                returnWrapper.hasData = hasData;
                returnWrapper.tableValues = sessionPartList;
            }
            
            return returnWrapper;
        }catch(Exception e){
            return returnWrapper;
        }
    }
    
    /******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyy) Author            Description
    *           ----  ---------       --------------------  -----------------------------
    * @version   1.0  ??              ??                   Initial version.
    * @version   2.0  17-06-2022      Von Pernicia         [CCN-EVE-1773-DV ] - Updated status value from Cancelled to Canceled
    ******************************************************************************/
    public without sharing class WithoutSharingClass{
        public List<Session_Participant__c> getSessionParticipants(String eventId){
            return [SELECT Id, Role__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.Email, Status__c, Session__c, Event__c FROM Session_Participant__c 
                    WHERE Event__c =: eventId AND Role__c != null AND Contact__c != null AND Status__c != 'Canceled'];
        }
        
        public List<Session_Participant__c> getSessionParticipantsCancelled(String eventId){
            return [SELECT Id, Role__c, Contact__r.FirstName, Contact__r.LastName, Contact__r.Email, Status__c, Session__c, Event__c FROM Session_Participant__c 
                    WHERE Event__c =: eventId AND Rank__c != null AND Role__c != null AND Contact__c != null AND Status__c = 'Canceled'];
        }
        
        public List<Session_Role__c> getSessionRoles(String eventId){
            return [SELECT Id, Role_Title__c, Number_of_Role__c, Session__c, Session__r.Name,Session__r.Start_Date_Time__c,Session__r.Start_Date_Time2__c FROM 
                    Session_Role__c WHERE Session__r.Event__c =: eventId ORDER BY Session__r.Name ASC];
        }
    }
    
    public class mainWrapper{
        @AuraEnabled public String message {get;set;}
        @AuraEnabled public String hasData {get;set;}
        @AuraEnabled public List<sessionParticipantWrapper> tableValues {get;set;}
    }
    
    public class sessionParticipantWrapper{
        @AuraEnabled public String SessionName {get;set;}
        @AuraEnabled public String SessionStartDate {get;set;}
        @AuraEnabled public String SessionRole {get;set;}
        @AuraEnabled public String ParticipantFirstName {get;set;}
        @AuraEnabled public String ParticipantLastName {get;set;}
        @AuraEnabled public String ParticipantEmail {get;set;}
        @AuraEnabled public String Status {get;set;}
    }
}