main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates Active milestone</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Milestone__c/fields/Milestone_Completed__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates milestone completion.
End Date &lt; Current Date</description>
    <label>Milestone Completed</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Milestone__c/fields/Parent_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Parent_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Milestone</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.Journey__c</field>
            <operation>equals</operation>
            <valueField>$Source.Journey__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Milestones &amp; Checkpoints (Parent Milestone)</relationshipLabel>
    <relationshipName>Milestones_Checkpoints</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

main/default/objects/Participant_Milestone__c/Participant_Milestone__c.object-meta.xml
<CustomObject>
    <description>All milestones of participants</description>
    <label>Participant Milestone</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Participant Milestone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Event End Date</description>
    <label>Milestone End Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates active record</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Milestone_Completed__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates the completion of the Participant Milestone based on the End Date.</description>
    <label>Milestone Completed</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Parent_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Parent_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Milestone</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.Journey__c</field>
            <operation>equals</operation>
            <valueField>Milestone__c.Journey__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones (Parent Milestone)</relationshipLabel>
    <relationshipName>Milestones_Checkpoints1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/BatchUpdateCompletePartMilestones.cls
/*******************************************************************************
 * @author       Angelo Rivera
 * @date         18.08.2021
 * @description  CCN-JOU-1245-DV - Updated Completed Milestone Flag in Participant Milestones
 * @revision     21.04.2022- APRivera - Created
 *******************************************************************************/

global class BatchUpdateCompletePartMilestones implements Database.Batchable<SObject>, Schedulable, Database.Stateful{

    public String strQuery = '';
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        
        //CCN-2359 XEN REYES 2.DEC.2022
        strQuery = 'SELECT Id, Milestone_Completed__c, End_Date__c FROM Participant_Milestone__c ' + 
                    'WHERE End_Date__c < TODAY ' +
                    'AND Milestone_Completed__c = FALSE ' + 
                    'AND ((Parent_Milestone__c != null AND Parent_Milestone__r.Is_Active__c = true AND Parent_Milestone__r.RecordType.Name = \'Milestone\') OR Parent_Milestone__c = null)';

        System.debug(LoggingLevel.DEBUG, 'QUERY: ' + strQuery);
        return Database.getQueryLocator(strQuery);
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope)
    {
        List<Participant_Milestone__c> lstMilestones = (List<Participant_Milestone__c>)scope;
        List<Participant_Milestone__c> lstMilestonesToUpdate = new List<Participant_Milestone__c>();
        
        if (!lstMilestones.isEmpty()) {
            for(Participant_Milestone__c m : lstMilestones){
                m.Milestone_Completed__c = true;
                lstMilestonesToUpdate.add(m);
            }

            //CCN-2359 XEN REYES 2.DEC.2022
            Database.SaveResult[] srList = Database.update(lstMilestonesToUpdate, false);
            for (Database.SaveResult sr : srList) {
                if (!sr.isSuccess()) {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('The following error has occurred. ' + sr.getId());                    
                        System.debug(err.getStatusCode() + ': ' + err.getMessage() + ' ' + err.getFields());
                    }
                }
            }
        }
    }

    global void finish(Database.BatchableContext BC) {

    }

    global void execute(SchedulableContext sc) {
        BatchUpdateCompletePartMilestones  batchObj = new  BatchUpdateCompletePartMilestones ();
        Id batchProcessId = Database.executeBatch(batchObj,100);
    }
}