main/default/objects/ONS_Email_Template_Setting__mdt/ONS_Email_Template_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Mapping of Email Template to the Notification Type of Outreach Notification Setting</description>
    <label>ONS Email Template Setting</label>
    <pluralLabel>ONS Email Template Settings</pluralLabel>
</CustomObject>

main/default/objects/ONS_Email_Template_Setting__mdt/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/ONS_Email_Template_Setting__mdt/fields/Notification_Type__c.field-meta.xml
<CustomField>
    <fullName>Notification_Type__c</fullName>
    <label>Notification Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/Outreach_Notification_Setting__c.object-meta.xml
<CustomObject>
    <description>Contains the configuration that will be used for each compass objects</description>
    <label>Outreach Notification Setting</label>
    <nameField>
        <label>Outreach Notification Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Notification Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_Setting__c/fields/Email_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Id__c</fullName>
    <label>Email Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Email_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Name__c</fullName>
    <description>Name of the Email Template</description>
    <label>Email Template Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Notification Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Invitation Registration Reminder</fullName>
            </value>
            <value>
                <fullName>Registration Confirmation Reminder</fullName>
            </value>
            <value>
                <fullName>Session Attendance Thank you</fullName>
            </value>
            <value>
                <fullName>Session Catchup</fullName>
            </value>
            <value>
                <fullName>Session Catchup Reminder</fullName>
            </value>
            <value>
                <fullName>Session Catchup Thank you</fullName>
            </value>
            <value>
                <fullName>Survey Catchup</fullName>
            </value>
            <value>
                <fullName>Survey Catchup Reminder</fullName>
            </value>
            <value>
                <fullName>Survey Reminder</fullName>
            </value>
            <value>
                <fullName>Survey Thank You</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/ONSettingTriggerHandler.cls
/*******************************************************************************************
  * @name: ONSettingTriggerHandler
  * @author: 
  * @created: 21-12-2021
  * @description: Handler for all the logic of the trigger for the Outreach Notification Setting object
  *
  * Changes (version)
  * -------------------------------------------------------------------------------------------
  *       		No.   Date(dd-mm-yyy) 	Author         	   	  Description
  *       		----  ---------------   --------------------  ---------------------------------
  * @version    1.0	  21-12-2021		Paolo Quiambao		  Initial Creation
  * 		    2.0   28-12-2021		Paolo Quiambao		  [CCN1062] Refactor to utilize custom metadata
  *********************************************************************************************/
public class ONSettingTriggerHandler {
    
    /*******************************************************************************************    
    * @name: onBeforeInsert
    * @author: Paolo Quiambao  
    * @created: 21-10-2021    
    * @description: Executes on before insert trigger event for Outreach Notification Setting   
    *    
    * -------------------------------------------------------------------------------------------
    *       	  No.   Date(dd-mm-yyy) 	Author         	   	  Description
    *       	  ----  ---------------     --------------------  -----------------------------
    * @version    1.0   21-12-2021   		Paolo Quiambao        [CCN856] Initial version.
	*********************************************************************************************/
    public static void onBeforeInsert(List<Outreach_Notification_Setting__c> newOutreachNotificationSettingList) {
        Map<String, EmailTemplate> typeToEmailTemplateIdMap = generateTypeToEmailTemplateIdMap();
        
        for(Outreach_Notification_Setting__c ons : newOutreachNotificationSettingList) {
            if(typeToEmailTemplateIdMap.containsKey(ons.Type__c)) {
                ons.Email_Template_Id__c = typeToEmailTemplateIdMap.get(ons.Type__c).Id;
                ons.Email_Template_Name__c = typeToEmailTemplateIdMap.get(ons.Type__c).Name;
            }
        }
    }
    
    /*******************************************************************************************    
    * @name: onBeforeUpdate
    * @author: Paolo Quiambao  
    * @created: 21-10-2021    
    * @description: Executes on before update trigger event for Outreach Notification Setting   
    *    
    * -------------------------------------------------------------------------------------------
    *       	  No.   Date(dd-mm-yyy) 	Author         	   	  Description
    *       	  ----  ---------------     --------------------  -----------------------------
    * @version    1.0   21-12-2021   		Paolo Quiambao        [CCN856] Initial version.
	*********************************************************************************************/
    public static void onBeforeUpdate(List<Outreach_Notification_Setting__c> newOutreachNotificationSettingList, Map<Id, Outreach_Notification_Setting__c> oldOutreachNotificationSettingMap) {
        Map<String, EmailTemplate> typeToEmailTemplateIdMap = generateTypeToEmailTemplateIdMap();
        
        for(Outreach_Notification_Setting__c ons : newOutreachNotificationSettingList) {
            if(typeToEmailTemplateIdMap.containsKey(ons.Type__c) && ons.Type__c != oldOutreachNotificationSettingMap.get(ons.Id).Type__c) {
                ons.Email_Template_Id__c = typeToEmailTemplateIdMap.get(ons.Type__c).Id;
                ons.Email_Template_Name__c = typeToEmailTemplateIdMap.get(ons.Type__c).Name;
            }    
        }
    }
    
    /*******************************************************************************************    
    * @name: generateTypeToEmailTemplateIdMap
    * @author: Paolo Quiambao  
    * @created: 21-12-2021    
    * @description: returns a map of Type and Email Template   
    *    
    * -------------------------------------------------------------------------------------------
    *       	  No.   Date(dd-mm-yyy) 	Author         	   	  Description
    *       	  ----  ---------------     --------------------  -----------------------------
    * @version    1.0   21-12-2021   		Paolo Quiambao        [CCN856] Initial version.
    * 			  2.0   28-12-2021			Paolo Quiambao		  [CCN1062] Refactor to utilize custom metadata
	*********************************************************************************************/
    public static Map<String, EmailTemplate> generateTypeToEmailTemplateIdMap() {
        Map<String, EmailTemplate> typeToEmailTemplateIdMap = new Map<String, EmailTemplate>();
        Map<String, EmailTemplate> emailTemplateMap = new Map<String, EmailTemplate>();
        
        for(EmailTemplate emailTemplate : [SELECT Id, Name FROM EmailTemplate WHERE Folder.Name = 'Compass']) {
            emailTemplateMap.put(emailTemplate.Name, emailTemplate);
        }
        
        // Updated by Paolo Quiambao [CCN-1062] Dec282021
        for(ONS_Email_Template_Setting__mdt onsMdt : ONS_Email_Template_Setting__mdt.getAll().values()) {
            if(onsMdt.Default__c) {
                typeToEmailTemplateIdMap.put(onsMdt.Notification_Type__c, emailTemplateMap.get(onsMdt.Email_Template_Name__c));
            }
        }
        
        return typeToEmailTemplateIdMap;
    }
}