main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/BatchUpdateParticipantSessions.cls
/*******************************************************************************************************
* Class Name      	: BatchUpdateParticipantSessions
* Description		: Batch Class to update Status field to Missed
* Author          	: RLugpatan
* Created On      	: 07/01/2022
* Modification Log	:
* -----------------------------------------------------------------------------------------------------
* Developer			  	Date			Modification ID		Description
* -----------------------------------------------------------------------------------------------------
* RLugpatan             07/01/2022		1000				Initial version - CCN-EVE-1827-DV
******************************************************************************************************/
public class BatchUpdateParticipantSessions implements Database.Batchable<SObject>, Schedulable, Database.Stateful{

    public String strQuery = '';
    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        List<String> lstStatuses = new List<String>{'Registered', 'Confirmed'};
        strQuery = 'SELECT Id, Status__c, Session__r.Start_Date_Time__c, Session__r.End_Date_Time__c, Session__r.IsActive__c FROM Session_Participant__c '+
            'WHERE Status__c IN: lstStatuses AND  Session__r.IsActive__c = TRUE ' +
            'AND (Session__r.Start_Date_Time__c = TODAY OR Session__r.End_Date_Time__c = TODAY)';
        System.debug(LoggingLevel.DEBUG, 'QUERY: ' + strQuery);
        return Database.getQueryLocator(strQuery);
    }

    public void execute(Database.BatchableContext BC, List<SObject> scope)
    {
        List<Session_Participant__c> lstPartipantSessions = (List<Session_Participant__c>)scope;
        List<Session_Participant__c> lstPartipantSessionsToUpdate = new List<Session_Participant__c>();
        if (!lstPartipantSessions.isEmpty()) {
            for(Session_Participant__c sp : lstPartipantSessions){
                sp.Status__c = 'Missed';
                lstPartipantSessionsToUpdate.add(sp);
            }
            try {
                Database.update(lstPartipantSessionsToUpdate);
            } catch(Exception e) {
                system.debug('Error :: '+e.getMessage());
                system.debug('Error :: '+e.getStackTraceString());
            }
        }
    }

    public void finish(Database.BatchableContext BC) {
    }

    public void execute(SchedulableContext sc) {
        BatchUpdateParticipantSessions  batchObj = new  BatchUpdateParticipantSessions ();
        Id batchProcessId = Database.executeBatch(batchObj,100);
    }
}