main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Confirmed_Participants__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Participants__c</fullName>
    <description>Total number of Session Participants with Status = Confirmed</description>
    <label>Confirmed Participants</label>
    <summaryFilterItems>
        <field>Session_Participant__c.Status__c</field>
        <operation>equals</operation>
        <value>Confirmed</value>
    </summaryFilterItems>
    <summaryForeignKey>Session_Participant__c.Session__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

main/default/objects/Session__c/fields/Registered_Participants__c.field-meta.xml
<CustomField>
    <fullName>Registered_Participants__c</fullName>
    <description>Total number of Session Participants with Status = Registered</description>
    <label>Registered Participants</label>
    <summaryFilterItems>
        <field>Session_Participant__c.Status__c</field>
        <operation>equals</operation>
        <value>Registered</value>
    </summaryFilterItems>
    <summaryForeignKey>Session_Participant__c.Session__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/fields/Total_Participants_Registered_New__c.field-meta.xml
<CustomField>
    <fullName>Total_Participants_Registered_New__c</fullName>
    <description>CCN-EVE-1834-DV - This is a system field updated by the apex trigger. This is referenced by Total_Participants_Registered to make sure the field showing is a read-only field.</description>
    <label>System Total Participants Registered</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Confirmed_Date__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_Date__c</fullName>
    <description>Confirmation Date</description>
    <label>Confirmed Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <label>Registration Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Date__c</fullName>
    <formula>Session__r.Start_Date_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session Start Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/BatchCalculateNumberOfSessionParticipant.cls
/******************************************************************************    
* Changes (version)
*            No.  Date(dd-mm-yyy) Author            Description
*           ----  ---------   --------------------  -----------------------------
* @version   1.0  07-29-2022   Rianno Rizarri       [CCN-EVE-1834-DV] This batch class will be used 1 time to calculate the number of participant per session.
*													This is due to the change of calculation of number of confirmed/registered participants
******************************************************************************/
public class BatchCalculateNumberOfSessionParticipant implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        //Query registered and confirmed participant
        return Database.getQueryLocator([SELECT Id FROM Session__c WHERE Confirmed_Participants__c > 0 OR Registered_Participants__c > 0]);
    }
    
    public void execute(Database.BatchableContext BC, List<Session__c> sessionList){
        Set<Id> sessionIds = new Set<Id>();
        for(Session__c sesh : sessionList){
            sessionIds.add(sesh.Id);
        }
        List<Session__c> sessionWithParticipant = new List<Session__c>();
        //session is queried again with participant on execute to prevent 'INVALID_QUERY_LOCATOR' in Batch Apex
        //https://help.salesforce.com/s/articleView?id=000323582&type=1
        sessionWithParticipant = [SELECT Id, 
                                  (SELECT ID, Session_Start_Date__c, Registration_Date__c, Confirmed_Date__c FROM Session_Participants__r 
                                   WHERE Status__c IN('Registered', 'Confirmed'))
                                  FROM Session__c WHERE ID IN: sessionIds AND (Confirmed_Participants__c > 0 OR Registered_Participants__c > 0)];
        List<Session__c> sessionToUpdate = new List<Session__c>();
        for(Session__c sesh : sessionWithParticipant){
            //commented out due to FATAL_ERROR System.QueryException: Aggregate query has too many rows for direct assignment, use FOR loop
            //https://help.salesforce.com/s/articleView?id=000323566&type=1
            //if(sesh.Session_Participants__r.size() > 0){
            //if(sesh.Session_Participants__r != null){
            Integer participantNumber = 0;
            for(Session_Participant__c seshPart : sesh.Session_Participants__r){
                //Count only participants that are confirmed or registered before the start date.
                if(seshPart.Confirmed_Date__c <= seshPart.Session_Start_Date__c || seshPart.Registration_Date__c <= seshPart.Session_Start_Date__c){
                    participantNumber++;
                }
            }
            Session__c newSesh = new Session__c();
            newSesh.Id = Sesh.Id;
            newSesh.Total_Participants_Registered_New__c = participantNumber;
            if(participantNumber> 0){
                sessionToUpdate.add(newSesh);                
            }
        }
        if(sessionToUpdate.size() > 0){
            Update sessionToUpdate;
        }
        
    }
    
    public void finish(Database.BatchableContext BC){
        
    }
}