main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Project__c/fields/Agile_RAID_Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Agile_RAID_Page_URL__c</fullName>
    <label>Agile RAID Page URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/classes/ProjectTriggerHandler1_Test.cls
@isTest
public class ProjectTriggerHandler1_Test {
    @testSetup static void createData() {
        //Create Project
        Project__c project = new Project__c(Name = 'Test Project',
                                                    Project_Code__c = 'test');
        insert project;
    }
    
    
    @isTest static void testUpdate(){
        
        Project__c project =  [SELECT Id, Project_Code__c, Agile_RAID_Page_URL__c from Project__c LIMIT 1];
        //Assert for Insert
        system.assertEquals('default/s/raid?id=test', Project.Agile_RAID_Page_URL__c);
        project.Project_Code__c = 'abcde';
        test.startTest();
        update project;
        test.stopTest();
        Project__c result =  [SELECT Id, Project_Code__c, Agile_RAID_Page_URL__c from Project__c LIMIT 1];
        //Assert for Update
        system.assertEquals('default/s/raid?id=abcde', result.Agile_RAID_Page_URL__c);
    }
}