main/default/objects/Agile_RAID__c/Agile_RAID__c.object-meta.xml
<CustomObject>
    <label>Agile RAID</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>RAID ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agile RAIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Agile_RAID__c/fields/CAPM_Project__c.field-meta.xml
<CustomField>
    <fullName>CAPM_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CAPM Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Agile RAIDs</relationshipLabel>
    <relationshipName>Agile_RAIDs_del</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Agile_RAID__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Agile_RAID__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Epic</label>
    <referenceTo>Epic__c</referenceTo>
    <relationshipLabel>Agile RAIDs</relationshipLabel>
    <relationshipName>RAIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Agile_RAID__c/fields/Raised_By__c.field-meta.xml
<CustomField>
    <fullName>Raised_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raised By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Agile_RAIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Agile_RAID__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Addressed</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Agile_RAID__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requirement</fullName>
            </value>
            <value>
                <fullName>Risk</fullName>
            </value>
            <value>
                <fullName>Assumption</fullName>
            </value>
            <value>
                <fullName>Action</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Idea</fullName>
            </value>
            <value>
                <fullName>Dependency</fullName>
            </value>
            <value>
                <fullName>Decision</fullName>
            </value>
            <value>
                <fullName>Decision-Made</fullName>
                <isActive>false</isActive>
                <label>Decision-Made</label>
            </value>
            <value>
                <fullName>Decision-Pending</fullName>
                <isActive>false</isActive>
                <label>Decision-Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Epic__c/Epic__c.object-meta.xml
<CustomObject>
    <label>Epic</label>
    <nameField>
        <label>Epic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Epic__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Requirements Tracking</fullName>
            </value>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>Roadmap</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/AgileRaidToStoryConverterBatchTest.cls
@isTest
private class AgileRaidToStoryConverterBatchTest {

    @isTest static void testBatch() {
        // Create test data for the batch to process
        List<Agile_Raid__c> raidRecords = new List<Agile_Raid__c>();
        Agile_Raid__c nAgileRaid = new Agile_Raid__c();
        nAgileRaid.Type__c = 'Requirement';
        nAgileRaid.Description__c = '<br/>Test';
        raidRecords.add(nAgileRaid);
        // Populate the raidRecords list with test data (you can create test records here)
        // Make sure to set the necessary fields such as CAPM_Project__c, Epic__c, Raised_By__c, etc.

        // Insert the test records into the database
        insert raidRecords;

        // Start the batch job
        Test.startTest();
        AgileRaidToStoryConverterBatch batchJob = new AgileRaidToStoryConverterBatch();
        Database.executeBatch(batchJob);

        // Stop the batch job
        Test.stopTest();

        // Perform assertions to validate the batch job's behavior
        // Query and assert on the records that should have been updated/inserted
        List<Agile_Raid__c> updatedRaidRecords = [SELECT Id, Status__c FROM Agile_Raid__c WHERE Id IN :raidRecords];

        Assert.areEqual(raidRecords.size(), updatedRaidRecords.size(), 'All records should have been updated.');
    }
}