main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Member_Status</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Participant__c/recordTypes/Participant.recordType-meta.xml
<RecordType>
    <fullName>Participant</fullName>
    <active>true</active>
    <label>Participant</label>
</RecordType>

main/default/globalValueSets/Member_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Attended</fullName>
    </customValue>
    <customValue>
        <fullName>Catch-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Responded</fullName>
        <isActive>false</isActive>
        <label>Responded</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <isActive>false</isActive>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <masterLabel>Member Status</masterLabel>
</GlobalValueSet>

main/default/classes/SendEmailToParticipantsController.cls
public class SendEmailToParticipantsController {
    
    private static WithoutSharingClass withoutShare = new WithoutSharingClass(); 
    
    @AuraEnabled 
    public static List<EmailTemplate> getEmailTemplate(){
        return withoutShare.getEmailTemplateWS();
    }
    
    @AuraEnabled 
    public static Map<String, String> getStatusValues(){        
        return withoutShare.getStatusValuesWC();
    }
    
    @AuraEnabled
    public static void sendEmails(String eventId, String statusValue, String templateValue){
		withoutShare.sendEmailsWC(eventId,statusValue,templateValue);
    }
    
    public without sharing class WithoutSharingClass{
        public List<EmailTemplate> getEmailTemplateWS(){
            //XEN REYES CCN-978 Mar 3, 2022
            List<String> applicableTemplates = Label.Event_Participant_Templates.split(',');
            return [SELECT Id,Body,Name,IsActive FROM EmailTemplate WHERE Folder.Name Like '%Compass%' AND Name IN: applicableTemplates AND IsActive = true];
        }
        public Map<String, String> getStatusValuesWC(){
            Map<String, String> options = new Map<String, String>();
            
            Schema.DescribeFieldResult fieldResult = Participant__c.Status__c.getDescribe();
            
            List<Schema.PicklistEntry> pValues = fieldResult.getPicklistValues();
            for (Schema.PicklistEntry p: pValues) {
                
                options.put(p.getValue(), p.getLabel());
            }
            return options;
        }
        public void sendEmailsWC(String eventId, String statusValue, String templateValue){
            SendEmailToParticipantsBatch batchClass = new SendEmailToParticipantsBatch((Id)eventId,statusValue,templateValue,new List<Id>());
            System.scheduleBatch(batchClass, 'Send Email to Participant: ' + Datetime.now(), 1, 100);
        }
    }
}