main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/recordTypes/Participant.recordType-meta.xml
<RecordType>
    <fullName>Participant</fullName>
    <active>true</active>
    <label>Participant</label>
</RecordType>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey_Participant__c/Survey_Participant__c.object-meta.xml
<CustomObject>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that has been selected as a participant for a survey</description>
    <inlineHelpText>Contact that has been selected as a participant for a survey</inlineHelpText>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <description>Survey that the contact has been selected to participate to</description>
    <inlineHelpText>Survey that the contact has been selected to participate to</inlineHelpText>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/SurveyParticipantSelectorController.cls
public with sharing class SurveyParticipantSelectorController {
  @AuraEnabled
  public static List<Contact> getContactsFromSurveyParticipants(
    String recordId
  ) {
    List<Contact> contactList = new List<Contact>();

    for (Survey_Participant__c surveyParticipant : [
      SELECT Id, Participant__c, Participant__r.Name, Participant__r.Email
      FROM Survey_Participant__c
      WHERE Survey__c = :recordId
      LIMIT 5000
    ]) {
      contactList.add(surveyParticipant.Participant__r);
    }

    return contactList;
  }

  @AuraEnabled
  public static void saveSelectedParticipants(
    List<String> objectIds,
    String recordId
  ) {
    Set<String> recordsToInsert = new Set<String>(objectIds);
    List<Survey_Participant__c> recordsToDelete = new List<Survey_Participant__c>();

    //check which ids are returned, if a survey participant id is not returned from UI, it will be deleted
    //if contact is new than what is currently in the survey participants, add it as a survey participant
    if (!objectIds.isEmpty()) {
      for (Survey_Participant__c surveyParticipant : [
        SELECT Id, Participant__c
        FROM Survey_Participant__c
        WHERE Survey__c = :recordId
        LIMIT 5000
      ]) {
        if (recordsToInsert.contains(surveyParticipant.Participant__c)) {
          recordsToInsert.remove(surveyParticipant.Participant__c);
        } else {
          recordsToDelete.add(surveyParticipant);
        }
      }

      if (!recordsToInsert.isEmpty()) {
        insertSurveyParticipants(recordsToInsert, recordId);
      }

      if (!recordsToDelete.isEmpty()) {
        try {
          delete recordsToDelete;
        } catch (Exception exc) {
          throw new AuraHandledException(exc.getMessage());
        }
      }
    } else {
      delete [
        SELECT Id, Participant__c
        FROM Survey_Participant__c
        WHERE Survey__c = :recordId
      ];
    }
  }

  private static void insertSurveyParticipants(
    Set<String> recordsToInsert,
    String recordId
  ) {
    List<Survey_Participant__c> newSurveyParticipants = new List<Survey_Participant__c>();

    for (String contactId : recordsToInsert) {
      newSurveyParticipants.add(
        new Survey_Participant__c(
          Participant__c = contactId,
          Survey__c = recordId
        )
      );
    }

    try {
      insert newSurveyParticipants;
    } catch (Exception exc) {
      throw new AuraHandledException(exc.getMessage());
    }
  }
}