main/default/objects/Case/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <label>Application</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compass Connect</fullName>
            </value>
            <value>
                <fullName>CCN</fullName>
                <label>Compass Change Navigator</label>
            </value>
            <value>
                <fullName>CPM</fullName>
                <label>Compass Project Manager</label>
            </value>
            <value>
                <fullName>CAPM</fullName>
                <label>Compass Agile Project Management</label>
            </value>
            <value>
                <fullName>AMZN</fullName>
                <label>AWS/Amazon Build</label>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>NCC</fullName>
            </value>
            <value>
                <fullName>Compass Change Navigator (CCN)</fullName>
                <isActive>false</isActive>
                <label>Compass Change Navigator (CCN)</label>
            </value>
            <value>
                <fullName>Compass Project Management (CPM)</fullName>
                <isActive>false</isActive>
                <label>Compass Project Management (CPM)</label>
            </value>
            <value>
                <fullName>Compass_Agile_Project_Management_CAPM</fullName>
                <isActive>false</isActive>
                <label>Compass_Agile_Project_Management_CAPM</label>
            </value>
            <value>
                <fullName>Compass_Change_Navigator_CCN</fullName>
                <isActive>false</isActive>
                <label>Compass_Change_Navigator_CCN</label>
            </value>
            <value>
                <fullName>Compass_Project_Management_CPM</fullName>
                <isActive>false</isActive>
                <label>Compass_Project_Management_CPM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Case/fields/Create_Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Create_Project_Task__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Project Task</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Case/fields/Onboarding_Automation_Error__c.field-meta.xml
<CustomField>
    <fullName>Onboarding_Automation_Error__c</fullName>
    <description>Field to get populated with any automation error encountered</description>
    <label>Onboarding Automation Error</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Requirements Tracking</fullName>
            </value>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>Roadmap</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Project_Task__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <label>Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Organization</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Project_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Project will be automatically populated upon saving if related to a Workplan.</inlineHelpText>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Discovery, Requirements Tracking, Completed, Canceled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipName>Project_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To identify the current status of Project task</description>
    <inlineHelpText>For TR: For Technical Review, For UI/UX
For QA: For Quality Assurance</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Estimate</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>For TR</fullName>
            </value>
            <value>
                <fullName>For QA</fullName>
            </value>
            <value>
                <fullName>For Release</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>SIT</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Prod Validation</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress - Off-Track</fullName>
            </value>
            <value>
                <fullName>In Progress - At Risk</fullName>
            </value>
            <value>
                <fullName>In Progress - On-Track</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Project_Task__c/recordTypes/Bug.recordType-meta.xml
<RecordType>
    <fullName>Bug</fullName>
    <active>true</active>
    <label>Bug</label>
</RecordType>

main/default/objects/Project_Task__c/recordTypes/Feature.recordType-meta.xml
<RecordType>
    <fullName>Feature</fullName>
    <active>true</active>
    <label>Feature</label>
</RecordType>

main/default/objects/Project_Task__c/recordTypes/Story.recordType-meta.xml
<RecordType>
    <fullName>Story</fullName>
    <active>true</active>
    <label>Story</label>
</RecordType>

main/default/globalValueSets/Organization.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DEV</fullName>
    </customValue>
    <customValue>
        <fullName>DEV2</fullName>
    </customValue>
    <customValue>
        <fullName>DEV3</fullName>
        <default>true</default>
        <label>DEV3</label>
    </customValue>
    <customValue>
        <fullName>UAT</fullName>
    </customValue>
    <customValue>
        <fullName>Staging</fullName>
    </customValue>
    <customValue>
        <fullName>Demo</fullName>
    </customValue>
    <customValue>
        <fullName>Production</fullName>
    </customValue>
    <customValue>
        <fullName>PDO</fullName>
    </customValue>
    <customValue>
        <fullName>Production (AP)</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>CRMPartial</fullName>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <masterLabel>Organization</masterLabel>
</GlobalValueSet>

main/default/classes/CaseTriggerUtility.cls
/*******************************************************************************
* @author           Christian Doctolero
* @date             07.30.2021
* @description      Utlity Handler Class for Case 
* @param        
* @Trigger Class    CaseTrigger
* @Handler Class    CaseTriggerHandler      
*******************************************************************************/

public class CaseTriggerUtility {
    /*******************************************************************************
    * @author           Christian Doctolero
    * @date             07.30.2021
    * @description      CAPM-49
    * @param        
    *******************************************************************************/
    public static void createStoryFromACase(Map<Id,Case> newCaseMap){
        Project_Task__c projTaskRec = new Project_Task__c();
        List<Project_Task__c> projTaskListToAdd = new List<Project_Task__c>();
        Id bugRecTypeId = [SELECT Id FROM RecordType WHERE Name = 'Bug'].Id;
        Id storyRecTypeId = [SELECT Id FROM RecordType WHERE Name = 'Story'].Id;
        Map<String, Id> projViaCodeMap = new Map<String, Id>(); 
        
        //Create a map of projects that has project code as its key
        for(Project__c prk: [SELECT Id, Project_Code__c FROM Project__c]){
            projViaCodeMap.put(prk.Project_Code__c, prk.Id);
        }

        for(Case cs: newCaseMap.values()){
            if(cs.Type == 'Incident'){
                projTaskRec.RecordTypeId = bugRecTypeId;
            }
            else if(cs.Type == 'New feature'){
                projTaskRec.RecordTypeId = storyRecTypeId;
                projTaskRec.Status__c = 'New'; 
            }
            projTaskRec.Title__c = cs.Subject;
            projTaskRec.Organization__c = 'Production';
            projTaskRec.Description__c = cs.Description;
            projTaskRec.OwnerId = cs.OwnerId;
            projTaskRec.Case__c = cs.Id;
            projTaskRec.Project__c = projViaCodeMap.get(cs.Application__c);

            projTaskListToAdd.add(projTaskRec);
        }

        insert projTaskListToAdd;
    }
    
    /*******************************************************************************
    * @author           Christian Doctolero
    * @date             07.30.2021
    * @description      CAPM-49
    * @param        
    *******************************************************************************/
    @future
    public static void updateCaseMovedToCAPM(Set<Id> caseIds){
        
        Map<Id, Id> projTaskViaCaseIdMap = new Map<Id, Id>();
        List<Case> casesToUpdateList = new List<Case>();
        
        for(Project_Task__c prj: [SELECT Id, Case__c FROM Project_Task__c WHERE Case__c != NULL]){
            projTaskViaCaseIdMap.put(prj.Case__c, prj.Id);
        }
        
        for(Case cs: [SELECT Id, Project_Task__c, Status, Resolution__c, Type, Create_Project_Task__c 
                        FROM Case WHERE Create_Project_Task__c = true]){

            if(cs.Type == 'Incident' || cs.Type == 'New Feature'){

                cs.Project_Task__c = projTaskViaCaseIdMap.get(cs.Id);
                cs.Status = 'Closed';
                cs.Resolution__c = 'Moved to CAPM';
                casesToUpdateList.add(cs);
            }
        }
        update casesToUpdateList;
    }
    
	/*******************************************************************************
    * @author           Iamca Cagurangan
    * @date             08.12.21
    * @description      CPM-55 Save automation error message to case field: Onboarding_Automation_Error__c  
    * @param        
    *******************************************************************************/
    @future
    public static void captureErrorMsg(String errorMsg, String objectName, String caseMap) {
        Map<Id,Case> newCases = (Map<Id,Case>)JSON.deserialize(caseMap, Map<Id,Case>.class);
        List<Case> caseToUpdate = new List<Case>();
        for(Case caseRec : newCases.values()){
            switch on objectName {
                when 'User' {
                    caseRec.Onboarding_Automation_Error__c = 'Error inserting user: '+errorMsg;
                }	
                when 'Contact' {
                    caseRec.Onboarding_Automation_Error__c = 'Error inserting contact: '+errorMsg;
                }
                when 'Project Resource' {
                    caseRec.Onboarding_Automation_Error__c = 'Error inserting project resource: '+errorMsg;
                }
            }
            caseToUpdate.add(caseRec);
        }
        
        update caseToUpdate;
    }
}