main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/ChangeEventTypeAction__c.field-meta.xml
<CustomField>
    <fullName>ChangeEventTypeAction__c</fullName>
    <description>Hidden field created for triggering MS Teams integration when the Event Type or Virtual Meeting Platform is updated via ChangeEventType Aura Component</description>
    <label>ChangeEventTypeAction</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/fields/Internal_Logistics_Required__c.field-meta.xml
<CustomField>
    <fullName>Internal_Logistics_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Internal Logistics Required?</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Event__c/fields/Re_Generate_URL__c.field-meta.xml
<CustomField>
    <fullName>Re_Generate_URL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re-Generate URL</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Event__c/fields/Virtual_Meeting_Platform__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Meeting_Platform__c</fullName>
    <label>Virtual Meeting Platform</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Event_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MS Teams</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/classes/CCEventTriggerHandlerTest.cls
@isTest
private class CCEventTriggerHandlerTest {
    @testSetup static void createData(){
        Compass_Setting__c comp = TestDataFactory.createCSData(1);
        insert comp;
        
		Campaign__c camp = TestDataFactory.createCampaign(1);
        insert camp;
        
    }
    static testmethod void testOrgWide(){
        Campaign__c campRec = [Select Id, Name FROM Campaign__c WHERE Name =: 'Test Campaign1' ];
        system.debug('camp' + campRec);
        
        Compass_Setting__c comp = [Select Id, Name, Email_Sender_Id__c FROM Compass_Setting__c WHERE Name =: 'Default Settings' ];
        List<Event__c> eventList = new List<Event__c>();
        for(Integer i = 0 ; i<=100 ;i++){
            Event__c eve = new Event__c();
            eve.Name = 'Test Event' + i;
            eve.Campaign__c = campRec.Id;
            eve.Email_Sender_Id__c = NULL;
            eventList.add(eve);
        }
        Test.startTest();        
        //Event__c eve = new Event__c(Name = 'Test Event', Campaign__c = campRec.Id, Email_Sender_Id__c = NULL);
        insert eventList;
        Test.stopTest();
        System.assert(eventList != null);
    }
    
    static testmethod void testRegenerateEventURL(){
        Campaign__c campRec = [Select Id, Name FROM Campaign__c WHERE Name =: 'Test Campaign1' ];
        system.debug('camp' + campRec);
        
        Compass_Setting__c comp = [Select Id, Name, Email_Sender_Id__c FROM Compass_Setting__c WHERE Name =: 'Default Settings' ];
        List<Event__c> eventList = new List<Event__c>();
        for(Integer i = 0 ; i<=100 ;i++){
            Event__c eve = new Event__c();
            eve.Name = 'Test Event' + i;
            eve.Campaign__c = campRec.Id;
            eve.Email_Sender_Id__c = NULL;
            eventList.add(eve);
        }
        insert eventList;
        
        Test.startTest();        
        Event__c evn = [SELECT Id, Re_Generate_URL__c FROM Event__c LIMIT 1];
        evn.Re_Generate_URL__c = true;
        evn.Internal_Logistics_Required__c = true; //[CCN-LOG-2217-DV] Xen Reyes 25Nov2022
        update evn;
        Test.stopTest();
        System.assert(eventList != null);
    }

    static testmethod void testVirtualMeetingIntegrationInPerson(){
        Campaign__c campRec = [Select Id, Name FROM Campaign__c WHERE Name =: 'Test Campaign1' ];
        system.debug('camp' + campRec);
        
        Compass_Setting__c comp = [Select Id, Name, Email_Sender_Id__c FROM Compass_Setting__c WHERE Name =: 'Default Settings' ];
        List<Event__c> eventList = new List<Event__c>();
        for(Integer i = 0 ; i<=100 ;i++){
            Event__c eve = new Event__c();
            eve.Name = 'Test Event' + i;
            eve.Campaign__c = campRec.Id;
            eve.Email_Sender_Id__c = NULL;
            eventList.add(eve);
            //Virtual, MS Teams InPersonToVirtual-RunIntegration
        }
        insert eventList;
        Test.setMock(HttpCalloutMock.class, new AzureAPIMockHttpResponseGenerator());
        Test.startTest();    
        Event__c evn = [SELECT Id, Re_Generate_URL__c FROM Event__c LIMIT 1];
        evn.Event_Type__c = 'In-Person';
        evn.ChangeEventTypeAction__c = 'VirtualToInPerson-RemoveVirtualPlatformInfo';
        update evn;
        Test.stopTest();
        System.assert(eventList != null);
    }

    static testmethod void testVirtualMeetingIntegrationVirtual(){
        Campaign__c campRec = [Select Id, Name FROM Campaign__c WHERE Name =: 'Test Campaign1' ];
        system.debug('camp' + campRec);
        
        Compass_Setting__c comp = [Select Id, Name, Email_Sender_Id__c FROM Compass_Setting__c WHERE Name =: 'Default Settings' ];
        List<Event__c> eventList = new List<Event__c>();
        for(Integer i = 0 ; i<=100 ;i++){
            Event__c eve = new Event__c();
            eve.Name = 'Test Event' + i;
            eve.Campaign__c = campRec.Id;
            eve.Email_Sender_Id__c = NULL;
            eventList.add(eve);
            //Virtual, MS Teams 
        }
        insert eventList;
        Test.setMock(HttpCalloutMock.class, new AzureAPIMockHttpResponseGenerator());
        Test.startTest();    
        Event__c evn = [SELECT Id, Re_Generate_URL__c FROM Event__c LIMIT 1];
        evn.Event_Type__c = 'Virtual';
        evn.Virtual_Meeting_Platform__c = 'MS Teams';
        evn.ChangeEventTypeAction__c = 'InPersonToVirtual-RunIntegration';
        update evn;

        Event__c evnTwo = [SELECT Id, Re_Generate_URL__c FROM Event__c LIMIT 1];
        evnTwo.Event_Type__c = 'In-Person';
        evnTwo.Virtual_Meeting_Platform__c = '';
        evnTwo.ChangeEventTypeAction__c = 'VirtualToInPerson-RemoveVirtualPlatformInfo';
        update evnTwo;

        Test.stopTest();
        System.assert(eventList != null);
    }
}