main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Internal_Logistics__c/Internal_Logistics__c.object-meta.xml
<CustomObject>
    <label>Internal Logistics</label>
    <nameField>
        <displayFormat>IL-{0000}</displayFormat>
        <label>Internal Logistics Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Logistics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Logistics__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Internal Logistics</relationshipLabel>
    <relationshipName>Internal_Logistics</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Logistics__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Name</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Internal Logistics</relationshipLabel>
    <relationshipName>Internal_Logistics</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Logistics__c/fields/Number_of_Locations__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Locations__c</fullName>
    <label>Number of Locations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Internal_Logistics__c/fields/Session_Locations__c.field-meta.xml
<CustomField>
    <fullName>Session_Locations__c</fullName>
    <label>Session Locations</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Meeting_URL__c.field-meta.xml
<CustomField>
    <fullName>Meeting_URL__c</fullName>
    <label>Meeting Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/CCEventTriggerUtility.cls
public with sharing class CCEventTriggerUtility {

    public class MyException extends Exception {}

    public static void generateOrdWideEmail(List < Event__c > eventList) {
        try {
            Compass_Setting__c compRec = new Compass_Setting__c();
            //Get the compass summary record for the Default Settings
            if (FlsUtils.isAccessible('Compass_Setting__c', new List < String > {
                    'Name',
                    'Email_Sender_Id__c'
                })) {
                compRec = [Select Id, Name, Email_Sender_Id__c, Email_Sender_Name__c FROM Compass_Setting__c WHERE Name =: 'Default Settings'
                    LIMIT 1
                ];
            }
            for (Event__c eventRec: eventList) {
                //if the email sender id of event is null, always copy from the default settings.
                if (eventRec.Email_Sender_Id__c == NULL) {
                    eventRec.Email_Sender_Id__c = compRec.Email_Sender_Id__c;
                }
                if (eventRec.Email_Sender_Name__c == NULL) {
                    eventRec.Email_Sender_Name__c = compRec.Email_Sender_Name__c;
                }
            }
        } catch (exception e) {

        }
    }

    /******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyy) Author            Description
    *           ----  ---------   --------------------  -----------------------------
    * @version   1.0  25-11-2022   Xen Reyes            [CCN-LOG-2217-DV] Initial version.
    ******************************************************************************/
    public static void eventInternalLogistics(List <Event__c> eventList, Boolean isInsert) {
        try {
            
            Map<Id, Event__c> eventMap = new Map<Id, Event__c>(eventList);
            Set<Id> eventWithoutLogisticsId = new Set<Id>();
            List<Internal_Logistics__c> logisticsToInsert = new List<Internal_Logistics__c>();
            
            if(!isInsert){
                for(Event__c e : [SELECT Id, (SELECT Id FROM Internal_Logistics__r) FROM Event__c WHERE Id IN: eventList]){
                    if(e.Internal_Logistics__r.isEmpty()) eventWithoutLogisticsId.add(e.Id);
                }

                Map<Id, Set<String>> eventIdSessionMeetingLocationsMap = new Map<Id, Set<String>>();
                for(Event__c e : [SELECT Id, (SELECT Id, Meeting_URL__c FROM CC_Sessions__r WHERE IsActive__c = true) FROM Event__c WHERE Id IN: eventWithoutLogisticsId]){
                    Set<String> sessionMeetingLocations = new Set<String> ();
                    for(Session__c s : e.CC_Sessions__r){
                        if(s.Meeting_URL__c != null) sessionMeetingLocations.add(s.Meeting_URL__c);
                    }
                    eventIdSessionMeetingLocationsMap.put(e.Id, sessionMeetingLocations);
                }
                
                if(!eventWithoutLogisticsId.isEmpty()){
                    for(String eventId : eventWithoutLogisticsId){

                        String sessionMeetingLocationsCon = '';
                        Integer numberOfSessionMeetingLocations = 0;

                        if(eventIdSessionMeetingLocationsMap.containsKey(eventId)){
                            List<String> locationList = new List<String>(eventIdSessionMeetingLocationsMap.get(eventId));
                            locationList.sort();
                            sessionMeetingLocationsCon = String.join(locationList, ', ');
                            numberOfSessionMeetingLocations = eventIdSessionMeetingLocationsMap.get(eventId).size();
                        }

                        logisticsToInsert.add(new Internal_Logistics__c(Event_Name__c = eventId, 
                                                                        Campaign__c = eventMap.get(eventId).Campaign__c,
                                                                        Session_Locations__c = sessionMeetingLocationsCon,
                                                                        Number_of_Locations__c = numberOfSessionMeetingLocations));
                    }
                }
            } else {
                for(Event__c eventVar : eventList){
                    logisticsToInsert.add(new Internal_Logistics__c(Event_Name__c = eventVar.Id, 
                                                                    Campaign__c = eventVar.Campaign__c));
                }
            }

            insert logisticsToInsert;

        } catch (exception e) {
            throw new MyException(e);
        }
    }
}