main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Site_Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Site_Picklist_Values__c</fullName>
    <inlineHelpText>Values automatically populate Site Picklist Values field on event, survey, and communication objects. Enter values as a comma-separated list.</inlineHelpText>
    <label>Site Picklist Values</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Site_picklist_values__c.field-meta.xml
<CustomField>
    <fullName>Site_picklist_values__c</fullName>
    <inlineHelpText>Field where values for the Site field in the community event registration page can be defined. Values should be comma-separated and configured in the Registration Field Configuration custom metadata settings to look into this field.</inlineHelpText>
    <label>Site Picklist Values</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field determines if a survey is active. Each event/session can only have one active survey at a time.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Survey__c/fields/Campaign_1__c.field-meta.xml
<CustomField>
    <fullName>Campaign_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Custom Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is to be deleted</description>
    <label>Campaign(old)</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Site_Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Site_Picklist_Values__c</fullName>
    <label>Site Picklist Values</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Survey__c/fields/Standalone_Survey_URL__c.field-meta.xml
<CustomField>
    <fullName>Standalone_Survey_URL__c</fullName>
    <description>Generates URL for stand-alone surveys</description>
    <inlineHelpText>Copy and paste the URL to distribute the survey</inlineHelpText>
    <label>Standalone Survey URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Survey_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Surveys (Campaign)</relationshipLabel>
    <relationshipName>CampaignSurveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Code__c.field-meta.xml
<CustomField>
    <fullName>Survey_Code__c</fullName>
    <description>Random code will be generated and will be the identifier for the survey</description>
    <label>Survey Code</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/classes/SurveyTriggerHelper.cls
public with sharing class SurveyTriggerHelper {
    
    public static void checkExistingActiveSurveys(List<Survey__c> surveys){
        Map<Id, Survey__c> eventIdSurveyMap = new Map<Id, Survey__c>();
        for (Survey__c s : surveys){
            eventIdSurveyMap.put(s.Event__c, s);
        }

        Map<Id, Integer> campaignCountChildrenSurveyMap = new Map<Id, Integer>();
        for (Event__c c: [SELECT Id, (SELECT Id FROM Surveys__r WHERE Active__c = TRUE) FROM Event__c WHERE Id IN: eventIdSurveyMap.keySet()]){
            campaignCountChildrenSurveyMap.put(c.Id, c.Surveys__r.size());
        }

        for (Id campaignId : campaignCountChildrenSurveyMap.keySet()){
            if (campaignCountChildrenSurveyMap.get(campaignId) > 0){
                eventIdSurveyMap.get(campaignId).Active__c.addError('This event/session already has an active survey. Each event/session can only have 1 active survey at a time. Please check again.');
            }
        }
    }

    public static void setSurveyCode(List<Survey__c> surveyList){
        final String COMMUNITY_URL = getCommunityURL();

        for (Survey__c survey : surveyList){
            if (String.isBlank(survey.Survey_Code__c) && String.isBlank(survey.Event__c)){
                final String SURVEY_CODE = generateCode();
                survey.Survey_Code__c = SURVEY_CODE;
                survey.Standalone_Survey_URL__c = COMMUNITY_URL + '/s/surveys?code=' + SURVEY_CODE;
            } else if (String.isNotBlank(survey.Event__c)){
                survey.Survey_Code__c = '';
                survey.Standalone_Survey_URL__c = '';
            }
        }
    }

    //XEN REYES CCN-SUR-3235-DV 14 July 2023
    public static void setSiteValues(List<Survey__c> surveyList){

        Set<Id> campaignToGet = new Set<Id>();
        Set<Id> eventToGet = new Set<Id>();
        for (Survey__c survey : surveyList){
            if (String.isBlank(survey.Event__c) && String.isNotBlank(survey.Survey_Campaign__c)){
                campaignToGet.add(survey.Survey_Campaign__c);
            } else if (String.isNotBlank(survey.Event__c)){
                eventToGet.add(survey.Event__c);
            }
        }

        Map<Id, Campaign__c> campaignMap = new Map<Id, Campaign__c>([SELECT Id, Site_Picklist_Values__c FROM Campaign__c WHERE Id IN: campaignToGet]);
        Map<Id, Event__c> eventMap = new Map<Id, Event__c>([SELECT Id, Site_Picklist_Values__c FROM Event__c WHERE Id IN: eventToGet]);

        for (Survey__c survey : surveyList){
            if (String.isBlank(survey.Event__c) && String.isNotBlank(survey.Survey_Campaign__c)){
                survey.Site_Picklist_Values__c = campaignMap.containsKey(survey.Survey_Campaign__c) ? campaignMap.get(survey.Survey_Campaign__c).Site_Picklist_Values__c : null;
            } else if (String.isNotBlank(survey.Event__c)){
                survey.Site_Picklist_Values__c = eventMap.containsKey(survey.Event__c) ? eventMap.get(survey.Event__c).Site_Picklist_Values__c : null;
            }
        }
    }

    private static String generateCode(){
        final String chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz';
        
        String token = '';
        while (token.length() <= 10) {
            Integer idx = Math.mod(Math.abs(Crypto.getRandomInteger()), chars.length());
            token += chars.substring(idx, idx + 1);
        }
        
        return token;
    }

    private static String getCommunityURL(){
        if (!Test.isRunningTest()){
            Network myNetwork = [SELECT Id FROM Network WHERE Name = 'Compass'];
            ConnectApi.Community  myCommunity = ConnectApi.Communities.getCommunity(myNetwork.id);
            return myCommunity.siteUrl ;
        } else {
            return 'some random url';   
        }
    }
}