main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Brief introduction to the campaign that displays under the campaign name on the campaign summary page.</inlineHelpText>
    <label>Campaign Summary Page Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of milestone</description>
    <label>Journey Milestone Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field determines if a survey is active. Each event/session can only have one active survey at a time.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Survey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is to be deleted</description>
    <label>Campaign(old)</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Survey description that will be displayed in the survey page</description>
    <label>Description</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/fields/Disclaimer__c.field-meta.xml
<CustomField>
    <fullName>Disclaimer__c</fullName>
    <label>Disclaimer</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Logo_Image_Id__c.field-meta.xml
<CustomField>
    <fullName>Logo_Image_Id__c</fullName>
    <label>Logo Image Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Survey_Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Surveys (Campaign)</relationshipLabel>
    <relationshipName>CampaignSurveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Logo__c.field-meta.xml
<CustomField>
    <fullName>Survey_Logo__c</fullName>
    <formula>IF(ISBLANK( Survey_Logo_URL__c ) ,&apos;&apos;,  IMAGE( Survey_Logo_URL__c ,&apos;Survey Logo&apos;, 50 ,50))</formula>
    <label>Survey Logo</label>
    <type>Text</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Survey_Logo_URL__c</fullName>
    <formula>IF( ISBLANK( Logo_Image_Id__c ),&apos;&apos;, &apos;/sfc/servlet.shepherd/version/download/&apos;+Logo_Image_Id__c)</formula>
    <label>Survey Logo URL</label>
    <type>Text</type>
</CustomField>

main/default/objects/Survey_Question__c/Survey_Question__c.object-meta.xml
<CustomObject>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey_Question__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Question displayed in the survey</description>
    <label>Description</label>
    <length>12000</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Max_Value__c.field-meta.xml
<CustomField>
    <fullName>Max_Value__c</fullName>
    <label>Max Value</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Min_Value__c.field-meta.xml
<CustomField>
    <fullName>Min_Value__c</fullName>
    <label>Min Value</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <inlineHelpText>For multi-select question, provide more than one choice and it should be on its own line.</inlineHelpText>
    <label>Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <label>Free text</label>
            </value>
            <value>
                <fullName>Range</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
                <label>Radio buttons</label>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Multi-select</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Survey_Question__c/fields/Sorting_Order__c.field-meta.xml
<CustomField>
    <fullName>Sorting_Order__c</fullName>
    <label>Sorting Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Step__c.field-meta.xml
<CustomField>
    <fullName>Step__c</fullName>
    <label>Step</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Survey_Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Question</relationshipLabel>
    <relationshipName>Survey_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/SurveyServicesTest.cls
@isTest
private class SurveyServicesTest {
  @testSetup
  static void setup() {
    String alias = 'tstSysAd';
    Profile profile = [
      SELECT Id
      FROM Profile
      WHERE Name = 'System Administrator'
    ];
    User sysad = new User(
      Username = alias + '@Test.com',
      Alias = alias,
      CommunityNickname = alias,
      TimeZoneSidKey = 'America/Chicago',
      LocaleSidKey = 'en_US',
      EmailEncodingKey = 'ISO-8859-1',
      LanguageLocaleKey = 'en_US',
      FirstName = alias,
      LastName = alias,
      Email = alias + '@Test.com',
      ProfileId = profile.Id,
      Department = 'Test'
    );
    insert sysad;

    System.runAs(sysad) {
      Campaign__c campaignRec = new Campaign__c();
      insert campaignRec;
      
      Compass_Setting__c comp = TestDataFactory.createCSData(1);
      insert comp;
      
      Event__c newEvent = new Event__c();
      newEvent.Name = 'TestEventName';
      newEvent.Campaign__c = campaignRec.Id;
      insert newEvent;

      //create Survey__c
      Survey__c oldSurvey = new Survey__c(
        Name = 'TestSurveyName',
        Active__c = true,
        Disclaimer__c = 'TEST DISCLAIMER',
        Event__c = newEvent.Id
      );
      insert oldSurvey;

      List<Survey_Question__c> oldSurveyQuestions = new List<Survey_Question__c>();
      Survey_Question__c question1 = new Survey_Question__c(
        Question_Type__c = 'Text',
        Description__c = 'Question Number 1',
        Sorting_Order__c = 1,
        Survey__c = oldSurvey.Id
      );
      Survey_Question__c question2 = new Survey_Question__c(
        Question_Type__c = 'Range',
        Description__c = 'Question Number 2',
        Sorting_Order__c = 2,
        Min_Value__c = 1,
        Max_Value__c = 10,
        Step__c = 1,
        Survey__c = oldSurvey.Id
      );
      Survey_Question__c question3 = new Survey_Question__c(
        Question_Type__c = 'Radio',
        Description__c = 'Question Number 3',
        Sorting_Order__c = 3,
        Options__c = 'Option 1\nOption 2\nOption 3\nOption 4',
        Survey__c = oldSurvey.Id
      );
      Survey_Question__c question4 = new Survey_Question__c(
        Question_Type__c = 'Picklist',
        Description__c = 'Question Number 4',
        Sorting_Order__c = 4,
        Options__c = 'Option 1\nOption 2\nOption 3\nOption 4',
        Survey__c = oldSurvey.Id
      );
      oldSurveyQuestions.add(question1);
      oldSurveyQuestions.add(question2);
      oldSurveyQuestions.add(question3);
      oldSurveyQuestions.add(question4);

      insert oldSurveyQuestions;
    }
  }

  //happy path test for SurveyServices.getSurveyDetails()
  static testMethod void test_getSurveyDetails_positive() {
    List<Survey__c> existingSurveys = [
      SELECT
        Id,
        Name,
        Active__c,
        Survey_Campaign__c,
        Disclaimer__c,
        Event__c,
        Logo_Image_Id__c,
        OwnerId,
        Survey_Logo__c,
        Survey_Logo_URL__c,
        (
          SELECT
            Id,
            Name,
            Description__c,
            Max_Value__c,
            Min_Value__c,
            Options__c,
            Question_Type__c,
            Sorting_Order__c,
            Step__c,
            Survey__c
          FROM Survey_Questions__r
        )
      FROM Survey__c
    ];
    Test.startTest();
    Map<String, Object> response = SurveyServices.getSurveyDetails(
      existingSurveys[0].Id
    );
    Test.stopTest();

    System.assertEquals(
      existingSurveys[0].Id,
      ((Survey__c) response.get('data')).Id
    );
  }

  //happy path test for SurveyServices.cloneSurvey()
  static testMethod void test_cloneSurvey_positive() {
    //retrieve sample records
    List<Survey__c> existingSurveys = [
      SELECT
        Id,
        Name,
        Active__c,
        Survey_Campaign__c,
        Disclaimer__c,
        Event__c,
        Logo_Image_Id__c,
        OwnerId,
        Survey_Logo__c,
        Survey_Logo_URL__c,
        (
          SELECT
            Id,
            Name,
            Description__c,
            Max_Value__c,
            Min_Value__c,
            Options__c,
            Question_Type__c,
            Sorting_Order__c,
            Step__c,
            Survey__c
          FROM Survey_Questions__r
        )
      FROM Survey__c
    ];

    Test.startTest();
    Survey__c surveyToClone = existingSurveys[0].clone(false, true);
    surveyToClone.Name = 'Copy of ' + surveyToClone.Name;
    surveyToClone.Active__c = false;
    String message = SurveyServices.cloneSurvey(
      existingSurveys[0].Id,
      surveyToClone,
      false,
      false
    );
    System.debug(message);
    Test.stopTest();

    List<Survey__c> afterCloning = [
      SELECT
        Id,
        Name,
        Active__c,
        Survey_Campaign__c,
        Disclaimer__c,
        Event__c,
        Logo_Image_Id__c,
        OwnerId,
        Survey_Logo__c,
        Survey_Logo_URL__c,
        (
          SELECT
            Id,
            Name,
            Description__c,
            Max_Value__c,
            Min_Value__c,
            Options__c,
            Question_Type__c,
            Sorting_Order__c,
            Step__c,
            Survey__c
          FROM Survey_Questions__r
        )
      FROM Survey__c
    ];

    System.assertEquals(2, afterCloning.size());
    System.assertEquals(surveyToClone.Name, afterCloning[1].Name);
    System.assertEquals(
      true,
      message.contains(SurveyServices.CLONED_SUCCESS_MESSAGE)
    );
  }

  //happy path test for SurveyServices.cloneSurvey()
  static testMethod void test_cloneSurvey_negative1() {
    //retrieve sample records
    List<Survey__c> existingSurveys = [
      SELECT
        Id,
        Name,
        Active__c,
        Survey_Campaign__c,
        Disclaimer__c,
        Event__c,
        Logo_Image_Id__c,
        OwnerId, //Milestone__c,
        Survey_Logo__c,
        Survey_Logo_URL__c,
        (
          SELECT
            Id,
            Name,
            Description__c,
            Max_Value__c,
            Min_Value__c,
            Options__c,
            Question_Type__c,
            Sorting_Order__c,
            Step__c,
            Survey__c
          FROM Survey_Questions__r
        )
      FROM Survey__c
    ];

    Test.startTest();
    Survey__c surveyToClone = existingSurveys[0];
    String message = SurveyServices.cloneSurvey(
      surveyToClone.Id,
      surveyToClone,
      true,
      true
    );
    Test.stopTest();

    List<Survey__c> afterCloning = [
      SELECT
        Id,
        Name,
        Active__c,
        Survey_Campaign__c,
        Disclaimer__c,
        Event__c,
        Logo_Image_Id__c,
        OwnerId, //Milestone__c,
        Survey_Logo__c,
        Survey_Logo_URL__c,
        (
          SELECT
            Id,
            Name,
            Description__c,
            Max_Value__c,
            Min_Value__c,
            Options__c,
            Question_Type__c,
            Sorting_Order__c,
            Step__c,
            Survey__c
          FROM Survey_Questions__r
        )
      FROM Survey__c
    ];

    //System.assertEquals(false, message.contains('Insert failed.'));
  }

  //happy path test for SurveyServices.test_getObjectAndFieldPrefix()
  static testMethod void test_fetchObjectAndFieldPrefix() {
    Test.startTest();
    SurveyServices.PrefixObjectAndFieldWrapper wrapper = SurveyServices.fetchObjectAndFieldPrefix();

    System.assert(String.isBlank(wrapper.errorMsg));
    Test.stopTest();
  }
}