main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/classes/CampaignHierarchyPage.cls
global with sharing class CampaignHierarchyPage {
    
    @AuraEnabled     
    public static String objectType(Id recordIdVal){
        Schema.SObjectType objType = recordIdVal.getSobjectType(); 
        return String.valueOf(objType);
        //return objType != null ? String.valueOf(objType).split('__', 2)[1] : '';
    }
    
    @AuraEnabled     
    public static List<Campaign__c> searchForCampaign(Id recordIdVal){
        String objType = objectType(recordIdVal); 
        List<Campaign__c> campList = new List<Campaign__c>();
        if(String.valueOf(objType) == 'Campaign__c'){
            if(FlsUtils.isAccessible('Campaign__c', new List<String>{'Name'})){
                campList = [SELECT Id, Name FROM Campaign__c WHERE Id =: recordIdVal];
            }
        }

        return campList;
    }
    
    @AuraEnabled     
    public static List<Event__c> searchForEvent(Id recordIdVal){
        String objType = objectType(recordIdVal); 
        List<Event__c> eventList;

        if(FlsUtils.isAccessible('Event__c', new List<String>{'Name','Campaign__c','Start_Date_Time__c','End_Date_Time__c','Time_Zone__c'})){
            if(String.valueOf(objType) == 'Campaign__c'){
                eventList = [SELECT Id, Name, Campaign__c, Start_Date_Time__c, End_Date_Time__c, Time_Zone__c FROM Event__c WHERE Campaign__c =: recordIdVal];
            }
            else if(String.valueOf(objType) == 'Event__c'){
                eventList = [SELECT Id, Name, Campaign__c, Start_Date_Time__c, End_Date_Time__c, Time_Zone__c FROM Event__c WHERE Id =: recordIdVal];
            }  
        }

        return eventList;
    }
    
    @AuraEnabled 
    public static List<Session__c> searchForSession(List<Id> eventList, Id recordIdVal){

        List<Session__c> sessionList;

        if((FlsUtils.isAccessible('Event__c', new List<String>{'Campaign__c'}))  
                && FlsUtils.isAccessible('Session__c', new List<String>{'Name', 'Event__c', 'Start_Date_Time__c','End_Date_Time__c','Time_Zone__c'})){
            if(!eventList.isEmpty()){
                sessionList = [SELECT Id, Name, Event__c, Event__r.Campaign__c, Start_Date_Time__c, End_Date_Time__c, Time_Zone__c FROM Session__c WHERE Event__c IN: eventList];
            }
            else if(recordIdVal != null){
                sessionList = [SELECT Id, Name, Event__c, Event__r.Campaign__c, Start_Date_Time__c, End_Date_Time__c, Time_Zone__c FROM Session__c WHERE Id =: recordIdVal];
            } 
        }

        return sessionList;
    }
}