main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Person</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/MS_Teams_Id__c.field-meta.xml
<CustomField>
    <fullName>MS_Teams_Id__c</fullName>
    <description>MS Team Integration - Meeting Id</description>
    <label>MS Teams Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/classes/AzureAPITest.cls
@isTest
private class AzureAPITest {

    @TestSetup
    static void createTestData() {
        Campaign__c camp = TestDataFactory.createCampaign(1);
        insert camp;
        Event__c event = TestDataFactory.createEvent('Test Event', camp.Id);
        event.Event_Type__c = 'Virtual';
        insert event;
    }


    @isTest
    static void testAzureAPIBatch() {

		Test.startTest();
        Event__c event = [SELECT Id FROM Event__c WHERE Event_Type__c = 'Virtual' LIMIT 1];
        Session__c sess = TestDataFactory.createSession('Test Session One',event.Id);
        sess.Start_Date_Time__c = System.now();
        sess.End_Date_Time__c = System.now().addHours(1);
        sess.Time_Zone__c = 'AFT';
        Test.setMock(HttpCalloutMock.class, new AzureAPIMockHttpResponseGenerator());
        insert sess;
        System.assertEquals(sess.Time_Zone__c , 'AFT');
        Test.stopTest();
    } 

    @isTest
    static void testAzureAPIBatchMock() {

		Test.startTest();
        Event__c event = [SELECT Id FROM Event__c WHERE Event_Type__c = 'Virtual' LIMIT 1];
        Session__c sess = TestDataFactory.createSession('Test Session One',event.Id);
        sess.Start_Date_Time__c = System.now();
        sess.End_Date_Time__c = System.now().addHours(1);
        sess.Time_Zone__c = 'AFT';
        insert sess;
        Test.setMock(HttpCalloutMock.class, new AzureAPIMockHttpResponseGenerator());
        Database.executeBatch(new AzureAPIBatch('POST',[SELECT Id FROM Session__c]));
        System.assertEquals(sess.Time_Zone__c , 'AFT');
        Test.stopTest();
    } 

    @isTest
    static void testAzureAPIEvent() {

		Test.startTest();
        Event__c event = TestDataFactory.createEvent('Test Event', [SELECT Id FROM Campaign__c LIMIT 1].Id);
        event.Event_Type__c = 'In-Person';
        insert event;
        Session__c sess = TestDataFactory.createSession('Test Session One',event.Id);
        sess.Start_Date_Time__c = System.now();
        sess.End_Date_Time__c = System.now().addHours(1);
        sess.Time_Zone__c = 'AFT';
        insert sess;

        event = [SELECT Id FROM Event__c WHERE Event_Type__c = 'In-Person' LIMIT 1];
        event.Event_Type__c = 'Virtual';
        update event;
        
        Test.setMock(HttpCalloutMock.class, new AzureAPIMockHttpResponseGenerator());
        Database.executeBatch(new AzureAPIBatch('POST',[SELECT Id FROM Session__c]));
        System.assertEquals(sess.Time_Zone__c , 'AFT');
        Test.stopTest();
    } 

    @isTest
    static void testAzureAPIGetMeeting() {
        Event__c event = TestDataFactory.createEvent('Test Event', [SELECT Id FROM Campaign__c LIMIT 1].Id);
        event.Event_Type__c = 'In-Person';
        insert event;
        Session__c sess = TestDataFactory.createSession('Test Session One',event.Id);
        sess.MS_Teams_Id__c = 'MSplMmMxNzBmMy0yZjNhLTQyM2YtODU1Yy1mMmQzZDNlZGYyOGUqMCoqMTk6bWVldGluZ19NbVF6WVdRelptRXRPVEZrTlMwME5tWTJMV0ZqWldFdE5HWmlOREZtTkdJME5UaGxAdGhyZWFkLnYy';
        sess.Start_Date_Time__c = System.now();
        sess.End_Date_Time__c = System.now().addHours(1);
        sess.Time_Zone__c = 'AFT';
        insert sess;

        event = [SELECT Id FROM Event__c WHERE Event_Type__c = 'In-Person' LIMIT 1];
        event.Event_Type__c = 'Virtual';
        update event;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new AzureAPIMockHttpResponseGenerator());
        AzureAPI.getMeetingUrl(sess);
        Test.stopTest();
    }
}