main/default/objects/Adhoc_Journey_Assignment__c/Adhoc_Journey_Assignment__c.object-meta.xml
<CustomObject>
    <description>Milestone Builder for Multiple Journeys</description>
    <label>Journey Assignment</label>
    <nameField>
        <displayFormat>JA{000000}</displayFormat>
        <label>Journey Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Adhoc_Journey_Assignment__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LInks to the Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Journey_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Adhoc_Journey_Assignment__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Journey_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Adhoc_Journey_Assignment__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Survey</description>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipName>Journey_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey_Response__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Response__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/SurveyResponseTriggerHandler.cls
/*******************************************************************************************
  * @name: SessionTriggerHandler
  * @author: Von Pernicia
  * @created: 03-02-2022
  * @description: Handler for all the logic of the trigger for the Survey Response object
*********************************************************************************************/
public class SurveyResponseTriggerHandler {
    public static boolean bPreventAI = false;
    public static boolean bPreventAU = false;

    /*******************************************************************************************
    * @author: Von Pernicia
    * @created: 03-02-2022
    * @description: logic after insert
    *
    * Changes (version)
    * -------------------------------------------------------------------------------------------
    *             No.   Date(dd-mm-yyy)   Author                Description
    *             ----  ---------------   --------------------  ---------------------------------
    * @version    1.0   03-02-2022        Von Pernicia          [CCN-496] Consolidate list of journey upon creation of the record to update Participant Milestone Metrics
    *********************************************************************************************/
    public static void onAfterInsert(List<Survey_Response__c> newSurveryRespList){

            
        Map<String, List<String>> journeyIdMap = new Map<String, List<String>>();
       
        for (Adhoc_Journey_Assignment__c adhoc: [SELECT id, Journey__c 
                                                FROM Adhoc_Journey_Assignment__c 
                                                WHERE Event__c in (SELECT Event__c 
                                                                    FROM Survey_Response__c 
                                                                    WHERE Id in: newSurveryRespList 
                                                                    AND Contact__c != NULL 
                                                                    AND Survey__r.Milestone__c = TRUE)])

        {
            if (!journeyIdMap.containsKey(adhoc.Journey__c)) {
                List<String> contactIdList = new List<String>();
                for (Survey_Response__c participant: newSurveryRespList) {
                    contactIdList.add(participant.Contact__c);
                }
                journeyIdMap.put(adhoc.Journey__c, contactIdList);
            }
        }

        for (Adhoc_Journey_Assignment__c adhoc: [SELECT id, Journey__c 
                                                FROM Adhoc_Journey_Assignment__c 
                                                WHERE Survey__c in (SELECT Survey__c 
                                                                    FROM Survey_Response__c 
                                                                    WHERE Id in: newSurveryRespList 
                                                                    AND Contact__c != NULL 
                                                                    AND Survey__r.Milestone__c = TRUE)])

        {
            if (!journeyIdMap.containsKey(adhoc.Journey__c)) {
                List<String> contactIdList = new List<String>();
                for (Survey_Response__c participant: newSurveryRespList) {
                    contactIdList.add(participant.Contact__c);
                }
                journeyIdMap.put(adhoc.Journey__c, contactIdList);
            }
        }


        if (journeyIdMap.size() > 0) {
            BatchProcessorUtility.insertBatchRecord(journeyIdMap, 'BatchSyncParticipantMilestoneMetric','SurveyResponseTriggerHandler');
        }                          

    }
}