main/default/objects/Adhoc_Journey_Assignment__c/Adhoc_Journey_Assignment__c.object-meta.xml
<CustomObject>
    <description>Milestone Builder for Multiple Journeys</description>
    <label>Journey Assignment</label>
    <nameField>
        <displayFormat>JA{000000}</displayFormat>
        <label>Journey Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Adhoc_Journey_Assignment__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>LInks to the Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Journey_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Adhoc_Journey_Assignment__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Journey_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Email_Template_Invitation_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Invitation_Id__c</fullName>
    <label>Email Template - Invitation Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/fields/Email_Template_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Registration_Id__c</fullName>
    <label>Email Template - Registration Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Journey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;For Review&quot;</defaultValue>
    <description>Status of the Journey</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Member_Status</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Participant__c/recordTypes/Participant.recordType-meta.xml
<RecordType>
    <fullName>Participant</fullName>
    <active>true</active>
    <label>Participant</label>
</RecordType>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Campaign End Date</description>
    <formula>Campaign__r.EndDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates Milestone</description>
    <label>Milestone</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/globalValueSets/Member_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Attended</fullName>
    </customValue>
    <customValue>
        <fullName>Catch-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Responded</fullName>
        <isActive>false</isActive>
        <label>Responded</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <isActive>false</isActive>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <masterLabel>Member Status</masterLabel>
</GlobalValueSet>

main/default/classes/SessionParticipantTriggerTest.cls
@isTest
private class SessionParticipantTriggerTest {
    @testSetup
    static void setup(){
        List<Apex_Trigger_Switch__c> atsList = new List<Apex_Trigger_Switch__c>();
        Apex_Trigger_Switch__c aps_sp = new Apex_Trigger_Switch__c();
        aps_sp.Name = 'SessionParticipantTrigger';
        aps_sp.Active__c = true;
        atsList.add(aps_sp);
        
        Apex_Trigger_Switch__c aps_event = new Apex_Trigger_Switch__c();
        aps_event.Name = 'EventTrigger';
        aps_event.Active__c = false;
        atsList.add(aps_event);
        
        insert atsList;
        
        Contact con1 = new Contact();
        con1.FirstName = 'Test Contact';
        con1.LastName = 'Record 1';
        con1.Email = 'testemail@testemail.com';
        insert con1;
        
        //Campaign  
        List<Campaign__c> campList = new List<Campaign__c>();
        Campaign__c camp1 = new Campaign__c();
        camp1.Name = 'Test Campaign 001';
        campList.add(camp1);
        
        insert campList;
   
        Journey__c testJourney = new Journey__c();
        testJourney.Name = 'Test Journey';
        testJourney.Campaign__c = campList[0].Id;
        testJourney.Status__c = 'Approved';
        testJourney.End_Date__c = System.now().addYears(1).date();
        insert testJourney;

        EmailTemplate e = new EmailTemplate (developerName = 'test', FolderId = UserInfo.getUserId(), TemplateType= 'Text', Name = 'test', IsActive = true);
        system.runAs( new User(Id = UserInfo.getUserId())){
        	insert e;
        }
        
        Compass_Setting__c compSetting = new Compass_Setting__c();
        compSetting.Name = 'Default Settings';
        compSetting.Email_Sender_Id__c = '123';
        compSetting.Email_Sender_Name__c = 'NAME';
        compSetting.Email_Template_Invitation_Id__c = e.Id;
        compSetting.Email_Template_Registration_Id__c = e.Id;
        insert compSetting;
        
        OrgWideEmailAddress owea = [SELECT Id, DisplayName FROM OrgWideEmailAddress WHERE DisplayName = 'Edera' LIMIT 1];
        
        //Event
        List<Event__c> eventList = new List<Event__c>();
        Event__c event1 = new Event__c();
        event1.Name = 'Test Event 001';
        event1.Campaign__c = camp1.Id;
        event1.Email_Sender_Id__c = owea.Id;
        event1.Email_Sender_Name__c = owea.DisplayName;
        event1.Milestone__c = true;
        event1.IsActive__c = true;
        event1.Start_Date_Time__c = system.today();
        event1.End_Date_Time__c = system.today() + 1;
        event1.Time_Zone__c = 'AKDT';
        event1.Session_Calendar_Invite_Delivery__c = 'Send on session confirmation';
        eventList.add(event1);
        
        Event__c event2 = new Event__c();
        event2.Campaign__c = camp1.Id;
        event2.Name = 'Test Event 002';
        event2.Milestone__c = true;
        event2.IsActive__c = true;
        event2.Start_Date_Time__c = system.today();
        event2.End_Date_Time__c = system.today() + 1;
         event2.Time_Zone__c = 'AKDT';
        event2.Session_Calendar_Invite_Delivery__c = 'Send on session registration';
        eventList.add(event2);
        
        insert eventList;

        Event__c event01 = [SELECT Id FROM Event__c WHERE Name ='Test Event 001' LIMIT 1]; 
       
        Adhoc_Journey_Assignment__c journeyAssignment = new Adhoc_Journey_Assignment__c (
            Journey__c = testJourney.id,
            Event__c = event01.Id,
            Type__c = 'Event'
        );
        insert journeyAssignment;
        
        //Session
        List<Session__c> sessionList = new List<Session__c>();
        Session__c session1 = new Session__c();
        session1.Name = 'Test Session 001';
        session1.Event__c = event1.Id;
        session1.Time_Zone__c = 'AKDT';
        session1.Start_Date_Time__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        session1.End_Date_Time__c = DateTime.newInstance(2020, 08, 29, 10, 30, 0);
        sessionList.add(session1);
        
        Session__c session2 = new Session__c();
        session2.Name = 'Test Session 002';
        session2.Event__c = event2.Id;

        sessionList.add(session2);
        
        insert sessionList;
        
        
        //Session Participant
        List<Session_Participant__c> sessionParticipantList = new List<Session_Participant__c>();
        Session_Participant__c sp = new Session_Participant__c();
        sp.Session__c = session1.Id;
		sp.Event__c = event1.Id;
		sp.Contact__c = con1.Id;
        sp.Status__c = 'Attended';
        sp.Invitation_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sp.Registration_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sessionParticipantList.add(sp);
        
        insert sessionParticipantList;
        
        
    }
    
    @isTest private static void calendarInviteTest(){
        Session__c session1 = [SELECT Id FROM Session__c WHERE Name ='Test Session 001' LIMIT 1];
        Event__c event1 = [SELECT Id FROM Event__c WHERE Name ='Test Event 001' LIMIT 1]; 
        Contact con1 = [SELECT Id FROM Contact WHERE FirstName = 'Test Contact' LIMIT 1];
        
        //Session Participant
        List<Session_Participant__c> sessionParticipantList = new List<Session_Participant__c>();
        Session_Participant__c sp = new Session_Participant__c();
        sp.Session__c = session1.Id;
		sp.Event__c = event1.Id;
		sp.Contact__c = con1.Id;
        sp.Status__c = 'Registered';
        sp.Invitation_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sp.Registration_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sessionParticipantList.add(sp);
        
        Test.startTest();
        insert sessionParticipantList;
        Test.stopTest();
    }
    
    @IsTest static void sendEmailToSessionParticipant(){
        Session__c session1 = [SELECT Id FROM Session__c WHERE Name ='Test Session 001' LIMIT 1];
        Event__c event1 = [SELECT Id FROM Event__c WHERE Name ='Test Event 001' LIMIT 1]; 
        Contact con1 = [SELECT Id FROM Contact WHERE FirstName = 'Test Contact' LIMIT 1];
        
        Participant__c participantData = new Participant__c();
        participantData.Event__c = event1.Id;
        participantData.Member_Contact__c = con1.Id;
        participantData.Status__c = 'Registered';
        insert participantData;
        
        //Session Participant
        List<Session_Participant__c> sessionParticipantList = new List<Session_Participant__c>();
        Session_Participant__c sp = new Session_Participant__c();
        sp.Session__c = session1.Id;
		sp.Event__c = event1.Id;
		sp.Contact__c = con1.Id;
        sp.Status__c = 'Attended';
        sp.Participant__c = participantData.Id;
        sp.Invitation_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sp.Registration_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sessionParticipantList.add(sp);
        
        Test.startTest();
        insert sessionParticipantList;
        Test.stopTest();
    }
    
    @isTest static void onAfterUpdate() {
        Session__c session1 = [SELECT Id FROM Session__c WHERE Name ='Test Session 001' LIMIT 1];
        Event__c event1 = [SELECT Id FROM Event__c WHERE Name ='Test Event 001' LIMIT 1]; 
        Contact con1 = [SELECT Id FROM Contact WHERE FirstName = 'Test Contact' LIMIT 1];
        
        List<Participant__c> participantDataList = new List<Participant__c>();
        Participant__c participantData = new Participant__c();
        participantData.Event__c = event1.Id;
        participantData.Member_Contact__c = con1.Id;
        participantData.Status__c = 'Registered';
        participantDataList.add(participantData);
        
        Participant__c participantData2 = new Participant__c();
        participantData2.Event__c = event1.Id;
        participantData2.Member_Contact__c = con1.Id;
        participantData2.Status__c = 'Registered';
        participantDataList.add(participantData2);
        insert participantDataList;
        
        //Session Participant
        List<Session_Participant__c> sessionParticipantList = new List<Session_Participant__c>();
        Session_Participant__c sp = new Session_Participant__c();
        sp.Session__c = session1.Id;
		sp.Event__c = event1.Id;
		sp.Contact__c = con1.Id;
        sp.Status__c = 'Attended';
        sp.Participant__c = participantData.Id;
        sp.Invitation_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sp.Registration_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sessionParticipantList.add(sp);
        
        Session_Participant__c sp2 = new Session_Participant__c();
        sp2.Session__c = session1.Id;
		sp2.Event__c = event1.Id;
		sp2.Contact__c = con1.Id;
        sp2.Status__c = 'Confirmed';
        sp2.Participant__c = participantData2.Id;
        sp2.Invitation_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sp2.Registration_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sessionParticipantList.add(sp2);       
        
        Session_Participant__c sp3 = new Session_Participant__c();
        sp3.Session__c = session1.Id;
		sp3.Event__c = event1.Id;
		sp3.Contact__c = con1.Id;
        sp3.Status__c = 'Declined';
        sp3.Participant__c = participantData2.Id;
        sp3.Invitation_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sp3.Registration_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sessionParticipantList.add(sp3);
        
        Test.startTest();
        insert sessionParticipantList;
        
        Session_Participant__c spUpdated = [SELECT Id, Status__c FROM Session_Participant__c WHERE Status__c = 'Attended' LIMIT 1];
        spUpdated.Status__c = 'Confirmed';
        update spUpdated;
        Test.stopTest();
    }
    
    @isTest static void onBeforeUpdate() {
        Session__c session1 = [SELECT Id FROM Session__c WHERE Name ='Test Session 001' LIMIT 1];
        Event__c event1 = [SELECT Id FROM Event__c WHERE Name ='Test Event 001' LIMIT 1]; 
        Contact con1 = [SELECT Id FROM Contact WHERE FirstName = 'Test Contact' LIMIT 1];
        
        List<Participant__c> participantDataList = new List<Participant__c>();
        Participant__c participantData = new Participant__c();
        participantData.Event__c = event1.Id;
        participantData.Member_Contact__c = con1.Id;
        participantData.Status__c = 'Registered';
        participantDataList.add(participantData);
        
        Participant__c participantData2 = new Participant__c();
        participantData2.Event__c = event1.Id;
        participantData2.Member_Contact__c = con1.Id;
        participantData2.Status__c = 'Registered';
        participantDataList.add(participantData2);
        insert participantDataList;
        
        //Session Participant
        List<Session_Participant__c> sessionParticipantList = new List<Session_Participant__c>();
        Session_Participant__c sp = new Session_Participant__c();
        sp.Session__c = session1.Id;
		sp.Event__c = event1.Id;
		sp.Contact__c = con1.Id;
        sp.Status__c = 'Attended';
        sp.Participant__c = participantData.Id;
        sp.Invitation_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sp.Registration_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sessionParticipantList.add(sp);
        
        Test.startTest();
        insert sessionParticipantList;
        
        Session_Participant__c spUpdated = [SELECT Id, Status__c FROM Session_Participant__c WHERE Status__c = 'Attended' LIMIT 1];
        spUpdated.Status__c = 'Declined';
        update spUpdated;
        Test.stopTest();
    }
    
    @isTest static void returnTrigger() {
        Session__c session1 = [SELECT Id FROM Session__c WHERE Name ='Test Session 001' LIMIT 1];
        Event__c event1 = [SELECT Id FROM Event__c WHERE Name ='Test Event 001' LIMIT 1]; 
        Contact con1 = [SELECT Id FROM Contact WHERE FirstName = 'Test Contact' LIMIT 1];
        
        Participant__c participantData = new Participant__c();
        participantData.Event__c = event1.Id;
        participantData.Member_Contact__c = con1.Id;
        participantData.Status__c = 'Registered';
        insert participantData;
        
        Apex_Trigger_Switch__c aps_sp = [SELECT Id, Active__c FROM Apex_Trigger_Switch__c WHERE Name = 'SessionParticipantTrigger'];
        aps_sp.Active__c = false;

        Session_Participant__c sp = new Session_Participant__c();
        sp.Session__c = session1.Id;
		sp.Event__c = event1.Id;
		sp.Contact__c = con1.Id;
        sp.Status__c = 'Attended';
        sp.Participant__c = participantData.Id;
        sp.Invitation_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        sp.Registration_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        
        Test.startTest();
        update aps_sp;
        insert sp;
        
        Test.stopTest();
    }
    
}