main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Journey</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey_Participant__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Journey_Participant__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Journey_Participant__c/fields/Journey_URL__c.field-meta.xml
<CustomField>
    <fullName>Journey_URL__c</fullName>
    <description>Journey URL</description>
    <label>Journey URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of milestone</description>
    <label>Journey Milestone Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone__c/Participant_Milestone__c.object-meta.xml
<CustomObject>
    <description>All milestones of participants</description>
    <label>Participant Milestone</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Participant Milestone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <label>Journey Milestone Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey Participant</description>
    <label>Participant</label>
    <referenceTo>Journey_Participant__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Milestone</description>
    <label>Journey Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/BatchCreateParticipantMilestones.cls
/*******************************************************************************
 * @author       Angelo Rivera
 * @date         14.Jan.2022
 * @description  Creates Participant Milestones
 * @revision     14.Jan.2022 - APRivera - Created
 *******************************************************************************/
global class BatchCreateParticipantMilestones implements Database.Batchable<SObject>, Database.Stateful{

    public String strQuery = '';
    public Map<Id, Journey__c> mapJourneysByIds = new Map<Id, Journey__c>();
    public String strJourneyCommunityURL = '';
    public Map<Id, List<Milestone__c>> mapMilestonesByJourneyIds = new Map<Id, List<Milestone__c>>();
    public Set<Id> setIds = new Set<Id>();
    public static List<Participant_Milestone__c> lstUserMilestonesToInsert = new List<Participant_Milestone__c>();

    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        try {
            strQuery = 'SELECT Id, Journey__c, Description__c, Contact__c, Journey_URL__c, CreatedDate ' +
                    'FROM Journey_Participant__c ' +
                    'WHERE Id IN: setIds ORDER BY CreatedDate ASC ';
//                    'LIMIT ' + String.valueOf(Limits.getLimitQueryRows() - Limits.getQueryRows());
            System.debug(LoggingLevel.DEBUG, 'QUERY: ' + strQuery);
            return Database.getQueryLocator(strQuery);
        } catch(Exception e) {
            return null;
        }
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope)
    {
        List<Journey_Participant__c> lstJourneyParticipants = (List<Journey_Participant__c>)scope;

        for (Journey_Participant__c userJourney : lstJourneyParticipants) {
            //retrieves Journey details to be copied over to user journey
            Journey__c journey = mapJourneysByIds.get(userJourney.Journey__c);

            List<Milestone__c> lstMilestones = new List<Milestone__c>();
            if(mapMilestonesByJourneyIds.containsKey(journey.Id)) lstMilestones.addAll(mapMilestonesByJourneyIds.get(journey.Id));
            //checks if there are Milestones from the Journey Template
            if (!lstMilestones.isEmpty()) {
                JourneyParticipantServices.createUserMilestones(lstMilestones, userJourney, lstUserMilestonesToInsert );
            }
        }
        try {
            if (!lstUserMilestonesToInsert.isEmpty()) {
                Database.insert(lstUserMilestonesToInsert);
            }
        } catch (Exception ex) {
            System.debug(LoggingLevel.DEBUG,'!@# ERROR IN INSERTING Participant_Milestone__c: ' + ex.getMessage());
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
}