main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Milestone</description>
    <label>Journey Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attestation</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

main/default/objects/Participant_Milestone__c/Participant_Milestone__c.object-meta.xml
<CustomObject>
    <description>All milestones of participants</description>
    <label>Participant Milestone</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Participant Milestone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey Participant</description>
    <label>Participant</label>
    <referenceTo>Journey_Participant__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Milestone</description>
    <label>Journey Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <description>Tracks the Milestone Progress</description>
    <formula>IF( Checkpoint__c , Checkpoint_Progress__c ,  Milestone_Progress__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/Participant_Milestone_Metric__c.object-meta.xml
<CustomObject>
    <description>Tracks the progress of participants milestone</description>
    <label>Participant Milestone Metric</label>
    <nameField>
        <displayFormat>PMM-{0000000}</displayFormat>
        <label>Participant Milestone Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestone Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone_Metric__c/fields/Metric_Used__c.field-meta.xml
<CustomField>
    <fullName>Metric_Used__c</fullName>
    <description>Metric Used</description>
    <label>Metric Used</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>Participants Milestone</description>
    <label>Milestone</label>
    <referenceTo>Participant_Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestone Metrics</relationshipLabel>
    <relationshipName>Participant_Milestone_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/BatchCreateParticipantMilestoneMetrics.cls
/*******************************************************************************
 * @author       Angelo Rivera
 * @date         14.Jan.2022
 * @description  Creates Participant Milestone Metrics
 * @revision     14.Jan.2022 - APRivera - Created
 *******************************************************************************/
global class BatchCreateParticipantMilestoneMetrics implements Database.Batchable<SObject>, Database.Stateful{

    public String strQuery;
    public static List<Participant_Milestone_Metric__c> lstUserMilestoneMetrics = new List<Participant_Milestone_Metric__c>();
    public Map<Id, Map<String, List<String>>> mapMilestoneMetricByTypeByJourneyId = new Map<Id, Map<String, List<String>>>();
    public Set<Id> setJourneyIds = new Set<Id>();
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        try {
            strQuery = 'SELECT Id, CreatedDate, Journey__c, Type__c, Journey__r.Journey__c ' +
                    'FROM Participant_Milestone__c ' +
                    'WHERE Progress__c = null AND Journey__r.Journey__c IN: setJourneyIds ORDER BY CreatedDate ASC '; //+
//                    'LIMIT ' + String.valueOf(Limits.getLimitQueryRows() - Limits.getQueryRows());
            System.debug(LoggingLevel.DEBUG, 'QUERY: ' + strQuery);
            return Database.getQueryLocator(strQuery);
        } catch(Exception e) {
            return null;
        }
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope)
    {
        Set<Id> setUserJourneyId = new Set<Id>();
        Map<Id, Id> mapJourneyIdsByUserJourneyIds = new Map<Id, Id>();
        List<Participant_Milestone__c> lstUserMilestones = (List<Participant_Milestone__c>)scope;
        for(Participant_Milestone__c pm : lstUserMilestones){
            setUserJourneyId.add(pm.Journey__c);
        }
        mapJourneyIdsByUserJourneyIds = JourneyParticipantServices.getJourneyIds(setUserJourneyId);
        for (Participant_Milestone__c userMilestone : lstUserMilestones) {
            Id journeyId = mapJourneyIdsByUserJourneyIds.get(userMilestone.Journey__c);// <Journey Participants Id , Journey Record>
            if (mapMilestoneMetricByTypeByJourneyId.containsKey(journeyId)) {
                Map<String, List<String>> mapMilestoneMetricByType = mapMilestoneMetricByTypeByJourneyId.get(journeyId);
                if (mapMilestoneMetricByType.containsKey(userMilestone.Type__c)) {
                    for (String strField : mapMilestoneMetricByType.get(userMilestone.Type__c)) {
                        Participant_Milestone_Metric__c umm = new Participant_Milestone_Metric__c();
                        umm.Metric_Used__c = strField;
                        umm.Milestone__c = userMilestone.Id;
                        lstUserMilestoneMetrics.add(umm);
                    }
                }
            }
        }

        try {
            if (!lstUserMilestoneMetrics.isEmpty()) {
                Database.insert(lstUserMilestoneMetrics);
            }
        } catch (Exception ex) {
            System.debug( LoggingLevel.DEBUG, '!@# ERROR IN INSERTING Participant_Milestone_Metric__c: ' + ex.getMessage() );
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
}