main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Journey</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Journey__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of milestone</description>
    <label>Journey Milestone Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Milestone__c/fields/Display_In_Dashboard__c.field-meta.xml
<CustomField>
    <fullName>Display_In_Dashboard__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Child Card on Dashboard</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Milestone__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates Active milestone</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/fields/Milestone_URL__c.field-meta.xml
<CustomField>
    <fullName>Milestone_URL__c</fullName>
    <description>URL for Milestone</description>
    <label>Journey Milestone Card Link</label>
    <type>Url</type>
</CustomField>

main/default/objects/Milestone__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the milestone tagged as checkpoint</description>
    <label>Checkpoint Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone__c.Journey__c</field>
            <operation>equals</operation>
            <valueField>$Source.Journey__c</valueField>
        </filterItems>
        <filterItems>
            <field>Milestone__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Checkpoint</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Milestones &amp; Checkpoints</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Milestone__c/fields/Parent_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Parent_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Milestone</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.Journey__c</field>
            <operation>equals</operation>
            <valueField>$Source.Journey__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Milestones &amp; Checkpoints (Parent Milestone)</relationshipLabel>
    <relationshipName>Milestones_Checkpoints</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Milestone__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Indicates sort order of Milestone</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

main/default/classes/MilestoneTriggerHandler.cls
/**
 * Created by angelorivera on 10/12/20.
 */

public class MilestoneTriggerHandler {
  /*******************************************************************************
   * @description  handles all after insert events.
   * @param        newMap - Trigger.newMap context variable
   * @revision     10.09.2020 - APRivera - Created
   *******************************************************************************/
  public static void handleAfterInsert(Map<Id, Milestone__c> newMap) {
    processMilestones(null, newMap, 'INSERT');
  }

  /*******************************************************************************
   * @description  handles all after update events.
   * @param        newMap - Trigger.newMap context variable
   * @revision     31.03.2021 - APRivera - Created
   *******************************************************************************/
  public static void handleBeforeUpdate(Map<Id, Milestone__c> newMap) {
    //processMilestones(null, newMap, 'UPDATE');
  }
  /*******************************************************************************
   * @description  handles all after update events.
   * @param        oldMap - Trigger.oldMap context variable
   * @param        newMap - Trigger.newMap context variable
   * @revision     31.03.2021 - APRivera - Created
   *******************************************************************************/
  public static void handleAfterUpdate(
          Map<Id, Milestone__c> oldMap,
          Map<Id, Milestone__c> newMap
  ) {
    processMilestones(oldMap, newMap, 'UPDATE');
  }

  /*******************************************************************************
   * @description  handles all after delete events.
   * @param        oldMap - Trigger.oldMap context variable
   * @revision     10.09.2020 - APRivera - Created
   *******************************************************************************/
  public static void handleBeforeDelete(Map<Id, Milestone__c> oldMap) {
    processMilestones(oldMap, null, 'DELETE');
  }

  /*******************************************************************************
   * @author       Angelo Rivera
   * @date         10.10.2020
   * @description  Process Milestones
   * @param        oldMap - map of the old records
   * @param        newMap - map of the new records
   * @param        evt - trigger event
   * @revision     10.10.2020 - APRivera - Created
   * @revision     24.12.2021 - Dbrinas - Updated/added Parent Milestone and Display field
   *******************************************************************************/
  public static void processMilestones(Map<Id, Milestone__c> oldMap, Map<Id, Milestone__c> newMap, String evt ) {
    List<Milestone__c> lstMilestones = new List<Milestone__c>();
    Set<Id> setJourneyIds = new Set<Id>();
    Set<Id> setMilestoneIds = new Set<Id>();
    Set<Decimal> setSortOrder = new Set<Decimal>();

    if (evt == 'INSERT') {
      for (Milestone__c mStones : newMap.values()) {
        if (mStones.Journey__c != null) {
          setJourneyIds.add(mStones.Journey__c);
          lstMilestones.add(mStones);
          setMilestoneIds.add(mStones.Id);
        }
      }
      if (!setJourneyIds.isEmpty()) JourneyParticipantServices.processNewMilestones(setJourneyIds,setMilestoneIds);
    } else if (evt == 'DELETE') {
      for (Milestone__c mStones : oldMap.values()) {
        if (mStones.Journey__c != null) {
          System.debug('!@#$ mStones ' + mStones);
          setJourneyIds.add(mStones.Journey__c);
          lstMilestones.add(mStones);
          setSortOrder.add(mStones.Sort_Order__c);
        }
      }
      if (!setJourneyIds.isEmpty()) {
        BatchDeleteParticipantMilestones batchObj = new  BatchDeleteParticipantMilestones();
        batchObj.setJourneyIds = setJourneyIds;
        batchObj.lstMilestones = lstMilestones;
        batchObj.setSortOrder = setSortOrder;
        Id batchProcessId = Database.executeBatch(batchObj,40);
      }
      //JourneyParticipantServices.processDeletedMilestones(setJourneyIds,lstMilestones);
    } else if (evt == 'UPDATE') {
      for (Milestone__c mStones : newMap.values()) {
        if (oldMap != null) {
          Milestone__c mStonesOld = oldMap.get(mStones.Id);
          if (mStones.Journey__c != null) {
            if (
                    mStones.RecordTypeId != mStonesOld.RecordTypeId ||
                            mStones.Sort_Order__c != mStonesOld.Sort_Order__c ||
                            mStones.Parent__c != mStonesOld.Parent__c ||
                            mStones.Is_Active__c != mStonesOld.Is_Active__c ||
                            mStones.Description__c != mStonesOld.Description__c ||
                            mStones.Start_Date__c != mStonesOld.Start_Date__c ||
                            mStones.End_Date__c != mStonesOld.End_Date__c ||
                            mStones.Milestone_URL__c != mStonesOld.Milestone_URL__c ||
                            mStones.Parent_Milestone__c != mStonesOld.Parent_Milestone__c || //Added by DinoBrinas [CCN973] Dec232021
                            mStones.Display_In_Dashboard__c != mStonesOld.Display_In_Dashboard__c //Added by DinoBrinas [CCN973] Dec232021
                    ) {
              setJourneyIds.add(mStones.Journey__c);
              lstMilestones.add(mStones);
            }
          }
        } else {
          setJourneyIds.add(mStones.Journey__c);
          lstMilestones.add(mStones);
        }
      }
      if(!setJourneyIds.isEmpty()) JourneyParticipantServices.processUpdatedMilestones( setJourneyIds, lstMilestones );
    }
  }
}