main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone__c/Participant_Milestone__c.object-meta.xml
<CustomObject>
    <description>All milestones of participants</description>
    <label>Participant Milestone</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Participant Milestone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey Participant</description>
    <label>Participant</label>
    <referenceTo>Journey_Participant__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Milestone</description>
    <label>Journey Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/Participant_Milestone_Metric__c.object-meta.xml
<CustomObject>
    <description>Tracks the progress of participants milestone</description>
    <label>Participant Milestone Metric</label>
    <nameField>
        <displayFormat>PMM-{0000000}</displayFormat>
        <label>Participant Milestone Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestone Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone_Metric__c/fields/Metric_Used__c.field-meta.xml
<CustomField>
    <fullName>Metric_Used__c</fullName>
    <description>Metric Used</description>
    <label>Metric Used</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>Participants Milestone</description>
    <label>Milestone</label>
    <referenceTo>Participant_Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestone Metrics</relationshipLabel>
    <relationshipName>Participant_Milestone_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/BatchDeleteMilestoneMetrics.cls
global class BatchDeleteMilestoneMetrics implements Database.Batchable<SObject>, Database.Stateful{

        public String strQuery = '';
        global Database.QueryLocator start(Database.BatchableContext BC)
        {
            try {
                if(Test.isRunningTest()){
                    strQuery = 'SELECT Id, Name, Metric_Used__c, Milestone__c, Milestone__r.Journey__c, Milestone__r.Journey__r.Journey__c ' +
                            'FROM Participant_Milestone_Metric__c';
                }else{
                    strQuery = 'SELECT Id, Name, Metric_Used__c, Milestone__c, Milestone__r.Journey__c, Milestone__r.Journey__r.Journey__c ' +
                            'FROM Participant_Milestone_Metric__c WHERE Milestone__r.Journey__r.Journey__c = \'a594X000002XBtXQAW\'';
                }

                System.debug(LoggingLevel.DEBUG, 'QUERY: ' + strQuery);
                return Database.getQueryLocator(strQuery);
            } catch(Exception e) {
                return null;
            }
        }

        global void execute(Database.BatchableContext BC, List<SObject> scope)
        {
            List<Participant_Milestone_Metric__c> lstMetrics = (List<Participant_Milestone_Metric__c>)scope;

            if (!lstMetrics.isEmpty()) {
                Database.delete(lstMetrics);
            }
        }

        global void finish(Database.BatchableContext BC) {

        }
    }