main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Indicates sort order of Milestone</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Participant_Milestone__c/Participant_Milestone__c.object-meta.xml
<CustomObject>
    <description>All milestones of participants</description>
    <label>Participant Milestone</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Participant Milestone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey Participant</description>
    <label>Participant</label>
    <referenceTo>Journey_Participant__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Milestone</description>
    <label>Journey Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/BatchDeleteParticipantMilestones.cls
/*******************************************************************************
 * @author       Angelo Rivera
 * @date         14.Jan.2022
 * @description  Deletes Participant Milestones
 * @revision     14.Jan.2022 - APRivera - Created
 *******************************************************************************/
global class BatchDeleteParticipantMilestones implements Database.Batchable<SObject>, Database.Stateful{

    public String strQuery = '';
    public Set<Id> setJourneyIds = new Set<Id>();
    public List<Milestone__c> lstMilestones = new List<Milestone__c>();
    public Set<Decimal> setSortOrder = new Set<Decimal>();
    public Map<Id, List<Participant_Milestone__c>> mapParticipantMilestonesByIds = new Map<Id, List<Participant_Milestone__c>>();
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        try {
            strQuery = 'SELECT Id  FROM Journey_Participant__c WHERE Journey__c IN :setJourneyIds ORDER BY CreatedDate ASC ';// +
//                        ' LIMIT ' + String.valueOf(Limits.getLimitQueryRows() - Limits.getQueryRows());
            System.debug(LoggingLevel.DEBUG, 'QUERY: ' + strQuery);
            return Database.getQueryLocator(strQuery);
        } catch(Exception e) {
            return null;
        }
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope)
    {
        List<Journey_Participant__c> lstJourneyParticipants = (List<Journey_Participant__c>)scope;

        if (!lstJourneyParticipants.isEmpty()) {
            System.debug(LoggingLevel.DEBUG,'!@# lstMilestones: ' + lstMilestones);

            Set<Id> setId = new Set<Id>();
            for(Journey_Participant__c journeyParticipant : lstJourneyParticipants){
                setId.add(journeyParticipant.Id);
            }

            for(Participant_Milestone__c pm : [SELECT Id, Name, Sort_Order__c, Journey__c
                                                FROM Participant_Milestone__c
                                                WHERE Sort_Order__c IN: setSortOrder
                                                AND Journey__c IN: setId]){
                if(mapParticipantMilestonesByIds.containsKey(pm.Journey__c)){
                    mapParticipantMilestonesByIds.get(pm.Journey__c).add(pm);
                }else{
                    mapParticipantMilestonesByIds.put(pm.Journey__c, new List<Participant_Milestone__c>());
                    mapParticipantMilestonesByIds.get(pm.Journey__c).add(pm);
                }
            }

            List<Participant_Milestone__c> lstParticipantMilestones = new List<Participant_Milestone__c>();
            for (Milestone__c m : lstMilestones) {
                for (Journey_Participant__c jp : lstJourneyParticipants) {
                    if (mapParticipantMilestonesByIds.containsKey(jp.Id)) {
                        for (Participant_Milestone__c pm : mapParticipantMilestonesByIds.get(jp.Id)) {
                            if ( pm.Sort_Order__c == m.Sort_Order__c) {
                                lstParticipantMilestones.add(pm);
                            }
                        }
                    }
                }
            }
            if (!lstParticipantMilestones.isEmpty()) Database.delete(lstParticipantMilestones);
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
}