main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description of the Journey</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Journey_Participant__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Journey_Participant__c/fields/Journey_URL__c.field-meta.xml
<CustomField>
    <fullName>Journey_URL__c</fullName>
    <description>Journey URL</description>
    <label>Journey URL</label>
    <type>Url</type>
</CustomField>

main/default/classes/JourneyParticipantTriggerHandler.cls
/**
* @description TriggerHandler Class for Journey_Participant__c Object Trigger
* @revision
*           10.09.2020 - APRivera - Initial Creation
**/

public class JourneyParticipantTriggerHandler {

    /*******************************************************************************
    * @description  handles all before insert events. Filter event criteria here
    * @param        newMap - Trigger.newMap context variable
    * @revision     10.09.2020 - APRivera - Created
    *******************************************************************************/
    public static void handleAfterInsert(Map<Id, Journey_Participant__c> newMap) {
        processNewJourneyParticipants(newMap);

        String strJourneyCommunityURL = JourneyParticipantServices.getCommunityURL( JourneyParticipantServices.UserJourneyCommunitySettings.Community_Name__c );
        Set<Id> setJourneyIds = new Set<Id>();
        for(Journey_Participant__c usrJourney : newMap.values()){
            setJourneyIds.add(usrJourney.Journey__c);
        }

        Map<Id, Journey__c> mapJourneysByIds = new Map<Id, Journey__c>();
        for(Journey__c j : [SELECT Id, Description__c FROM Journey__c WHERE Id IN: setJourneyIds]){
            mapJourneysByIds.put(j.Id, j);
        }

        List<Journey_Participant__c> lstJourneyParticipants = new List<Journey_Participant__c>();
        for(Journey_Participant__c usrJourney : newMap.values()){
            if(mapJourneysByIds.containsKey(usrJourney.Journey__c) && usrJourney.Journey__c != null){
                Journey_Participant__c newJP = new Journey_Participant__c();
                newJP.Id = usrJourney.Id;
                newJP.Description__c = usrJourney.Description__c != null ? usrJourney.Description__c : mapJourneysByIds.get(usrJourney.Journey__c).Description__c;
                newJP.Journey_URL__c = strJourneyCommunityURL + '/s/journey?journeyId=' + usrJourney.Id;
                lstJourneyParticipants.add(newJP);
            }
        }
        update lstJourneyParticipants;
    }


    /*******************************************************************************
    * @author       Angelo Rivera
    * @date         10.09.2020
    * @description  Process User Journeys
    * @param        newMap - map of the new records
    * @revision     10.09.2020 - APRivera - Created
    *******************************************************************************/
    public static void processNewJourneyParticipants(Map<Id, Journey_Participant__c> newMap){
        List<Journey_Participant__c> lstUserJourneys = new List<Journey_Participant__c>();
        Set<Id> setJourneyTemplateId = new Set<Id>();
        Set<Id> setIds = new Set<Id>();

        for(Journey_Participant__c usrJourney : newMap.values()){
            if(usrJourney.Journey__c != null){
                setJourneyTemplateId.add(usrJourney.Journey__c);
                lstUserJourneys.add(usrJourney);
                setIds.add(usrJourney.Id);
            }
        }

        if(!lstUserJourneys.isEmpty()){
            JourneyParticipantServices.processNewUserJourneys(lstUserJourneys, setJourneyTemplateId, setIds);
        }
    }
}