main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates active record</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Journey_Participant__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates Active milestone</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/fields/Parent_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Parent_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Milestone</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.Journey__c</field>
            <operation>equals</operation>
            <valueField>$Source.Journey__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Milestones &amp; Checkpoints (Parent Milestone)</relationshipLabel>
    <relationshipName>Milestones_Checkpoints</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Milestone__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Indicates sort order of Milestone</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Milestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Milestone</description>
    <label>Journey Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attestation</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Milestone__c/recordTypes/Checkpoint.recordType-meta.xml
<RecordType>
    <fullName>Checkpoint</fullName>
    <active>true</active>
    <label>Checkpoint</label>
</RecordType>

main/default/objects/Milestone__c/recordTypes/Milestone.recordType-meta.xml
<RecordType>
    <fullName>Milestone</fullName>
    <active>true</active>
    <label>Milestone</label>
</RecordType>

main/default/objects/Participant_Milestone__c/Participant_Milestone__c.object-meta.xml
<CustomObject>
    <description>All milestones of participants</description>
    <label>Participant Milestone</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Participant Milestone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone__c/fields/Checkpoint_Name__c.field-meta.xml
<CustomField>
    <fullName>Checkpoint_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Checkpoint</description>
    <label>Checkpoint Name</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones (Checkpoint Name)</relationshipLabel>
    <relationshipName>Checkpoints</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Checkpoint_Progress__c.field-meta.xml
<CustomField>
    <fullName>Checkpoint_Progress__c</fullName>
    <description>Checkpoint progress</description>
    <label>Checkpoint Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates active record</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey Participant</description>
    <label>Participant</label>
    <referenceTo>Journey_Participant__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Milestone</description>
    <label>Journey Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Parent_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Parent_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Milestone</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.Journey__c</field>
            <operation>equals</operation>
            <valueField>Milestone__c.Journey__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones (Parent Milestone)</relationshipLabel>
    <relationshipName>Milestones_Checkpoints1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <description>Tracks the Milestone Progress</description>
    <formula>IF( Checkpoint__c , Checkpoint_Progress__c ,  Milestone_Progress__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/Participant_Milestone_Metric__c.object-meta.xml
<CustomObject>
    <description>Tracks the progress of participants milestone</description>
    <label>Participant Milestone Metric</label>
    <nameField>
        <displayFormat>PMM-{0000000}</displayFormat>
        <label>Participant Milestone Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestone Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone_Metric__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>Participants Milestone</description>
    <label>Milestone</label>
    <referenceTo>Participant_Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestone Metrics</relationshipLabel>
    <relationshipName>Participant_Milestone_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/UpdateCheckpointProgressBatch.cls
/**
 * Created by angelorivera on 6/12/2022.
 */

global class UpdateCheckpointProgressBatch implements Database.Batchable <SObject>, Database.Stateful{
    public String strQuery;
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        System.debug(LoggingLevel.DEBUG, 'QUERY: ' + strQuery);
        return Database.getQueryLocator(strQuery);
    }

/*******************************************************************************
* @author       angelorivera
* @date         na
* @return       strResult
* @revision     27/12/2022 - angelorivera [CCN-2429]: Added journeyParticipantbyJourneyIdMap
*******************************************************************************/
    global void execute(Database.BatchableContext BC, List<SObject> participantMilestoneRecs)
    {
        List<Participant_Milestone_Metric__c> participantMilestoneMetricList = (List<Participant_Milestone_Metric__c>)participantMilestoneRecs;
        Set<Id> setMilestoneIds = new Set<Id>();
        // Start CCN-2429: Added journeyParticipantbyJourneyIdMap
        Map<Id, Set<Id>> journeyParticipantbyJourneyIdMap = new Map<Id, Set<Id>>();
        for (Participant_Milestone_Metric__c metric : participantMilestoneMetricList) {

            // get all Participant Milestone Ids
            setMilestoneIds.add(metric.Milestone__c);
            Set<Id> journeyParticipantSet = new Set<Id>();

            // get the groupings of Journey Participants by Journet Id
            if (journeyParticipantbyJourneyIdMap.containsKey(metric.Milestone__r.Journey__r.Journey__c)) {
                journeyParticipantSet.add(metric.Milestone__r.Journey__c);
                journeyParticipantbyJourneyIdMap.get(metric.Milestone__r.Journey__r.Journey__c).addAll(journeyParticipantSet);
            } else {
                journeyParticipantSet.add(metric.Milestone__r.Journey__c);
                journeyParticipantbyJourneyIdMap.put(metric.Milestone__r.Journey__r.Journey__c, new Set<Id>());
                journeyParticipantbyJourneyIdMap.get(metric.Milestone__r.Journey__r.Journey__c).addAll(journeyParticipantSet);
            }
        }

        // End CCN-2429: Added journeyParticipantbyJourneyIdMap

        if (!setMilestoneIds.isEmpty()) {
            Map<Id,Participant_Milestone__c> mapParentParticipantMilestoneById = new Map<Id, Participant_Milestone__c>();
            Set<Id> setParticipantCheckpointIds = new Set<Id>();
            Map<Id, Map<Id, Set<Id>>> mapMilestonesByCheckpointIdsByParticipantIds = new Map<Id, Map<Id, Set<Id>>>();
            for (Participant_Milestone__c participantMilestone : [SELECT Id, Name, Parent_Milestone__c, Journey__c, Progress__c, Type__c, Checkpoint_Name__c
                                                                    FROM Participant_Milestone__c
                                                                    WHERE Id IN: setMilestoneIds 
                                                                    ORDER BY Journey__c,Parent_Milestone__c, Progress__c ASC]) {

                // group parent milestone Ids by checkpoint Ids and by Participant Ids
                //if(participantMilestone.Checkpoint_Name__c != null){
                if(mapMilestonesByCheckpointIdsByParticipantIds.containsKey(participantMilestone.Journey__c)){
                    Map<Id, Set<Id>> mapMilestoneIdByCheckpoint = new Map<Id, Set<Id>>();
                    //get map of Parent Participant Milestones by Checkpoint Id
                    mapMilestoneIdByCheckpoint = mapMilestonesByCheckpointIdsByParticipantIds.get(participantMilestone.Journey__c);
                    if (mapMilestoneIdByCheckpoint.containsKey(participantMilestone.Checkpoint_Name__c)) {
                        mapMilestoneIdByCheckpoint.get(participantMilestone.Checkpoint_Name__c).add(participantMilestone.Id);
                    } else {
                        mapMilestoneIdByCheckpoint.put(participantMilestone.Checkpoint_Name__c, new Set<Id>());
                        mapMilestoneIdByCheckpoint.get(participantMilestone.Checkpoint_Name__c).add(participantMilestone.Id);
                    }
                    mapMilestonesByCheckpointIdsByParticipantIds.get(participantMilestone.Journey__c).putAll(mapMilestoneIdByCheckpoint);
                }else{
                    Map<Id, Set<Id>> mapMilestoneIdByCheckpoint = new Map<Id, Set<Id>>();
                    mapMilestoneIdByCheckpoint.put(participantMilestone.Checkpoint_Name__c, new Set<Id>());
                    mapMilestoneIdByCheckpoint.get(participantMilestone.Checkpoint_Name__c).add(participantMilestone.Id);
                    mapMilestonesByCheckpointIdsByParticipantIds.put(participantMilestone.Journey__c, new Map<Id, Set<Id>>());
                    mapMilestonesByCheckpointIdsByParticipantIds.get(participantMilestone.Journey__c).putAll(mapMilestoneIdByCheckpoint);
                }
                setParticipantCheckpointIds.add(participantMilestone.Checkpoint_Name__c);
                mapParentParticipantMilestoneById.put(participantMilestone.Id, participantMilestone);
                //}
            }
            // update checkpoint progress
            // Start CCN-2429: Added journeyParticipantbyJourneyIdMap param
            updateCheckpointPMM(journeyParticipantbyJourneyIdMap, mapParentParticipantMilestoneById, setParticipantCheckpointIds, mapMilestonesByCheckpointIdsByParticipantIds);
            // End CCN-2429: Added journeyParticipantbyJourneyIdMap
        }
    }

/*******************************************************************************
* @author       angelorivera
* @date         na
* @return       strResult
* @revision     27/12/2022 - angelorivera [CCN-2429]: Added journeyParticipantbyJourneyIdMap
*******************************************************************************/
    global static void updateCheckpointPMM(Map<Id, Set<Id>> journeyParticipantbyJourneyIdMap, Map<Id,Participant_Milestone__c> mapParticipantMilestoneById,  Set<Id> pmCheckpointIds,  Map<Id, Map<Id, Set<Id>>> mapMilestonesByCheckpointIdsByParticipantIds){
        Map<Id,List<Participant_Milestone__c>> mapParticipantCheckpointById = new Map<Id, List<Participant_Milestone__c>>();
        for(Participant_Milestone__c participantCheckpointRec : [SELECT Id, Name, Checkpoint_Progress__c, Milestone__c, Journey__c, Sort_Order__c
                                                                    FROM Participant_Milestone__c
                                                                    WHERE Milestone__c IN: pmCheckpointIds AND Is_Active__c = TRUE
                                                                    ORDER BY Journey__c, Milestone__c]){
            if(mapParticipantCheckpointById.containsKey(participantCheckpointRec.Journey__c)){
                mapParticipantCheckpointById.get(participantCheckpointRec.Journey__c).add(participantCheckpointRec);
            }else{
                mapParticipantCheckpointById.put(participantCheckpointRec.Journey__c, new List<Participant_Milestone__c>());
                mapParticipantCheckpointById.get(participantCheckpointRec.Journey__c).add(participantCheckpointRec);
            }
        }

        List<Participant_Milestone__c> listParticipantCheckpointsTobeUpdated = new List<Participant_Milestone__c>();

        // Start CCN-2429: Added new iteration for journeyParticipantbyJourneyIdMap
        // iterate through each Journey
        for(Id journeyId : journeyParticipantbyJourneyIdMap.keySet()){
            // go through each journey participant
            for(Id journeyParticipantId : journeyParticipantbyJourneyIdMap.get(journeyId)){
                Map<Id, Set<Id>> mapMilestoneIdByCheckpoint = new Map<Id, Set<Id>>();
                if(mapMilestonesByCheckpointIdsByParticipantIds.containsKey(journeyParticipantId)){
                    // get map of Parent Participant Milestones by Checkpoint Id
                    mapMilestoneIdByCheckpoint = mapMilestonesByCheckpointIdsByParticipantIds.get(journeyParticipantId);

                    // go through each checkpoint
                    for(Id checkpointId : mapMilestoneIdByCheckpoint.keySet()){
                        Set<Id> setParentMilestoneIds = new Set<Id>();
                        // get all Parent Milestone Ids
                        setParentMilestoneIds.addAll(mapMilestoneIdByCheckpoint.get(checkpointId));

                        // go through all parent milestone linked to the current checkpoint in the iteration
                        Double tempProgress = 0;
                        Double iCtr = 0;
                        System.debug(LoggingLevel.DEBUG,'@@@@@ Checkpoint : ' + checkpointId);

                        // go through each parent participant milestone
                        for(Id parentMilestoneId : setParentMilestoneIds){
                            if(mapParticipantMilestoneById.containsKey(parentMilestoneId)){
                                // get the progress of the parent milestones
                                tempProgress = tempProgress + mapParticipantMilestoneById.get(parentMilestoneId).Progress__c;
                                System.debug(LoggingLevel.DEBUG,'@@@@@ Progress: ' + mapParticipantMilestoneById.get(parentMilestoneId).Progress__c);
                                iCtr++;
                            }
                        }
                        System.debug(LoggingLevel.DEBUG,'@@@@@ tempProgress: ' + tempProgress);
                        System.debug(LoggingLevel.DEBUG,'@@@@@ Number of milestones: ' + iCtr);

                        // update the progress of the checkpoint
                        for(Participant_Milestone__c pm : mapParticipantCheckpointById.get(journeyParticipantId)){
                            if(pm.Milestone__c == checkpointId){
                                Double dProgress = tempProgress/iCtr;
                                System.debug(LoggingLevel.DEBUG,'@@@@@ dProgress: ' + dProgress);
                                pm.Checkpoint_Progress__c = dProgress;
                                System.debug(LoggingLevel.DEBUG,'@@@@@ Participant_Milestone__c: ' + pm.Checkpoint_Progress__c);
                                listParticipantCheckpointsTobeUpdated.add(pm);
                            }
                        }
                    }
                }
            }
            // End CCN-2429: Added new iteration for journeyParticipantbyJourneyIdMap
        }
        if(!listParticipantCheckpointsTobeUpdated.isEmpty()){
            Database.update(listParticipantCheckpointsTobeUpdated);
        }
    }

    global void finish(Database.BatchableContext bc){

    }
}