main/default/objects/Batch_Processor__c/Batch_Processor__c.object-meta.xml
<CustomObject>
    <description>Temp table that stores Record Ids to be processed by Compass Batch class</description>
    <label>Batch Processor</label>
    <nameField>
        <displayFormat>BP{000000}</displayFormat>
        <label>Batch Processor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Processor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Batch_Processor__c/fields/Parameter_1__c.field-meta.xml
<CustomField>
    <fullName>Parameter_1__c</fullName>
    <label>Parameter 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Record_Id_2__c.field-meta.xml
<CustomField>
    <fullName>Record_Id_2__c</fullName>
    <label>Record Id 2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Record Id</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Trigger_Source__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Source__c</fullName>
    <label>Trigger Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Batch Type</description>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/classes/BatchProcessorUtility.cls
global class BatchProcessorUtility {

    global static void insertBatchRecord(Map<String, List<String>> recordIdMap, String type, String triggerSource) {

        List<Batch_Processor__c> batchProcessorList = new List<Batch_Processor__c>();

        for (String journeyId: recordIdMap.keySet()) {

            for (String contactId: recordIdMap.get(journeyId)) {

                Batch_Processor__c batchProcessor = new Batch_Processor__c(
                    Record_Id__c = contactId,
                    Record_Id_2__c = journeyId,
                    Type__c = type,
                    Trigger_Source__c = triggerSource
                );

                batchProcessorList.add(batchProcessor);
            }
        }

        if (!batchProcessorList.isEmpty()) {
            insert batchProcessorList;
        }
    }

    //CCN-1551 XEN REYES 29 April 2022
    global static void insertBatchRecord(Set<String> recordIdSet, String type, String triggerSource,  String param1) {

        List<Batch_Processor__c> batchProcessorList = new List<Batch_Processor__c>();

        for (String recordId: recordIdSet) {

            Batch_Processor__c batchProcessor = new Batch_Processor__c(
                Record_Id__c = recordId,
                Type__c = type,
                Trigger_Source__c = triggerSource,
                Parameter_1__c = param1
            );

            batchProcessorList.add(batchProcessor);
        }

        if (!batchProcessorList.isEmpty()) {
            insert batchProcessorList;
        }
    }

}