main/default/objects/Batch_Processor__c/Batch_Processor__c.object-meta.xml
<CustomObject>
    <description>Temp table that stores Record Ids to be processed by Compass Batch class</description>
    <label>Batch Processor</label>
    <nameField>
        <displayFormat>BP{000000}</displayFormat>
        <label>Batch Processor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Processor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Batch_Processor__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Record Id</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Batch Type</description>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Educator</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Trainor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Do_Not_Send_Resource_Confirmation_Email__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Send_Resource_Confirmation_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do Not Send Resource Confirmation Email</description>
    <label>Do Not Send Resource Confirmation Email</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Internal_Resource__c/Internal_Resource__c.object-meta.xml
<CustomObject>
    <label>Internal Resource</label>
    <nameField>
        <displayFormat>IR-{000000}</displayFormat>
        <label>Event Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Resource__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Internal Resources</relationshipLabel>
    <relationshipName>Internal_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Internal Resources</relationshipLabel>
    <relationshipName>Internal_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/classes/BatchEventDeliveryConfirmation.cls
/******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyyy)          Author                      Description
    *           ----  -----------------    -------------------       -----------------------------
    * @version   1.0  23-06-2022             Von Pernicia            [CCN-EVE-2390-DV] Intial Version. scheduler and batch job to send Event Delivery Confirmation
    ******************************************************************************/ 
global with sharing class BatchEventDeliveryConfirmation implements Database.Batchable<SObject>, Schedulable, Database.Stateful{

    public String strQuery;
    public String emailTemplateId;
    public Set<String> resourceIdList;
    public List<Batch_Processor__c> batchProcessorList = new List<Batch_Processor__c>();

    global void execute(SchedulableContext sc) {

        String finalResourceId ; 
        String queryString;
        Set<String> resourceIds = new Set<String>();
        
        
        List<Batch_Processor__c> batchList = [SELECT Id, Record_Id__c
        FROM Batch_Processor__c
        WHERE Type__c = 'BatchEventDeliveryConfirmation'];

        for (Batch_Processor__c batch: batchList) {

           
            if (!resourceIds.contains(batch.Record_Id__c) && batch.Record_Id__c != null) {
                if (String.isEmpty(finalResourceId)) {
                    finalResourceId = '\'' + batch.Record_Id__c + '\'';
                } else {
                    finalResourceId = finalResourceId + ',' + '\'' + batch.Record_Id__c + '\'';
                }
                resourceIds.add(batch.Record_Id__c);
            }
        }

        if (!batchList.isEmpty()) {
           
            queryString = ' SELECT Id, Contact__r.email, Event__r.Email_Sender_Id__c, Event__r.Do_Not_Send_Resource_Confirmation_Email__c ' +
            'FROM Internal_Resource__c ' +
            'WHERE Id in (' + finalResourceId + ')  ';
            
            system.debug('@@ queryString' + queryString);
            BatchEventDeliveryConfirmation batchObj = new BatchEventDeliveryConfirmation();
            batchObj.strQuery = queryString;
            batchObj.batchProcessorList = batchList;            
            Id batchProcessId = Database.executeBatch(batchObj,2000);
        }
    }
   
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        try {

            this.emailTemplateId = '';
         
            this.emailTemplateId = [SELECT Id 
                                    FROM EmailTemplate 
                                    WHERE DeveloperName = 'Event_Session_Delivery_Confirmation'].Id;

            return Database.getQueryLocator(this.strQuery);
        }catch(Exception e) {
            return null;
        }
    }

    global void execute(Database.BatchableContext BC, List<SObject> sessionRecord){
       
        List<Internal_Resource__c> irsList = (List<Internal_Resource__c>)sessionRecord;
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>(); 
        List<String> emailTo;
        for(Internal_Resource__c ir: irsList){
            if(!ir.Event__r.Do_Not_Send_Resource_Confirmation_Email__c){
                emailTo = new List<String>{ ir.Contact__r.email };

                Messaging.SingleEmailMessage message = Messaging.renderStoredEmailTemplate(this.emailTemplateId, null, ir.Id);
                message.setOrgWideEmailAddressId(ir.Event__r.Email_Sender_Id__c);
                message.setToAddresses(emailTo);
                message.setUseSignature(false); 
                message.setSaveAsActivity(false);

                emails.add(message);
            }
          
        }
       
        Messaging.sendEmail(emails);
    }

    global void finish(Database.BatchableContext BC) {
        
        if (!this.batchProcessorList.isEmpty()) {
            delete this.batchProcessorList;
        }
    }
}