main/default/objects/Batch_Processor__c/Batch_Processor__c.object-meta.xml
<CustomObject>
    <description>Temp table that stores Record Ids to be processed by Compass Batch class</description>
    <label>Batch Processor</label>
    <nameField>
        <displayFormat>BP{000000}</displayFormat>
        <label>Batch Processor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Processor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Batch_Processor__c/fields/Record_Id_2__c.field-meta.xml
<CustomField>
    <fullName>Record_Id_2__c</fullName>
    <label>Record Id 2</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Record Id</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Batch Type</description>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey_Participant__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates active record</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Journey_Participant__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Checkpoint__c.field-meta.xml
<CustomField>
    <fullName>Checkpoint__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates milestone as checkpoint</description>
    <label>Checkpoint</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Milestone__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates Active milestone</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to the milestone tagged as checkpoint</description>
    <label>Checkpoint Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone__c.Journey__c</field>
            <operation>equals</operation>
            <valueField>$Source.Journey__c</valueField>
        </filterItems>
        <filterItems>
            <field>Milestone__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Checkpoint</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Milestones &amp; Checkpoints</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Milestone__c/fields/Parent_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Parent_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Milestone</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.Journey__c</field>
            <operation>equals</operation>
            <valueField>$Source.Journey__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Milestones &amp; Checkpoints (Parent Milestone)</relationshipLabel>
    <relationshipName>Milestones_Checkpoints</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Milestone__c/fields/Related_RecordId__c.field-meta.xml
<CustomField>
    <fullName>Related_RecordId__c</fullName>
    <description>Contains the related record id (Could be Event, Session, Survey or Communication)</description>
    <label>Related Record Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

main/default/objects/Milestone__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Indicates sort order of Milestone</description>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Milestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Milestone</description>
    <label>Journey Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Attestation</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Participant_Milestone__c/Participant_Milestone__c.object-meta.xml
<CustomObject>
    <description>All milestones of participants</description>
    <label>Participant Milestone</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Participant Milestone Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone__c/fields/Checkpoint__c.field-meta.xml
<CustomField>
    <fullName>Checkpoint__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates Checkpoint</description>
    <label>Checkpoint</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Checkpoint_Name__c.field-meta.xml
<CustomField>
    <fullName>Checkpoint_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Checkpoint</description>
    <label>Checkpoint Name</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones (Checkpoint Name)</relationshipLabel>
    <relationshipName>Checkpoints</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Checkpoint_Progress__c.field-meta.xml
<CustomField>
    <fullName>Checkpoint_Progress__c</fullName>
    <description>Checkpoint progress</description>
    <label>Checkpoint Progress</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates active record</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey Participant</description>
    <label>Participant</label>
    <referenceTo>Journey_Participant__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Milestone</description>
    <label>Journey Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones</relationshipLabel>
    <relationshipName>Participant_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Parent_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Parent_Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Milestone</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Milestone__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Milestone</value>
        </filterItems>
        <filterItems>
            <field>Milestone__c.Journey__c</field>
            <operation>equals</operation>
            <valueField>Milestone__c.Journey__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestones (Parent Milestone)</relationshipLabel>
    <relationshipName>Milestones_Checkpoints1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/Progress__c.field-meta.xml
<CustomField>
    <fullName>Progress__c</fullName>
    <description>Tracks the Milestone Progress</description>
    <formula>IF( Checkpoint__c , Checkpoint_Progress__c ,  Milestone_Progress__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Progress</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

main/default/objects/Participant_Milestone__c/fields/System_Generated__c.field-meta.xml
<CustomField>
    <fullName>System_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates system generated record</description>
    <label>System Generated</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/Participant_Milestone_Metric__c.object-meta.xml
<CustomObject>
    <description>Tracks the progress of participants milestone</description>
    <label>Participant Milestone Metric</label>
    <nameField>
        <displayFormat>PMM-{0000000}</displayFormat>
        <label>Participant Milestone Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Milestone Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant_Milestone_Metric__c/fields/Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Completion_Date__c</fullName>
    <description>Metric Completion Date</description>
    <label>Completion Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/fields/Metric_Used__c.field-meta.xml
<CustomField>
    <fullName>Metric_Used__c</fullName>
    <description>Metric Used</description>
    <label>Metric Used</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <description>Participants Milestone</description>
    <label>Milestone</label>
    <referenceTo>Participant_Milestone__c</referenceTo>
    <relationshipLabel>Participant Milestone Metrics</relationshipLabel>
    <relationshipName>Participant_Milestone_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant_Milestone_Metric__c/fields/System_Generated__c.field-meta.xml
<CustomField>
    <fullName>System_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates System Generated record</description>
    <label>System Generated</label>
    <type>Checkbox</type>
</CustomField>

main/default/classes/SchedBatSyncParticipantMilestoneMetric.cls
global class SchedBatSyncParticipantMilestoneMetric implements Schedulable {

    /*******************************************************************************
     * @author       Von Pernicia
     * @date         na
     * @description  method used in updateParticipantMilestone Aura component
     * @return       strResult
     * @revision     Na         - Von Pernicia: created classs to run sync base on Batch Processor object
     *               10/08/2022 - Von Pernicia [CCN-1984]: Updated query to fix timeout issue
     *               11/11/2022 - Von Pernicia [CCN-2288]: Added "Failed" as part of the filter criteria
     *******************************************************************************/
    global void execute(SchedulableContext ctx) {
        String finalJourneyId ;
        String finalContactId ; 
        String queryString;
        Set<String> journeyIds = new Set<String>();
        Set<String> contactIds = new Set<String>();

        // Start CCN-1984: Von Pernicia
        List<AsyncApexJob> aJob= [ 
                    SELECT Id, Status, ApexClassID 
                    FROM AsyncApexJob 
                    WHERE ApexClass.Name = 'BatchSyncParticipantMilestoneMetric' AND Status not in ('Completed', 'Aborted', 'Failed')
                    ];

        if(aJob.isEmpty()) {
        
            List<Batch_Processor__c> batchList = [SELECT Id, Record_Id__c, Record_Id_2__c
            FROM Batch_Processor__c
            WHERE Type__c = 'BatchSyncParticipantMilestoneMetric'];

            for (Batch_Processor__c batch: batchList) {

                //CCN-2303 XEN REYES Nov122022
                if (!journeyIds.contains(batch.Record_Id_2__c) && batch.Record_Id_2__c != null ) {
                    if (String.isEmpty(finalJourneyId)) {
                        finalJourneyId = '\'' + batch.Record_Id_2__c + '\'';
                    } else {
                        finalJourneyId = finalJourneyId + ',' + '\'' + batch.Record_Id_2__c + '\'';
                    }
                    journeyIds.add(batch.Record_Id_2__c);
                }

                //CCN-2303 XEN REYES Nov122022
                if (!contactIds.contains(batch.Record_Id__c) && batch.Record_Id__c != null) {
                    if (String.isEmpty(finalContactId)) {
                        finalContactId = '\'' + batch.Record_Id__c + '\'';
                    } else {
                        finalContactId = finalContactId + ',' + '\'' + batch.Record_Id__c + '\'';
                    }
                    contactIds.add(batch.Record_Id__c);
                }
            }

            if (!batchList.isEmpty()) {
                
                /*queryString = 'SELECT Id, Name, Journey__r.Journey__c, Journey__r.Contact__c, MileStone__r.Related_RecordId__c, MileStone__r.Name, Milestone__c, Milestone__r.Parent__c, Contact__c, Type__c, Checkpoint__c, Sort_Order__c, Progress__c, Checkpoint_Name__c, Checkpoint_Progress__c, ' +
                        '(SELECT Id, Name, Completion_Date__c, Metric_Used__c, Milestone__c, System_Generated__c FROM Participant_Milestone_Metrics__r WHERE Completion_Date__c = NULL) ' +
                        'FROM Participant_Milestone__c  ' +
                        'WHERE Journey__r.Journey__c in (' + finalJourneyId + ') AND ' +
                        'Journey__r.Contact__c in (' + finalContactId + ') ' +
                        'ORDER BY Journey__c, Contact__c, Sort_Order__c ';*/

                        queryString = ' SELECT Id, Name, Completion_Date__c, Metric_Used__c, Milestone__c, System_Generated__c, ' +
                        'Milestone__r.Name, ' +
                        'Milestone__r.Journey__c, ' +
                        'Milestone__r.Journey__r.Journey__c, ' +
                        'Milestone__r.MileStone__r.Related_RecordId__c, ' +
                        'Milestone__r.MileStone__r.Name, ' +
                        'Milestone__r.Milestone__c, ' +
                        'Milestone__r.Milestone__r.Parent__c, ' +
                        'Milestone__r.Contact__c, ' +
                        'Milestone__r.Type__c, ' +
                        'Milestone__r.Checkpoint__c, ' +
                        'Milestone__r.Sort_Order__c, ' +
                        'Milestone__r.Progress__c, ' +
                        'Milestone__r.Checkpoint_Name__c, ' +
                        'Milestone__r.Checkpoint_Progress__c, ' +
                        'Milestone__r.Parent_Milestone__c ' +
                        'FROM Participant_Milestone_Metric__c ' +
                        'WHERE Milestone__r.Journey__r.Journey__c in (' + finalJourneyId + ')  ' +
                        'AND Milestone__r.Journey__r.Contact__c in (' + finalContactId + ') ' +
            			'AND Milestone__r.Is_Active__c = TRUE ' + // CCN-2429 [01-01-2023]: Added new Parameter - Von Pernicia
                        'ORDER BY Milestone__r.Journey__c, Milestone__r.Contact__c, Milestone__r.Sort_Order__c ';
                system.debug('@@ queryString' + queryString);
                BatchSyncParticipantMilestoneMetric batchObj = new BatchSyncParticipantMilestoneMetric();
                batchObj.strQuery = queryString;
                batchObj.journeyIds = journeyIds;
                batchObj.finalContactId = finalContactId; // CCN-2429 [01-01-2023]: Added new Parameter - Von Pernicia
                batchObj.batchProcessorList = batchList; 
                Id batchProcessId = Database.executeBatch(batchObj,2000);

                // delete processed records from Batch processor
                //delete batchList;
                // End CCN-1984: Von Pernicia
            }
        }
    }
}