main/default/objects/Batch_Processor__c/Batch_Processor__c.object-meta.xml
<CustomObject>
    <description>Temp table that stores Record Ids to be processed by Compass Batch class</description>
    <label>Batch Processor</label>
    <nameField>
        <displayFormat>BP{000000}</displayFormat>
        <label>Batch Processor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Processor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Batch_Processor__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Record Id</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Batch Type</description>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/classes/SchedBatParticipantEmailComm.cls
global class SchedBatParticipantEmailComm implements Schedulable{

    global void execute(SchedulableContext ctx) {
        
        //CCN-1551 XEN REYES 29 April 2022
        /* Set<Id> pptIds = new Set<Id>();
        List<Batch_Processor__c> batchList = [SELECT Id, Record_Id__c
                                            FROM Batch_Processor__c
                                            WHERE Type__c = 'ParticipantEmailCommunicationBatch'];

        for (Batch_Processor__c batch: batchList) {
            pptIds.add(batch.Record_Id__c);
        }*/
        
        Map<Id, Batch_Processor__c> batchList = new Map<Id, Batch_Processor__c>([SELECT Id
                                            FROM Batch_Processor__c
                                            WHERE Type__c = 'ParticipantEmailCommunicationBatch']);

        if (!batchList.keySet().isEmpty()) {
            Database.executeBatch(new ParticipantEmailCommunicationBatch(batchList.keySet()), 20);

            // delete processed records from Batch processor 
            // delete batchList.values();
        }
    }
}