main/default/objects/Batch_Processor__c/Batch_Processor__c.object-meta.xml
<CustomObject>
    <description>Temp table that stores Record Ids to be processed by Compass Batch class</description>
    <label>Batch Processor</label>
    <nameField>
        <displayFormat>BP{000000}</displayFormat>
        <label>Batch Processor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Processor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Batch_Processor__c/fields/Parameter_1__c.field-meta.xml
<CustomField>
    <fullName>Parameter_1__c</fullName>
    <label>Parameter 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Record Id</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Member_Contact__c.field-meta.xml
<CustomField>
    <fullName>Member_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Event_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Member_Status</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Participant__c/recordTypes/Participant.recordType-meta.xml
<RecordType>
    <fullName>Participant</fullName>
    <active>true</active>
    <label>Participant</label>
</RecordType>

main/default/globalValueSets/Member_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Attended</fullName>
    </customValue>
    <customValue>
        <fullName>Catch-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Responded</fullName>
        <isActive>false</isActive>
        <label>Responded</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <isActive>false</isActive>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <masterLabel>Member Status</masterLabel>
</GlobalValueSet>

main/default/classes/ParticipantEmailCommunicationBatch.cls
/*******************************************************************************************
* @name: ParticipantEmailCommunicationBatch
* @author: Xen Reyes
* @created: 24-01-2022
* @description: [CCN1139] This is batch to chunk sending out email everytime there is a event participant status change.
*
* Changes (version)
* -------------------------------------------------------------------------------------------
*        No.   Date(dd-mm-yyy) Author         Description
*        ----  ---------    --------------------  -----------------------------
* @version   1.0   24-01-2022    Xen Reyes          Initial version.
*********************************************************************************************/
public class ParticipantEmailCommunicationBatch implements Database.Batchable<sObject>{
    
    public String queryString;
    public Set<Id> participantIdsVar;
    public Set<Id> batchProcessorIdsVar;

    public ParticipantEmailCommunicationBatch(Set<Id> participantIds) {

        //CCN-1551 XEN REYES 29 April 2022
        /* participantIdsVar = participantIds;
        DescribeSObjectResult objDescribe = Participant__c.getSObjectType().getDescribe();
        List<String> fields = new List<String> (objDescribe.fields.getMap().keySet());
        queryString = 'SELECT ' + String.join(fields, ',') + ' FROM Participant__c WHERE Id IN: participantIdsVar'; */

        batchProcessorIdsVar = participantIds;
        DescribeSObjectResult objDescribe = Batch_Processor__c.getSObjectType().getDescribe();
        List<String> fields = new List<String> (objDescribe.fields.getMap().keySet());
        queryString = 'SELECT ' + String.join(fields, ',') + ' FROM Batch_Processor__c WHERE Id IN: batchProcessorIdsVar'; 
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(queryString);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope){
        
        Set<Id> pptIds = new Set<Id>();

        //CCN-2304 XenReyes Nov122022
        for(Batch_Processor__c bp: (List<Batch_Processor__c>) scope) {
            if(bp.Record_Id__c != null) pptIds.add(bp.Record_Id__c);
        }

        Map<Id, Participant__c> pptMap = new Map<Id, Participant__c>([SELECT Id, Event__c, Member_Contact__c 
                                                                        FROM Participant__c 
                                                                        WHERE Id IN: pptIds
                                                                        AND Member_Contact__c != null
                                                                        AND Member_Contact__r.IsEmailBounced = false
                                                                        AND Member_Contact__r.Email != null]);

        Set<Id> eventIds = new Set<Id>();
        Map<String, List<Participant__c>> participantMap =  new Map<String, List<Participant__c>>();
        for(Batch_Processor__c bp: (List<Batch_Processor__c>) scope){
            if(!pptMap.containsKey(bp.Record_Id__c)) continue;
            Participant__c participant = pptMap.get(bp.Record_Id__c);
            if(participantMap.containsKey(bp.Parameter_1__c)){
                List<Participant__c> dataList = participantMap.get(bp.Parameter_1__c);
                dataList.add(participant);
                eventIds.add(participant.Event__c);
                participantMap.put(bp.Parameter_1__c, dataList);
            } else{
                eventIds.add(participant.Event__c);
                participantMap.put(bp.Parameter_1__c, new List<Participant__c>{participant});
            }
        }

        /* Set<Id> eventIds = new Set<Id>();
        Map<String, List<Participant__c>> participantMap =  new Map<String, List<Participant__c>>();
        for(Participant__c participant: (List<Participant__c>) scope){
            if(participantMap.containsKey(participant.Status__c)){
                List<Participant__c> dataList = participantMap.get(participant.Status__c);
                dataList.add(participant);
                eventIds.add(participant.event__c);
                participantMap.put(participant.Status__c, dataList);
            } else{
                eventIds.add(participant.event__c);
                participantMap.put(participant.Status__c, new List<Participant__c>{participant});
            }
        } */

        ParticipantTriggerUtility.sendEmailToParticipant(participantMap, eventIds);
        delete scope;
    }

    public void finish(Database.BatchableContext BC){
        
    }

}