main/default/objects/Batch_Processor__c/Batch_Processor__c.object-meta.xml
<CustomObject>
    <description>Temp table that stores Record Ids to be processed by Compass Batch class</description>
    <label>Batch Processor</label>
    <nameField>
        <displayFormat>BP{000000}</displayFormat>
        <label>Batch Processor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Processor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Batch_Processor__c/fields/Parameter_1__c.field-meta.xml
<CustomField>
    <fullName>Parameter_1__c</fullName>
    <label>Parameter 1</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>Record Id</description>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Trigger_Source__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Source__c</fullName>
    <label>Trigger Source</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Batch_Processor__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Batch Type</description>
    <label>Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Domain_Name_Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Domain_Name_Event_Registration__c</fullName>
    <label>Domain Name (Event Registration)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Educator</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Trainor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Do_Not_Send_Event_Confirmation_email__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Send_Event_Confirmation_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Send Event Confirmation email</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Event__c/fields/Session_Calendar_Invite_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Session_Calendar_Invite_Delivery__c</fullName>
    <description>This field determines in which stage between registration or confirmation is the Calendar Invite sent</description>
    <label>Session Calendar Invite Delivery</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Send on session registration</fullName>
                <default>true</default>
                <label>Send on session registration</label>
            </value>
            <value>
                <fullName>Send on session confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Member_Contact__c.field-meta.xml
<CustomField>
    <fullName>Member_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Event_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant__c/fields/Process_from_Event_Page__c.field-meta.xml
<CustomField>
    <fullName>Process_from_Event_Page__c</fullName>
    <defaultValue>false</defaultValue>
    <description>checker used for guest registration to avoid email duplicates</description>
    <label>Process from Event Page</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <description>Registration Date</description>
    <label>Registration Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Participant__c/fields/Send_Event_Registration_Notification__c.field-meta.xml
<CustomField>
    <fullName>Send_Event_Registration_Notification__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send Event Registration Notification</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Member_Status</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Participant__c/recordTypes/Participant.recordType-meta.xml
<RecordType>
    <fullName>Participant</fullName>
    <active>true</active>
    <label>Participant</label>
</RecordType>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Domain_Name__c</fullName>
    <label>Domain Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event_Invite_Delivery_Option__c.field-meta.xml
<CustomField>
    <fullName>Event_Invite_Delivery_Option__c</fullName>
    <formula>TEXT(Event__r.Session_Calendar_Invite_Delivery__c)</formula>
    <label>Event Invite Delivery Option</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <label>Registration Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session_Attendance_Thank_You_Message__c.field-meta.xml
<CustomField>
    <fullName>Session_Attendance_Thank_You_Message__c</fullName>
    <label>Session Attendance Thank You Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/globalValueSets/Member_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Attended</fullName>
    </customValue>
    <customValue>
        <fullName>Catch-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Responded</fullName>
        <isActive>false</isActive>
        <label>Responded</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <isActive>false</isActive>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <masterLabel>Member Status</masterLabel>
</GlobalValueSet>

main/default/classes/SessionParticipantTriggerHandler.cls
/*******************************************************************************************
  * @name: SessionTriggerHandler
  * @author: 
  * @created: XX-XX-XXXX
  * @description: Handler for all the logic of the trigger for the Session object
  *
  * Changes (version)
  * -------------------------------------------------------------------------------------------
  *             No.   Date(dd-mm-yyy)   Author                Description
  *             ----  ---------------   --------------------  ---------------------------------
  * @version    1.0   XX-XX-XXXX                              Initial Creation
  *             2.0   06-12-2021        Paolo Quiambao        [CCN981] Added code to sync Rich Text
  *                                                           from Session
  *             3.0   28-01-2022        DinoBrinas            [CCN1153] Fix the recursive issue
  *       4.0   23-03-2022    Paolo Quiambao      [CCN934] Replace Domain Name with Domain Name (Event Registration)
  *       5.0    25-04-2022    Paolo Quiambao      [CCN-EVE-1219-DV] Add automation for Confirmed Date and Declined Date
  * @version    4.0  17-08-2022   JC Espino            [CCN-EVE-1726-DV] Added criteria of when to send Calendar Invite
  *********************************************************************************************/
  public class SessionParticipantTriggerHandler{
    // @author: [CCN-1153] Updated by dinoBrinas
    // @description: This is used to avoid the recursive on the apex trigger.
    // @date: Jan282022
    public static boolean bPreventAI = false;
    public static boolean bPreventAU = false;
    public static boolean isFromAttendancePage = false; //CCN-1028 XR 27 May 2022
    
    /******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyy) Author            Description
    *           ----  ---------   --------------------  -----------------------------
    * @version   1.0  ??           ??                   Initial version.
    * @version   2.0  29-01-2022   VonPernicia          [CCN-496] Added new method "updateParticipantMilestoneMetrics" to call to update Participant Milestone Metics
    * @version   3.0  07-07-2022   Rianno Rizarri       [CCN-EVE-1834-DV] Added new method SessionParticipantTriggerUtility.countSessionPartipants to call the method
    * @version   4.0  17-08-2022   JC Espino            [CCN-EVE-1726-DV] Added criteria of when to send Calendar Invite
    * @version   6.0  12-01-2022   Von Pernicia         [CCN-2466] Remove logic that creates records in Batch_Processor__c
    ******************************************************************************/
    public static void onAfterInsert(List<Session_Participant__c> newSessionParticipantList, Map<Id,Session_Participant__c> newSessionParticipantMap, 
                                     List<Session_Participant__c> oldSessionParticipantList, Map<Id,Session_Participant__c> oldSessionParticipantMap){
        //Start CCN-EVE-1834-DV: Rianno Rizarri
		SessionParticipantTriggerUtility.countSessionPartipants(newSessionParticipantList);
        //End CCN-EVE-1834-DV: Rianno Rizarri
        Set<Id> participantIdSet = new Set<Id>();
		//Gabriel Delvin *08-10-2023* CCN-EVE-3426-DV
		SessionParticipantTriggerUtility.updateContactTitleRank(newSessionParticipantList);
        // Start CCN-2466 Von Pernicia: Removed logic
        //List<Session_Participant__c> updateParticipantMilestoneList = new List<Session_Participant__c>();
        // End CCN-2466 Von Pernicia: Removed logic                                

        List<Participant__c> participantsToUpdate = new List<Participant__c>();
        // UPDATED BY JC ESPINO AUG162022 [CCN-EVE-1726-DV]
        Map<Id, List<Session_Participant__c>> eventToParticipantsMap = new Map<Id, List<Session_Participant__c>>();
        Map<Id,Session_Participant__c> participantsToReceiveCalendarInvite = new Map<Id,Session_Participant__c>();

        for(Session_Participant__c sessionParticipant: newSessionParticipantList){
            if(sessionParticipant.Status__c == 'Confirmed'){
                // UPDATED BY JC ESPINO AUG162022 [CCN-EVE-1726-DV] - Added mechanism to check Event field Session_Calendar_Invite_Delivery__c

                if(!eventToParticipantsMap.containsKey(sessionParticipant.Event__c)) {
                    eventToParticipantsMap.put(sessionParticipant.Event__c, new List<Session_Participant__c>());
                }
                eventToParticipantsMap.get(sessionParticipant.Event__c).add(sessionParticipant);
                // END [CCN-EVE-1726-DV]
            }

            // Start CCN-2466 Von Pernicia: Removed logic
            /*if(!String.isEmpty(String.valueOf(sessionParticipant.Registration_Date__c)) &&  ( sessionParticipant.Status__c == 'Registered' || sessionParticipant.Status__c == 'Invited')) {
                updateParticipantMilestoneList.add(sessionParticipant);
            }*/
            // End CCN-2466 Von Pernicia: Removed logic

            // UPDATED BY JC ESPINO AUG162022 [CCN-EVE-1726-DV] - Added special case to send Calendar Invite during registration
            if(sessionParticipant.Status__c == 'Registered' && sessionParticipant.Event_Invite_Delivery_Option__c == 'Send on session registration') {
                participantsToReceiveCalendarInvite.put(sessionParticipant.Id, sessionParticipant);
            }
            // END [CCN-EVE-1726-DV]

            participantIdSet.add(sessionParticipant.Participant__c);
        }

        // UPDATED BY JC ESPINO AUG162022 [CCN-EVE-1726-DV] - Added special case to send Calendar Invite during registration
        if(!participantsToReceiveCalendarInvite.isEmpty()) {
            SessionParticipantTriggerUtility.sendCalendarInvite(participantsToReceiveCalendarInvite.values());
        }

        if(!eventToParticipantsMap.isEmpty()) {
            sendInvites(eventToParticipantsMap);
        }
        
        /* CCN-EVE-2500-DV XEN REYES 30Jan2023 */
        /* Map<Id, Participant__c> participantList = new Map<Id, Participant__c>();
        if(FlsUtils.isAccessible('Participant__c', new List<String>{'Status__c', 'Event__c', 'Member_Contact__c'})){
            //Send Emails to Participant                                 
            participantList = new Map<Id, Participant__c>([SELECT Id, Status__c, Event__r.Do_Not_Send_Event_Confirmation_email__c, 
                                                           Event__c, Member_Contact__c, Member_Contact__r.Email, Process_from_Event_Page__c,
                                                           (SELECT Id, Status__c, Participant__c FROM Session_Participants__r)
                                                           FROM Participant__c WHERE Id IN: participantIdSet]); 
        }*/

        //CCN-1551 XEN REYES 29 April 2022
        /* List<Participant__c> participantInvited = new List<Participant__c>();
        Map<String, List<Participant__c>> participantMap =  new Map<String, List<Participant__c>>();
        Set<Id> eventIds = new Set<Id>();
        for(Participant__c participant: participantList.values()){
            if(!participant.Event__r.Do_Not_Send_Event_Confirmation_email__c &&
               participant.Status__c == UtilityConstant.PARTICIPANT_STATUS_REGISTERED){
                if(participantMap.containsKey(UtilityConstant.PARTICIPANT_STATUS_REGISTERED)){
                    List<Participant__c> dataList = participantMap.get(UtilityConstant.PARTICIPANT_STATUS_REGISTERED);
                    dataList.add(participant);
                    eventIds.add(participant.Event__c);
                    participantMap.put(UtilityConstant.PARTICIPANT_STATUS_REGISTERED, dataList);
                }
                else{
                    List<Participant__c> dataList = new List<Participant__c>();
                    dataList.add(participant);
                    eventIds.add(participant.Event__c);
                    participantMap.put(UtilityConstant.PARTICIPANT_STATUS_REGISTERED, dataList);
                }
            }
        }
        
        if(!participantMap.isEmpty()){
            system.debug('debug CCN-1414');
            SessionParticipantTriggerUtility.sendEmailToParticipant(participantMap, eventIds);
        } */
        
        /* CCN-EVE-2500-DV XEN REYES 30Jan2023 */
        if(participantIdSet.size() > 0){
             SessionParticipantTriggerUtility.updateParentParticipantStatus(newSessionParticipantMap, participantIdSet);
        } 
        
        // Start CCN-2466 Von Pernicia: Removed logic
        /*if (updateParticipantMilestoneList.size() > 0) {
            SessionParticipantTriggerUtility.updateParticipantMilestoneMetrics(updateParticipantMilestoneList);
        }
        */
        // End CCN-2466 Von Pernicia: Removed logic
        
        //CCN-1551 XEN REYES 29 April 2022, CCN-1028 XR 27 May 2022
        if(!participantIdSet.isEmpty() && !isFromAttendancePage){
            Set<String> participantIdSetStr = (Set<String>) JSON.deserialize(JSON.serialize(participantIdSet), Set<String>.class);
            Set<String> pptIdsExisting = new Set<String>();
            for(Batch_Processor__c bb : [SELECT Id, Record_Id__c, Parameter_1__c, Type__c FROM Batch_Processor__c 
                                            WHERE Record_Id__c IN: participantIdSetStr 
                                            AND Type__c = 'ParticipantEmailCommunicationBatch'
                                            AND Trigger_Source__c = 'ParticipantTriggerHandler'
                                            AND Parameter_1__c =: UtilityConstant.PARTICIPANT_STATUS_REGISTERED]){
                pptIdsExisting.add(bb.Record_Id__c);
            }

            if(!pptIdsExisting.isEmpty()) participantIdSetStr.removeAll(pptIdsExisting);
            if(!participantIdSetStr.isEmpty()) BatchProcessorUtility.insertBatchRecord(participantIdSetStr,'ParticipantEmailCommunicationBatch','ParticipantTriggerHandler',UtilityConstant.PARTICIPANT_STATUS_REGISTERED);
        }

        /* for(Participant__c participant : [SELECT Id, Send_Event_Registration_Notification__c FROM Participant__c WHERE Id IN :participantIdSet]) {
            participant.Send_Event_Registration_Notification__c = true;
            participantsToUpdate.add(participant);
            System.debug('$$$$ participant.Send_Event_Registration_Notification__c: ' + participant.Send_Event_Registration_Notification__c);
        }

        System.debug('$$$$ participantsToUpdate: ' + participantsToUpdate);
        
        // update participantsToUpdate;
        List<Database.SaveResult> updRes = Database.update(participantsToUpdate);
        System.debug('$$$$ updRes: ' + updRes);

        // System.assert(false); */
                                                                         
    }
    
    /******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyy) Author            Description
    *           ----  ---------   --------------------  -----------------------------
    * @version   1.0  ??           ??                   Initial version.
    * @version   2.0  29-01-2022   VonPernicia          [CCN-496] Added new method "updateParticipantMilestoneMetrics" to call to update Participant Milestone Metics
    *            3.0  23-03-2022   Paolo Quiambao       [CCN934] Replace Domain Name with Domain Name (Event Registration)
    *            4.0  26-06-2022   Von Pernicia         [CCN-EVE-1719-DV] This will pull all canceled session partcipant record to create and send canceled email notification.
    *            5.0  07-07-2022   Rianno Rizarri       [CCN-EVE-1834-DV] Added new method SessionParticipantTriggerUtility.countSessionPartipants to call the method
    * @version   6.0  17-08-2022   JC Espino            [CCN-EVE-1726-DV] Added criteria of when to send Calendar Invite
    * @version   6.0  12-01-2022   Von Pernicia         [CCN-2466] Remove logic that creates records in Batch_Processor__c
    ******************************************************************************/
    public static void onAfterUpdate(List<Session_Participant__c> newSessionParticipantList, Map<Id,Session_Participant__c> newSessionParticipantMap, 
                                     List<Session_Participant__c> oldSessionParticipantList, Map<Id,Session_Participant__c> oldSessionParticipantMap){
            //Start CCN-EVE-1834-DV: Rianno Rizarri
			SessionParticipantTriggerUtility.countSessionPartipants(newSessionParticipantList);
            //End CCN-EVE-1834-DV: Rianno Rizarri
            Set<Id> participantIdSet = new Set<Id>();
			//Gabriel Delvin *08-10-2023* CCN-EVE-3426-DV
            SessionParticipantTriggerUtility.updateContactTitleRank(newSessionParticipantList);
            // Start CCN-2466 Von Pernicia: Removed logic
            //List<Session_Participant__c> updateParticipantMilestoneList = new List<Session_Participant__c>();
            // End CCN-2466 Von Pernicia: Removed logic

            List<Session_Participant__c> sessPartEmailCanceledRec = new List<Session_Participant__c>();
            // UPDATED BY JC ESPINO AUG162022 [CCN-EVE-1726-DV]
            Map<Id, List<Session_Participant__c>> eventToParticipantsMap = new Map<Id, List<Session_Participant__c>>();

            for(Session_Participant__c sessionParticipant: newSessionParticipantList){
                if(sessionParticipant.Status__c != oldSessionParticipantMap.get(sessionParticipant.Id).Status__c && sessionParticipant.Status__c == 'Confirmed'){
                    // UPDATED BY JC ESPINO AUG162022 [CCN-EVE-1726-DV] - Added mechanism to check Event field Session_Calendar_Invite_Delivery__c

                    if(!eventToParticipantsMap.containsKey(sessionParticipant.Event__c)) {
                        eventToParticipantsMap.put(sessionParticipant.Event__c, new List<Session_Participant__c>());
                    }
                    eventToParticipantsMap.get(sessionParticipant.Event__c).add(sessionParticipant);        
                    // END [CCN-EVE-1726-DV]
                }
                
                // Start CCN-2466 Von Pernicia: Removed logic
                /*if(sessionParticipant.Status__c != oldSessionParticipantMap.get(sessionParticipant.Id).Status__c && sessionParticipant.Status__c == 'Attended'){
                    updateParticipantMilestoneList.add(sessionParticipant);
                }*/
                // End CCN-2466 Von Pernicia: Removed logic

                // Start CCN-EVE-1719-DV: Von 
                if(sessionParticipant.Status__c != oldSessionParticipantMap.get(sessionParticipant.Id).Status__c && sessionParticipant.Status__c == 'Canceled'){
                    sessPartEmailCanceledRec.add(sessionParticipant);
                }
                // End CCN-EVE-1719-DV: Von 
                
                participantIdSet.add(sessionParticipant.Participant__c);
            }
                                         
            // UPDATED BY JC ESPINO AUG162022 [CCN-EVE-1726-DV] - gets participants with the correct event settings to send calendar invite
            if(!eventToParticipantsMap.isEmpty()) {
                sendInvites(eventToParticipantsMap);
            }

            // Start CCN-EVE-1719-DV: Von 
            if(!sessPartEmailCanceledRec.isEmpty()){
                SessionParticipantTriggerUtility.sendCalendarCancelation(sessPartEmailCanceledRec);
            }
            // End CCN-EVE-1719-DV: Von
            
            /* CCN-EVE-2500-DV XEN REYES 30Jan2023 */
            /* Map<Id, Participant__c> participantList = new Map<Id, Participant__c>();
            if(FlsUtils.isAccessible('Participant__c', new List<String>{'Status__c', 'Event__c', 'Member_Contact__c'})){                             
                participantList = new Map<Id, Participant__c>([SELECT Id, Status__c, Event__r.Do_Not_Send_Event_Confirmation_email__c, 
                                                               Event__c, Member_Contact__c, Member_Contact__r.Email, Process_from_Event_Page__c,
                                                               (SELECT Id, Status__c, Participant__c FROM Session_Participants__r)
                                                               FROM Participant__c WHERE Id IN: participantIdSet]); 
            } */
            
            /* CCN-EVE-2500-DV XEN REYES 30Jan2023 */
            if(participantIdSet.size() > 0){
                 SessionParticipantTriggerUtility.updateParentParticipantStatus(newSessionParticipantMap, participantIdSet);
            }          
            
            // Start CCN-2466 Von Pernicia: Removed logic
            /*if (updateParticipantMilestoneList.size() > 0) {
                SessionParticipantTriggerUtility.updateParticipantMilestoneMetrics(updateParticipantMilestoneList);
            }*/
            // End CCN-2466 Von Pernicia: Removed logic
            /* Commented out just for deployment, will remove comment after
            //ADDED BY FRANCIS BAGTAS Feb 09 2022 to Log Interaction Record
            List<InteractionTriggerHandler.InteractionWrapper> InteractionWrapperList = new List<InteractionTriggerHandler.InteractionWrapper>();
            InteractionTriggerHandler.InteractionWrapper wrappInteraction;
            for(Session_Participant__c sessionParticipant : [SELECT Id,Event__r.Campaign__c,Event__c,Session__c,Contact__c,Status__c FROM Session_Participant__c WHERE ID IN: newSessionParticipantMap.keySet()]){// Query the Session Participant Object and related/lookup object information
               // If Status field is updated Log Interaction as Session Interaction
                if(sessionParticipant.Status__c != oldSessionParticipantMap.get(sessionParticipant.Id).Status__c){
                  wrappInteraction = new InteractionTriggerHandler.InteractionWrapper();
                    wrappInteraction.recordTypeName = 'Session Interaction';
              wrappInteraction.campaignId = sessionParticipant.Event__r.Campaign__c;
              wrappInteraction.eventId = sessionParticipant.Event__c;
              wrappInteraction.sessionId = sessionParticipant.Session__c;
              wrappInteraction.contactId = sessionParticipant.Contact__c;
                    wrappInteraction.status = sessionParticipant.Status__c;
                    
                    InteractionWrapperList.add(wrappInteraction);
                }
            }
            InteractionTriggerHandler.createInteractionRecord(InteractionWrapperList);
      */
    }
    
    
    public static void onBeforeInsert(List<Session_Participant__c> newSessionParticipantList, Map<Id,Session_Participant__c> newSessionParticipantMap, 
                                      List<Session_Participant__c> oldSessionParticipantList, Map<Id,Session_Participant__c> oldSessionParticipantMap){
            
            // Updated by Paolo Quiambao [CCN-934] Mar232021
            //Compass_Setting__c compassSetting = [SELECT Id, Domain_Name_Event_Registration__c FROM Compass_Setting__c WHERE Name = 'Default Settings' LIMIT 1];
            
      //This is the old logic for 934, to be removed. Brought back so we can test 1191
            Compass_Setting__c compassSetting = [SELECT Id, Domain_Name__c FROM Compass_Setting__c WHERE Name = 'Default Settings' LIMIT 1];

            Set<Id> sessionIdSet = new Set<Id>();
            Map<Id, Session__c> sessionMap = new Map<Id, Session__c>();
            
            for(Session_Participant__c sessionParticipant : newSessionParticipantList) {
                // Updated by Paolo Quiambao [CCN-934] Mar232021
                //sessionParticipant.Domain_Name__c = compassSetting.Domain_Name_Event_Registration__c;

        //This is the old logic for 934, to be removed. Brought back so we can test 1191
                sessionParticipant.Domain_Name__c = compassSetting.Domain_Name__c;
                sessionIdSet.add(sessionParticipant.Session__c);
            }
                                          
            for(Session__c session : [SELECT Id, Session_Attendance_Thank_You_Message__c, Session_Catchup_Message__c, Session_Catchup_Reminder_Message__c, Session_Catchup_Thank_You_Message__c FROM Session__c WHERE Id IN :sessionIdSet]) {
                sessionMap.put(session.Id, session);                                              
            }
                    
            // Updated by Paolo Quiambao [CCN-981] Dec062021
            for(Session_Participant__c sessionParticipant : newSessionParticipantList) {
                sessionParticipant.Session_Attendance_Thank_You_Message__c = sessionMap.get(sessionParticipant.Session__c).Session_Attendance_Thank_You_Message__c;
                sessionParticipant.Session_Catchup_Message__c = sessionMap.get(sessionParticipant.Session__c).Session_Catchup_Message__c;
                sessionParticipant.Session_Catchup_Reminder_Message__c = sessionMap.get(sessionParticipant.Session__c).Session_Catchup_Reminder_Message__c;
                sessionParticipant.Session_Catchup_Thank_You_Message__c = sessionMap.get(sessionParticipant.Session__c).Session_Catchup_Thank_You_Message__c;
                
                // Updated by Paolo Quiambao [CCN-EVE-1219-DV] Apr252022
                if(sessionParticipant.Status__c == 'Confirmed') {
                    sessionParticipant.Confirmed_Date__c = System.now();
                }
                else if(sessionParticipant.Status__c == 'Declined') {
                    sessionParticipant.Declined_Date__c = System.now();
                }

                // UPDATED BY JC Espino [CCN-1038] MAY 24 2022
                if(sessionParticipant.Status__c == 'Attended') {
                    sessionParticipant.Attendance_Date__c = System.now();
                }
            }
    }
    
    
    /******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyy) Author            Description
    *           ----  ---------   --------------------  -----------------------------
    * @version   1.0  ??           ??                   Initial version.
    * @version   2.0  17-06-2022   VonPernicia          [CCN-EVE-1773-DV] Added new condition if status to populate Canceled Date if status is set to canceled
    ******************************************************************************/
    public static void onBeforeUpdate(List<Session_Participant__c> newSessionParticipantList, Map<Id,Session_Participant__c> newSessionParticipantMap, 
                                      List<Session_Participant__c> oldSessionParticipantList, Map<Id,Session_Participant__c> oldSessionParticipantMap){
        
        // Updated by Paolo Quiambao [CCN-EVE-1219-DV] Apr252022
        for(Session_Participant__c sessionParticipant : newSessionParticipantList) {
            if(oldSessionParticipantMap.get(sessionParticipant.Id).Status__c != sessionParticipant.Status__c && sessionParticipant.Status__c == 'Confirmed' && sessionParticipant.Confirmed_Date__c == null) {
                sessionParticipant.Confirmed_Date__c = System.now();
            }
            else if(oldSessionParticipantMap.get(sessionParticipant.Id).Status__c != sessionParticipant.Status__c && sessionParticipant.Status__c == 'Declined' && sessionParticipant.Declined_Date__c == null) {
                sessionParticipant.Declined_Date__c = System.now();
            }

            // UPDATED BY JC Espino [CCN-1038] MAY 24 2022
            if(sessionParticipant.Attendance_Date__c == null && 
                (oldSessionParticipantMap.get(sessionParticipant.Id).Status__c != 'Attended' && sessionParticipant.Status__c == 'Attended')) {
                sessionParticipant.Attendance_Date__c = System.now();
            }

            // CCN-EVE-1773-DV: Von Pernicia
            if(sessionParticipant.Canceled_Date__c == null && 
                (oldSessionParticipantMap.get(sessionParticipant.Id).Status__c != 'Canceled' && sessionParticipant.Status__c == 'Canceled')) {
                sessionParticipant.Canceled_Date__c = System.now();
            }
        }
    }
    
    /*public static void onBeforeDelete(List<Session_Participant__c> newSessionParticipantList, Map<Id,Session_Participant__c> newSessionParticipantMap, 
                                      List<Session_Participant__c> oldSessionParticipantList, Map<Id,Session_Participant__c> oldSessionParticipantMap){
    }  
    public static void onAfterUndelete(List<Session_Participant__c> newSessionParticipantList, Map<Id,Session_Participant__c> newSessionParticipantMap, 
                                       List<Session_Participant__c> oldSessionParticipantList, Map<Id,Session_Participant__c> oldSessionParticipantMap){
    }  
    */
    /******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyy) Author            Description
    * @version   1.0  07-07-2022   Rianno Rizarri       Initial version. [CCN-EVE-1834-DV] Added new method SessionParticipantTriggerUtility.countSessionPartipants to call the method
    ******************************************************************************/
      public static void onAfterDelete(List<Session_Participant__c> newSessionParticipantList, Map<Id,Session_Participant__c> newSessionParticipantMap,
                                       List<Session_Participant__c> oldSessionParticipantList, Map<Id,Session_Participant__c> oldSessionParticipantMap){
                                           //Start CCN-EVE-1834-DV: Rianno Rizarri
                                           SessionParticipantTriggerUtility.countSessionPartipants(newSessionParticipantList);
                                           //End CCN-EVE-1834-DV: Rianno Rizarri
    }

    /******************************************************************************    
    * Changes (version)
    *            No.  Date(dd-mm-yyy) Author            Description
    * @version   1.0  17-08-2022      JC Espino         Initial version. [CCN-EVE-1726-DV] New method to send calendar invites on Session Confirmation
    ******************************************************************************/
    public static void sendInvites(Map<Id, List<Session_Participant__c>> participantsMap) {
        List<Session_Participant__c> sessPartEmailRec = new List<Session_Participant__c>();
        Map<Id, Event__c> eventsMap = new Map<Id, Event__c>([SELECT Id, Session_Calendar_Invite_Delivery__c FROM Event__c WHERE Id IN :participantsMap.keySet() AND Session_Calendar_Invite_Delivery__c = 'Send on session confirmation']);

        for(Id eventId : eventsMap.keySet()) {
            sessPartEmailRec.addAll(participantsMap.get(eventId));
        }

        if(!sessPartEmailRec.isEmpty()){
            SessionParticipantTriggerUtility.sendCalendarInvite(sessPartEmailRec);
        }
    }
}