main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Project_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Tasks (Contact)</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/QA_Task__c.field-meta.xml
<CustomField>
    <fullName>QA_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QA Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Project Tasks (QA Task)</relationshipLabel>
    <relationshipName>QA_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Test_Execution__c.field-meta.xml
<CustomField>
    <fullName>Test_Execution__c</fullName>
    <label>Test Execution</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Project_Task__c/recordTypes/QA.recordType-meta.xml
<RecordType>
    <fullName>QA</fullName>
    <active>true</active>
    <label>QA</label>
</RecordType>

main/default/objects/Test_Execution__c/Test_Execution__c.object-meta.xml
<CustomObject>
    <label>Test Execution</label>
    <nameField>
        <label>Test Execution Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Test_Execution__c/fields/Actual_Results__c.field-meta.xml
<CustomField>
    <fullName>Actual_Results__c</fullName>
    <description>Test Execution Actual Results</description>
    <label>Actual Results</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/From_Test_Execution_Button__c.field-meta.xml
<CustomField>
    <fullName>From_Test_Execution_Button__c</fullName>
    <defaultValue>false</defaultValue>
    <label>From Test Execution Button</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/IsClone__c.field-meta.xml
<CustomField>
    <fullName>IsClone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Clone</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/QA_Task__c.field-meta.xml
<CustomField>
    <fullName>QA_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QA Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Test Executions (QA Task)</relationshipLabel>
    <relationshipName>Test_Executions3</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Testing_Phase__c.field-meta.xml
<CustomField>
    <fullName>Testing_Phase__c</fullName>
    <description>Identifies the phase in the testing process</description>
    <label>Testing Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>System Integration Testing</fullName>
                <label>SIT</label>
            </value>
            <value>
                <fullName>User Acceptance Testing</fullName>
                <label>UAT</label>
            </value>
            <value>
                <fullName>Prod Smoke Testing</fullName>
                <label>SMOKE</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/TestExecutionTriggerHandler.cls
public class TestExecutionTriggerHandler {
    
    public static void onBeforeInsert(List<Test_Execution__c> newTestExecutionTaskList, Map<Id,Test_Execution__c> newTestExecutionTaskMap, List<Test_Execution__c> oldTestExecutionTaskList, Map<Id,Test_Execution__c> oldTestExecutionTaskMap){
        
        Set<Id> QATaskIds = new Set<Id>();
        List<Test_Execution__c> testExecutionFromButtonList = new List<Test_Execution__c>();
        
        for (Test_Execution__c testExecRecord : newTestExecutionTaskList){
            //START - CAPM-PMG-929-DV - MGP - 11/4/2023
            //if (testExecRecord.From_Test_Execution_Button__c
            if (testExecRecord.From_Test_Execution_Button__c && !testExecRecord.isClone() && !testExecRecord.IsClone__c){
                if(testExecRecord.Assigned_To__c == null){
                    testExecRecord.addError('Assigned To is required. Kindly complete the field.');
                }else{
                    testExecRecord.OwnerId = testExecRecord.Assigned_To__c;
                    testExecutionFromButtonList.add(testExecRecord);
                    QATaskIds.add(testExecRecord.QA_Task__c);
                }
                
            }else if(testExecRecord.isClone() || testExecRecord.IsClone__c){
                if(!testExecRecord.IsClone__c){
                    testExecRecord.Assigned_To__c = null;
                    testExecRecord.Testing_Phase__c = 'Other';
                }
                
                testExecRecord.Actual_Results__c = null;
                
                QATaskIds.add(testExecRecord.QA_Task__c);
                formatTestExecutionFromQA(newTestExecutionTaskList, QATaskIds);
            }//END - CAPM-PMG-929-DV - MGP - 11/4/2023
        }
        
        if(!testExecutionFromButtonList.isEmpty() && !QATaskIds.isEmpty()){
            formatTestExecutionFromQA(testExecutionFromButtonList, QATaskIds);
        }
        
    }
    
    
    public static void formatTestExecutionFromQA(List<Test_Execution__c> newTestExecutionList, Set<Id> QATaskIds){
        Map<String, Integer> mapOfTENamesAndCount = new Map<String, Integer>();
        Integer counter = 1;
        Map<String, String> testingPhaseMap = new Map<String, String>{'System Integration Testing' => 'SIT', 'User Acceptance Testing' => 'UAT', 'Prod Smoke Testing' => 'SMOKE', 'Other' => 'Other'};
            Map<Id, Test_Execution__c> testExecutionCountMap = new Map<Id, Test_Execution__c>([SELECT Id, Test_Execution__c.Name, QA_Task__c, Testing_Phase__c, Assigned_To__c, QA_Task__r.Name FROM Test_Execution__c WHERE QA_Task__c IN: QATaskIds]);
        System.debug('TECountmap: '+testExecutionCountMap.size());
        for (Test_Execution__c tee : testExecutionCountMap.values()){
            String teKey = (String.isNotBlank(tee.Name) ? extractSubstringUntilQA(tee.Name) : tee.Name)  + '-TE-' + testingPhaseMap.get(tee.Testing_Phase__c);
            String testExecutionNameFormat =  teKey + ';' + tee.QA_Task__c ;
            if(mapOfTENamesAndCount.containsKey(testExecutionNameFormat)){
                mapOfTENamesAndCount.put(testExecutionNameFormat, mapOfTENamesAndCount.get(testExecutionNameFormat)+1);
            }else{
                mapOfTENamesAndCount.put(testExecutionNameFormat, 1);
            }        
        }
        for(Test_Execution__c te: newTestExecutionList){
            String teKey = (String.isNotBlank(te.Name) ? extractSubstringUntilQA(te.Name) : te.Name)  + '-TE-' + testingPhaseMap.get(te.Testing_Phase__c);
            
            
            if(!mapOfTENamesAndCount.containsKey(teKey+';'+te.QA_Task__c)){
                mapOfTENamesAndCount.put(teKey+';'+te.QA_Task__c, 1);
                te.Name = teKey + '-' + 1 ; 
            }else{
                te.Name = teKey + '-' + (mapOfTENamesAndCount.get(teKey+';'+te.QA_Task__c)+1) ;
                mapOfTENamesAndCount.put((teKey+';'+te.QA_Task__c),mapOfTENamesAndCount.get(teKey+';'+te.QA_Task__c) + 1);
            }
            
            //START - CAPM-PMG-929-DV - MGP - 11/4/2023
            
        }
    }
    
    public static String extractSubstringUntilQA(String input) {
        Integer index = input.indexOf('-QA');
        if (index != -1) {
            return input.substring(0, index + 3); // Include "QA-" in the result
        }
        return input; // Return the original string if "QA-" is not found
    }
    
}