main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Project_Task__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipName>Project_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Release_Item__c/Release_Item__c.object-meta.xml
<CustomObject>
    <label>Release Item</label>
    <nameField>
        <displayFormat>RI{00000}</displayFormat>
        <label>Release Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Release_Item__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Release Items</relationshipLabel>
    <relationshipName>Release_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Release_Item__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Release Items</relationshipLabel>
    <relationshipName>Release_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Release_Item__c/fields/Release_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>Release_Item_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Release_Item_Status</valueSetName>
    </valueSet>
</CustomField>

main/default/globalValueSets/Release_Item_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Ready</fullName>
    </customValue>
    <customValue>
        <fullName>For Release (UAT)</fullName>
    </customValue>
    <customValue>
        <fullName>For Release (Demo)</fullName>
    </customValue>
    <customValue>
        <fullName>For Release (Prod)</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Blocked</fullName>
    </customValue>
    <customValue>
        <fullName>Deployed</fullName>
        <isActive>false</isActive>
        <label>Deployed</label>
    </customValue>
    <customValue>
        <fullName>In Deployment</fullName>
        <isActive>false</isActive>
        <label>In Deployment</label>
    </customValue>
    <customValue>
        <fullName>Ready for Deployment</fullName>
        <isActive>false</isActive>
        <label>Ready for Deployment</label>
    </customValue>
    <customValue>
        <fullName>In UAT Testing</fullName>
        <isActive>false</isActive>
        <label>In UAT Testing</label>
    </customValue>
    <customValue>
        <fullName>In Unit Testing</fullName>
        <isActive>false</isActive>
        <label>In Unit Testing</label>
    </customValue>
    <customValue>
        <fullName>In Development</fullName>
        <isActive>false</isActive>
        <label>In Development</label>
    </customValue>
    <customValue>
        <fullName>In Smoke Testing</fullName>
        <isActive>false</isActive>
        <label>In Smoke Testing</label>
    </customValue>
    <masterLabel>Release Item Status</masterLabel>
</GlobalValueSet>

main/default/classes/ReleaseItemTriggerHandler.cls
public class ReleaseItemTriggerHandler {
    public static boolean bPreventAI = false;
    public static boolean bPreventAU = false;
    public static boolean bPreventBI = false;
    public static boolean bPreventBU = false;
   
    public static void onBeforeInsert(List<Release_Item__c> newReleaseItemList,Map<Id, Release_Item__c> newReleaseItemMap,List<Release_Item__c> oldReleaseItemList, Map<Id, Release_Item__c> oldReleaseItemMap){
        Set<Id> releaseItemIds = releaseItemId(newReleaseItemList);
        if(releaseItemIds.Size() > 0){
            ReleaseItemTriggerUtility.updateReleaseItemDate(releaseItemIds, newReleaseItemList);
        }
    }
    
    public static void onBeforeUpdate(List<Release_Item__c> newReleaseItemList, Map<Id, Release_Item__c> newReleaseItemMap, List<Release_Item__c> oldReleaseItemList, Map<Id, Release_Item__c> oldReleaseItemMap){
        Set<Id> releaseItemIds = releaseItemId(newReleaseItemList);
        if(releaseItemIds.Size() > 0){
            ReleaseItemTriggerUtility.updateReleaseItemDate(releaseItemIds, newReleaseItemList);
        }
    }
    
    public static void onAfterInsert(List<Release_Item__c> newReleaseItemList, Map<Id, Release_Item__c> newReleaseItemMap, List<Release_Item__c> oldReleaseItemList, Map<Id, Release_Item__c> oldReleaseItemMap){
        Set<Id> devTaskToUpdate = devTaskId(newReleaseItemList);
        if(devTaskToUpdate.Size() > 0){
            ReleaseItemTriggerUtility.updateDevStatusToComplete(devTaskToUpdate);
        }
    }
    
    public static void onAfterUpdate(List<Release_Item__c> newReleaseItemList, Map<Id, Release_Item__c> newReleaseItemMap, List<Release_Item__c> oldReleaseItemList, Map<Id, Release_Item__c> oldReleaseItemMap){
        Set<Id> devTaskToUpdate = devTaskId(newReleaseItemList);
        if(devTaskToUpdate.Size() > 0){
            ReleaseItemTriggerUtility.updateDevStatusToComplete(devTaskToUpdate);
        }
    }
    
    /*
    public static void onAfterDelete(List<Release_Item__c> newReleaseItemList, Map<Id,Release_Item__c> newReleaseItemMap, List<Release_Item__c> oldReleaseItemList, Map<Id,Release_Item__c> oldReleaseItemMap){
    }
    public static void onBeforeDelete(List<Release_Item__c> newReleaseItemList, Map<Id,Release_Item__c> newReleaseItemMap, List<Release_Item__c> oldReleaseItemList, Map<Id,Release_Item__c> oldReleaseItemMap){
    }
    public static void onAfterUndelete(List<Release_Item__c> newReleaseItemList, Map<Id,Release_Item__c> newReleaseItemMap, List<Release_Item__c> oldReleaseItemList, Map<Id,Release_Item__c> oldReleaseItemMap){
    }*/
    
    public static Set<Id> devTaskId (List<Release_Item__c> releaseItemList){
        Set<Id> devTaskToUpdate = new Set<Id>();
        for(Release_Item__c releaseItem : releaseItemList){  
            if(releaseItem.Release_Item_Status__c == 'Completed' || releaseItem.Release_Item_Status__c == 'Closed'){
                devTaskToUpdate.add(releaseItem.Project_Task__c);
            }
        }
        return devTaskToUpdate;
    }
    
    public static Set<Id> releaseItemId (List<Release_Item__c> releaseItemList){
        Set<Id> releaseItemsToUpdate = new Set<Id>();
        for(Release_Item__c releaseItem : releaseItemList){
            If(String.IsBlank(String.valueof(releaseItem.Release_Date__c)) && releaseItem.Release__c != null){
                releaseItemsToUpdate.add(releaseItem.Id);
            }
        }
        return releaseItemsToUpdate;
    }

}