main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Project_Task__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipName>Project_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Sign_off_Technical_Review__c.field-meta.xml
<CustomField>
    <fullName>Sign_off_Technical_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sign-off (Technical Review)</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To identify the current status of Project task</description>
    <inlineHelpText>For TR: For Technical Review, For UI/UX
For QA: For Quality Assurance</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Estimate</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>For TR</fullName>
            </value>
            <value>
                <fullName>For QA</fullName>
            </value>
            <value>
                <fullName>For Release</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>SIT</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Prod Validation</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress - Off-Track</fullName>
            </value>
            <value>
                <fullName>In Progress - At Risk</fullName>
            </value>
            <value>
                <fullName>In Progress - On-Track</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Release_Item__c/Release_Item__c.object-meta.xml
<CustomObject>
    <label>Release Item</label>
    <nameField>
        <displayFormat>RI{00000}</displayFormat>
        <label>Release Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Release_Item__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Release Items</relationshipLabel>
    <relationshipName>Release_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Release_Item__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Release Items</relationshipLabel>
    <relationshipName>Release_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Release_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Blocked</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

main/default/classes/ReleaseItemTriggerUtility.cls
public class ReleaseItemTriggerUtility {
    public static void updateDevStatusToComplete(Set<Id> DevTaskIdSet){
        List<Project_Task__c> projTaskList = [Select Id, Status__c from Project_Task__c where Id IN: DevTaskIdSet];
        for(Project_Task__c projTaskRec: projTaskList){
            projTaskRec.Sign_off_Technical_Review__c = true;
            //10/05/2023 - Updated by MGP - CAPM-PMG-877-DV
            //projTaskRec.Status__c = 'Completed';
            projTaskRec.Status__c = 'Deployed';
        }
        database.update(projTaskList);
    }
    
    public static void updateReleaseItemDate(Set<Id> releaseItemId, List<Release_Item__c> releaseItemList){
        Map<Id,Date> releaseItemMap = new Map<Id,Date>();
        List<Release_Item__c> releaseItemListToUpdate = [Select Id, Release_Date__c, Release__c, Release__r.Release_Date__c from Release_Item__c where Id IN: releaseItemId];
        for(Release_Item__c releaseItemRec: releaseItemListToUpdate){
            releaseItemMap.put(releaseItemRec.Id, releaseItemRec.Release__r.Release_Date__c); 
        }
        for(Release_Item__c releaseItemRec: releaseItemList){
            releaseItemRec.Release_Date__c = releaseItemMap.get(releaseItemRec.Id);
        }
    }
}