main/default/objects/Outreach_Notification__c/Outreach_Notification__c.object-meta.xml
<CustomObject>
    <description>Links to the related notification settings and record that will use the settings</description>
    <label>Outreach Notification</label>
    <nameField>
        <label>Outreach Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describes the Outreach Notification</description>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/Outreach_Notification_Setting__c.object-meta.xml
<CustomObject>
    <description>Contains the configuration that will be used for each compass objects</description>
    <label>Outreach Notification Setting</label>
    <nameField>
        <label>Outreach Notification Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outreach Notification Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Outreach_Notification_Setting__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Describes the purpose of the notification</description>
    <label>Description</label>
    <length>250</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/L1_Days__c.field-meta.xml
<CustomField>
    <fullName>L1_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Level 1 Notification:
The number of days prior to Event/Session Start Date.</description>
    <inlineHelpText>Level 1 Notification:
A number of days prior to Event/Session Start Date or Catchup Start Date.</inlineHelpText>
    <label>L1 Days</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Outreach_Notification__c.field-meta.xml
<CustomField>
    <fullName>Outreach_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Outreach Notifiocation record</description>
    <label>Outreach Notification</label>
    <referenceTo>Outreach_Notification__c</referenceTo>
    <relationshipLabel>Outreach Notification Settings</relationshipLabel>
    <relationshipName>Outreach_Notification_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Outreach_Notification_Setting__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Notification Type</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Invitation Registration Reminder</fullName>
            </value>
            <value>
                <fullName>Registration Confirmation Reminder</fullName>
            </value>
            <value>
                <fullName>Session Attendance Thank you</fullName>
            </value>
            <value>
                <fullName>Session Catchup</fullName>
            </value>
            <value>
                <fullName>Session Catchup Reminder</fullName>
            </value>
            <value>
                <fullName>Session Catchup Thank you</fullName>
            </value>
            <value>
                <fullName>Survey Catchup</fullName>
            </value>
            <value>
                <fullName>Survey Catchup Reminder</fullName>
            </value>
            <value>
                <fullName>Survey Reminder</fullName>
            </value>
            <value>
                <fullName>Survey Thank You</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/ONSEmailSenderControllerTest.cls
/*******************************************************************************************
  * @name: ONSEmailSenderControllerTest
  * @author: Paolo Quiambao
  * @created: 20-12-2021
  * @description: Test class to cover the ONSEmailSenderController Apex Class
  *
  * Changes (version)
  * -------------------------------------------------------------------------------------------
  *       		No.   Date(dd-mm-yyy) 	Author         	   	  Description
  *       		----  ---------------   --------------------  -----------------------------
  * @version    1.0   20-1-2021   		Paolo Quiambao        [CCN856] Initial version.
  *********************************************************************************************/
@isTest
public class ONSEmailSenderControllerTest {
    @testSetup 
    static void setupData() {
        Outreach_Notification__c outreachNotif = new Outreach_Notification__c(Name = 'Test', Description__c = 'Test');
        insert outreachNotif;
        
        Outreach_Notification_Setting__c ons = new Outreach_Notification_Setting__c(Name = 'Test', Description__c = 'Test', Type__c = 'Invitation Registration Reminder', Outreach_Notification__c = outreachNotif.Id, L1_Days__c = 1);
        insert ons;
    }
    
    @isTest
    static void getSelectedEmailTemplates_shouldReturnOrgWideAddresses_whenCalled() {
        Outreach_Notification_Setting__c ons = [SELECT Id FROM Outreach_Notification_Setting__c LIMIT 1];
        
        Test.startTest();
        PageReference pageRef = Page.ONSEmailSenderPage; 
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(ons.Id));
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ons);
        ONSEmailSenderController con = new ONSEmailSenderController(sc);
        List<SelectOption> selectOptionList = con.getSelectedOrgWideAddress();
        Test.stopTest();
        
        System.assertNotEquals(0, selectOptionList.size(), 'No Org Wide Addresses were returned');
    }
    
    @isTest
    static void save_shouldPopulateEmailSenderId_whenCalled() {
        Outreach_Notification_Setting__c ons = [SELECT Id FROM Outreach_Notification_Setting__c LIMIT 1];
        
        Test.startTest();
        PageReference pageRef = Page.ONSEmailSenderPage; 
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(ons.Id));
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ons);
        ONSEmailSenderController con = new ONSEmailSenderController(sc);
        con.orgWideAddress = String.valueOf([SELECT Id, Address, DisplayName FROM OrgWideEmailAddress LIMIT 1].Id);
        con.save();
        Test.stopTest();
        
        Outreach_Notification_Setting__c onsUpdated = [SELECT Id, Email_Sender_Id__c FROM Outreach_Notification_Setting__c LIMIT 1];
        System.assertNotEquals(null, onsUpdated.Email_Sender_Id__c, 'Email Sender Id is not populated.');
    }
    
    @isTest
    static void testSaveWithException() {
        Outreach_Notification_Setting__c ons = [SELECT Id, Email_Sender_Id__c FROM Outreach_Notification_Setting__c LIMIT 1];
        
        Test.startTest();
        PageReference pageRef = Page.ONSEmailSenderPage; 
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', String.valueOf(ons.Id));
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ons);
        ONSEmailSenderController con = new ONSEmailSenderController(sc);
        con.orgWideAddress = String.valueOf([SELECT Id, Address, DisplayName FROM OrgWideEmailAddress LIMIT 1].Id);
        delete ons;
        con.save();
        Test.stopTest();
        
        System.assertEquals(null, ons.Email_Sender_Id__c, 'Method did not have an exception.');
    }
}