main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Email_Template_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Registration_Id__c</fullName>
    <label>Email Template - Registration Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Do_Not_Send_Event_Confirmation_email__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Send_Event_Confirmation_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Send Event Confirmation email</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Member_Contact__c.field-meta.xml
<CustomField>
    <fullName>Member_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Event_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Participant__c/fields/Send_Event_Registration_Notification__c.field-meta.xml
<CustomField>
    <fullName>Send_Event_Registration_Notification__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Send Event Registration Notification</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Participant__c/recordTypes/Participant.recordType-meta.xml
<RecordType>
    <fullName>Participant</fullName>
    <active>true</active>
    <label>Participant</label>
</RecordType>

main/default/classes/BatchParticipantSendEmail.cls
/*******************************************************************************************
* @name: BatchParticipantSendEmail
* @author: DinoBrinas
* @created: 01-02-2022
* @description: [CCN1153] This is batch to Send the Email
*
* Changes (version)
* -------------------------------------------------------------------------------------------
*           No.   Date(dd-mm-yyy)   Author                   Description
*           ----  ---------         --------------------    -----------------------------
* @version   1.0  01-02-2022        DinoBrinas               Initial version.
*********************************************************************************************/
global class BatchParticipantSendEmail implements Database.Batchable<SObject>, Database.Stateful{
    public String strQuery;
    public Map<Id, Event__c> eventsMap;
    public Map<Id, OrgWideEmailAddress> owea;
    public Compass_Setting__c compS;
    public Id eventRegistrationTemplate;
    public Set<Id> setParticipantIdstemp;
    public List<Participant__c> listParticipantRecords_UpdateSendEmailCheckbox = new List<Participant__c>();
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        try {
            Set<Id> setParticipantIds = this.setParticipantIdstemp;
            return Database.getQueryLocator(strQuery);
        }catch(Exception e) {
            return null;
        }
    }

    global void execute(Database.BatchableContext BC, List<SObject> objParticipantRecords){
        system.debug('REGISTERED!!!!! ');
        List<Participant__c> listParticipantRecords = (List<Participant__c>)objParticipantRecords;
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>(); 
        for(Participant__c participant: listParticipantRecords){
            if(!(this.eventsMap.get(participant.Event__c).Do_Not_Send_Event_Confirmation_email__c)){
                String emailTemplateId = this.compS.Email_Template_Registration_Id__c != null ? this.compS.Email_Template_Registration_Id__c : this.eventRegistrationTemplate;
                String emailSenderId = this.eventsMap.get(participant.Event__c).Email_Sender_Id__c;
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                message.setOrgWideEmailAddressId(this.eventsMap.get(participant.Event__c).Email_Sender_Id__c);
                message.setSaveAsActivity(false);
                message.setWhatId(participant.Id);
                message.setTemplateId(emailTemplateId);
                message.setTargetObjectId(participant.Member_Contact__c);
                emails.add(message);
            }
            participant.Send_Event_Registration_Notification__c = false;
            listParticipantRecords_UpdateSendEmailCheckbox.add(participant);
        }
        Messaging.sendEmail(emails);
        
    }
    global void finish(Database.BatchableContext BC) {
        if(listParticipantRecords_UpdateSendEmailCheckbox <> null){
            update this.listParticipantRecords_UpdateSendEmailCheckbox;
        }
    }
}