main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Email_Template_Issue_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Issue_Id__c</fullName>
    <label>Email Template - Issue Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/fields/Parking_Lot_User__c.field-meta.xml
<CustomField>
    <fullName>Parking_Lot_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parking Lot User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Issue__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Project_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Issue__c/fields/Issue_Page_URL_c__c.field-meta.xml
<CustomField>
    <fullName>Issue_Page_URL_c__c</fullName>
    <label>Issue_Page_URL__c</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Issue__c/fields/Raised_By__c.field-meta.xml
<CustomField>
    <fullName>Raised_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raised By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Project_Issues1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Issue__c/fields/Raised_By_Email__c.field-meta.xml
<CustomField>
    <fullName>Raised_By_Email__c</fullName>
    <label>Raised By Email</label>
    <type>Email</type>
</CustomField>

main/default/objects/Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>Addressed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/IssueTriggerHandler.cls
/**
@revision Kyzer Buhay - Removed Project in Class name (ProjectIssueTriggerHandler) to IssueTriggerHandler
@revision Rianno Rizarri - Added inner class declared without sharing for guest users to retrieve relevant records.
							For retrieving of existing contacts that matches the email from the issue record.
**/
public class IssueTriggerHandler extends TriggerHandler{
	protected override void beforeInsert(List<SObject> newRecords) {
		defaultRaisedBy(newRecords);
        populateUrl(newRecords);
	}
    
	protected override void beforeUpdate(Map<Id, SObject> updatedRecordsMap, Map<Id, SObject> oldRecordsMap) {
		defaultRaisedBy(getUpdatedRecordsWithChangedFields(new List<sObjectField>{
			Issue__c.Raised_By_Email__c,
			Issue__c.Raised_By__c
		}));
        populateUrl(updatedRecordsMap.values());
	}
    
	protected override void afterUpdate(Map<Id, SObject> updatedRecordsMap, Map<Id, SObject> oldRecordsMap) {
		issueAddressedNotification(updatedRecordsMap, oldRecordsMap);
	}

	private void issueAddressedNotification(Map<Id, SObject> updatedRecordsMap, Map<Id, SObject> oldRecordsMap){
		Compass_Setting__c cs = new Compass_Setting__c();
		Set<Id> eventIds = new Set<Id>();
		Set<Id> contactIds = new Set<Id>();
        Set<Id> issueIdsToNotify = new Set<Id>();
		Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>();
		
		for(Issue__c issue: (List<Issue__c>) updatedRecordsMap.values()){
            Issue__c oldIssue = (Issue__c) oldRecordsMap.get(issue.Id);
			if(issue.Event__c != null){
				eventIds.add(issue.Event__c);
			}
			if(issue.Raised_By__c != null){
				contactIds.add(issue.Raised_By__c);
			}
            //filter issue id to notify
            if(issue.Status__c != oldIssue.Status__c && issue.Status__c == 'Addressed'){
                issueIdsToNotify.add(issue.Id);
            }
		}
        
        if(!issueIdsToNotify.isEmpty()){
			cs = [SELECT Id, Email_Template_Issue_Id__c FROM Compass_Setting__c LIMIT 1];            
            
            Map<Id,Event__c> eventMap = new Map<Id,Event__c>([SELECT Id, Email_Sender_Id__c, Email_Sender_Name__c FROM Event__c WHERE Id IN:eventIds]);
            Map<Id,Contact> contactMap = new Map<Id,Contact>([SELECT Id, Email FROM Contact WHERE Id IN: contactIds]);
            Map<Id,OrgWideEmailAddress> orgWideEmailAddressMap = new Map<Id,OrgWideEmailAddress>([SELECT Id, Address, DisplayName FROM OrgWideEmailAddress LIMIT 200]);
    
            for(Issue__c issue: (List<Issue__c>) updatedRecordsMap.values()){
                if(issueIdsToNotify.contains(issue.Id) && eventMap.containsKey(issue.Event__c)){
                    Event__c eventRec = eventMap.get(issue.Event__c);
                    if(eventRec.Email_Sender_Id__c != null){
                        if(orgWideEmailAddressMap.containsKey(eventRec.Email_Sender_Id__c) && contactMap.containsKey(issue.Raised_By__c)){
                            Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                            message.setTargetObjectId(issue.Raised_By__c); 
                            message.setOrgWideEmailAddressId(orgWideEmailAddressMap.get(eventRec.Email_Sender_Id__c).Id);
                            message.setReplyTo(orgWideEmailAddressMap.get(eventRec.Email_Sender_Id__c).Address);
                            message.setUseSignature(false); 
                            message.setBccSender(false); 
                            message.setSaveAsActivity(true);
                            message.setWhatId(issue.Id);
                            message.setTemplateID(cs.Email_Template_Issue_Id__c);
                            message.toAddresses = new String[] {contactMap.get(issue.Raised_By__c).Email};
                            messages.add(message);
                        }
                    }
                }
            }
		}
		if(!messages.isEmpty()){
			try{
				if(!Test.isRunningTest()){
				Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
				}
			}catch(EmailException e){
				// IF MESSAGE CONTAINS "UNVERIFIED_SENDER_ADDRESS":
				throw new EmailException('Email Sending Failed: UNVERIFIED_SENDER_ADDRESS');
			}
		}
	}

	private void defaultRaisedBy(List<Issue__c> newRecords){
		
		Set<String> emails = new Set<String>();
		// Updated by rrizarri [CCN-857] Oct152021
		// Added a checker to make sure the newRecordsList is not empty
		if(newRecords <> null && newRecords.size() > 0){
			for (Issue__c issue : (List<Issue__c>) newRecords){
				emails.add(issue.Raised_By_Email__c);
			}
		}// end of Edit for [CCN-857]
		
		// Find contacts if it's existing;
		// Updated by rrizarri [CCN-857] Oct152021
		// We utilized without sharing so we can access the existing contacts that guest user can't access
		WithoutSharingClass withoutSharing = new WithoutSharingClass();
		Map<String, Contact> emailContactMap = new Map<String, Contact>();
		List<Contact> listContactWithEmail = new List<Contact>();
		// Added a checker to make sure the emails set is not empty
		if(emails <> null && emails.size() > 0){
			try{
				listContactWithEmail = withoutSharing.getContact(emails);
			}catch(Exception errorAPI){
				system.debug('TRY-CATCH-EmailException-->' + errorAPI);
			}
			for (Contact con : listContactWithEmail){
				emailContactMap.put(con.Email, con);
			}
		}// end of Edit for [CCN-857]


		// get emails that are not existing as contacts
		Set<String> foundContacts = new Set<String>(emailContactMap.keySet());
		Set<String> newEmails = new Set<String>(emails);
		newEmails.removeAll(foundContacts);

		List<Contact> contactList = new List<Contact>();
		for (String em : newEmails){
			contactList.add(new Contact(Email=em, LastName=Em));
		}

		if (contactList.size() > 0){
			insert contactList;
			for (Contact con : contactList){
				emailcontactMap.put(con.Email, con);
			}
		}

		for (Issue__c issue : (List<Issue__c>) newRecords){
			// Updated by rrizarri [CCN-857] Oct152021
			// Added a checker to make sure the emailContactMap map is not empty
            if(emailContactMap.containsKey(issue.Raised_By_Email__c)){
                issue.Raised_By__c = emailContactMap.get(issue.Raised_By_Email__c).Id;
            }// end of Edit for [CCN-857]
		}
	}
    
    private void populateUrl(List<Issue__c> newRecords){
        Set<Id> evtIds = new Set<Id>();
        for(Issue__c projIssue : newRecords){
            evtIds.add(projIssue.Event__c);
        }
        Map<Id,Event__c> eventMap = new Map<Id,Event__c> ([SELECT Id, OwnerId, Parking_Lot_User__c,Parking_Lot_User__r.Email,Owner.Email,Event_Id__c 
                                                           FROM Event__c 
                                                           WHERE Id IN: evtIds]);
        for(Issue__c projIssue : newRecords){
            projIssue.Issue_Page_URL_c__c =  getCommunityURL('Compass') + '/s/issue-tracker?id=' + eventMap.get(projIssue.Event__c)?.Event_Id__c;
        }
    }
    
     
   private String getCommunityURL(string communityName){
        if (!Test.isRunningTest()){
            Network myNetwork = [SELECT Id FROM Network WHERE Name = :communityName];
            ConnectApi.Community  myCommunity = ConnectApi.Communities.getCommunity(myNetwork.id);
            return myCommunity.siteUrl ;
        } else {
            return 'some random url';   
        }
    }
	/*******************************************************************************************
	* @name: WithoutSharingClass
	* @author: Rianno Rizarri
	* @created: 15-10-2021
	* @description: Needs inner class declared without sharing for guest users to retrieve relevant records
	* 
	* Changes (version)
	* -------------------------------------------------------------------------------------------
*        		No.   Date(dd-mm-yyy) 	Author         			Description
	*        	----  ---------    		--------------------  	-----------------------------
	* @version  1.0   15-10-2021   		Rianno Rizarri  		[CCN-857] Initial version.
	*********************************************************************************************/
    private without sharing class WithoutSharingClass {

        public List<Contact> getContact(Set<String> emails){
            return [SELECT Email FROM Contact WHERE Email IN: emails ];
        }
    }
}