main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the client or organization the campaign is associated with. This connects the campaign to client data.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Brief introduction to the campaign that displays under the campaign name on the campaign summary page.</inlineHelpText>
    <label>Campaign Summary Page Subtitle</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <inlineHelpText>Please select the most appropriate type of Contact.  For employees, please input information in the employee relevant information per policy.</inlineHelpText>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee - FT</fullName>
            </value>
            <value>
                <fullName>Employee- PT</fullName>
            </value>
            <value>
                <fullName>Employee- 1099</fullName>
            </value>
            <value>
                <fullName>Contractor (employed by another firm)</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Educator</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Trainor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/fields/Parking_Lot_User__c.field-meta.xml
<CustomField>
    <fullName>Parking_Lot_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parking Lot User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Parking_Lot__c/Parking_Lot__c.object-meta.xml
<CustomObject>
    <label>Parking Lot</label>
    <nameField>
        <displayFormat>PL-{000000}</displayFormat>
        <label>Parking Lot Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parking Lots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Parking_Lot__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <formula>Event__r.Campaign__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Campaign</label>
    <type>Text</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Parking Lots</relationshipLabel>
    <relationshipName>Parking_Lots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/First_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Modified_Date__c</fullName>
    <description>This field will be populated when the Address by is not empty.</description>
    <label>First Modified Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Raised_By__c.field-meta.xml
<CustomField>
    <fullName>Raised_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raised By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Parking Lots</relationshipLabel>
    <relationshipName>Parking_Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Resolution_Answer__c.field-meta.xml
<CustomField>
    <fullName>Resolution_Answer__c</fullName>
    <label>Resolution/Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Parking_Lot__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
            <value>
                <fullName>Statement BH</fullName>
                <isActive>false</isActive>
                <label>Statement BH</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/ParkingLotTriggerHandler_Test.cls
@isTest (SeeAllData = false)
public class ParkingLotTriggerHandler_Test {
    
    @testSetup 
    static void setUp() {
        Apex_Trigger_Switch__c switchh = new Apex_Trigger_Switch__c();
        switchh.Name = 'ParkingLotTrigger';
        switchh.Active__c = true;
        insert switchh;
        
        TestFactory.ParkingLotTestDataFactory df = new TestFactory.ParkingLotTestDataFactory();
        df.make();
        df.persist();
    }
    @IsTest
    static void should_send_update_successfully(){
        Parking_Lot__c pl = [SELECT ID, First_Modified_Date__c FROM Parking_Lot__c Limit 1];
        System.assert(pl.First_Modified_Date__c == null, 'First Modified Date field has an initial value of null.');
        Test.startTest();
            pl.Status__c = 'Closed';
            update pl;
        Test.stopTest();
        System.assert(pl.Status__c == 'Closed', 'Unexpected Error, update did not push through');
        Parking_Lot__c plUpdated = [SELECT ID, First_Modified_Date__c  FROM Parking_Lot__c Limit 1];
        System.assert(plUpdated.First_Modified_Date__c != null, 'First Modified Date field is ' + pl.First_Modified_Date__c);
    }
    
    //This is to test the First Modified of Parking Lot and populate the First Modified Date field.
    @IsTest
    static void should_send_update_for_FirstModified_successfully(){
        Parking_Lot__c pl = [SELECT ID, First_Modified_Date__c, Status__c FROM Parking_Lot__c Limit 1];
        System.assert(pl.First_Modified_Date__c == null, 'First Modified Date field has an initial value of null.');
        Test.startTest();
            pl.Description__c  = 'This is to test the Open Email Template.';
            update pl;
        Test.stopTest();
        System.assert(pl.Status__c == 'Open', 'Unexpected Error, update did not push through');
        Parking_Lot__c plUpdated = [SELECT ID, First_Modified_Date__c  FROM Parking_Lot__c Limit 1];
        System.assert(plUpdated.First_Modified_Date__c != null, 'First Modified Date field is ' + pl.First_Modified_Date__c);
    }

    
    @IsTest
    static void should_send_email_from_compass_setting(){
        Test.startTest();
        LotWithDefault fact = new LotWithDefault();
        fact.make();
        fact.persist();
        Parking_Lot__c lot = fact.getLot();
        lot.Resolution_Answer__c = 'Something';
        lot.Status__c = 'Closed';
        update lot;
        Parking_Lot__c updated = [
            SELECT ID, 
            Status__c, 
            Resolution_Answer__c 
            FROM Parking_Lot__c 
            WHERE Id = :lot.Id
        ];
        System.assert(updated.Status__c == 'Closed', 'Unexpected Error, update did not push through');
        Test.stopTest();
    }

    private class LotWithDefault implements TestFactory.DataFactory{
        private Contact con;
        private Event__c evt;
        private Parking_Lot__c pl;
        
        public void make(){
            this.con = new Contact();
            this.con.Firstname = 'Random';
            this.con.Lastname = 'Random Last Name';
            this.con.Email = 'me@random.com';
            this.con.Contact_Type__c = 'Client';

            insert this.con;

            Campaign__c  campaignRec = new Campaign__c();
            Account acc = new Account(Name ='Test Acc');
       		insert acc;
            campaignRec.Account__c = acc.Id;
            insert campaignRec;
            
            this.evt = new Event__c();
            this.evt.Name = 'Some Event';
            this.evt.Campaign__c =campaignRec.Id;
            this.evt.Event_Id__c = 'Test';
            this.evt.Parking_Lot_User__c = this.con.Id;
            this.evt.Compass_Setting__c = [SELECT ID FROM Compass_Setting__c LIMIT 1].Id;
            insert this.evt;
        }
        public void persist(){
            this.pl = new Parking_Lot__c(
                Event__c = this.evt.Id,
                Raised_By__c = this.con.Id,
                Description__c = 'Question 1',
                Status__c = 'Open',
                Type__c = 'Issue'
            );
            insert this.pl;
        }
        public Parking_Lot__c getLot(){
            return this.pl;
        }
    }
}