main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Email_Template_Invitation_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Invitation_Id__c</fullName>
    <label>Email Template - Invitation Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/fields/Email_Template_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Registration_Id__c</fullName>
    <label>Email Template - Registration Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Details__c.field-meta.xml
<CustomField>
    <fullName>Session_Details__c</fullName>
    <label>Session Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/classes/calendarControllerTest.cls
@isTest
public class calendarControllerTest {
    
   @testSetup static void setup() {
       
        EmailTemplate e = new EmailTemplate (DeveloperName = 'test', FolderId = UserInfo.getUserId(), TemplateType= 'Text', Name = 'test', IsActive = true);
        System.runAs( new User(Id = UserInfo.getUserId())){
            insert e;
        }
       
       	Compass_Setting__c compSetting = new Compass_Setting__c();
        compSetting.Name = 'Default Settings';
        compSetting.Email_Sender_Id__c = '123';
        compSetting.Email_Sender_Name__c = 'NAME';
        compSetting.Email_Template_Invitation_Id__c = e.Id;
        compSetting.Email_Template_Registration_Id__c = e.Id;
        insert compSetting;
       
        // Create common test records
        Apex_Trigger_Switch__c eventSwitch = new Apex_Trigger_Switch__c();
        eventSwitch.Name = 'EventTrigger';
        eventSwitch.active__c = true;
        insert eventSwitch;
      	Campaign__c camp = new Campaign__c(Name='Test Name');
      	insert camp;
       	Event__c evnt = new Event__c(Name='Test Name', Time_Zone__c = 'PST', IsActive__c=true,Campaign__c=camp.Id, Start_Date_Time__c = DateTime.now(), End_Date_Time__c=DateTime.now().AddDays(1));
      	insert evnt;
       	Session__c session1 = new Session__c(Name='Test Name', Time_Zone__c = 'PST', Start_Date_Time__c = DateTime.now(), End_Date_Time__c=DateTime.now().AddDays(1), Event__c=evnt.Id);
      	insert session1;
       
        
       
   
    }
    static testMethod void getEventsTest() {
       Compass_Setting__c compassSetting = [SELECT Id, Domain_Name__c FROM Compass_Setting__c WHERE Name = 'Default Settings'
        LIMIT 1];
        
        System.debug('Gavvv ' + compassSetting);
      	Campaign__c campaign = [SELECT Id FROM Campaign__c LIMIT 1];
        calendarController.getEvents('Event__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById', false, campaign.Id, new List<String> {'Virtual', 'In-Person', 'Hybrid'});
        calendarController.getEvents('Event__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById', true, campaign.Id, new List<String> {'Virtual', 'In-Person', 'Hybrid'});
    	//CCN-1000 Modified by Rianno Rizarri Apr 15, 2022
        calendarController.getEventsExceptShowToLinks('Event__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById', false, campaign.Id, new List<String> {'Virtual', 'In-Person', 'Hybrid'}, new List<String> {'Test1', 'Test2', 'Test3'});
        calendarController.getEventsExceptShowToLinks('Event__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById', true, campaign.Id, new List<String> {'Virtual', 'In-Person', 'Hybrid'}, new List<String> {'Test1', 'Test2', 'Test3'});
        //CCN-1000 Modified by Rianno Rizarri Apr 15, 2022
    }
    static testMethod void upsertEventsTest() {
        Session__c session1 = [SELECT Id, Event__r.Event_Id__c FROM Session__c LIMIT 1];
        calendarController.upsertEvents('{"title":"Test Name","startDateTime":"2017-04-26T17:00:00-07:00","endDateTime":"2017-04-26T19:00:00-07:00","description":"asdasd"}', 'Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById');
    	calendarController.upsertEvents('{"id":'+'"'+String.valueOf(session1.Id)+'"'+',"title":"Test Name","startDateTime":"2017-04-26T17:00:00-07:00","endDateTime":"2017-04-26T19:00:00-07:00","description":"asdasd"}', 'Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById');
        calendarController.getEventTypes();
    	System.assert(session1 != null);
    }
    static TestMethod void getRecIdTest(){
        Session__c session1 = [SELECT Id, Event__c, Event__r.Event_Id__c FROM Session__c LIMIT 1];
        String eventId = calendarController.getRecId(session1.Event__r.Event_Id__c);
        System.assertEquals(eventId, session1.Event__c);
    }
    static TestMethod void insertSessionTest(){
        Session__c session1 = [SELECT Id, Event__c, Event__r.Event_Id__c FROM Session__c LIMIT 1];
        calendarController.insertSession('{"id":'+'"'+String.valueOf(session1.Id)+'"'+',"title":"dasdsad","startDateTime":"2017-04-26T17:00:00-07:00","endDateTime":"2017-04-26T19:00:00-07:00","description":"asdasd"}', 'Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById', session1.Event__c);
    	calendarController.insertSession('{"id":'+'"'+String.valueOf(session1.Id)+'"'+',"title":"dasdsad","startDateTime":"2017-04-26T17:00:00-07:00","endDateTime":"2017-04-26T19:00:00-07:00","description":"asdasd"}', 'Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById', null);
    	Session__c session2 = [SELECT Id, Event__c, Event__r.Event_Id__c FROM Session__c WHERE Name = 'Test Name'  LIMIT 1];
        System.assert(session2 != null);
    }
    static testMethod void deleteEventTest() {
        Session__c session1 = [SELECT Id, Event__c, Event__r.Event_Id__c FROM Session__c LIMIT 1];
        calendarController.deleteEvent(session1.Id, 'Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById');
        Session__c session2 = [SELECT Id, Event__c, Event__r.Event_Id__c FROM Session__c WHERE Id=:session1.Id LIMIT 1];
        System.assert(session1 != null);
    }
    static testMethod void crudSecurityTest() {
        calendarController.isAccessible('Event__c');
        calendarController.isAccessible('Event__c','Name');
        calendarController.isCreateable('Event__c');
        calendarController.isDeletable('Event__c');
        System.assert(calendarController.isAccessible('Event__c') == true);
    }
}