main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the client or organization the campaign is associated with. This connects the campaign to client data.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Session_Details__c.field-meta.xml
<CustomField>
    <fullName>Session_Details__c</fullName>
    <label>Session Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/classes/AnyEventCalCtrlTest.cls
@isTest
public class AnyEventCalCtrlTest {
    
   @testSetup static void setup() {
        // Create common test records
        Apex_Trigger_Switch__c eventSwitch = new Apex_Trigger_Switch__c();
        eventSwitch.Name = 'EventTrigger';
        eventSwitch.active__c = true;
        insert eventSwitch;
       	Account acc = new Account(Name ='Test Acc');
       insert acc;
      	Campaign__c camp = new Campaign__c(Name='Test Name', Account__c = acc.Id);
      	insert camp;
       	Event__c evnt = new Event__c(Name='Test Name', IsActive__c=true,Campaign__c=camp.Id, Start_Date_Time__c = DateTime.now(), End_Date_Time__c=DateTime.now().AddDays(1), Time_Zone__c='ET');
      	insert evnt;
       	Session__c session1 = new Session__c(Name='Test Name',IsActive__c=true,Start_Date_Time__c = DateTime.now(), End_Date_Time__c=DateTime.now().AddDays(1), Event__c=evnt.Id, Time_Zone__c='ET');
      	insert session1;
    }
  static testMethod void getEventsTest() {
      
      	Session__c session1 = [SELECT Id, Event__r.Event_Id__c FROM Session__c LIMIT 1];
  
      	String eventId = String.valueOf(session1.Event__r.Event_Id__c);
      	SObject session3 = [SELECT Id, Event__r.Event_Id__c FROM Session__c WHERE Event__r.Event_Id__c =:eventId];
      	System.Debug('!@#$%session3 : '+session3);
        List<String> sessionId = new List<String>();
        AnyEventCalCtrl.getEvents('Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById', false, eventId, sessionId);
        AnyEventCalCtrl.getEvents('Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById', true, eventId, sessionId);
      	System.assert(session3 != null);
    }
    static testMethod void upsertEventsTest() {
        Session__c session1 = [SELECT Id, Event__r.Event_Id__c FROM Session__c LIMIT 1];
        AnyEventCalCtrl.upsertEvents('{"id":'+'"'+String.valueOf(session1.Id)+'"'+',"title":"dasdsad","startDateTime":"2017-04-26T17:00:00-07:00","endDateTime":"2017-04-26T19:00:00-07:00","description":"asdasd"}', 'Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById');
    	AnyEventCalCtrl.upsertEvents('{"id":'+'"'+String.valueOf(session1.Id)+'"'+',"title":"dasdsad","startDateTime":"2017-04-26T17:00:00-07:00","endDateTime":"2017-04-26T19:00:00-07:00","description":"asdasd"}', 'Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById');
    	System.assert(session1 != null);
    }
    static TestMethod void getRecIdTest(){
        Session__c session1 = [SELECT Id, Event__c, Event__r.Event_Id__c FROM Session__c LIMIT 1];
        String eventId = AnyEventCalCtrl.getRecId(session1.Event__r.Event_Id__c);
        System.assertEquals(eventId, session1.Event__c);
    }
    static TestMethod void insertSessionTest(){
        Session__c session1 = [SELECT Id, Event__c, Event__r.Event_Id__c FROM Session__c LIMIT 1];
        AnyEventCalCtrl.insertSession('{"id":'+'"'+String.valueOf(session1.Id)+'"'+',"title":"dasdsad","startDateTime":"2017-04-26T17:00:00-07:00","endDateTime":"2017-04-26T19:00:00-07:00","description":"asdasd"}', 'Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById', session1.Event__c);
    	AnyEventCalCtrl.insertSession('{"id":'+'"'+String.valueOf(session1.Id)+'"'+',"title":"dasdsad","startDateTime":"2017-04-26T17:00:00-07:00","endDateTime":"2017-04-26T19:00:00-07:00","description":"asdasd"}', 'Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById', null);
    }
    static testMethod void deleteEventTest() {
        Session__c session1 = [SELECT Id, Event__c, Event__r.Event_Id__c FROM Session__c LIMIT 1];
        AnyEventCalCtrl.deleteEvent(session1.Id, 'Session__c', 'Name', 'Start_Date_Time__c', 'End_Date_Time__c', 'Session_Details__c', 'CreatedById');
        Session__c session2 = [SELECT Id, Event__c, Event__r.Event_Id__c FROM Session__c WHERE Id=:session1.Id LIMIT 1];
        System.assert(session1 != null);
    }
    static testMethod void crudSecurityTest() {
        AnyEventCalCtrl.isAccessible('Event__c');
        AnyEventCalCtrl.isAccessible('Event__c','Name');
        AnyEventCalCtrl.isCreateable('Event__c');
        AnyEventCalCtrl.isDeletable('Event__c');
        System.assert(AnyEventCalCtrl.isAccessible('Event__c') == true);
    }
}