main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Contact_Us_User__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the user to whom activities raised from the Contact Us page will be assigned to. If this field is empty, the activities will be assigned to the campaign&apos;s owner.</description>
    <label>Contact Us User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Contact_Us_User__c.field-meta.xml
<CustomField>
    <fullName>Contact_Us_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field contains the user to whom activities raised from the Contact Us page will be assigned to. If this field is empty, the activities will be assigned to the campaign&apos;s owner.</description>
    <label>Contact Us User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contact_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Location_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Member_Status</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Domain_Name__c.field-meta.xml
<CustomField>
    <fullName>Domain_Name__c</fullName>
    <label>Domain Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/globalValueSets/Member_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Invited</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <customValue>
        <fullName>Attended</fullName>
    </customValue>
    <customValue>
        <fullName>Catch-Up</fullName>
    </customValue>
    <customValue>
        <fullName>Missed</fullName>
    </customValue>
    <customValue>
        <fullName>Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Responded</fullName>
        <isActive>false</isActive>
        <label>Responded</label>
    </customValue>
    <customValue>
        <fullName>Cancelled</fullName>
        <isActive>false</isActive>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>Sent</fullName>
        <isActive>false</isActive>
        <label>Sent</label>
    </customValue>
    <masterLabel>Member Status</masterLabel>
</GlobalValueSet>

main/default/classes/EventConfirmationControllerTest.cls
/**
@author Jasmine Nguyen
@date 31 August 2020
@group NCC
@description Event Confirmation Template
@revision   Jasmine Nguyen - 05 Septemper: Uncommented and modified testGetSessionsDetails()
to accomondate the changes in the helper class
**/

@isTest
public with sharing class EventConfirmationControllerTest {
  
    @TestSetup
    static void makeData(){
        //User testUser = TestFactory.createInteralUser('Test', 'User', 'testUser15092020@gmail.com', 'System Administrator');
        User testUser = TestDataFactory.createUser('Test', 'User', 'testUser15092020@gmail.com', 'System Administrator');
        System.runAs(testUser){
            Compass_Setting__c cSetting = TestDataFactory.createCSData(1);
            cSetting.Domain_Name__c  = 'https://dev3-nationalcoordinationcenter.cs90.force.com/Compass';
            insert cSetting;
            
            List<Apex_Trigger_Switch__c> atsList = new List<Apex_Trigger_Switch__c>();
            Apex_Trigger_Switch__c aps_p = TestDataFactory.createTriggerSwitch('ParticipantTrigger');
            aps_p.Active__c = false;
            atsList.add(aps_p);
            
            Apex_Trigger_Switch__c aps_sp = TestDataFactory.createTriggerSwitch('SessionParticipantTrigger');
            aps_sp.Active__c = false;
            atsList.add(aps_sp);
            insert atsList;
            
            Account testAccount = TestDataFactory.createAccount('Test Account');
            testAccount.BillingStreet = '123 Green Avenue';
            testAccount.BillingCity = 'Melbourne';
            testAccount.BillingPostalCode = '3000';
            testAccount.BillingState = 'VIC';
            testAccount.BillingCountry = 'Australia';
            insert testAccount;
            
            User campaignOwner = TestDataFactory.createUser('Campaign', 'Owner', 'campaign.owner@gmail.com', 'System Administrator');
            campaignOwner.TimeZoneSidKey = 'America/New_York';
            insert campaignOwner;
            
            Campaign parentEvent = TestDataFactory.createStandardCampaign('Parent Event');
            parentEvent.Location__c = testAccount.Id;
            parentEvent.OwnerId = campaignOwner.Id;
            parentEvent.Start_Date_Time__c = DateTime.newInstance(2020, 8, 29, 8, 30, 0);
            parentEvent.End_Date_Time__c = DateTime.newInstance(2020, 8, 31, 12, 30, 0);
            insert parentEvent;
            
            Campaign childSession = TestDataFactory.createStandardCampaign('Child Session');
            childSession.ParentId = parentEvent.Id;
            childSession.Start_Date_Time__c = DateTime.newInstance(2020, 8, 29, 8, 30, 0);
            childSession.End_Date_Time__c = DateTime.newInstance(2020, 8, 29, 12, 30, 0);
            insert childSession;
            
            Contact attendee = TestDataFactory.createContact('Test', 'Attendee', 'test.attendee@gmail.com');
            insert attendee;
            
            CampaignMember cm = TestFactory.createCampaignMember(parentEvent.Id, attendee);
            Event__c e = TestFactory.createEvent('Test Event');
            Session__c testSessionRec = new Session__c();
            testSessionRec.Contact__c = attendee.Id;
            testSessionRec.Session__C = childSession.Id;
            testSessionRec.Event__c = e.Id;
            testSessionRec.Start_Date_Time__c = System.now().addDays(7);
            testSessionRec.End_Date_Time__c = System.now().addDays(8);
            testSessionRec.Time_Zone__c = 'PST';
            insert testSessionRec;
            
            Participant__c p = TestDataFactory.createParticipant(e.Id, attendee.Id);
            insert p;
            
            Session_Participant__c sp = TestDataFactory.createSessionParticipant(testSessionRec.Id);
            sp.Event__c = e.Id;
            sp.Contact__c = attendee.Id;
            sp.Status__c = 'Registered';
            insert sp;
        }
    }

    @isTest
    public static void testGetSessionsDetailsWithContactUsUser(){
        User testUser = [SELECT Id FROM User WHERE Username = 'testUser15092020@gmail.com' LIMIT 1];
        System.runAs(testUser){
            Account testAccount2 = new Account();
            testAccount2.Name = 'Some Account 2';
            testAccount2.BillingStreet = '456 Green Avenue';
            testAccount2.BillingCity = 'Melbourne';
            testAccount2.BillingPostalCode = '3055';
            testAccount2.BillingState = 'VIC';
            testAccount2.BillingCountry = 'Australia';
            insert testAccount2;
            User contactUsUser = TestFactory.createInteralUser('ContactUs', 'User', 'contactus@gmail.com', 'System Administrator');
            contactUsUser.TimeZoneSidKey = 'America/New_York';
            update contactUsUser;
            User campaignOwner2 = TestFactory.createInteralUser('Campaign', 'Owner2', 'campaign.owner2@gmail.com', 'System Administrator');
            campaignOwner2.TimeZoneSidKey = 'America/New_York';
            update campaignOwner2;
            Campaign parentEvent = TestFactory.createCampaign('Parent Event 2', 'Event');
            parentEvent.Location__c = testAccount2.Id;
            parentEvent.OwnerId = campaignOwner2.Id;
            parentEvent.Start_Date_Time__c = DateTime.newInstance(2020, 8, 29, 8, 30, 0);
            parentEvent.End_Date_Time__c = DateTime.newInstance(2020, 8, 31, 12, 30, 0);
            parentEvent.Contact_Us_User__c = contactUsUser.Id;
            update parentEvent;
            Campaign childSession = TestFactory.createCampaign('Child Session 2', 'Session');
            childSession.ParentId = parentEvent.Id;
            childSession.Start_Date_Time__c = DateTime.newInstance(2020, 8, 29, 8, 30, 0);
            childSession.End_Date_Time__c = DateTime.newInstance(2020, 8, 29, 12, 30, 0);
            update childSession;
            Contact attendee = TestFactory.createContact('Test', 'Attendee2', 'test.attendee2@gmail.com');
            CampaignMember cm = TestFactory.createCampaignMember(parentEvent.Id, attendee);
            Event__c e = TestFactory.createEvent('Test Event2');
            Session__c testSessionRec = new Session__c();
            testSessionRec.Contact__c = attendee.Id;
            testSessionRec.Session__C = childSession.Id;
            testSessionRec.Event__c = e.Id;
            insert testSessionRec;
            List<CampaignMember> campaignMemberList = [SELECT Id FROM CampaignMember WHERE Contact.Email = 'test.attendee2@gmail.com'];
            if (campaignMemberList.size() > 0){
                EventConfirmationController ecc = new EventConfirmationController();
                ecc.setCampaignMemberId(campaignMemberList[0].Id);
                Test.startTest();
                List<EventConfirmationHelper.SessionWrapper> resultSessions = ecc.getSessions();
                Test.stopTest();
                if (resultSessions != null && resultSessions.size() > 0){
                    System.assertEquals(campaignMemberList[0].Id, ecc.getCampaignMemberId());
                    System.assertEquals(1, resultSessions.size());
                    System.assertEquals('Child Session 2', resultSessions[0].Name);
                    System.assertEquals('08/29/2020', resultSessions[0].SessionDate);
                    System.assertEquals('8:30 AM to 12:30 PM', resultSessions[0].SessionTime);
                    System.assertEquals('456 Green Avenue, Melbourne, VIC 3055, Australia', resultSessions[0].SessionLocation);
                }
            }
        }
    }


    @isTest
    public static void testGetSessionsDetailsWithoutContactUsUser(){
        User testUser = [SELECT Id FROM User WHERE Username = 'testUser15092020@gmail.com' LIMIT 1];
        System.runAs(testUser){
            List<CampaignMember> campaignMemberList = [SELECT Id FROM CampaignMember WHERE Contact.Email = 'test.attendee@gmail.com'];
            if (campaignMemberList.size() > 0){
                EventConfirmationController ecc = new EventConfirmationController();
                ecc.setCampaignMemberId(campaignMemberList[0].Id);
                Test.startTest();
                List<EventConfirmationHelper.SessionWrapper> resultSessions = ecc.getSessions();
                Test.stopTest();
                if (resultSessions != null && resultSessions.size() > 0){
                    System.assertEquals(campaignMemberList[0].Id, ecc.getCampaignMemberId());
                    System.assertEquals(1, resultSessions.size());
                    System.assertEquals('Child Session', resultSessions[0].Name);
                    System.assertEquals('08/29/2020', resultSessions[0].SessionDate);
                    System.assertEquals('8:30 AM to 12:30 PM', resultSessions[0].SessionTime);
                    System.assertEquals('123 Green Avenue, Melbourne, VIC 3000, Australia', resultSessions[0].SessionLocation);
                }
            }
        }
    }

    @isTest
    public static void testGetFormattedDateTimeNull(){
        EventConfirmationController ecc = new EventConfirmationController();
        System.assertEquals('', ecc.getFormattedDatetime());
    }
    
    @isTest
    public static void testGetFormattedStartDateTimeWithContactUsUser(){
        User testUser = [SELECT Id FROM User WHERE Username = 'testUser15092020@gmail.com' LIMIT 1];
        System.runAs(testUser){
            Account testAccount3 = new Account();
            testAccount3.Name = 'Some Account 3';
            testAccount3.BillingStreet = '789 Green Avenue';
            testAccount3.BillingCity = 'Melbourne';
            testAccount3.BillingPostalCode = '3022';
            testAccount3.BillingState = 'VIC';
            testAccount3.BillingCountry = 'Australia';
            insert testAccount3;
            User contactUsUser3 = TestFactory.createInteralUser('ContactUs', 'User3', 'contactus3@gmail.com', 'System Administrator');
            contactUsUser3.TimeZoneSidKey = 'America/New_York';
            update contactUsUser3;
            User campaignOwner3 = TestFactory.createInteralUser('Campaign', 'Owner3', 'campaign.owner3@gmail.com', 'System Administrator');
            campaignOwner3.TimeZoneSidKey = 'America/New_York';
            update campaignOwner3;
            Campaign parentEvent = TestFactory.createCampaign('Parent Event 2', 'Event');
            parentEvent.Location__c = testAccount3.Id;
            parentEvent.OwnerId = campaignOwner3.Id;
            parentEvent.Start_Date_Time__c = DateTime.newInstance(2020, 8, 29, 8, 30, 0);
            parentEvent.End_Date_Time__c = DateTime.newInstance(2020, 8, 31, 12, 30, 0);
            parentEvent.Contact_Us_User__c = contactUsUser3.Id;
            update parentEvent;
            Campaign childSession = TestFactory.createCampaign('Child Session 2', 'Session');
            childSession.ParentId = parentEvent.Id;
            childSession.Start_Date_Time__c = DateTime.newInstance(2020, 8, 29, 8, 30, 0);
            childSession.End_Date_Time__c = DateTime.newInstance(2020, 8, 29, 12, 30, 0);
            update childSession;
            Contact attendee = TestFactory.createContact('Test', 'Attendee2', 'test.attendee2@gmail.com');
            CampaignMember cm = TestFactory.createCampaignMember(parentEvent.Id, attendee);
            Event__c e = TestFactory.createEvent('Test Event1');
            Session__c testSessionRec = new Session__c();
            testSessionRec.Contact__c = attendee.Id;
            testSessionRec.Session__C = childSession.Id;
            testSessionRec.Event__c = e.Id;
            insert testSessionRec;
            List<Campaign> campaigns = [SELECT ID, OwnerId FROM Campaign WHERE Name = 'Parent Event 2' LIMIT 1];
            if (campaigns.size() > 0){
                EventConfirmationController ecc = new EventConfirmationController();
                ecc.campaignId = campaigns[0].Id;
                ecc.campaignOwnerId = campaigns[0].OwnerId;
                ecc.defined_format = 'EEE, d MMM yyyy h:mm a';
                ecc.startOrEndDate = 'start';
                //System.assertEquals('Sat, 29 Aug 2020 8:30 AM', ecc.getFormattedDatetime());   
            }
        }
    }
    
    @isTest
    public static void testGetFormattedEndDateTime(){
        /*User testUser = [SELECT Id FROM User WHERE Username = 'testUser15092020@gmail.com' LIMIT 1];
        System.runAs(testUser){
            List<Campaign> campaigns = [SELECT ID, OwnerId FROM Campaign WHERE Name = 'Parent Event' LIMIT 1];
            if (campaigns.size() > 0){
                EventConfirmationController ecc = new EventConfirmationController();
                ecc.campaignId = campaigns[0].Id;
                ecc.campaignOwnerId = campaigns[0].OwnerId;
                ecc.defined_format = 'EEE, d MMM yyyy h:mm a';
                ecc.startOrEndDate = 'end';
                //System.assertEquals('Mon, 31 Aug 2020 12:30 PM', ecc.getFormattedDatetime());   
            }
        }*/
        List<Campaign> campaigns = [SELECT ID, OwnerId FROM Campaign WHERE Name = 'Parent Event' LIMIT 1];
        List<Event__c> event = [SELECT Id FROM Event__c LIMIT 1];
        Test.startTest();
        EventConfirmationHelper.getFormattedDateTimeHelper(campaigns[0].OwnerId, event[0].Id, 'start', 'EEE, d MMM yyyy h:mm a', 'date');
        Test.stopTest();
    }
    
    @isTest
    public static void testGetFormattedEndDateTimeWithException(){
        User testUser = [SELECT Id FROM User WHERE Username = 'testUser15092020@gmail.com' LIMIT 1];
        System.runAs(testUser){
            List<Campaign> campaigns = [SELECT ID, OwnerId FROM Campaign WHERE Name = 'Parent Event' LIMIT 1];
            if (campaigns.size() > 0){
                EventConfirmationController ecc = new EventConfirmationController();
                EventConfirmationHelper.throwFakeException = true;
                ecc.campaignId = campaigns[0].Id;
                ecc.campaignOwnerId = campaigns[0].OwnerId;
                ecc.defined_format = 'EEE, d MMM yyyy h:mm a';
                ecc.startOrEndDate = 'end';
                System.assertEquals('', ecc.getFormattedDatetime());   
            }
        }
    }
    
    @isTest
    public static void getSessionsDetailsTest() {
        List<Participant__c> participantList = [SELECT Id FROM Participant__c LIMIT 1];
        Test.startTest();
        EventConfirmationHelper.EventConfirmationWrapper ecw = EventConfirmationHelper.getSessionsDetails(participantList[0].Id);
        Test.stopTest();
    }
}