main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the client or organization the campaign is associated with. This connects the campaign to client data.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign__c/fields/Site_Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Site_Picklist_Values__c</fullName>
    <inlineHelpText>Values automatically populate Site Picklist Values field on event, survey, and communication objects. Enter values as a comma-separated list.</inlineHelpText>
    <label>Site Picklist Values</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Email_Template_Invitation_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Invitation_Id__c</fullName>
    <label>Email Template - Invitation Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/fields/Email_Template_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Registration_Id__c</fullName>
    <label>Email Template - Registration Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Contact/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Message_BCC__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_BCC__c</fullName>
    <label>Email Message BCC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Message_CC__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_CC__c</fullName>
    <label>Email Message CC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/fields/Site_picklist_values__c.field-meta.xml
<CustomField>
    <fullName>Site_picklist_values__c</fullName>
    <inlineHelpText>Field where values for the Site field in the community event registration page can be defined. Values should be comma-separated and configured in the Registration Field Configuration custom metadata settings to look into this field.</inlineHelpText>
    <label>Site Picklist Values</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Member_Contact__c.field-meta.xml
<CustomField>
    <fullName>Member_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Event_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/classes/CC_EventRegistrationClassTest.cls
/**
* Created by angelorivera on 30/8/20.
* Modified by Jasmine Nguyen on 10/9/2020 to use Start_Date_Time__c and End_Date_Time__c fields
*/

@IsTest
private class CC_EventRegistrationClassTest {
    
    @testSetup
    static void makeTestData(){
        OrgWideEmailAddress owea = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];
        
        EmailTemplate eTemp = new EmailTemplate (developerName = 'test', FolderId = UserInfo.getUserId(), TemplateType= 'Text', Name = 'test', IsActive = true);
        system.runAs( new User(Id = UserInfo.getUserId())){
            insert eTemp;
        }
        
        Apex_Trigger_Switch__c aps = new Apex_Trigger_Switch__c();
        aps.Name = 'EventTrigger';
        aps.Active__c = false;
        insert aps;

        Apex_Trigger_Switch__c st = new Apex_Trigger_Switch__c();
        st.Name = 'SessionTrigger';
        st.Active__c = true;
        insert st;
        
        /*Compass_Setting__c setting = new Compass_Setting__c();
        setting.Name = 'Default Settings';
        setting.Email_Sender_Id__c = 'qwerty';
        insert setting;*/
        
        Compass_Setting__c setting = new Compass_Setting__c();
        setting.Name = 'Default Settings';
        setting.Email_Sender_Name__c = 'NAME';
        setting.Email_Template_Invitation_Id__c = eTemp.Id;
        setting.Email_Template_Registration_Id__c = eTemp.Id;
        setting.Email_Sender_Id__c = owea.Id;
        insert setting;
        
        Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;
        
        Campaign__c camp = new Campaign__c();
        camp.Name = 'Test Campaign';
        camp.Account__c = acc.Id;
        insert camp;
        
        Contact c = new Contact();
        c.FirstName = 'John';
        c.LastName = 'John';
        c.Department = 'IT';
        c.Site__c = 'Test1';
        c.Email = 'John@test.com';
        insert c;

        Contact c2 = new Contact();
        c2.FirstName = 'k';
        c2.LastName = 'buhay';
        c2.Department = 'IT';
        c.Site__c = 'Test1';
        c2.Email = 'kbuhay@ulapp.co';
        insert c2;
        
        Event__c e = new Event__c();
        e.Event_Id__c = 'xxxxxxxxxx';
        e.Campaign__c = camp.id;
        e.Start_Date_Time__c = DateTime.Now();
        e.End_Date_Time__c = DateTime.Now().addDays(1);
        e.Email_Sender_Name__c = 'TEST 123';
        e.Email_Message_CC__c = 'testMail@mail.com';
        e.Email_Message_BCC__c = 'testMail@mail.com';
        e.Email_Sender_Id__c = owea.Id;
        //CCN-907 XEN REYES 11032021
        e.Site_picklist_values__c = 'Test1,Test2,Test3';
        e.Time_Zone__c = 'CDT';
        insert e;
        
        Participant__c p = new Participant__c();
        p.Member_Contact__c = c.id;
        p.Event__c = e.id;
        insert p;
        
        Session__c s = new Session__c();
        s.Event__c = e.id;
        s.IsActive__c = true;
        s.Time_Zone__c = 'CDT'; 
        s.Start_Date_Time__c = DateTime.Now();
        s.End_Date_Time__c = DateTime.Now().addHours(2);
        insert s;
        
        Lead l = new Lead();
        l.FirstName = 'Jane';
        l.LastName = 'Doe';
        l.Email = 'JaneDoe@test.com';
        l.Company = 'Acme';
        insert l;
        
    }
    
    @IsTest
    static void testInit() {
        CC_EventRegistrationClass.resultWrapper resultWrappers = new CC_EventRegistrationClass.resultWrapper();
        
        Participant__c p = [SELECT id,Name FROM Participant__c LIMIT 1];
        Event__c e = [SELECT Event_Id__c FROM Event__c Limit 1];
        
        Test.startTest();
        resultWrappers = CC_EventRegistrationClass.DoInit(e.Event_Id__c,p.Name);
        Test.stopTest();
        
    }
    
    @IsTest
    static void getCampaignMemberStatusTest(){
        
        Participant__c p = [SELECT id,Name,Event__c,Member_Contact__c FROM Participant__c LIMIT 1];
        Test.startTest();
        String result  = CC_EventRegistrationClass.getCampaignMemberStatus(p.Member_Contact__c,p.Event__c);
        Test.stopTest();
        
    }
    
    @IsTest
    static void submitBookingTest(){
        
        
        Session__c s = [Select id FROM Session__c limit 1];
        Event__c e = [Select id,Event_Id__c FROM Event__c limit 1];
        
        List<String> sessionIdsc  = new List<String>();
        sessionIdsc.Add(s.Id);        
        
        Test.startTest();
        String result  = CC_EventRegistrationClass.submitBooking(e.Event_Id__c,
                                                                 '{"RegistrationField_FirstName-Contact|FirstName":"kyzer","RegistrationField_LastName-Contact|LastName":"buhay",' +
                                                                 '"RegistrationField_Email-Contact|Email":"kbuhay@ulapp.co","RegistrationField_Department-Contact|Department":"IT","RegistrationField_Site-Contact|Site__c":"Test1"}',
                                                                 sessionIdsc,'"RegistrationField_Title-Contact|Title":{"required":false,"active":false}"');
        Test.stopTest();
        
    }
    
    @IsTest
    static void submitBookingTest2(){
        
        
        Session__c s = [Select id FROM Session__c limit 1];
        Event__c e = [Select id,Event_Id__c FROM Event__c limit 1];
        
        List<String> sessionIdsc  = new List<String>();
        sessionIdsc.Add(s.Id);        
        
        Test.startTest();
        String result  = CC_EventRegistrationClass.submitBooking(e.Event_Id__c,
                                                                 '{"RegistrationField_FirstName-Contact|FirstName":"kyzer","RegistrationField_LastName-Contact|LastName":"buhay",' +
                                                                 '"RegistrationField_Email-Contact|Email":"kbuhay@ulapp.co","RegistrationField_Department-Contact|Department":"IT","RegistrationField_Site-Contact|Site__c":"Test1"}',
                                                                 sessionIdsc,'"RegistrationField_Title-Contact|Title":{"required":false,"active":false}"');
        Test.stopTest();
        
    }    
    
    @IsTest
    static void submitBookingTest3(){
        
        
        Session__c s = [Select id FROM Session__c limit 1];
        Event__c e = [Select id,Event_Id__c FROM Event__c limit 1];
        
        List<String> sessionIdsc  = new List<String>();
        sessionIdsc.Add(s.Id);        
        
        Test.startTest();
        String result  = CC_EventRegistrationClass.submitBooking(e.Event_Id__c,
                                                                 '{"RegistrationField_FirstName-Contact|FirstName":"kyzer","RegistrationField_LastName-Contact|LastName":"buhay",' +
                                                                 '"RegistrationField_Email-Contact|Email":"kbuhay@ulapp.co","RegistrationField_Department-Contact|Department":"IT","RegistrationField_Site-Contact|Site__c":"Test1"}',
                                                                 sessionIdsc,'"RegistrationField_Title-Contact|Title":{"required":false,"active":false}"');
        Test.stopTest();
        
    }   

    @IsTest
    static void submitBookingTest4(){
        
        
        Session__c s = [Select id FROM Session__c limit 1];
        Event__c e = [Select id,Event_Id__c FROM Event__c limit 1];
        
        List<String> sessionIdsc  = new List<String>();
        sessionIdsc.Add(s.Id);        
        
        Test.startTest();
        String result  = CC_EventRegistrationClass.submitBooking(e.Event_Id__c,
                                                                 '{"RegistrationField_FirstName-Contact|FirstName":"no","RegistrationField_LastName-Contact|LastName":"contacttest",' +
                                                                 '"RegistrationField_Email-Contact|Email":"nocontacttest@ulapp.co","RegistrationField_Department-Contact|Department":"IT","RegistrationField_Site-Contact|Site__c":"Test1"}',
                                                                 sessionIdsc,'"RegistrationField_Title-Contact|Title":{"required":false,"active":false}"');
        Test.stopTest();
        
    }   

    @IsTest
    static void computeTimeZoneDiffTest(){
        
        Datetime testDateTime = DateTime.newInstance(2022, 6, 12, 0, 30, 0);
        Test.startTest();
        Datetime outputDate = CC_EventRegistrationClass.computeTimeZoneDiff(testDateTime, 'Asia/Manila');
        Test.stopTest();
        
        String outDate = outputDate.format('MMMM d, yyyy', 'Asia/Manila');

        System.assertEquals('June 12, 2022', outDate, 'Expected Date in text not equal to the actual output date.');

    }

    /* @IsTest
    static void generateMapByStringFieldTest(){
        
        List<Lead> leadList = [SELECT Id, LastName FROM Lead];
        Test.startTest();
        Map<String, sObject> resultMap  = CC_EventRegistrationClass.generateMapByStringField(leadList, 'LastName');
        Test.stopTest();
        
        Lead expectedLead = [SELECT Id, LastName FROM Lead WHERE Lastname = 'Doe'];
        System.assertEquals(expectedLead.Id, resultMap.get('Doe').Id);
    } */
    
    
    
}