main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the client or organization the campaign is associated with. This connects the campaign to client data.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Email_Template_Invitation_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Invitation_Id__c</fullName>
    <label>Email Template - Invitation Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/fields/Email_Template_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Registration_Id__c</fullName>
    <label>Email Template - Registration Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Internal_Resource__c/Internal_Resource__c.object-meta.xml
<CustomObject>
    <label>Internal Resource</label>
    <nameField>
        <displayFormat>IR-{000000}</displayFormat>
        <label>Event Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Resource__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Internal Resources</relationshipLabel>
    <relationshipName>Internal_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Internal Resources</relationshipLabel>
    <relationshipName>Internal_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Role__c/Internal_Resource_Role__c.object-meta.xml
<CustomObject>
    <label>Internal Resource Role</label>
    <nameField>
        <displayFormat>IRN-{0000}</displayFormat>
        <label>Internal Resource Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Resource Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Resource_Role__c/fields/Internal_Resource_Number_of_Role__c.field-meta.xml
<CustomField>
    <fullName>Internal_Resource_Number_of_Role__c</fullName>
    <label>Internal Resource Number of Role</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Internal_Resource_Role__c/fields/Internal_Resource_Role_Description__c.field-meta.xml
<CustomField>
    <fullName>Internal_Resource_Role_Description__c</fullName>
    <label>Internal Resource Role Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Internal_Resource_Role__c/fields/Internal_Resource_Role_Title__c.field-meta.xml
<CustomField>
    <fullName>Internal_Resource_Role_Title__c</fullName>
    <label>Internal Resource Role Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/objects/Internal_Resource_Role__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Internal Resource Roles</relationshipLabel>
    <relationshipName>Internal_Resource_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/Internal_Resource_Session__c.object-meta.xml
<CustomObject>
    <label>Internal Resource Session</label>
    <nameField>
        <displayFormat>IRS-{000000}</displayFormat>
        <label>Session Resource  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Resource Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Resource_Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Resource Number</label>
    <referenceTo>Internal_Resource__c</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Resource_Session_Role__c.field-meta.xml
<CustomField>
    <fullName>Resource_Session_Role__c</fullName>
    <label>Resource Session Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Resource_Session_Status__c.field-meta.xml
<CustomField>
    <fullName>Resource_Session_Status__c</fullName>
    <label>Resource Session Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/classes/MassSessionInternalAllocationTest.cls
@IsTest
public class MassSessionInternalAllocationTest {
    @TestSetup
    static void setupData(){
        OrgWideEmailAddress owea = [SELECT Id FROM OrgWideEmailAddress LIMIT 1];
        
        EmailTemplate eTemp = new EmailTemplate (developerName = 'test', FolderId = UserInfo.getUserId(), TemplateType= 'Text', Name = 'test', IsActive = true);
        system.runAs( new User(Id = UserInfo.getUserId())){
          insert eTemp;
        }
        
        Apex_Trigger_Switch__c aps = new Apex_Trigger_Switch__c();
        aps.Name = 'EventTrigger';
        aps.Active__c = false;
        insert aps;
        
        Compass_Setting__c setting = new Compass_Setting__c();
        setting.Name = 'Default Settings';
        setting.Email_Sender_Name__c = 'NAME';
        setting.Email_Template_Invitation_Id__c = eTemp.Id;
        setting.Email_Template_Registration_Id__c = eTemp.Id;
        setting.Email_Sender_Id__c = owea.Id;
        insert setting;
          
        Account ac = new Account(name ='Ulapp');
        insert ac; 

        Campaign__c camp = new Campaign__c();
        camp.Account__c = ac.Id;
        camp.Name = 'Test Campaign';
        insert camp;
        
        Contact c = new Contact();
        c.FirstName = 'John';
        c.LastName = 'John';
        c.Department = 'IT';
        c.Email = 'johnMassSessionSignUpController_Test@test.com';
        insert c;
        
        Event__c e = new Event__c();
        e.Event_Id__c = 'xxxxxxxxxx';
        e.Campaign__c = camp.id;
        e.Start_Date_Time__c = DateTime.Now();
        e.End_Date_Time__c = DateTime.Now().addHours(1);
        e.Email_Sender_Name__c = 'TEST 123';
        e.Time_Zone__c = 'ET';
        e.Email_Sender_Id__c = owea.Id;
        insert e;
        
        Internal_Resource__c p = new Internal_Resource__c();
        p.Contact__c = c.id;
        p.Event__c = e.id;
        insert p;
        
        Session__c s = new Session__c();
        s.Event__c = e.id;
        s.IsActive__c = true;
        s.Time_Zone__c = 'CDT';  
        s.Start_Date_Time__c = DateTime.Now();
        s.End_Date_Time__c = DateTime.Now().addHours(1);
        insert s;
        
        Internal_Resource_Role__c intRole = new Internal_Resource_Role__c();
        intRole.Internal_Resource_Role_Title__c = 'Test Role';
        intRole.Internal_Resource_Role_Description__c = 'Test Role';
        intRole.Internal_Resource_Number_of_Role__c = 1;
        intRole.Session__c = s.Id;
        insert intRole;
    }
    
    @IsTest
    static void getRolesTest(){
        MassSessionInternalAllocationController.mainWrapper wrapper = new MassSessionInternalAllocationController.mainWrapper();
        
        Id sessRecId = [SELECT Id FROM Session__c LIMIT 1].Id;
        
        Test.startTest();
            wrapper = MassSessionInternalAllocationController.getRoles(sessRecId);
        Test.stopTest();
        
        System.assertEquals('Success', wrapper.message);
    }
    
    @IsTest
    static void getRolesWithParticipantTest(){
        MassSessionInternalAllocationController.mainWrapper wrapper = new MassSessionInternalAllocationController.mainWrapper();
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Internal_Resource__c ir = [Select Id, Contact__c FROM Internal_Resource__c LIMIT 1];
        
        Internal_Resource_Session__c irs = new Internal_Resource_Session__c();
        irs.Resource__c = ir.Id;
        irs.Event__c = sessRec.Event__c;
        irs.Session__c = sessRec.Id;
        irs.Contact__c = ir.Contact__c;
        insert irs;
        
        Test.startTest();
            wrapper = MassSessionInternalAllocationController.getRoles(sessRec.Id);
        Test.stopTest();
        
        System.assertEquals('Success', wrapper.message);
    }

    
    @IsTest
    static void saveInternalResourceSessionTest(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        String paramStr = '[{"Email":"testsss1@m.com","FirstName":"Test","Id":"'+ sessRec.Id + '","LastName":"Schedulerr","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        Test.startTest();
            message = MassSessionInternalAllocationController.saveSessionInternalResource(paramStr,sessRec.Id);
        Test.stopTest();
        
        System.assertEquals('', message);
    }
    
    @IsTest
    static void saveInternalResourceSessionExistingTest(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Internal_Resource__c ir = [Select Id, Contact__c FROM Internal_Resource__c LIMIT 1];
        
        Internal_Resource_Session__c irs = new Internal_Resource_Session__c();
        irs.Resource__c = ir.Id;
        irs.Event__c = sessRec.Event__c;
        irs.Session__c = sessRec.Id;
        irs.Contact__c = ir.Contact__c;
        irs.Resource_Session_Role__c = 'Test Role';
        insert irs;

        String paramStr = '[{"Email":"john@test.com","FirstName":"John","Id":"'+ sessRec.Id + '","LastName":"John","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        Test.startTest();
            message = MassSessionInternalAllocationController.saveSessionInternalResource(paramStr,sessRec.Id);
        Test.stopTest();
        System.assertEquals('', message);
    }
    
    @IsTest
    static void saveInternalResourceSessionExistingTestChangePart(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Internal_Resource__c ir = [Select Id, Contact__c FROM Internal_Resource__c LIMIT 1];
        
        Internal_Resource_Session__c irs = new Internal_Resource_Session__c();
        irs.Resource__c  = ir.Id;
        irs.Event__c = sessRec.Event__c;
        irs.Session__c = sessRec.Id;
        irs.Contact__c = ir.Contact__c;
        irs.Resource_Session_Role__c = 'Test Role';
        irs.Resource_Session_Status__c = 'Registered';
        insert irs;

        String paramStr = '[{"Email":"john2@test.com","FirstName":"John2","Id":"'+ sessRec.Id + '","LastName":"John2","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        MassSessionInternalAllocationController.getRoles(sessRec.Id);
        
        Test.startTest();
            message = MassSessionInternalAllocationController.saveSessionInternalResource(paramStr,sessRec.Id);
        Test.stopTest();
        System.assertEquals('', message);
    }
    
   
   
   
    @IsTest
    static void saveInternalResourceSessionExistingTestNoChange(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Internal_Resource__c ir = [Select Id, Contact__c FROM Internal_Resource__c LIMIT 1];
        
        Internal_Resource_Session__c irs = new Internal_Resource_Session__c();
        irs.Resource__c  = ir.Id;
        irs.Event__c = sessRec.Event__c;
        irs.Session__c = sessRec.Id;
        irs.Contact__c = ir.Contact__c;
        irs.Resource_Session_Role__c = 'Test Role';
        irs.Resource_Session_Status__c = 'Registered';
        insert irs;

        String paramStr = '[{"Email":"john@test.com","FirstName":"John","Id":"'+ sessRec.Id + '","LastName":"John","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        MassSessionInternalAllocationController.getRoles(sessRec.Id);
        
        Test.startTest();
            message = MassSessionInternalAllocationController.saveSessionInternalResource(paramStr,sessRec.Id);
        Test.stopTest();
        System.assertEquals('', message);
    }
     @IsTest
    static void removeRole(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Internal_Resource__c ir = [Select Id, Contact__c FROM Internal_Resource__c LIMIT 1];
        
        Internal_Resource_Session__c irs = new Internal_Resource_Session__c();
        irs.Resource__c  = ir.Id;
        irs.Event__c = sessRec.Event__c;
        irs.Session__c = sessRec.Id;
        irs.Contact__c = ir.Contact__c;
        irs.Resource_Session_Role__c = 'Test Role';
        irs.Resource_Session_Status__c = 'Registered';
        insert irs;

        String paramStr = '[{"Email":"","FirstName":"","Id":"'+ sessRec.Id + '","LastName":"","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        MassSessionInternalAllocationController.getRoles(sessRec.Id);
        
        Test.startTest();
            message = MassSessionInternalAllocationController.saveSessionInternalResource(paramStr,sessRec.Id);
            MassSessionInternalAllocationController.removeRole(irs.Id);
        Test.stopTest();
    }
  
    @IsTest
    static void saveInternalResourceSessionExistingTestNoName(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Internal_Resource__c ir = [Select Id, Contact__c FROM Internal_Resource__c LIMIT 1];
        
        Internal_Resource_Session__c irs = new Internal_Resource_Session__c();
        irs.Resource__c  = ir.Id;
        irs.Event__c = sessRec.Event__c;
        irs.Session__c = sessRec.Id;
        irs.Contact__c = ir.Contact__c;
        irs.Resource_Session_Role__c = 'Test Role';
        irs.Resource_Session_Status__c = 'Registered';
        insert irs;

        String paramStr = '[{"Email":"john@test.com","FirstName":"","Id":"'+ sessRec.Id + '","LastName":"John","Role":"Test Role",' +
            '"RoleAndDesc":"Test Role Test Role","RoleDescription":"Test Role"}]';
        
        MassSessionInternalAllocationController.getRoles(sessRec.Id);
        
        Test.startTest();
            message = MassSessionInternalAllocationController.saveSessionInternalResource(paramStr,sessRec.Id);
        Test.stopTest();
        System.assertNotEquals('', message);
    }
    
    @IsTest
    static void getEventDetailsTest(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Test.startTest();
            message = MassSessionInternalAllocationController.getEventDetails(sessRec.Id);
        Test.stopTest();
        System.assertNotEquals('', message);
    }
    
    @IsTest
    static void getEventDetails2Test(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Test.startTest();
            message = MassSessionInternalAllocationController.getEventDetails2(sessRec.Id);
        Test.stopTest();
        System.assertNotEquals('', message);
    }
    
    @IsTest 
    static void getEventDetails3Test(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Test.startTest();
            message = MassSessionInternalAllocationController.getEventDetailsId(sessRec.Id);
        Test.stopTest();
        System.assertNotEquals('', message);
    }
    @IsTest
    static void getSessionDetailsTest(){
        String message = '';
        Session__c sessRec = [SELECT Id,Event__c FROM Session__c LIMIT 1];
        Test.startTest();
            Session__c s = MassSessionInternalAllocationController.getSessionDetails(sessRec.Id);
        Test.stopTest();
        System.assertNotEquals(null, s);
    }
}