main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Email_Template_Issue_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Issue_Id__c</fullName>
    <label>Email Template - Issue Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Contact/fields/Login_Token__c.field-meta.xml
<CustomField>
    <fullName>Login_Token__c</fullName>
    <label>Login Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Educator</fullName>
            </value>
            <value>
                <fullName>Medical Assistant</fullName>
            </value>
            <value>
                <fullName>Nurse</fullName>
            </value>
            <value>
                <fullName>Trainor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>Issue ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Issue__c/fields/Date_Raised__c.field-meta.xml
<CustomField>
    <fullName>Date_Raised__c</fullName>
    <label>Date Raised</label>
    <type>Date</type>
</CustomField>

main/default/objects/Issue__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Issues</relationshipLabel>
    <relationshipName>Project_Issues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Issue__c/fields/Raised_By__c.field-meta.xml
<CustomField>
    <fullName>Raised_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Raised By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Project_Issues1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Issue__c/fields/Raised_By_Email__c.field-meta.xml
<CustomField>
    <fullName>Raised_By_Email__c</fullName>
    <label>Raised By Email</label>
    <type>Email</type>
</CustomField>

main/default/objects/Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>Addressed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Issue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domain Access Issue/User Sign-on Issues</fullName>
            </value>
            <value>
                <fullName>Domain Issue Impacting Workbook Execution</fullName>
            </value>
            <value>
                <fullName>Workflow Issue</fullName>
            </value>
            <value>
                <fullName>Hardware Issue</fullName>
            </value>
            <value>
                <fullName>Training Room Issue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/IssueTriggerHandler_Test.cls
/**
@revision Kyzer Buhay - Removed Project in Class name (ProjectIssueTriggerHandler_Test) to IssueTriggerHandler_Test
**/
@isTest
public class IssueTriggerHandler_Test {
   
    @TestSetup
    static void makeData(){
        List<Apex_Trigger_Switch__c> switchRecs = TestDataFactory.createAllTriggerSwitch();
        insert switchRecs;
        
        Compass_Setting__c comp = TestDataFactory.createCSData(1);
        insert comp;
        
        Event__c evt = TestFactory.createEvent('TestEvent');
        
        //Create Existing Contact
        String email = 'test@email.com';
        String token = '123';
        Contact con = new Contact();
        con.LastName = email;
        con.Email = email;
        //con.Login_Token__c = token;
        insert con;
        
        EmailTemplate e = new EmailTemplate (developerName = 'test', FolderId = UserInfo.getUserId(), TemplateType= 'Text', Name = 'test', IsActive = true);
        system.runAs( new User(Id = UserInfo.getUserId())){
        	insert e;
        }
        Compass_Setting__c cs = new Compass_Setting__c(Email_Template_Issue_Id__c = e.Id);
        system.runAs( new User(Id = UserInfo.getUserId())){
        	insert cs;
        }
    }

    @isTest
    static void testShouldDefault(){
        List<Issue__c> issues = new List<Issue__c>();  
        Event__c evt = [SELECT ID FROM Event__c LIMIT 1];
        issues.add(new Issue__c(
            Event__c = evt.Id,
            Raised_By_Email__c = 'test@email.com',
            Description__c = 'description',
            Status__c = 'New',
            Type__c = 'Domain Access Issue/User Sign-on Issues',
            Date_Raised__c = date.today()
        ));
        issues.add(new Issue__c(
            Event__c = evt.Id,
            Raised_By_Email__c = 'test@test.com',
            Description__c = 'description',
            Status__c = 'New',
            Type__c = 'Domain Access Issue/User Sign-on Issues',
            Date_Raised__c = date.today()
        ));
        Test.startTest();
            insert issues;
        Test.stopTest();
        for (Issue__c projIssue : [
            SELECT ID,
            Raised_By__c
            FROM Issue__c
        ]){
            System.assertNotEquals(null, projIssue.Raised_By__c, 'the raised_by did not default');
        }
        System.assertEquals(2, [SELECT ID FROM Issue__c].size(), 'the number of issues inserted is not equal');
        Update issues;
    }

    @isTest
    static void testShouldDefaultDuringUpdate(){
        List<Issue__c> issues = new List<Issue__c>();
    
        Event__c evt = [SELECT ID FROM Event__c LIMIT 1];
        issues.add(new Issue__c(
            Event__c = evt.Id,
            Raised_By_Email__c = 'test@email.com',
            Description__c = 'description',
            Status__c = 'New',
            Type__c = 'Domain Access Issue/User Sign-on Issues',
            Date_Raised__c = date.today()
        ));
        issues.add(new Issue__c(
            Event__c = evt.Id,
            Raised_By_Email__c = 'test@test.com',
            Description__c = 'description',
            Status__c = 'New',
            Type__c = 'Domain Access Issue/User Sign-on Issues',
            Date_Raised__c = date.today()
        ));
        insert issues;
        Test.startTest();
            for (Issue__c issue : issues){
                issue.Raised_By__c = null;
            }
            Update issues;
        Test.stopTest();
        for (Issue__c projIssue : [
            SELECT ID,
            Raised_By__c
            FROM Issue__c 
        ]){
            System.assertNotEquals(null, projIssue.Raised_By__c, 'the raised_by did not default');
        }
        System.assertEquals(2, [SELECT ID FROM Issue__c].size(), 'the number of issues inserted is not equal');
    }
    
    @isTest
    static void testIssueAddressed(){
        OrgWideEmailAddress owea = [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress LIMIT 1];
        Event__c evt = [SELECT Id, Email_Sender_Id__c FROM Event__c LIMIT 1];
        evt.Email_Sender_Id__c = owea.Id;
        update evt;
        
        Issue__c issue = new Issue__c(Event__c = evt.Id,
            Raised_By_Email__c = 'test@email.com',
            Description__c = 'description',
            Status__c = 'New',
            Type__c = 'Domain Access Issue/User Sign-on Issues',
            Date_Raised__c = date.today());
		insert issue;
        
        Test.startTest();
            issue.Status__c = 'Addressed';
        	update issue;
        Test.stopTest();
        
        //EmailMessage em = [SELECT Id, FromAddress FROM EmailMessage WHERE FromAddress =: owea.Address AND ToAddress =: issue.Raised_By_Email__c];
    	//System.assert(em != null);
    }
}