main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Survey_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Reminder_Message__c</fullName>
    <label>Survey Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Participant__c/fields/Survey_Thank_You_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Thank_You_Message__c</fullName>
    <label>Survey Thank You Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Participant__c/recordTypes/Participant.recordType-meta.xml
<RecordType>
    <fullName>Participant</fullName>
    <active>true</active>
    <label>Participant</label>
</RecordType>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field determines if a survey is active. Each event/session can only have one active survey at a time.</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Standalone_Survey_URL__c.field-meta.xml
<CustomField>
    <fullName>Standalone_Survey_URL__c</fullName>
    <description>Generates URL for stand-alone surveys</description>
    <inlineHelpText>Copy and paste the URL to distribute the survey</inlineHelpText>
    <label>Standalone Survey URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Catchup_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Message__c</fullName>
    <label>Survey Catch-Up Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Catchup_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Reminder_Message__c</fullName>
    <label>Survey Catch-Up Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Code__c.field-meta.xml
<CustomField>
    <fullName>Survey_Code__c</fullName>
    <description>Random code will be generated and will be the identifier for the survey</description>
    <label>Survey Code</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Survey_Participant__c/Survey_Participant__c.object-meta.xml
<CustomObject>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that has been selected as a participant for a survey</description>
    <inlineHelpText>Contact that has been selected as a participant for a survey</inlineHelpText>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <description>Survey that the contact has been selected to participate to</description>
    <inlineHelpText>Survey that the contact has been selected to participate to</inlineHelpText>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Catchup_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Message__c</fullName>
    <label>Survey Catch-Up Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Catchup_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Reminder_Message__c</fullName>
    <label>Survey Catch-Up Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Reminder_Message__c</fullName>
    <label>Survey Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Thank_You_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Thank_You_Message__c</fullName>
    <label>Survey Thank You Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/classes/SurveyTriggerTest.cls
@isTest 
public with sharing class SurveyTriggerTest {
    
    @TestSetup
    static void makeData(){
        Apex_Trigger_Switch__c aps_p = new Apex_Trigger_Switch__c();
        aps_p.Name = 'ParticipantTrigger';
        aps_p.Active__c = false;
        insert aps_p;
        
        Event__c testEvent = TestFactory.createEvent('Test Campaign');
        TestFactory.createEvent('Test Campaign 2');
        Survey__c testActiveSurvey1 = TestFactory.createSurvey(testEvent.Id, 'Test Active Survey 1');
        
        Contact cont = TestFactory.createContact('Test', 'Contact', 'testcontact@gmail.com');
        
        Survey_Participant__c surveyParticipant = new Survey_Participant__c();
        surveyParticipant.Survey__c = testActiveSurvey1.Id;
        surveyParticipant.Participant__c = cont.Id;
        insert surveyParticipant;
        
        Participant__c participant = new Participant__c();
        participant.Event__c = testEvent.Id;
        insert participant;
        
    }

    @isTest
    public static void testCreateMultiActiveSurveys(){
        Test.startTest();
        Event__c testEvent = [SELECT Id FROM Event__c WHERE Name =: 'Test Campaign' LIMIT 1];
        try{
            Survey__c testActiveSurvey2 = TestFactory.createSurvey(testEvent.Id, 'Test Active Survey 2');
        } catch(DmlException e){
            System.assertNotEquals(null, e);
        }
        Test.stopTest();
    }

    @isTest
    public static void testCreateOneActiveSurveys(){
        // De-activate test survey 1
        Survey__c testActiveSurvey1 = [SELECT Id, Active__c FROM Survey__c WHERE Name = 'Test Active Survey 1'];
        testActiveSurvey1.Active__c = false;
        update testActiveSurvey1;

        Test.startTest();
        Event__c testEvent = [SELECT Id FROM Event__c WHERE Name =: 'Test Campaign' LIMIT 1];
        // Insert active survey 2
        try{
            Survey__c testActiveSurvey2 = TestFactory.createSurvey(testEvent.Id, 'Test Active Survey 2');
        } catch(DmlException e){
            System.assertNotEquals(null, e);
        }
        Test.stopTest();

        List<Survey__c> resultSurveyList = [SELECT Id FROM Survey__c WHERE Name = 'Test Active Survey 2'];
        System.assertEquals(1, resultSurveyList.size());
    }

    @isTest
    public static void testUpdateUnactiveSurveyToActive(){
        Event__c testEvent = [SELECT Id FROM Event__c WHERE Name =: 'Test Campaign' LIMIT 1];

        // Insert an inactive survey under event
        Survey__c inactiveSurvey = new Survey__c();
        inactiveSurvey.Name = 'Inactive Survey';
        inactiveSurvey.Active__c = false;
        inactiveSurvey.Event__c = testEvent.Id;
        insert inactiveSurvey;

        Test.startTest();
        try{
            inactiveSurvey.Active__c = true;
            update inactiveSurvey;
        } catch(DmlException e){
            System.assertNotEquals(null, e);
        }

        Test.stopTest();
    }

    @isTest
    public static void testSurveyCodeGeneration_shouldGenerateCode_whenSurveyIsCreatedWithoutEvent(){
        Test.startTest();
        TestFactory.createSurvey(null, 'Test Active Survey 1 without Event');
        Test.stopTest();

        List<Survey__c> resultSurveyList = [SELECT Id, Survey_Code__c, Standalone_Survey_URL__c FROM Survey__c WHERE Name = 'Test Active Survey 1 without Event'];
        System.assert(String.isNotBlank(resultSurveyList.get(0).Survey_Code__c));
        System.assert(String.isNotBlank(resultSurveyList.get(0).Standalone_Survey_URL__c));
    }

    @isTest
    public static void testSurveyCodeGeneration_shouldNotGenerateCode_whenSurveyIsCreatedWithEvent(){

        Event__c testEvent = [SELECT Id FROM Event__c WHERE Name =: 'Test Campaign 2' LIMIT 1];

        Test.startTest();
        TestFactory.createSurvey(testEvent.Id, 'Test Active Survey 1 with Event');
        Test.stopTest();

        List<Survey__c> resultSurveyList = [SELECT Id, Survey_Code__c, Standalone_Survey_URL__c FROM Survey__c WHERE Name = 'Test Active Survey 1 with Event'];
        System.assert(String.isBlank(resultSurveyList.get(0).Survey_Code__c));
        System.assert(String.isBlank(resultSurveyList.get(0).Standalone_Survey_URL__c));
    }

    @isTest
    public static void testSurveyCodeGeneration_shouldGenerateCode_whenSurveyIsUpdatedWithoutEvent(){
        Event__c testEvent = [SELECT Id FROM Event__c WHERE Name =: 'Test Campaign' LIMIT 1];

        Test.startTest();

        // Insert an inactive survey under event
        Survey__c inactiveSurvey = new Survey__c();
        inactiveSurvey.Name = 'Inactive Survey';
        inactiveSurvey.Active__c = false;
        inactiveSurvey.Event__c = testEvent.Id;
        insert inactiveSurvey;

        inactiveSurvey.Event__c = null;
        update inactiveSurvey;

        Test.stopTest();

        List<Survey__c> resultSurveyList = [SELECT Id, Survey_Code__c, Standalone_Survey_URL__c FROM Survey__c WHERE Id = :inactiveSurvey.Id];
        System.assert(String.isNotBlank(resultSurveyList.get(0).Survey_Code__c));
        System.assert(String.isNotBlank(resultSurveyList.get(0).Standalone_Survey_URL__c));
    }

    @isTest
    public static void testSurveyCodeGeneration_shouldNotGenerateCode_whenSurveyIsUpdatedWithEvent(){
        Event__c testEvent = [SELECT Id FROM Event__c WHERE Name =: 'Test Campaign' LIMIT 1];

        Test.startTest();

        // Insert an inactive survey under event
        Survey__c inactiveSurvey = new Survey__c();
        inactiveSurvey.Name = 'Inactive Survey';
        inactiveSurvey.Active__c = false;
        insert inactiveSurvey;

        inactiveSurvey.Event__c = testEvent.Id;
        update inactiveSurvey;

        Test.stopTest();

        List<Survey__c> resultSurveyList = [SELECT Id, Survey_Code__c, Standalone_Survey_URL__c FROM Survey__c WHERE Id = :inactiveSurvey.Id];
        System.assert(String.isBlank(resultSurveyList.get(0).Survey_Code__c));
        System.assert(String.isBlank(resultSurveyList.get(0).Standalone_Survey_URL__c));
    }
    
    // Added by RLugpatan [CCN-1049] Jan062022
    @isTest
    public static void testSyncSurveyRichTextFields(){
        Survey__c testSurvey = [SELECT Id FROM Survey__c WHERE Name =: 'Test Active Survey 1' LIMIT 1];
        
        Test.startTest();
        
        // Update Survey record
        testSurvey.Survey_Thank_You_Message__c = 'Test Survey Thank you Message';
        testSurvey.Survey_Catchup_Message__c = 'Test Survey Catchup Message';
        testSurvey.Survey_Catchup_Reminder_Message__c = 'Test Survey Catchup Reminder Message';
        testSurvey.Survey_Reminder_Message__c = 'Test Survey Reminder Message';
        update testSurvey;
        
        Test.stopTest();
        
        Survey_Participant__c surveyParticipant = [SELECT Id, Survey_Thank_You_Message__c, Survey_Catchup_Reminder_Message__c, Survey_Catchup_Message__c, 
                                         Survey_Reminder_Message__c, Survey__r.Survey_Thank_You_Message__c, Survey__r.Survey_Catchup_Reminder_Message__c, 
                                         Survey__r.Survey_Catchup_Message__c, Survey__r.Survey_Reminder_Message__c
                                         FROM Survey_Participant__c WHERE Survey__c = :testSurvey.Id]; 
        System.assertEquals(surveyParticipant.Survey__r.Survey_Thank_You_Message__c, surveyParticipant.Survey_Thank_You_Message__c);
        System.assertEquals(surveyParticipant.Survey__r.Survey_Catchup_Message__c, surveyParticipant.Survey_Catchup_Message__c);
        System.assertEquals(surveyParticipant.Survey__r.Survey_Catchup_Reminder_Message__c, surveyParticipant.Survey_Catchup_Reminder_Message__c);
        System.assertEquals(surveyParticipant.Survey__r.Survey_Reminder_Message__c, surveyParticipant.Survey_Reminder_Message__c);
    }
}