main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Email_Template_Invitation_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Invitation_Id__c</fullName>
    <label>Email Template - Invitation Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Compass_Setting__c/fields/Email_Template_Registration_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Registration_Id__c</fullName>
    <label>Email Template - Registration Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Registration Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Aborted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Proposed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Invitation_Date__c.field-meta.xml
<CustomField>
    <fullName>Invitation_Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <label>Invitation Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Readiness_Self_Ranking__c.field-meta.xml
<CustomField>
    <fullName>Readiness_Self_Ranking__c</fullName>
    <label>Readiness Self Ranking</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novice</fullName>
            </value>
            <value>
                <fullName>Advanced Beginner</fullName>
            </value>
            <value>
                <fullName>Proficient</fullName>
            </value>
            <value>
                <fullName>Expert</fullName>
            </value>
            <value>
                <fullName>Observer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Session_Participant__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <label>Registration Date</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Catchup</fullName>
                <label>Catch-Up</label>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/CC_SessionParticipantsAttendedTest.cls
/** 
 * @Date: 05/18/2021
 * @Description: test class for CC_SessionParticipantsAttended
 * @Modification: increase code coverage for [CCN975]
**/
@isTest (seeAllData = false)
public with sharing class CC_SessionParticipantsAttendedTest {

    @TestSetup static void testData(){
        User adminUser = TestFactory.createInteralUser('first','last','admin@compass.test.com','System Administrator');

        System.runAs(adminUser) {
            Apex_Trigger_Switch__c apexSwitch = TestDataFactory.createTriggerSwitch('EventTrigger');
            insert apexSwitch;
            
            EmailTemplate e = new EmailTemplate (developerName = 'test', FolderId = UserInfo.getUserId(), TemplateType= 'Text', Name = 'test', IsActive = true);
            insert e;
            
            Compass_Setting__c compSetting = new Compass_Setting__c();
            compSetting.Name = 'Default Settings';
            compSetting.Email_Sender_Id__c = '123';
            compSetting.Email_Sender_Name__c = 'NAME';
            compSetting.Email_Template_Invitation_Id__c = e.Id;
            compSetting.Email_Template_Registration_Id__c = e.Id;
            insert compSetting;
            
            
            Event__c  event = TestFactory.createEvent('TestEventName');
            Session__c session = TestFactory.createSession('Test Session',event.Id); 
            List<Session_Participant__c> participants = TestFactory.createSessionParticipants(2,session.Id);
            participants[0].Status__c = 'Registered';
            participants[1].Status__c = 'Registered';
            insert participants;
            
            //Contact
            Contact con1 = new Contact();
            con1.FirstName = 'Test Contact';
            con1.LastName = 'Record 1';
            con1.Email = 'testemail@testemail.com';
            insert con1;
            
            //Campaign  
            List<Campaign__c> campList = new List<Campaign__c>();
            Campaign__c camp1 = new Campaign__c();
            camp1.Name = 'Test Campaign 001';
            campList.add(camp1);
            
            insert campList;
            
            OrgWideEmailAddress owea = [SELECT Id, DisplayName FROM OrgWideEmailAddress WHERE DisplayName = 'Edera' LIMIT 1];
            
            //Event
            List<Event__c> eventList = new List<Event__c>();
            Event__c event1 = new Event__c();
            event1.Name = 'Test Event 001';
            event1.Campaign__c = camp1.Id;
            event1.Email_Sender_Id__c = owea.Id;
            event1.Email_Sender_Name__c = owea.DisplayName;
            eventList.add(event1);
            
            Event__c event2 = new Event__c();
            event2.Campaign__c = camp1.Id;
            event2.Name = 'Test Event 002';
            eventList.add(event2);
            
            insert eventList;
            
            //Session
            List<Session__c> sessionList = new List<Session__c>();
            Session__c session1 = new Session__c();
            session1.Name = 'Test Session 001';
            session1.Event__c = event1.Id;
            session1.Start_Date_Time__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
            session1.End_Date_Time__c = DateTime.newInstance(2020, 08, 29, 10, 30, 0);
            sessionList.add(session1);
            
            Session__c session2 = new Session__c();
            session2.Name = 'Test Session 002';
            session2.Event__c = event2.Id;
            session2.Time_Zone__c = 'EDT';  
            sessionList.add(session2);
            
            insert sessionList;
            
            
            //Session Participant
            List<Session_Participant__c> sessionParticipantList = new List<Session_Participant__c>();
            Session_Participant__c sp = new Session_Participant__c();
            sp.Session__c = session1.Id;
            sp.Event__c = event1.Id;
            sp.Contact__c = con1.Id;
            sp.Status__c = 'Attended';
            sp.Invitation_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
            sp.Registration_Date__c = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
            sessionParticipantList.add(sp);
            
            insert sessionParticipantList;
            
        }
    }

    @IsTest
    static void testGetSessionParticipants() {
        User adminUser = [SELECT Id FROM User WHERE Username = 'admin@compass.test.com'];
        
        System.runAs(adminUser) {
            Session__c session = [SELECT Id FROM Session__c LIMIT 1];
            List<Session_Participant__c> participants = null;

            Test.startTest();
                participants = CC_SessionParticipantsAttended.getSessionParticipants(session.Id);
            Test.stopTest();

            System.assert(participants != null);
        }     
    }   

    @IsTest
    static void testMarkSessionParticipantsToAttended() {
        User adminUser = [SELECT Id FROM User WHERE Username = 'admin@compass.test.com'];
        
        System.runAs(adminUser) {
            List<Session_Participant__c> participants = [SELECT Id,Session__c,Status__c FROM Session_Participant__c];

            Test.startTest();
                participants = CC_SessionParticipantsAttended.markSessionParticipantsToAttended(participants[0].Session__c,participants);
            Test.stopTest();

            System.assert(participants.isEmpty());
        }     
    }   

    @IsTest
    static void testMarkSessionParticipantsToAttendedError() {
        User adminUser = [SELECT Id FROM User WHERE Username = 'admin@compass.test.com'];
        
        System.runAs(adminUser) {
            Boolean isError = false;
            Test.startTest();
            try {
                CC_SessionParticipantsAttended.markSessionParticipantsToAttended(null,null);
            } catch (Exception e) {
                isError = true;
            }
            Test.stopTest();
            
            System.assert(isError);
        }     
    }   
    
    /**
    * @description  Added for [CCN975]
    **/
    @IsTest
    static void testGetEventAttendedParticipantFieldsJSON() {
        User adminUser = [SELECT Id FROM User WHERE Username = 'admin@compass.test.com'];
        
        System.runAs(adminUser) {
            Session__c session = [SELECT Id FROM Session__c limit 1];
            
            Test.startTest();
            String attendedFields = CC_SessionParticipantsAttended.getEventAttendedParticipantFieldsJSON(session.Id);
            Test.stopTest();
            
        }     
    }   
    
    /**
    * @description  Added for [CCN975]
    **/
    @IsTest
    static void testGetEventAttendedParticipantFieldsJSONError() {
        User adminUser = [SELECT Id FROM User WHERE Username = 'admin@compass.test.com'];
        
        System.runAs(adminUser) {
            
            Test.startTest();
            try {
                String attendedFields = CC_SessionParticipantsAttended.getEventAttendedParticipantFieldsJSON(null);
            }catch (Exception e){
                System.assert(TRUE);
            }
            Test.stopTest();
        }     
    }   

    /**
    * @description  Added for [CCN975]
    **/    
    @IsTest
    static void testGetPickListValues() {
        User adminUser = [SELECT Id FROM User WHERE Username = 'admin@compass.test.com'];
        
        System.runAs(adminUser) {
            
            Test.startTest();
            List<String> picklistValues = CC_SessionParticipantsAttended.getPickListValues('Readiness_Self_Ranking__c');
            Test.stopTest();
            
        }     
    }      
    
}