main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Contact/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <description>Parent Event&apos;s Event Id</description>
    <formula>Event__r.Event_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Event Id</label>
    <type>Text</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Code__c.field-meta.xml
<CustomField>
    <fullName>Survey_Code__c</fullName>
    <description>Random code will be generated and will be the identifier for the survey</description>
    <label>Survey Code</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Fields_JSON__c.field-meta.xml
<CustomField>
    <fullName>Survey_Fields_JSON__c</fullName>
    <description>Contains the JSON string for the selected fields and if they are required, to be displayed in the survey</description>
    <label>Survey Fields JSON</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Survey_Field_Configuration__mdt/Survey_Field_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Stores the fields that can be displayed in a survey</description>
    <label>Survey Field Configuration</label>
    <pluralLabel>Survey Field Configurations</pluralLabel>
</CustomObject>

main/default/objects/Survey_Field_Configuration__mdt/fields/Actual_Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Actual_Field_Type__c</fullName>
    <label>Actual Field Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Lookup</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Survey_Field_Configuration__mdt/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <inlineHelpText>Which side of the form would you like the field placed?</inlineHelpText>
    <label>Column</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Left</fullName>
                <default>true</default>
                <label>Left</label>
            </value>
            <value>
                <fullName>Right</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Survey_Field_Configuration__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>Contains the API name of the field</description>
    <label>Field API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Survey_Field_Configuration__mdt/fields/Form_Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Form_Field_Type__c</fullName>
    <inlineHelpText>Corresponds which input type the field will be</inlineHelpText>
    <label>Form Field Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Survey_Field_Configuration__mdt/fields/Message_when_Required__c.field-meta.xml
<CustomField>
    <fullName>Message_when_Required__c</fullName>
    <defaultValue>&quot;This field is required&quot;</defaultValue>
    <inlineHelpText>This message will be displayed when the field is required and is not filled-up</inlineHelpText>
    <label>Message when Required</label>
    <type>TextArea</type>
</CustomField>

main/default/objects/Survey_Field_Configuration__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>The API Name of the object where the field is related to</description>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Survey_Field_Configuration__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>In what order does the field will be displayed?</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

main/default/objects/Survey_Response__c/Survey_Response__c.object-meta.xml
<CustomObject>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>Survey Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey_Response__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Response__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Session where the response will be recorded against</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Response__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Responses</relationshipLabel>
    <relationshipName>Survey_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/SurveyFieldPickerControllerTest.cls
@isTest(IsParallel = true)
private class SurveyFieldPickerControllerTest {
    
    private final static String SURVEY_CODE = '546hgfh7456';
    private final static String JSON_FOR_WITH_EVENT_SURVEY = '{"Contact|FirstName":true,"Contact|LastName":true,"Contact|Email":true,"Contact|Facility__c":false,"Survey_Response__c|Session__c":true}';
	private final static String JSON_FOR_WITHOUT_EVENT_SURVEY = '{"Contact|FirstName":true,"Contact|LastName":true,"Contact|Email":true}';
	private final static String SURVEY_WITH_EVENT = 'Test Survey with Event';
    private final static String SURVEY_WITH_EVENT_NO_SELECTED_FIELDS = 'Test Survey with Event No Selected Survey Field';
    private final static String SURVEY_NO_EVENT = 'Test Survey No Event';
    
    @TestSetup
    private static void setupData(){
        List<Apex_Trigger_Switch__c> switchRecs = TestDataFactory.createAllTriggerSwitch();
        insert switchRecs;
        
        Compass_Setting__c comp = TestDataFactory.createCSData(1);
        insert comp;
        
        Event__c newCampaign = TestFactory.createEvent('Test Campaign');
        newCampaign.Event_Id__c = 'zhCoziiBzcb';
        update newCampaign;

        Event__c newCampaign2 = TestFactory.createEvent('Test Campaign2');
        newCampaign.Event_Id__c = 'zhCoziiBzcc';
        update newCampaign2;

        Survey__c newSurvey = TestFactory.createSurvey(newCampaign.Id, SURVEY_WITH_EVENT);
        newSurvey.Survey_Fields_JSON__c = JSON_FOR_WITH_EVENT_SURVEY;
        
        TestFactory.createSurvey(newCampaign2.Id, SURVEY_WITH_EVENT_NO_SELECTED_FIELDS);

        Survey__c newSurvey2 = TestFactory.createSurvey(null, SURVEY_NO_EVENT);
        newSurvey2.Survey_Code__c = SURVEY_CODE;
        newSurvey2.Survey_Fields_JSON__c = JSON_FOR_WITHOUT_EVENT_SURVEY;
        update new List<Survey__c>{newSurvey, newSurvey2};
    }
    
    @isTest
    private static void getSurveyFieldsFromMetadata_shouldReturnValuesFromMetadata_whenSurveyRecordIdIsProvidedAndNoSelectedFields(){
        Survey__c surveyRecord = [SELECT Id FROM Survey__c WHERE Name = :SURVEY_WITH_EVENT_NO_SELECTED_FIELDS LIMIT 1];
        
        SurveyFieldPickerController.mockFieldConfiguration = setMockFieldConfigValues(true);
        
        Test.startTest();
        List<SurveyFields> surveyFieldList = SurveyFieldPickerController.getSurveyFieldsFromMetadata(surveyRecord.Id);
        Test.stopTest();
        
        System.assert(!surveyFieldList.isEmpty(), 'Survey Field from metadata should not return blank');
    }
    
    @isTest
    private static void getSurveyFieldsFromMetadata_shouldThrowExceptionWhileFetchingRecords_whenSurveyRecordIdIsInvalid(){   
        final String FAKE_ID = TestFactory.getRecordFakeId(Survey__c.sObjectType.getDescribe().getSobjectType());
        
        Test.startTest();
        AuraHandledException exc;
        
        try{
            List<SurveyFields> surveyFieldList = SurveyFieldPickerController.getSurveyFieldsFromMetadata(FAKE_ID);
        } catch(AuraHandledException e){
            exc = e;
        }
        
        System.assertNotEquals(null, exc, 'Exception expected');
        
        Test.stopTest();
    }
    
    @isTest
    private static void getSurveyFieldsFromMetadata_shouldReturnValuesFromSurveyJSONField_whenSurveyLinkedToEvent(){
        Survey__c surveyRecord = [SELECT Id FROM Survey__c WHERE Name = :SURVEY_WITH_EVENT LIMIT 1];
        
        SurveyFieldPickerController.mockFieldConfiguration = setMockFieldConfigValues(true);
        
        Test.startTest();
        List<SurveyFields> surveyFieldList = SurveyFieldPickerController.getSurveyFieldsFromMetadata(surveyRecord.Id);
        Test.stopTest();
        
        System.assertEquals(5, surveyFieldList.size(), 'Survey Field from Survey JSON should have returned 5 results.');
    }
    
    @isTest
    private static void getSurveyFieldsFromMetadata_shouldReturnValuesFromSurveyJSONField_whenSurveyNotLinkedToEventAndNoFieldsSelected(){
        Survey__c surveyRecord = [SELECT Id FROM Survey__c WHERE Name = :SURVEY_NO_EVENT LIMIT 1];
        
        SurveyFieldPickerController.mockFieldConfiguration = setMockFieldConfigValues(false);
        
        Test.startTest();
        List<SurveyFields> surveyFieldList = SurveyFieldPickerController.getSurveyFieldsFromMetadata(surveyRecord.Id);
        Test.stopTest();
        
        System.assert(!surveyFieldList.isEmpty(), 'Survey Field from Survey JSON should not return blank');
    }
    
    @isTest
    private static void getSurveyFieldsFromMetadata_shouldReturnValuesFromSurveyJSONField_whenSurveyNotLinkedToEventAndFieldsAreSelected(){
        Survey__c surveyRecord = [SELECT Id FROM Survey__c WHERE Name = :SURVEY_NO_EVENT LIMIT 1];
        
        SurveyFieldPickerController.mockFieldConfiguration = setMockFieldConfigValues(false);
        
        Test.startTest();
        List<SurveyFields> surveyFieldList = SurveyFieldPickerController.getSurveyFieldsFromMetadata(surveyRecord.Id);
        Test.stopTest();
        
        System.assertEquals(4, surveyFieldList.size(), 'Survey Field from Survey JSON should have returned 4 results.');
    }
    
    @isTest
    private static void getSurveyFieldsFromMetadata_shouldSaveSurvey(){
        Survey__c surveyRecord = [SELECT Id FROM Survey__c WHERE Name = :SURVEY_NO_EVENT LIMIT 1];
   
        Test.startTest();
        SurveyFieldPickerController.saveSelectedFields(JSON_FOR_WITH_EVENT_SURVEY, surveyRecord.Id);
        Test.stopTest();
        
        surveyRecord = [SELECT Id, Survey_Fields_JSON__c FROM Survey__c WHERE Id = :surveyRecord.Id LIMIT 1];
        System.assertEquals(JSON_FOR_WITH_EVENT_SURVEY, surveyRecord.Survey_Fields_JSON__c, 'Survey Fields passed to be updated on the survey should have matched the one on the survey already');
    }
    
    @isTest
    private static void getSurveyFieldsFromMetadata_shouldThrowExceptionWhileSaving_whenSurveyRecordIdIsInvalid(){
        final String FAKE_ID = TestFactory.getRecordFakeId(Survey__c.sObjectType.getDescribe().getSobjectType());
        
        Test.startTest();
        AuraHandledException exc;
        
        try{
            SurveyFieldPickerController.saveSelectedFields(JSON_FOR_WITH_EVENT_SURVEY, FAKE_ID);
        } catch(AuraHandledException e){
            exc = e;
        }
        
        System.assertNotEquals(null, exc, 'Exception expected');
        
        Test.stopTest();
    }
    
    //sets mock metadata records to avoid dependency on actual metadata records
    private static List<Survey_Field_Configuration__mdt> setMockFieldConfigValues(Boolean isForEvent){
        List<Survey_Field_Configuration__mdt> surveyFieldConfig = new List<Survey_Field_Configuration__mdt>();
        surveyFieldConfig.add(new Survey_Field_Configuration__mdt(Order__c = 1, Label = 'First Name', Column__c = 'Left', Object_API_Name__c = 'Contact', 
                                                                  Field_API_Name__c = 'FirstName', Form_Field_Type__c = 'Text', Actual_Field_Type__c = 'Text',
                                                                  Message_when_Required__c = 'First Name is required'));
        surveyFieldConfig.add(new Survey_Field_Configuration__mdt(Order__c = 2, Label = 'Last Name', Column__c = 'Left', Object_API_Name__c = 'Contact', 
                                                                  Field_API_Name__c = 'LastName', Form_Field_Type__c = 'Text', Actual_Field_Type__c = 'Text',
                                                                  Message_when_Required__c = 'Last Name is required'));
        surveyFieldConfig.add(new Survey_Field_Configuration__mdt(Order__c = 3, Label = 'Email', Column__c = 'Left', Object_API_Name__c = 'Contact', 
                                                                  Field_API_Name__c = 'Email', Form_Field_Type__c = 'Text', Actual_Field_Type__c = 'Text',
                                                                  Message_when_Required__c = 'Email is required'));
        surveyFieldConfig.add(new Survey_Field_Configuration__mdt(Order__c = 4, Label = 'Facility', Column__c = 'Right', Object_API_Name__c = 'Contact', 
                                                                  Field_API_Name__c = 'Facility__c', Form_Field_Type__c = 'Text', Actual_Field_Type__c = 'Text',
                                                                  Message_when_Required__c = 'Facility is required'));
        
        if (isForEvent){
        	surveyFieldConfig.add(new Survey_Field_Configuration__mdt(Order__c = 5, Label = 'Session', Column__c = 'Right', Object_API_Name__c = 'Survey_Response__c', 
                                                                  Field_API_Name__c = 'Session__c', Form_Field_Type__c = 'Picklist', Actual_Field_Type__c = 'Lookup',
                                                                  Message_when_Required__c = 'Session is required'));                   
        }
                              
        return surveyFieldConfig;
    }
}