main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the client or organization the campaign is associated with. This connects the campaign to client data.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign__c/fields/Site_Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Site_Picklist_Values__c</fullName>
    <inlineHelpText>Values automatically populate Site Picklist Values field on event, survey, and communication objects. Enter values as a comma-separated list.</inlineHelpText>
    <label>Site Picklist Values</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Compass_Setting__c/fields/Notify_Emails__c.field-meta.xml
<CustomField>
    <fullName>Notify_Emails__c</fullName>
    <label>Notify Emails</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Compass_Setting__c/fields/Notify_User__c.field-meta.xml
<CustomField>
    <fullName>Notify_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Notify User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Compass_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Contact/fields/Contact_Type__c.field-meta.xml
<CustomField>
    <fullName>Contact_Type__c</fullName>
    <inlineHelpText>Please select the most appropriate type of Contact.  For employees, please input information in the employee relevant information per policy.</inlineHelpText>
    <label>Contact Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employee - FT</fullName>
            </value>
            <value>
                <fullName>Employee- PT</fullName>
            </value>
            <value>
                <fullName>Employee- 1099</fullName>
            </value>
            <value>
                <fullName>Contractor (employed by another firm)</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Site_picklist_values__c.field-meta.xml
<CustomField>
    <fullName>Site_picklist_values__c</fullName>
    <inlineHelpText>Field where values for the Site field in the community event registration page can be defined. Values should be comma-separated and configured in the Registration Field Configuration custom metadata settings to look into this field.</inlineHelpText>
    <label>Site Picklist Values</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Member_Contact__c.field-meta.xml
<CustomField>
    <fullName>Member_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member (Contact)</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Event_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/Session_Participant__c.object-meta.xml
<CustomObject>
    <label>Participant Session</label>
    <nameField>
        <displayFormat>SM-{000000}</displayFormat>
        <label>Session Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participant Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session_Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant</label>
    <referenceTo>Participant__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session_Participant__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/TestDataFactory.cls
public with sharing class TestDataFactory {
    public static Compass_Setting__c createCSData(Integer recordCounter) {
        Compass_Setting__c record = new Compass_Setting__c(
            Name             = 'Default Settings',
            Email_Sender_Name__c     = 'Default Name',
            Notify_User__c        =  UserInfo.getUserId(),
            Notify_Emails__c      = 'test@gmail.com'
        );
        return record;
    }
    public static Campaign__c createCampaign(Integer recordCounter) {
        
        Account acc = createAccount('Test Account');
        insert acc;
        
        Campaign__c record = new Campaign__c(
            Name = 'Test Campaign' + recordCounter,
            Site_Picklist_Values__c = 'Site 1,Site 2,Site 3',
            Account__c = acc.Id
        );
        return record;
    }
    public static Apex_Trigger_Switch__c createTriggerSwitch(String operationName) {
        Apex_Trigger_Switch__c record = new Apex_Trigger_Switch__c(
            Name          = operationName,
            Active__c        = true
        );
        
        return record;
    }
    public static Account createAccount(String name) {
        Account record = new Account(
            Name = name
        );
        
        return record;
    }
    public static User createUser(String firstname, String lastname, String email, String profileName) {
        Profile p = [SELECT Id FROM Profile WHERE Name =: profileName LIMIT 1];
        User record = new User(
            FirstName = firstname,
            LastName = lastname,
            Email = email,
            Username = email,
            Alias = firstname.charAt(0)+lastname,
            EmailEncodingKey='UTF-8',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            ProfileId = p.Id,
            TimeZoneSidKey='America/New_York'
        );
        
        return record;
    }
    public static Campaign createStandardCampaign(String campaignName) {
        Campaign record = new Campaign(
            Name = campaignName,
            IsActive = true
        );
        
        return record;
    }
    public static Event__c createEvent(String name, Id campaignId) {
        Event__c record = new Event__c(
            Name = name,
            Campaign__c = campaignId
        );
        
        return record;
    }
    public static Session__c createSession(String name, String eventId) {
        Session__c record = new Session__c(
            Name = name,
            Event__c = eventId
        );
        
        return record;
    }
    public static Participant__c createParticipant(Id eventId, Id contactId) {
        Participant__c record = new Participant__c(
            Event__c = eventId,
            Member_Contact__c = contactId
        );
        
        return record;
    }
    public static Session_Participant__c createSessionParticipant(Id sessionId) {
        Session_Participant__c record = new Session_Participant__c(
            Session__c = sessionId
        );
        
        return record;
    }
    public static Contact createContact(String firstname, String lastname, String email){
        Contact newContact = new Contact(
            Firstname = firstname,
            Lastname = lastname,
            Email = email,
            Contact_Type__c = 'Client'
        );
        return newContact;
    }
    //update every time a new switch is added
    public static List<Apex_Trigger_Switch__c> createAllTriggerSwitch() {
        List<Apex_Trigger_Switch__c> apexSwitchRecords = new List<Apex_Trigger_Switch__c>();
        apexSwitchRecords.add(TestDataFactory.createTriggerSwitch('EventTrigger'));
        apexSwitchRecords.add(TestDataFactory.createTriggerSwitch('SessionParticipantTrigger'));
        return apexSwitchRecords;
    }
}