main/default/objects/Apex_Trigger_Switch__c/Apex_Trigger_Switch__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Apex Trigger Switch</label>
</CustomObject>

main/default/objects/Campaign/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>CC Events</relationshipLabel>
    <relationshipName>CC_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Campaign/fields/End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Time__c</fullName>
    <label>End Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date Time</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Campaign/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>Time Zone</description>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

main/default/objects/Campaign/recordTypes/Session.recordType-meta.xml
<RecordType>
    <fullName>Session</fullName>
    <active>true</active>
    <label>Session</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Campaign__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Name of the client or organization the campaign is associated with. This connects the campaign to client data.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Compass_Setting__c/Compass_Setting__c.object-meta.xml
<CustomObject>
    <label>Compass Setting</label>
    <nameField>
        <label>Compass Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Compass Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Compass_Setting__c.field-meta.xml
<CustomField>
    <fullName>Compass_Setting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compass Setting</label>
    <referenceTo>Compass_Setting__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Id__c</fullName>
    <label>Email Sender Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Email_Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Sender_Name__c</fullName>
    <label>Email Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Event__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Milestone</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Event__c/fields/Resource_Calendar_Invite_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Resource_Calendar_Invite_Delivery__c</fullName>
    <description>Resource Calendar Invite Delivery</description>
    <label>Resource Calendar Invite Delivery</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Send on session registration</fullName>
            </value>
            <value>
                <fullName>Send on session confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Event__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <description>Main RecordType for Events</description>
    <label>Event</label>
</RecordType>

main/default/objects/Internal_Resource__c/Internal_Resource__c.object-meta.xml
<CustomObject>
    <label>Internal Resource</label>
    <nameField>
        <displayFormat>IR-{000000}</displayFormat>
        <label>Event Resource Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Resource__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Internal Resources</relationshipLabel>
    <relationshipName>Internal_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Internal Resources</relationshipLabel>
    <relationshipName>Internal_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/Internal_Resource_Session__c.object-meta.xml
<CustomObject>
    <label>Internal Resource Session</label>
    <nameField>
        <displayFormat>IRS-{000000}</displayFormat>
        <label>Session Resource  Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal Resource Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Internal_Resource_Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Resource Number</label>
    <referenceTo>Internal_Resource__c</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Resource_Session_Status__c.field-meta.xml
<CustomField>
    <fullName>Resource_Session_Status__c</fullName>
    <label>Resource Session Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Internal_Resource_Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Internal Resource Sessions</relationshipLabel>
    <relationshipName>Internal_Resource_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <description>Milestone</description>
    <label>Milestone &amp; Checkpoint</label>
    <nameField>
        <label>Journey Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones &amp; Checkpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Milestones &amp; Checkpoints</relationshipLabel>
    <relationshipName>Milestones_Checkpoints</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Session__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions (Campaign)</relationshipLabel>
    <relationshipName>AttendeeSessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Do_Not_Send_Calendar_Invite__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Send_Calendar_Invite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Send Calendar Invite</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>CC_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Session__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates Milestone</description>
    <label>Milestone</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Session__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zone</valueSetName>
    </valueSet>
</CustomField>

main/default/classes/InternalResourceSessionTrigger_Test.cls
@IsTest
private class InternalResourceSessionTrigger_Test {
    @TestSetup
    static void makeData(){

        // Create Apex Trigger Switch
        List<Apex_Trigger_Switch__c> atsList = new List<Apex_Trigger_Switch__c>();

        Apex_Trigger_Switch__c ats = new Apex_Trigger_Switch__c();
        ats.Name        = 'InternalResourceSessionTrigger';
        ats.Active__c   = true;
        insert ats;
        
        Compass_Setting__c cSetting = TestDataFactory.createCSData(1);
        cSetting.Domain_Name__c  = 'https://dev3-nationalcoordinationcenter.cs90.force.com/Compass';
        insert cSetting;

        // Create Contacts
        List<Contact> contactsList = new List<Contact>();

        Contact testContact1 = new Contact();
        testContact1.FirstName  = 'Test 1';
        testContact1.LastName   = 'Contact 1';
        testContact1.Email      = 'testContact1@testemail.com';
        contactsList.add(testContact1);

        Contact testContact2 = new Contact();
        testContact2.FirstName  = 'Test 2';
        testContact2.LastName   = 'Contact 2';
        testContact2.Email      = 'testContact2@testemail.com';
        contactsList.add(testContact2);

        insert contactsList;

        // Create Location
        Id locationRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Location').getRecordTypeId();
        Account testLocation = new Account();
        testLocation.Name           = 'Test Location';
        testLocation.RecordTypeId   = locationRecTypeId;
        insert testLocation;

        // Create Campaign
        Campaign__c testCampaign1 = new Campaign__c();
        testCampaign1.Name = 'Test Campaign 001';
        testCampaign1.Account__c = testLocation.Id;
        insert testCampaign1;

        OrgWideEmailAddress owea = [SELECT Id, DisplayName FROM OrgWideEmailAddress LIMIT 1];

        // Create Events
        List<Event__c> eventsList = new List<Event__c>();

        Event__c testEvent1 = new Event__c();
        testEvent1.Name                                 = 'Test Event 001';
        testEvent1.Campaign__c                          = testCampaign1.Id;
        testEvent1.Email_Sender_Id__c                   = owea.Id;
        testEvent1.Email_Sender_Name__c                 = owea.DisplayName;
        testEvent1.Milestone__c                         = true;
        testEvent1.IsActive__c                          = true;
        testEvent1.Start_Date_Time__c                   = system.today();
        testEvent1.End_Date_Time__c                     = system.today() + 1;
        testEvent1.Time_Zone__c                         = 'AKDT';
        testEvent1.Resource_Calendar_Invite_Delivery__c = 'Send on session registration';
        eventsList.add(testEvent1);

        Event__c testEvent2 = new Event__c();
        testEvent2.Name                                 = 'Test Event 002';
        testEvent2.Campaign__c                          = testCampaign1.Id;
        testEvent2.Email_Sender_Id__c                   = owea.Id;
        testEvent2.Email_Sender_Name__c                 = owea.DisplayName;
        testEvent2.Milestone__c                         = true;
        testEvent2.IsActive__c                          = true;
        testEvent2.Start_Date_Time__c                   = system.today();
        testEvent2.End_Date_Time__c                     = system.today() + 1;
        testEvent2.Time_Zone__c                         = 'CDT';
        testEvent2.Resource_Calendar_Invite_Delivery__c = 'Send on session confirmation';
        eventsList.add(testEvent2);

        insert eventsList;

        // Create Sessions
        List<Session__c> sessionsList = new List<Session__c>();
        
        Session__c testSession1 = new Session__c();
        testSession1.Name                           = 'Test Session 001';
        testSession1.Event__c                       = testEvent1.Id;
        testSession1.Time_Zone__c                   = 'AKDT';
        testSession1.Start_Date_Time__c             = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        testSession1.End_Date_Time__c               = DateTime.newInstance(2020, 08, 29, 10, 30, 0);
        testSession1.Do_Not_Send_Calendar_Invite__c = false;
        sessionsList.add(testSession1);

        Session__c testSession2 = new Session__c();
        testSession2.Name                           = 'Test Session 001';
        testSession2.Event__c                       = testEvent2.Id;
        testSession2.Time_Zone__c                   = 'CDT';
        testSession2.Start_Date_Time__c             = DateTime.newInstance(2020, 08, 29, 9, 30, 0);
        testSession2.End_Date_Time__c               = DateTime.newInstance(2020, 08, 29, 10, 30, 0);
        testSession2.Do_Not_Send_Calendar_Invite__c = false;
        sessionsList.add(testSession2);

        insert sessionsList;

        // Create Internal Resources
        List<Internal_Resource__c> internalResources = new List<Internal_Resource__c>();

        Internal_Resource__c ir1 = new Internal_Resource__c();
        ir1.Contact__c  = testcontact1.Id;
        ir1.Event__c    = testEvent1.Id;
        internalResources.add(ir1);

        Internal_Resource__c ir2 = new Internal_Resource__c();
        ir2.Contact__c  = testcontact2.Id;
        ir2.Event__c    = testEvent2.Id;
        internalResources.add(ir2);

        insert internalResources;
    }

    
    @IsTest
    static void testEmailForRegisteredResource() {
        
        Internal_Resource__c internalResource = [SELECT Id, Contact__c, Contact__r.LastName FROM Internal_Resource__c WHERE Contact__r.LastName = 'Contact 1'];
        Session__c session = [SELECT Id, Event__c, Event__r.Resource_Calendar_Invite_Delivery__c FROM Session__c WHERE Event__r.Resource_Calendar_Invite_Delivery__c = 'Send on session registration'];

        Test.startTest();
            Internal_Resource_Session__c irSession = new Internal_Resource_Session__c();
            irSession.Event__c                      = session.Event__c;
            irSession.Contact__c                    = internalResource.Contact__c;
            irSession.Resource__c                   = internalResource.Id;
            irSession.Session__c                    = session.Id;
            irSession.Resource_Session_Status__c    = 'Registered';

            insert irSession;

            Integer emailInvocations = Limits.getEmailInvocations();
        Test.stopTest();

        //system.assert(emailInvocations > 0, 'An email should be sent');
    }

    
    @IsTest
    static void testEmailForConfirmedResource() {
        
        Internal_Resource__c internalResource = [SELECT Id, Contact__c, Contact__r.LastName FROM Internal_Resource__c WHERE Contact__r.LastName = 'Contact 2'];
        Session__c session = [SELECT Id, Event__c, Event__r.Resource_Calendar_Invite_Delivery__c FROM Session__c WHERE Event__r.Resource_Calendar_Invite_Delivery__c = 'Send on session confirmation'];
        Internal_Resource_Session__c irSession = new Internal_Resource_Session__c();
            irSession.Event__c                      = session.Event__c;
            irSession.Contact__c                    = internalResource.Contact__c;
            irSession.Resource__c                   = internalResource.Id;
            irSession.Session__c                    = session.Id;
            irSession.Resource_Session_Status__c    = 'Registered';

        insert irSession;

        Test.startTest();
            Internal_Resource_Session__c irSessionUpdate = [SELECT Id, Resource_Session_Status__c FROM Internal_Resource_Session__c WHERE Resource_Session_Status__c = 'Registered'];
            irSessionUpdate.Resource_Session_Status__c = 'Confirmed';

            update irSessionUpdate;

            Integer emailInvocations = Limits.getEmailInvocations();
        Test.stopTest();

        //system.assert(emailInvocations > 0, 'An email should be sent');
    }
}