main/default/objects/Epic__c/Epic__c.object-meta.xml
<CustomObject>
    <label>Epic</label>
    <nameField>
        <label>Epic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Epic__c/fields/Epic_Code__c.field-meta.xml
<CustomField>
    <fullName>Epic_Code__c</fullName>
    <label>Epic Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Epic__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Epics</relationshipLabel>
    <relationshipName>Epics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Project__c/fields/Starting_Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Starting_Task_Number__c</fullName>
    <label>Starting Task Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Project__c/fields/Task_Number_Display_Format__c.field-meta.xml
<CustomField>
    <fullName>Task_Number_Display_Format__c</fullName>
    <label>Task Number Display Format</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Project_Task__c/fields/Alternative_Title__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Title__c</fullName>
    <label>Alternative Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Project Tasks (Contact)</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Epic will be automatically populated upon saving if related to a Workplan.</inlineHelpText>
    <label>Epic</label>
    <referenceTo>Epic__c</referenceTo>
    <relationshipLabel>Project Tasks (Epic)</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feature</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Project_Task__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Feature</value>
        </filterItems>
        <filterItems>
            <field>Project_Task__c.Feature_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Project_Task__c.Epic__c</field>
            <operation>equals</operation>
            <valueField>$Source.Epic__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Project Tasks (Functionality)</relationshipLabel>
    <relationshipName>Features1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Project will be automatically populated upon saving if related to a Workplan.</inlineHelpText>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Discovery, Requirements Tracking, Completed, Canceled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipName>Project_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/QA_Task__c.field-meta.xml
<CustomField>
    <fullName>QA_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QA Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Project Tasks (QA Task)</relationshipLabel>
    <relationshipName>QA_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Test_Execution__c.field-meta.xml
<CustomField>
    <fullName>Test_Execution__c</fullName>
    <label>Test Execution</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Project_Task__c/recordTypes/QA.recordType-meta.xml
<RecordType>
    <fullName>QA</fullName>
    <active>true</active>
    <label>QA</label>
</RecordType>

main/default/objects/Sprint__c/Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Sprint__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/Test_Execution__c.object-meta.xml
<CustomObject>
    <label>Test Execution</label>
    <nameField>
        <label>Test Execution Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Test_Execution__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Epic</label>
    <referenceTo>Epic__c</referenceTo>
    <relationshipLabel>Test Executions</relationshipLabel>
    <relationshipName>Test_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feature</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Test Executions</relationshipLabel>
    <relationshipName>Test_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/From_Test_Execution_Button__c.field-meta.xml
<CustomField>
    <fullName>From_Test_Execution_Button__c</fullName>
    <defaultValue>false</defaultValue>
    <label>From Test Execution Button</label>
    <type>Checkbox</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Test Executions</relationshipLabel>
    <relationshipName>Test_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/QA_Task__c.field-meta.xml
<CustomField>
    <fullName>QA_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QA Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Test Executions (QA Task)</relationshipLabel>
    <relationshipName>Test_Executions3</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Testing_Phase__c.field-meta.xml
<CustomField>
    <fullName>Testing_Phase__c</fullName>
    <description>Identifies the phase in the testing process</description>
    <label>Testing Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>System Integration Testing</fullName>
                <label>SIT</label>
            </value>
            <value>
                <fullName>User Acceptance Testing</fullName>
                <label>UAT</label>
            </value>
            <value>
                <fullName>Prod Smoke Testing</fullName>
                <label>SMOKE</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/CloneTestExecutionScreenCtrlTest.cls
@isTest
public class CloneTestExecutionScreenCtrlTest {

    @TestSetup
    static void createData(){
        User ceoUser = [SELECT Id, UserRole.DeveloperName FROM User WHERE UserRole.DeveloperName='CEO' AND isActive = True LIMIT 1];
        System.runAs ( ceoUser ) {
            Profile compassAgilePMUserId = [SELECT Id FROM Profile WHERE Name = 'Compass Agile PM User'];
            //UserRole r = [SELECT Id, DeveloperName FROM UserRole WHERE DeveloperName = 'UlappCustomerUser' LIMIT 1];
            system.debug('profid:' + compassAgilePMUserId);
            Account ac = new Account(name ='Ulapp');
            insert ac; 
           
            Contact con = new Contact(LastName ='testCon',AccountId = ac.Id, Email='test1@com.com');
            insert con;  
                      
            User user = new User(alias = 'test123', email='test123@noemail.com',
                    emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                    localesidkey='en_US', country='United States',IsActive =true,
                    ContactId = con.Id, PortalRole='Manager',
                    timezonesidkey='America/Los_Angeles', username='tester@noemail.com', profileid = compassAgilePMUserId.Id);
            System.debug('userbeforecreate:'  + user);
        }
        
        Id accCustomerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer').getRecordTypeId();
        Account customerAccount = new Account();
        customerAccount.Name = 'Test Account #1';
        customerAccount.RecordTypeId = accCustomerRecordTypeId;
        insert customerAccount;
        
        Project__c projRecord = new Project__c();
        projRecord.Project_Code__c = '0000';
        projRecord.Name = 'Test Project #A';
        projRecord.Account__c = customerAccount.Id;
        projRecord.Starting_Task_Number__c = 0;
        projRecord.Task_Number_Display_Format__c = '{mm}';
        projRecord.Project_Code__c = 'PROJ';
        
        insert projRecord;
        
        Project__c projRecord2 = new Project__c();
        projRecord2.Project_Code__c = '0000';
        projRecord2.Name = 'Test Project #B';
        projRecord2.Account__c = customerAccount.Id;
        projRecord.Starting_Task_Number__c = 0;
        projRecord2.Task_Number_Display_Format__c = '{mm}';
        projRecord2.Project_Code__c = 'PRO';
        
        insert projRecord2;


        Epic__c epicRecord1 = new Epic__c();
        epicRecord1.Epic_Code__c = 'EPI';
        epicRecord1.Name = 'Test Epic #A';
        epicRecord1.Epic_Code__c = 'EPI';
        epicRecord1.Project__c = projRecord.Id;

        insert epicRecord1;
        
        
        Sprint__c dBacklogSprint = new Sprint__c();
        dBacklogSprint.Name = 'Backlog (Test Project #A)';
        dBacklogSprint.Project__c = projRecord.Id;
        insert dBacklogSprint;
        
        
        List<Sprint__c> sprintList = new List<Sprint__c>();
        for(Integer i = 1; i < 5; i++){
            Sprint__c sprint = new Sprint__c();
            sprint.Name = 'Sample Sprint ' + i+1;
            sprint.Project__c = projRecord.Id;
            sprint.Start_Date__c = System.today(); 
            sprint.End_Date__c = Date.valueOf(System.today()).addDays(30); 
            
            if(i > 1){
                sprint.Start_Date__c = Date.valueOf(System.today()).addDays((30*i)+1); 
                sprint.End_Date__c = Date.valueOf(System.today()).addDays((30*i+1)+1);  
            }
            sprintList.add(sprint);
        }
        insert sprintList;

        Id qaRecType = [Select Id from RecordType WHERE Name = 'QA'].Id;
        List<Project_Task__c> projTaskList = new List<Project_Task__c>();

        Project_Task__c qaBugRecord = new Project_Task__c();
        qaBugRecord.Project__c = projRecord.Id;
        qaBugRecord.Epic__c = epicRecord1.Id;
        qaBugRecord.RecordTypeId = qaRecType;
        qaBugRecord.Name = 'Next';
        qaBugRecord.Title__c = 'QA: Test';
        qaBugRecord.Alternative_Title__c = 'QA Record';
        projTaskList.add(qaBugRecord);
        insert projTaskList;
    }
    
    @isTest
    public static void getData_Test(){
        Id qaRecType = [Select Id from RecordType WHERE Name = 'QA'].Id;
        
        Project__c projRecord = [SELECT Id, Name, OwnerId FROM Project__c WHERE Name = 'Test Project #A' LIMIT 1];
        Epic__c epicRecord = [SELECT Id, Name FROM Epic__c WHERE Name = 'Test Epic #A' LIMIT 1];
        Project_Task__c fpt = [SELECT Id FROM Project_Task__c WHERE Alternative_Title__c = 'QA Record' LIMIT 1];
        User owner = [Select Id From User LIMIT 1];
        Test.startTest();
        
        Test_Execution__c testExecutionFromButton = new Test_Execution__c();
        testExecutionFromButton.Assigned_To__c = owner.Id;
        testExecutionFromButton.From_Test_Execution_Button__c = TRUE;
        testExecutionFromButton.Project__c = projRecord.Id;
        testExecutionFromButton.Epic__c = epicRecord.Id;
        testExecutionFromButton.QA_Task__c = [SELECT Id FROM Project_Task__c WHERE RecordTypeId =: qaRecType LIMIT 1].Id;
        testExecutionFromButton.Feature__c = fpt.Id;
        testExecutionFromButton.Testing_Phase__c = 'System Integration Testing';
            
        insert testExecutionFromButton;
        
        	CloneTestExecutionScreenController.getData([SELECT Id FROM Project_Task__c LIMIT 1].Id);
        Test.stopTest();
    }
    
     @isTest
    public static void getTestExecutionsById_Test(){
        
        
        Test.startTest();
        Id qaRecType = [Select Id from RecordType WHERE Name = 'QA'].Id;
        
        Project__c projRecord = [SELECT Id, Name, OwnerId FROM Project__c WHERE Name = 'Test Project #A' LIMIT 1];
        Epic__c epicRecord = [SELECT Id, Name FROM Epic__c WHERE Name = 'Test Epic #A' LIMIT 1];
        Project_Task__c fpt = [SELECT Id FROM Project_Task__c WHERE Alternative_Title__c = 'QA Record' LIMIT 1];
        User owner = [Select Id From User LIMIT 1];
        
        Test_Execution__c testExecutionFromButton = new Test_Execution__c();
        testExecutionFromButton.Assigned_To__c = owner.Id;
        testExecutionFromButton.From_Test_Execution_Button__c = TRUE;
        testExecutionFromButton.Project__c = projRecord.Id;
        testExecutionFromButton.Epic__c = epicRecord.Id;
        testExecutionFromButton.QA_Task__c = [SELECT Id FROM Project_Task__c WHERE RecordTypeId =: qaRecType LIMIT 1].Id;
        testExecutionFromButton.Feature__c = fpt.Id;
        testExecutionFromButton.Testing_Phase__c = 'System Integration Testing';
            
        insert testExecutionFromButton;
        CloneTestExecutionScreenController.getTestExecutionsById(new List<String>{[SELECT Id FROM Test_Execution__c].Id});
        Test.stopTest();
        
    }
}