main/default/objects/Epic__c/Epic__c.object-meta.xml
<CustomObject>
    <label>Epic</label>
    <nameField>
        <label>Epic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Epic__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Epics</relationshipLabel>
    <relationshipName>Epics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Test_Execution__c/Test_Execution__c.object-meta.xml
<CustomObject>
    <label>Test Execution</label>
    <nameField>
        <label>Test Execution Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Executions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Test_Execution__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Test_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Dev_Task__c.field-meta.xml
<CustomField>
    <fullName>Dev_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dev Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Test Executions (Dev Task)</relationshipLabel>
    <relationshipName>Test_Executions2</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Epic</label>
    <referenceTo>Epic__c</referenceTo>
    <relationshipLabel>Test Executions</relationshipLabel>
    <relationshipName>Test_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Expected_Results__c.field-meta.xml
<CustomField>
    <fullName>Expected_Results__c</fullName>
    <label>Expected Results</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Feature__c.field-meta.xml
<CustomField>
    <fullName>Feature__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Feature</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Test Executions</relationshipLabel>
    <relationshipName>Test_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Functionality__c.field-meta.xml
<CustomField>
    <fullName>Functionality__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Functionality</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Test Executions (Functionality)</relationshipLabel>
    <relationshipName>Test_Executions1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Test Executions</relationshipLabel>
    <relationshipName>Test_Executions</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/QA_Task__c.field-meta.xml
<CustomField>
    <fullName>QA_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QA Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Test Executions (QA Task)</relationshipLabel>
    <relationshipName>Test_Executions3</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Template_Task__c.field-meta.xml
<CustomField>
    <fullName>Template_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template Task</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria for Template Task.</errorMessage>
        <filterItems>
            <field>Project_Task__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Template</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Test Executions (Template Task)</relationshipLabel>
    <relationshipName>Template_Project_Task_Child</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Test_Scenario__c.field-meta.xml
<CustomField>
    <fullName>Test_Scenario__c</fullName>
    <label>Test Step</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Test_Execution__c/fields/Testing_Phase__c.field-meta.xml
<CustomField>
    <fullName>Testing_Phase__c</fullName>
    <description>Identifies the phase in the testing process</description>
    <label>Testing Phase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>System Integration Testing</fullName>
                <label>SIT</label>
            </value>
            <value>
                <fullName>User Acceptance Testing</fullName>
                <label>UAT</label>
            </value>
            <value>
                <fullName>Prod Smoke Testing</fullName>
                <label>SMOKE</label>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/CloneTestExecutionScreenController.cls
/**
* 			@description Controller for CloneTestExecutionScreen LWC 
* 
*           11/29/2023 - Miguel Punzal - Initial Version
*
**/
public class CloneTestExecutionScreenController {
    
    public class TestExecutionData {
        @AuraEnabled public List<Test_Execution__c> testExeuctionRecords = new List<Test_Execution__c>();
        @AuraEnabled public List<TestingPhaseValue> testingPhaseValues = new List<TestingPhaseValue>();
    }
    
    public class TestingPhaseValue {
        @AuraEnabled public String label = '';
        @AuraEnabled public String value = '';
    }
    
    @AuraEnabled
    public static TestExecutionData getData(String recId){
        
        TestExecutionData teData = new TestExecutionData();
        teData.testExeuctionRecords = getTestExecutions(recId);
        teData.testingPhaseValues = getTestingPhaseValues();
        return teData;
    }
    
    @AuraEnabled
    public static List<TestingPhaseValue> getTestingPhaseValues(){
        List<TestingPhaseValue> testingPhaseValues = new List<TestingPhaseValue>();
        
        // Get the object describe result
        Schema.DescribeSObjectResult describeResult = Schema.getGlobalDescribe().get('Test_Execution__c').getDescribe();
        
        // Get the field describe result for the picklist field
        Schema.DescribeFieldResult fieldDescribe = describeResult.fields.getMap().get('Testing_Phase__c').getDescribe();
        
        // Check if the field is a picklist
        if (fieldDescribe.getType() == Schema.DisplayType.PICKLIST) {
            // Get the picklist values
            List<Schema.PicklistEntry> picklistValues = fieldDescribe.getPicklistValues();
            
            // Loop through the picklist values to get label and value
            for (Schema.PicklistEntry picklistEntry : picklistValues) {
                TestingPhaseValue teVal = new TestingPhaseValue();
                teVal.label = picklistEntry.getLabel();
                teVal.value = picklistEntry.getValue();
                testingPhaseValues.add(teVal); 
            }
        } else {
            // Handle if the field is not a picklist
            System.debug('Field is not a picklist.');
        }
            
        return testingPhaseValues;
    }
    
    @AuraEnabled
    public static List<Test_Execution__c> getTestExecutions(String recordId){
        if(String.isBlank(recordId)){
            return new List<Test_Execution__c>();
        }
        return [SELECT Id, Name, QA_Task__c, Expected_Results__c, Testing_Phase__c, Epic__c, Epic__r.Name, Assigned_To__c, Assigned_To__r.Name, OwnerId, Owner.Name, Project__c, Feature__c, Functionality__c, Dev_Task__c, Template_Task__c, Test_Scenario__c  FROM Test_Execution__c 
                WHERE QA_Task__c =: recordId OR Project__c =: recordId OR Functionality__c =: recordId OR Feature__c =: recordId OR Epic__c =: recordId OR Dev_Task__c =: recordId ORDER BY Name ASC];
    }
    
    @AuraEnabled
    public static List<Test_Execution__c> getTestExecutionsById(List<String> recordIds){
        if(recordIds.isEmpty()){
            return new List<Test_Execution__c>();
        }
        return [SELECT Id, Name, QA_Task__c, Expected_Results__c, Testing_Phase__c, Epic__c, Epic__r.Name, Assigned_To__c, Assigned_To__r.Name, OwnerId, Owner.Name, Project__c, Feature__c, Functionality__c, Dev_Task__c, Template_Task__c, Test_Scenario__c FROM Test_Execution__c 
                WHERE Id IN :recordIds];
    }
}