main/default/objects/Epic__c/Epic__c.object-meta.xml
<CustomObject>
    <label>Epic</label>
    <nameField>
        <label>Epic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Epics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Epic__c/fields/Epic_Code__c.field-meta.xml
<CustomField>
    <fullName>Epic_Code__c</fullName>
    <label>Epic Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Epic__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Epics</relationshipLabel>
    <relationshipName>Epics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Epic__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Requirements Tracking</fullName>
            </value>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>Roadmap</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

main/default/objects/Project__c/fields/Starting_Task_Number__c.field-meta.xml
<CustomField>
    <fullName>Starting_Task_Number__c</fullName>
    <label>Starting Task Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Requirements Tracking</fullName>
            </value>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Live</fullName>
            </value>
            <value>
                <fullName>In Development</fullName>
            </value>
            <value>
                <fullName>Roadmap</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Project__c/fields/Task_Number_Display_Format__c.field-meta.xml
<CustomField>
    <fullName>Task_Number_Display_Format__c</fullName>
    <label>Task Number Display Format</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

main/default/objects/Project_Task__c/Project_Task__c.object-meta.xml
<CustomObject>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Project_Task__c/fields/Epic__c.field-meta.xml
<CustomField>
    <fullName>Epic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Epic will be automatically populated upon saving if related to a Workplan.</inlineHelpText>
    <label>Epic</label>
    <referenceTo>Epic__c</referenceTo>
    <relationshipLabel>Project Tasks (Epic)</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Feature_Code__c.field-meta.xml
<CustomField>
    <fullName>Feature_Code__c</fullName>
    <label>Feature Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Project will be automatically populated upon saving if related to a Workplan.</inlineHelpText>
    <label>Project</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Project__c.Status__c</field>
            <operation>notEqual</operation>
            <value>Discovery, Requirements Tracking, Completed, Canceled</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipName>Project_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Sprint__c.field-meta.xml
<CustomField>
    <fullName>Sprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sprint</label>
    <referenceTo>Sprint__c</referenceTo>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Project_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To identify the current status of Project task</description>
    <inlineHelpText>For TR: For Technical Review, For UI/UX
For QA: For Quality Assurance</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Estimate</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>For TR</fullName>
            </value>
            <value>
                <fullName>For QA</fullName>
            </value>
            <value>
                <fullName>For Release</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>On-hold</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
            </value>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Ready</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>SIT</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Prod Validation</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress - Off-Track</fullName>
            </value>
            <value>
                <fullName>In Progress - At Risk</fullName>
            </value>
            <value>
                <fullName>In Progress - On-Track</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Project_Task__c/recordTypes/Story.recordType-meta.xml
<RecordType>
    <fullName>Story</fullName>
    <active>true</active>
    <label>Story</label>
</RecordType>

main/default/objects/Release__c/Release__c.object-meta.xml
<CustomObject>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Release__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Releases</relationshipLabel>
    <relationshipName>Releases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Release_Item__c/Release_Item__c.object-meta.xml
<CustomObject>
    <label>Release Item</label>
    <nameField>
        <displayFormat>RI{00000}</displayFormat>
        <label>Release Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Release Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Release_Item__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Project_Task__r.Project__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project</label>
    <type>Text</type>
</CustomField>

main/default/objects/Release_Item__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>Project_Task__c</referenceTo>
    <relationshipLabel>Release Items</relationshipLabel>
    <relationshipName>Release_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Release_Item__c/fields/Release__c.field-meta.xml
<CustomField>
    <fullName>Release__c</fullName>
    <label>Release</label>
    <referenceTo>Release__c</referenceTo>
    <relationshipLabel>Release Items</relationshipLabel>
    <relationshipName>Release_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Release_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

main/default/objects/Sprint__c/Sprint__c.object-meta.xml
<CustomObject>
    <label>Sprint</label>
    <nameField>
        <label>Sprint  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Sprint__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Sprints</relationshipLabel>
    <relationshipName>Sprints</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Sprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF(AND(Start_Date__c &gt; TODAY(), End_Date__c &gt; TODAY()),
IMAGE(&quot;https://ulapp-developers.force.com/projects/resource/1609548260000/Icon_Status_Planning&quot;,&quot;N&quot;,20,65),

IF(AND(Start_Date__c &lt;= TODAY(), End_Date__c &gt; TODAY()),
IMAGE(&quot;https://ulapp-developers.force.com/projects/resource/1609548240000/Icon_Status_Active&quot;,&quot;N&quot;,20,65),

IF(AND(Start_Date__c &lt; TODAY(), End_Date__c &lt; TODAY()),
IMAGE(&quot;https://ulapp-developers.force.com/projects/resource/1609513559000/Icon_Complete&quot;,&quot;N&quot;,20,65),

IMAGE(&quot;https://ulapp-developers.force.com/projects/resource/1609548664000/Icon_Status_Accepted&quot;,&quot;N&quot;,20,65)
)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

main/default/globalValueSets/Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <customValue>
        <fullName>Withdrawn</fullName>
    </customValue>
    <customValue>
        <fullName>Blocked</fullName>
    </customValue>
    <masterLabel>Status</masterLabel>
</GlobalValueSet>

main/default/classes/ReleaseItemTriggerHandlerTest.cls
@IsTest
public class ReleaseItemTriggerHandlerTest {

    @TestSetup
    static void createData(){
        Apex_Trigger_Switch__c switchh = new Apex_Trigger_Switch__c();
        switchh.Name = 'ReleaseItemTrigger';
        switchh.Active__c = true;
        insert switchh;
        
        Project__c projRecord = new Project__c();
        projRecord.Project_Code__c = '0000';
        projRecord.Name = 'Test Project #A';
        projRecord.Starting_Task_Number__c = 0;
        projRecord.Task_Number_Display_Format__c = '{mm}';
        insert projRecord;
        
        Sprint__c dBacklogSprint = new Sprint__c();
        dBacklogSprint.Name = 'Backlog (Test Project #A)';
        dBacklogSprint.Project__c = projRecord.Id;
        dBacklogSprint.End_Date__c = system.today();
        insert dBacklogSprint;
        
        Epic__c epic = new Epic__c();
        epic.Project__c = projRecord.Id;
        epic.Epic_Code__c = 'E1';
        insert epic;
        
        Project_Task__c projTask = new Project_Task__c();
        projTask.Sprint__c = dBacklogSprint.Id;
        projTask.Project__c = projRecord.Id;
        projTask.Epic__c = epic.Id;
        projTask.Status__c = 'New';
        projTask.RecordTypeId = [SELECT Id FROM RecordType WHERE sObjectType='Project_Task__c' AND DeveloperName LIKE '%Story%' LIMIT 1].Id;
        projTask.Feature_Code__c = 'Test';
        insert projTask;
        
        Release__c release = new Release__c();
        release.Project__c = projRecord.Id;
        release.Release_Date__c = System.today();        
        insert release;
    }

    @IsTest
    static void ApexTriggerSwitchTest(){
        // Commented by dinoBrinas Nov52021
        //Apex_Trigger_Switch__c switchh = Apex_Trigger_Switch__c.getInstance('ReleaseItemTrigger');
        //switchh.Active__c = true;
        //update switchh;
        
        
        
        Project_Task__c devTaskRec = [Select Id, Status__c from Project_Task__c Limit 1];
        Release__c releaseRec = [Select Id, Release_Date__c from Release__c Limit 1];
        List<Release_Item__c> releaseItemList = new List<Release_Item__c>();
        for(Integer i = 0; i < 3; i ++){
            Release_Item__c newReleaseItemRec = new Release_Item__c();
            newReleaseItemRec.Project_Task__c = devTaskRec.id;
            newReleaseItemRec.Release__c = releaseRec.Id;
            newReleaseItemRec.Release_Item_Status__c = 'Completed';
            releaseItemList.add(newReleaseItemRec);
        }
        insert releaseItemList;
    }

    @IsTest
    static void releaseItemInsertTest(){
        Project_Task__c devTaskRec = [Select Id, Status__c from Project_Task__c Limit 1];
        Release__c releaseRec = [Select Id, Release_Date__c from Release__c Limit 1];
        List<Release_Item__c> releaseItemList = new List<Release_Item__c>();
        for(Integer i = 0; i < 3; i ++){
            Release_Item__c newReleaseItemRec = new Release_Item__c();
            newReleaseItemRec.Project_Task__c = devTaskRec.id;
            newReleaseItemRec.Release__c = releaseRec.Id;
            newReleaseItemRec.Release_Item_Status__c = 'Completed';
            releaseItemList.add(newReleaseItemRec);
        }
        insert releaseItemList;
    }
    
    @IsTest
    static void releaseItemUpdateTest(){
        Project_Task__c devTaskRec = [Select Id, Status__c from Project_Task__c Limit 1];
        Release__c releaseRec = [Select Id, Release_Date__c from Release__c Limit 1];
        List<Release_Item__c> releaseItemList = new List<Release_Item__c>();
        for(Integer i = 0; i < 3; i ++){
            Release_Item__c newReleaseItemRec = new Release_Item__c();
            newReleaseItemRec.Project_Task__c = devTaskRec.id;
            newReleaseItemRec.Release__c = releaseRec.Id;
            newReleaseItemRec.Release_Item_Status__c = 'Completed';
            releaseItemList.add(newReleaseItemRec);
        }
        insert releaseItemList;
        
        List<Release_Item__c> releaseListUp = [Select Id, Status__c from Release_Item__c];
        for(Release_Item__c releaseItem : releaseListUp){
            releaseItem.Release_Item_Status__c = 'Completed';
        }
        update releaseListUp;
    }
}