main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;For Review&quot;</defaultValue>
    <description>Status of the Journey</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Milestone_Metric__c/Milestone_Metric__c.object-meta.xml
<CustomObject>
    <description>Metrics used to calculate progress of each Milestone</description>
    <label>Milestone Metric</label>
    <nameField>
        <displayFormat>MM-{0000000}</displayFormat>
        <label>Milestone Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Milestone_Metric__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <description>Links to Journey</description>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Milestone Metrics</relationshipLabel>
    <relationshipName>Milestone_Metrics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Milestone_Metric__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Milestone</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Attestation</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Quick Check</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/classes/MilestoneMetricTrigger_Test.cls
/*******************************************************************************
 * @author       Kyzer Buhay
 * @date         05/04/2021
 * @description  Test class for MilestoneMetricTrigger/Handler
 *******************************************************************************/
@IsTest(IsParallel=true)
public class MilestoneMetricTrigger_Test {
  @testSetup
  static void createData() {
    Campaign__c testCampaign = new Campaign__c();
    testCampaign.Name = 'Test Campaign Name';
    insert testCampaign;

    Journey__c testJourney = new Journey__c();
    testJourney.Name = 'Test Journey';
    testJourney.Campaign__c = testCampaign.Id;
    testJourney.Status__c = 'Approved';
    insert testJourney;
  }
  @isTest
  static void insertMilestoneMetric() {
    Test.startTest();
    Journey__c testJourney = [
      SELECT Id, Name
      FROM Journey__c
      WHERE Name = 'Test Journey'
      LIMIT 1
    ];

    Milestone_Metric__c mMetric = new Milestone_Metric__c();
    mMetric.Journey__c = testJourney.Id;
    mMetric.Type__c = 'Communication';
    insert mMetric;
    Test.stopTest();
    System.assertNotEquals([SELECT Id FROM Milestone_Metric__c], null);
  }

  @isTest
  static void deleteMilestoneMetric() {
    Test.startTest();
    Journey__c testJourney = [
      SELECT Id, Name
      FROM Journey__c
      WHERE Name = 'Test Journey'
      LIMIT 1
    ];

    Milestone_Metric__c mMetric = new Milestone_Metric__c();
    mMetric.Journey__c = testJourney.Id;
    mMetric.Type__c = 'Communication';
    insert mMetric;

    delete mMetric;
    Test.stopTest();
    System.assertNotEquals([SELECT Id FROM Milestone_Metric__c], null);
  }
}