main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey__c/fields/Journey_Preview_URL__c.field-meta.xml
<CustomField>
    <fullName>Journey_Preview_URL__c</fullName>
    <description>URL of Journey for preview</description>
    <label>Journey Landing Page URL</label>
    <type>Url</type>
</CustomField>

main/default/objects/Journey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;For Review&quot;</defaultValue>
    <description>Status of the Journey</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/JourneyCommunitySettings__c/JourneyCommunitySettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Journey Community Settings</description>
    <label>Journey Community Settings</label>
</CustomObject>

main/default/objects/JourneyCommunitySettings__c/fields/Community_Name__c.field-meta.xml
<CustomField>
    <fullName>Community_Name__c</fullName>
    <description>Community Name</description>
    <label>Community Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

main/default/classes/JourneyTriggerHandler_Test.cls
/*******************************************************************************
 * @author       Allen Francisco
 * @date         13.02.2021
 * @description  Test class for JourneyTriggerHandler
 * @revision     13.02.2021 - ADFrancisco - Created
 *******************************************************************************/
@isTest(IsParallel=true)
public class JourneyTriggerHandler_Test {
  @testSetup
  static void createData() {
    JourneyCommunitySettings__c jcSettings = new JourneyCommunitySettings__c();
    jcSettings.Community_Name__c = 'Compass';
    jcSettings.Name = 'Journey';
    insert jcSettings;
  }
  @IsTest
  static void runTrigger() {
    Test.startTest();
    Campaign__c testCampaign = new Campaign__c();
    testCampaign.Name = 'Test Campaign Name';
    insert testCampaign;

    Journey__c testJourney = new Journey__c();
    testJourney.Name = 'Test Journey';
    testJourney.Campaign__c = testCampaign.Id;
    testJourney.Status__c = 'For Review';
    insert testJourney;
    Test.stopTest();
    System.assertNotEquals([SELECT Id FROM Journey__c], null);
  }

  @IsTest
  static void runTriggerHandler() {
    Test.startTest();
    Campaign__c testCampaign = new Campaign__c();
    testCampaign.Name = 'Test Campaign Name';
    insert testCampaign;

    Journey__c testJourney = new Journey__c();
    testJourney.Name = 'Test Journey';
    testJourney.Campaign__c = testCampaign.Id;
    testJourney.Status__c = 'For Review';
    insert testJourney;

    Journey__c queriedTestJourney = [
      SELECT Id, Name, Campaign__c, Status__c, Journey_Preview_URL__c
      FROM Journey__c
      WHERE Id = :testJourney.Id
      LIMIT 1
    ];
    JourneyTriggerHandler.populateJourneyURL(
      new List<Journey__c>{ queriedTestJourney }
    );
    Test.stopTest();
    System.assertNotEquals([SELECT Id FROM Journey__c], null);
  }
}