main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;For Review&quot;</defaultValue>
    <description>Status of the Journey</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/JourneyParticipantTriggerHandler_Test.cls
/*******************************************************************************
 * @author       Allen Francisco
 * @date         13.02.2021
 * @description  Test class for JourneyParticipantTriggerHandler
 * @revision     13.02.2021 - ADFrancisco - Created
 *******************************************************************************/
@isTest(IsParallel=true)
public class JourneyParticipantTriggerHandler_Test {
  @IsTest
  static void runTrigger() {
    Campaign__c testCampaign = new Campaign__c();
    testCampaign.Name = 'Test Campaign Name';

    insert testCampaign;

    Journey__c testJourney = new Journey__c();
    testJourney.Name = 'Test Journey';
    testJourney.Campaign__c = testCampaign.Id;
    testJourney.Status__c = 'For Review';
    insert testJourney;

    Test.startTest();
    Journey_Participant__c testParticipant = new Journey_Participant__c();
    testParticipant.Journey__c = testJourney.Id;
    insert testParticipant;
    Test.stopTest();
    System.assertNotEquals([SELECT Id FROM Journey_Participant__c], null);
  }
}