main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

main/default/classes/LinktreeControllerTest.cls
@istest
public with sharing class LinktreeControllerTest {
    
    @isTest
    public static void LinktreeTest() { 
        campaign__c c = new campaign__c(name = 'test campaign');
        insert c;
        c.Name = 'test campaign Updated';
        update c;
        
        Campaign__c cc = linktreeController.getcampaignDetail('abc');
        System.assertEquals(null, cc.id);
        
        cc = linktreeController.getcampaignDetail(c.Id);
        System.assertEquals(c.id, cc.id);
        
        //cc = linktreeController.getcampaignDetail('abc');
        //System.assertEquals(null, cc.id);
        
        List<Event__c> listE = linktreeController.getcampaignEvents(c.Id);
        System.assertEquals(0, listE.size());
        
        cc = linktreeController.getcampaignDetail(null);
        System.assertEquals(null, cc);
        
        listE = linktreeController.getcampaignEvents(null);
        System.assertEquals(null, listE);
        
        listE = linktreeController.getcampaignEvents('null');
        System.assertEquals(null, null);

    }
}