main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Communication__c/Communication__c.object-meta.xml
<CustomObject>
    <label>Communication</label>
    <nameField>
        <label>Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Communications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Communication__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links to Camapaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Communications</relationshipLabel>
    <relationshipName>Communications</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Communication__c/fields/Email_Delivery_Date_Time_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Email_Delivery_Date_Time_Schedule__c</fullName>
    <description>Determines when the email communication will be sent</description>
    <label>Email Delivery Date/Time Schedule</label>
    <type>DateTime</type>
</CustomField>

main/default/objects/Communication__c/fields/Email_Recipient_BCC__c.field-meta.xml
<CustomField>
    <fullName>Email_Recipient_BCC__c</fullName>
    <inlineHelpText>Separate each email address with a comma</inlineHelpText>
    <label>Email Recipient BCC</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Communication__c/fields/Email_Recipient_CC__c.field-meta.xml
<CustomField>
    <fullName>Email_Recipient_CC__c</fullName>
    <inlineHelpText>Separate each email address with a comma</inlineHelpText>
    <label>Email Recipient CC</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/Communication__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Real-time</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Communication__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Communications</relationshipLabel>
    <relationshipName>Communications</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Communication__c/fields/Organization_Wide_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Organization_Wide_Email_Id__c</fullName>
    <label>Organization Wide Email Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

main/default/objects/Communication__c/fields/Reply_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Reply_Email_Address__c</fullName>
    <label>Reply Email Address</label>
    <type>Email</type>
</CustomField>

main/default/objects/Communication__c/fields/Sender_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Sender_Email_Address__c</fullName>
    <label>Sender Email Address</label>
    <type>Email</type>
</CustomField>

main/default/objects/Communication__c/fields/Sender_Name__c.field-meta.xml
<CustomField>
    <fullName>Sender_Name__c</fullName>
    <label>Sender Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

main/default/objects/Communication__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Outbox</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Communication_Recipient__c/Communication_Recipient__c.object-meta.xml
<CustomObject>
    <label>Communication Recipient</label>
    <nameField>
        <displayFormat>CCCR{00000}</displayFormat>
        <label>CC Communication Recipient Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Communication Recipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Communication_Recipient__c/fields/CC_Communication__c.field-meta.xml
<CustomField>
    <fullName>CC_Communication__c</fullName>
    <label>CC Communication</label>
    <referenceTo>Communication__c</referenceTo>
    <relationshipName>CC_Communication_Recipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Communication_Recipient__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Communication Recipients</relationshipLabel>
    <relationshipName>Communication_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Communication_Recipient__c/fields/Journey_Participant__c.field-meta.xml
<CustomField>
    <fullName>Journey_Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Journey Participant</label>
    <referenceTo>Journey_Participant__c</referenceTo>
    <relationshipLabel>Communication Recipients</relationshipLabel>
    <relationshipName>Communication_Recipients</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Communication_Recipient__c/fields/Send_as__c.field-meta.xml
<CustomField>
    <fullName>Send_as__c</fullName>
    <label>Send as</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To</fullName>
            </value>
            <value>
                <fullName>CC</fullName>
            </value>
            <value>
                <fullName>BCC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Email_Settings__c/Email_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Email_Settings</label>
</CustomObject>

main/default/objects/Email_Settings__c/fields/Max_Email_CC_BCC_Number__c.field-meta.xml
<CustomField>
    <fullName>Max_Email_CC_BCC_Number__c</fullName>
    <label>Max Email CC/BCC Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Email_Settings__c/fields/Max_Email_To_Number__c.field-meta.xml
<CustomField>
    <fullName>Max_Email_To_Number__c</fullName>
    <label>Max Email To Number</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/objects/Journey__c/Journey__c.object-meta.xml
<CustomObject>
    <label>Journey</label>
    <nameField>
        <label>Journey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journeys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Journey__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campaign</description>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Journeys</relationshipLabel>
    <relationshipName>Journeys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;For Review&quot;</defaultValue>
    <description>Status of the Journey</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>For Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

main/default/objects/Journey_Participant__c/Journey_Participant__c.object-meta.xml
<CustomObject>
    <label>Journey Participant</label>
    <nameField>
        <displayFormat>JP-{00000}</displayFormat>
        <label>Participant Journey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Journey_Participant__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Journey_Participant__c/fields/Journey__c.field-meta.xml
<CustomField>
    <fullName>Journey__c</fullName>
    <label>Journey</label>
    <referenceTo>Journey__c</referenceTo>
    <relationshipLabel>Journey Participants</relationshipLabel>
    <relationshipName>Journey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/classes/EmailSenderSchedulableTest.cls
/*******************************************************************************
 * @author       Kyzer Buhay
 * @date         06.19.2021
 * @description  Test class for EmailSenderSchedulable
 *******************************************************************************/
@IsTest
public class EmailSenderSchedulableTest {

    @TestSetup
    static void createData(){
        Email_Settings__c setting = new Email_Settings__c();
        setting.Max_Email_CC_BCC_Number__c = 25;
        setting.Max_Email_To_Number__c = 100;
        insert setting;
        
        // Account
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        insert testAccount;
        
        // Contact
        List<Contact> contactList = new List<Contact>();
        for(Integer i = 0; i < 3; i++){
            Contact newContact = new Contact();
            newContact.FirstName = 'Test FirstName' + i;
            newContact.LastName = 'Test LastName' + i;
            newContact.Email = 'testContactEmail' + i + '@testing.com';
            newContact.AccountId = testAccount.Id;
            contactList.add(newContact);
        }
        
        // for contact with HasOptedOutOfEmail set to true
        Contact newContact = new Contact(FirstName = 'Contact', 
                                         LastName = 'HasOptedOutOfEmail',
                                         Email = 'HasOptedOutOfEmail@testing.com',
                                         AccountId = testAccount.Id,
                                         HasOptedOutOfEmail = true);
        contactList.add(newContact);
        insert contactList;

        // Campaign
        Campaign__c testCampaign = new Campaign__c();
        testCampaign.Name = 'Test Campaign';
        insert testCampaign;

        // Journey
        List<Journey__c> journeyList = new List<Journey__c>();
        Journey__c testJourneyA = new Journey__c();
        testJourneyA.Name = 'Test Journey A';
        testJourneyA.Campaign__c = testCampaign.Id;
        testJourneyA.Status__c = 'For Review';
        journeyList.add(testJourneyA);

        Journey__c testJourneyB = new Journey__c();
        testJourneyB.Name = 'Test Journey B';
        testJourneyB.Campaign__c = testCampaign.Id;
        testJourneyB.Status__c = 'Approved';
        journeyList.add(testJourneyB);
        insert journeyList;

        // Journey Participant
        List<Journey_Participant__c> journeyParticipantList = new List<Journey_Participant__c>(); 
        for(Contact con : contactList){
            Journey_Participant__c newParticipant = new Journey_Participant__c();
        
            newParticipant.Contact__c = con.Id;
            newParticipant.Journey__c = testJourneyA.Id;
            if(con.HasOptedOutOfEmail == true){
                newParticipant.Journey__c = testJourneyB.Id;
            }
            journeyParticipantList.add(newParticipant);
        }
        insert journeyParticipantList;
        
        // OrgWideEmailAddress
        Id emailAddressesId = [SELECT Id FROM OrgWideEmailAddress LIMIT 1].Id;

        // Communication
        Communication__c newComms = new Communication__c();
        newComms.Status__c = 'Draft';
        newComms.Campaign__c = testCampaign.Id;
        newComms.Frequency__c = 'Real-time';
        newComms.Organization_Wide_Email_Id__c = emailAddressesId;
        newComms.Email_Recipient_CC__c = 'cctest@testing.com, cctest2@testing.com';
        newComms.Email_Recipient_BCC__c = 'bcctest@testing.com';
        newComms.Subject__c = 'Test Subject';
        newComms.Body__c = 'Test Body';
        newComms.Sender_Name__c = 'Test';
        newComms.Sender_Email_Address__c = 'test@test.com';
        newComms.Sender_Name__c = 'Test';
        newComms.Email_Delivery_Date_Time_Schedule__c = System.now();
        insert newComms;

        // Communication Recipients
        List<Communication_Recipient__c> commsRecipients = new List<Communication_Recipient__c>(); 
        for(Journey_Participant__c jParticipant : journeyParticipantList){
            Communication_Recipient__c newRecipient = new Communication_Recipient__c();
            newRecipient.CC_Communication__c = newComms.Id;
            newRecipient.Journey_Participant__c = jParticipant.Id;
            newRecipient.Contact__c = jParticipant.Contact__c;
            newRecipient.Send_as__c = 'To'; //CCN-1004 Xen Reyes January 25, 2022
            commsRecipients.add(newRecipient);
        }
        insert commsRecipients;
    }
    
    @IsTest
    static void emailSendTestSchedWithNoErrors(){
        Communication__c testCommRec = [SELECT Id, 
                                         Email_Template_Id__c, 
                                         Subject__c, 
                                         Body__c, 
                                         Email_Recipient_CC__c, 
                                         Email_Recipient_BCC__c,
                                         Reply_Email_Address__c,
                                         Organization_Wide_Email_Id__c,
                                         Email_Delivery_Date_Time_Schedule__c FROM Communication__c LIMIT 1];
        List<Communication_Recipient__c> crList = [SELECT Id, 
                                                   Contact__c, 
                                                   Journey_Participant__c,
                                                   Journey_Participant__r.Contact__c FROM Communication_Recipient__c
                                                   WHERE Send_as__c = 'To']; //CCN-1004 Xen Reyes January 25, 2022
        
        Test.startTest();
        	EmailSenderSchedulable emailSenderSched = new EmailSenderSchedulable(JSON.serialize(testCommRec), JSON.serialize(crList), testCommRec.Organization_Wide_Email_Id__c, true, 0);
			
        	String cronExp = '0 0 1 * * ?';
        	System.schedule('Schedule this', cronExp, emailSenderSched);
        
        	List<AsyncApexJob> jobsScheduled = [SELECT Id, ApexClassID, ApexClass.Name, Status, JobType FROM AsyncApexJob WHERE JobType = 'ScheduledApex'];
    		System.assertEquals(1, jobsScheduled.size(), 'Expecting one scheduled job');
        	System.assertEquals('EmailSenderSchedulable', jobsScheduled[0].ApexClass.Name, 'EmailSenderSchedulable should be the expected scheduled job');
        Test.stopTest();
    }
}