main/default/objects/Campaign/recordTypes/Campaign.recordType-meta.xml
<RecordType>
    <fullName>Campaign</fullName>
    <active>true</active>
    <description>This is  the main campaign record</description>
    <label>Campaign</label>
</RecordType>

main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <label>Participant</label>
    <nameField>
        <displayFormat>EM-{000000}</displayFormat>
        <label>Participant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Participant__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Participant__c/fields/Survey_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Reminder_Message__c</fullName>
    <label>Survey Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Participant__c/fields/Survey_Thank_You_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Thank_You_Message__c</fullName>
    <label>Survey Thank You Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/Survey__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Catchup_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Message__c</fullName>
    <label>Survey Catch-Up Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey__c/fields/Survey_Catchup_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Reminder_Message__c</fullName>
    <label>Survey Catch-Up Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Participant__c/Survey_Participant__c.object-meta.xml
<CustomObject>
    <label>Survey Participant</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Survey Participant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

main/default/objects/Survey_Participant__c/fields/Participant__c.field-meta.xml
<CustomField>
    <fullName>Participant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contact that has been selected as a participant for a survey</description>
    <inlineHelpText>Contact that has been selected as a participant for a survey</inlineHelpText>
    <label>Participant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <description>Survey that the contact has been selected to participate to</description>
    <inlineHelpText>Survey that the contact has been selected to participate to</inlineHelpText>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Participants</relationshipLabel>
    <relationshipName>Survey_Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Catchup_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Message__c</fullName>
    <label>Survey Catch-Up Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Catchup_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Catchup_Reminder_Message__c</fullName>
    <label>Survey Catch-Up Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Reminder_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Reminder_Message__c</fullName>
    <label>Survey Reminder Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/objects/Survey_Participant__c/fields/Survey_Thank_You_Message__c.field-meta.xml
<CustomField>
    <fullName>Survey_Thank_You_Message__c</fullName>
    <label>Survey Thank You Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

main/default/classes/SurveyParticipantTriggerTest.cls
@isTest
public class SurveyParticipantTriggerTest {
    
    @TestSetup
    static void makeData(){
        Event__c testEvent = TestFactory.createEvent('Test Campaign');
        TestFactory.createEvent('Test Campaign 2');
        Survey__c testActiveSurvey1 = TestFactory.createSurvey(testEvent.Id, 'Test Active Survey 1');
        
        Contact cont = TestFactory.createContact('Test', 'Contact', 'testcontact@gmail.com');
    }
    
    // Added by RLugpatan [CCN-1049] Jan062022
    @isTest
    public static void testSyncSurveyRichTextFields(){
        Survey__c testSurvey = [SELECT Id FROM Survey__c WHERE Name =: 'Test Active Survey 1' LIMIT 1];
        Contact cont = [Select Id From Contact LIMIT 1];
        
        Test.startTest();
        
        // Update Survey record
        testSurvey.Survey_Thank_You_Message__c = 'Test Survey Thank you Message';
        testSurvey.Survey_Catchup_Message__c = 'Test Survey Catchup Message';
        testSurvey.Survey_Catchup_Reminder_Message__c = 'Test Survey Catchup Reminder Message';
        testSurvey.Survey_Reminder_Message__c = 'Test Survey Reminder Message';
        update testSurvey;
        
        Survey_Participant__c surveyParticipant = new Survey_Participant__c();
        surveyParticipant.Survey__c = testSurvey.Id;
        surveyParticipant.Participant__c = cont.Id;
        insert surveyParticipant;
        
        Test.stopTest();
        
        Survey_Participant__c surveyParticipantChecking = [SELECT Id, Survey_Thank_You_Message__c, Survey_Catchup_Reminder_Message__c, Survey_Catchup_Message__c, 
                                                   Survey_Reminder_Message__c, Survey__r.Survey_Thank_You_Message__c, Survey__r.Survey_Catchup_Reminder_Message__c, 
                                                   Survey__r.Survey_Catchup_Message__c, Survey__r.Survey_Reminder_Message__c
                                                   FROM Survey_Participant__c WHERE Id = :surveyParticipant.Id]; 
        System.assertEquals(surveyParticipantChecking.Survey_Thank_You_Message__c, surveyParticipantChecking.Survey__r.Survey_Thank_You_Message__c);
        System.assertEquals(surveyParticipantChecking.Survey_Catchup_Message__c, surveyParticipantChecking.Survey__r.Survey_Catchup_Message__c);
        System.assertEquals(surveyParticipantChecking.Survey_Catchup_Reminder_Message__c, surveyParticipantChecking.Survey__r.Survey_Catchup_Reminder_Message__c);
        System.assertEquals(surveyParticipantChecking.Survey_Reminder_Message__c, surveyParticipantChecking.Survey__r.Survey_Reminder_Message__c);
    }
}